### ISSUE TITLE
Option to keep operators in between lines on the new line

### ISSUE THREAD

**Issue by daboross** [rust-lang-nursery/rustfmt#1010]
I couldn't find an issue for this already, and I'm unsure about the formatting guidelines on this, but it'd be nice to have an option to avoid this:

``` diff
-        self.velocity_x += force_x / self.settings.weight * delta_time
-                    * self.settings.tick_constant;
-        self.velocity_y += force_y / self.settings.weight * delta_time
-                    * self.settings.tick_constant;
+        self.velocity_x += force_x / self.settings.weight * delta_time *
+                           self.settings.tick_constant;
+        self.velocity_y += force_y / self.settings.weight * delta_time *
+                           self.settings.tick_constant;
```

To me at least, having the operators that separate expressions split between lines on the new line is much easier to read than having them on the end of the previous line. I didn't have the spacing right previously in this example, but it'd be nice to keep the operators on the new line rather than putting them at the end of the old one.

**Comment by topecongiro** [comment]
This is now the default style.
