### ISSUE TITLE
Replace `[T]::join` where `T: AsRef<str>` by Itertools' `join`

### ISSUE THREAD

**Issue by marcusklaas** [rust-lang-nursery/rustfmt#1014]
There's a few places where we collect an iter into a `Vec` and then join them into one big string. With itertools' `join` method on iterators, that allocation can be avoided.

**Comment by imjacobclark** [comment]
Hopefully covered this in PR #1042, first contribution to Rust, any changes/suggestions/edits needed - let me know!
