### ISSUE TITLE
Indent mistake with nested struct lit

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1019]
https://github.com/rust-lang/rust/pull/33939/files#diff-3d823311f2b08736340d87893d91e770R471

```
+                Ok((autoderef,
+                    ty::MethodCallee {
+                    def_id: this.read_struct_field("def_id", 1, |this| Ok(this.read_def_id(dcx)))
+                                .unwrap(),
+                    ty: this.read_struct_field("ty", 2, |this| Ok(this.read_ty(dcx)))
+                            .unwrap(),
+                    substs: this.read_struct_field("substs", 3, |this| {
+                                    Ok(dcx.tcx.mk_substs(this.read_substs(dcx)))
+                                })
+                                .unwrap(),
+                }))
```

**Comment by nrc** [comment]
Yeah, I was also playing with this, made some things better and some things worse. Examples of how I'd like this to work:

```
    let foasdfasfso = Sfgdsfgdsfgdfsgdsf {
        dfasd: dsfadsfasdfsdf,
        dsfasd: sdfgdfg,
    };

    let dsfasdfddddddddddddddddddddddddddddddddddddd = dsfsdffffffff(dddddddddddd,
                                                                     dsfsfsdfsfdddddd);

    Okdfgsdfgsdgsdfdfgsd((autoderef,
                          ty::MethodCallee {
                              def_id: this.unwrap(),
                              ty: this.unwrap(),
                              substs: this.read_struct_field("substs", 3, |this| {
                                              Ok(dcx.tcx.mk_substs(this.read_substs(dcx)))
                                          })
                                          .unwrap(),
                          }))
```

The problem is subtle, but I think it comes down to something like the `Indent` should track alignments for visual and block formatted items separately.

**Comment by marcusklaas** [comment]
That may not be necessary. Recall that we already have two levels of indent: one passed explicitly to the `rewrite` function, and one in the `RewriteContext`.
We could create a new `RewriteContext` which `Indent` is equal to the visual indent of the function argument.

It just gets a bit tricky when you have function arguments which are closures, which could use either one of the indents depending on its length...

**Comment by marcusklaas** [comment]
100% agreed on the ideal formatting btw

**Comment by marcusklaas** [comment]
Just played around with this a little. Turns around we already do visual indentation for struct function arguments. In the example we're looking at a tuple function argument though... Not sure how to fix this..

**Comment by topecongiro** [comment]
Closing since this is fixed on the current master.
