### ISSUE TITLE
Maintainer nit: please do dev in your own fork :-)

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustfmt#1020]
Every time I run `git fetch`, I get a bunch of remote branches added / removed that aren't really part of the repo proper. Eg, just now:

```
$ git fetch
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 9 (delta 8), reused 9 (delta 8), pack-reused 0
Unpacking objects: 100% (9/9), done.
From https://github.com/rust-lang-nursery/rustfmt
 * [new branch]      try-double-indent -> origin/try-double-indent
```

Since the repo lives under `rust-lang-nursery` now, I think it'd be better if you did dev in your own GitHub fork and made PRs from there. :heart:

**Comment by nrc** [comment]
Oh yeah, whoops, I keep forgetting to do this
