### ISSUE TITLE
Handle `..` in tuple / tuple struct patterns (RFC 1492)

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustfmt#1021]
This was added in https://github.com/rust-lang/rust/pull/33639 as implementation for [RFC 1492](https://github.com/rust-lang/rfcs/blob/master/text/1492-dotdot-in-patterns.md). Support was added in syntex_syntax v0.33.

**Comment by sinkuu** [comment]
Sorry for cluttering!
Fix: #1151
