### ISSUE TITLE
Break out lints into a separate binary

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustfmt#1027]
I just skimmed the open 1.0 blockers to get an idea of what's out there. #209 (Check for license) jumped out as one that is more like linting than formatting. This goes along with TODO / FIXME checking in my opinion.

From my perspective as a user, this functionality should be in a separate tool, let's say `rustlint` for lack of a better name.

In https://github.com/rust-lang-nursery/rustfmt/pull/798#issuecomment-194228458, @nrc said

> Yeah, I have been considering a less monolithic vision recently. I'm not exactly how it should work and how to make it ergonomic though. 

I understand an overarching motivation from @nrc's point of view is to replace `make tidy` in the rust repo (#20). We can still get there by breaking out those lints into a separate binary that lives under the `rustfmt` repo—most easily in the same crate. I haven't looked at control flow to see how mixed in these features are, but it seems like it should be possible given the code is already there.

**Comment by nrc** [comment]
What is the advantage of a separate binary over configuration options for these things?

**Comment by kamalmarhubi** [comment]
I think that's not really the right question. The only pro of a single binary I see is that it's the way it's done now. Given a tool that is called `rustfmt` and whose tag line is `Formats Rust code`, I don't really expect it to give me any warnings about anything. As I wrote in #798:

> rustfmt is a *formatting* tool: it takes code in, and spits out better formatted code that abides by conventions. *Reporting* style deviations belongs in a lint tool.

This fits expectations across language ecosystems: I can't think of a language where a formating tool produces warnings about style issues. Ones I've looked at: [clang-format], [gofmt], [autopep8].

[autopep8]: https://github.com/hhatto/autopep8#usage
[clang-format]: http://clang.llvm.org/docs/ClangFormat.html
[gofmt]: https://golang.org/cmd/gofmt/

**Comment by nrc** [comment]
The pro is that from a user's point of view, they only need one tool instead of several. That convenience is important. I would argue that any IDE is a formatting tool that produces warnings about all sorts of errors, so there is (sort of) precedent. 

Anyway, I'm open to the idea of multiple tools, just want to properly evaluate the pros and cons.

**Comment by kamalmarhubi** [comment]
> Anyway, I'm open to the idea of multiple tools, just want to properly evaluate the pros and cons.
