### ISSUE TITLE
missing comment after attribute

### ISSUE THREAD

**Issue by waywardmonkeys** [rust-lang-nursery/rustfmt#1029]
``` rust
pub struct Foo {
    #[doc(hidden)]
    // This will get deleted.
    bar: String,
}
```

As indicated by the comment, running that block through rustfmt results in the comment going away. Happens on the playground as well as my local install.

**Comment by dhardy** [comment]
Same if comment is at the end of the line:
```
struct X {
    // `x` is an important number.
    #[allow(unused)] // TODO: use
    x: u32,
}
```

*Please* fix. In general there is very little one can assume about comments without reading them; e.g. in my example above it would not be valid to move the "TODO" comment in any way other than changing the number of spaces before and after the `//`; if this is bad style, leaves too long lines or whatever then *rustfmt* still cannot do anything other than warn about it (at least, unless the style guide specifically mentions how to wrap long comments following an attribute).

**Comment by mjkillough** [comment]
This is similar to #410, which is about the comments at the end of the line, after the attribute.

**Comment by sanmai-NL** [comment]
Both bugs reported here are still present: See: https://is.gd/zDlsfT. In addition, see another bug, third in the example: attributes within a function block that have a trailing comment become deindented.
