### ISSUE TITLE
Weird formatting of method signature

### ISSUE THREAD

**Issue by nagisa** [rust-lang-nursery/rustfmt#1036]
![screenshot from 2016-06-05 18-49-02](https://cloud.githubusercontent.com/assets/679122/15806557/3922043a-2b4e-11e6-876a-3d7956c494b5.png)

from https://github.com/rust-lang/rust/pull/34087/files#r65819646

**Comment by nagisa** [comment]
Another weird one 
![screenshot from 2016-06-05 18-50-32](https://cloud.githubusercontent.com/assets/679122/15806579/67528faa-2b4e-11e6-9aa8-c33ffb647a09.png)

**Comment by nrc** [comment]
We don't tend to go massively multi-line on types. I actually like what Rustfmt has done on the second example. The first is arguable, but I find the first a bit weird, guess it is just something I don't see very often.

**Comment by nagisa** [comment]
Why is it putting a `->` under a `self` rather than under `fn` or `fn` + 1 indent in 2nd example?

**Comment by nrc** [comment]
@nagisa the style is to align the `->` with the arguments (I personally prefer it aligned with indent + 1, but the current style was more popular). It looks better when there are many arguments, rather than just `self`, and when the return type isn't so long.
