### ISSUE TITLE
Split impl<...> X for Y<...> at 'for'

### ISSUE THREAD

**Issue by nagisa** [rust-lang-nursery/rustfmt#1037]
![screenshot from 2016-06-05 18-52-08](https://cloud.githubusercontent.com/assets/679122/15806588/bab0d440-2b4e-11e6-8906-8d9d797d6d90.png)

**Comment by dawirstejeck** [comment]
I will take a look at this.

**Comment by dawirstejeck** [comment]
I find this quite tough to do right. Could take a bit.

**Comment by nrc** [comment]
I would examine `self_ty.rewrite`, which is the concrete type of the `impl` declaration. If it contains a newline, then I would try reformatting it on a newline (this only requires changing the indent and budget supplied to the function). You could then compare the two versions, but I think that actually you could always put a newline before `for` in this case and use the second reformatting.

I think checking for a newline in the reformatted type is all you need to do - you will never affect the earlier part of the impl, and that is the only place that a linebreak can happen. You could also try this if the result of reformatting was `None` - in that case we couldn't fit the text into the budget, but if you give more space (by inserting the newline before `for`, then there might be enough space.

You should just check that when you do split, `where` clauses are still handled properly.

Also, you'll need to delay actually appending `for` until you have the final string for the type.

Ping me on irc if you want more info.

**Comment by dawirstejeck** [comment]
Thanks @nrc! I will come up with something.
