### ISSUE TITLE
`impl` + attribute + comment ⇒ missing whatever was before the comment

### ISSUE THREAD

**Issue by mcarton** [rust-lang-nursery/rustfmt#1040]
*rustfmt* currently produce invalid code on [one of Clippy‘s file](https://github.com/Manishearth/rust-clippy/blob/a2c427470bb6c21ca0f0cafd65b9dd182917c3be/clippy_lints/src/misc.rs).
I've been able to reduce it to this:

```rust
impl LateLintPass for UsedUnderscoreBinding {
    #[cfg_attr(rustfmt, rustfmt_skip)]
    fn check_expr() { // FIXME: #944
    }
}
```

which produces:
```diff
3c3,4
<     fn check_expr() { // FIXME: #944
---
> 
>     // FIXME: #944
```

**Comment by marcusklaas** [comment]
I suspect we're passing skipped parts through the missed spans machinery, whereas we should probably just take the associated string verbatim.
