### ISSUE TITLE
Flag for CI which ensures no formatting happens

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustfmt#1041]
Thinking through how rustfmt might be integrated into the CI of a project it might be easiest to have a flag like `--verify` which causes rustfmt to return a nonzero exit code if any changes were made. That is, all PRs would fail to land unless they'd been properly formatted by rustfmt.

Does that sound reasonable to others?

**Comment by marcusklaas** [comment]
This is a fairly high priority issue: https://github.com/rust-lang-nursery/rustfmt/issues/860. There's already a PR for this too. I don't know in what state it currently is though. It needs a rebase at the very least.

Closing this for being a dupe.

**Comment by alexcrichton** [comment]
Oh oops, I looked around but failed to find that, thanks for the pointer and sorry for the noise!
