### ISSUE TITLE
Not splitting `else if` between 102 and 124 cols long

### ISSUE THREAD

**Issue by jeanm** [rust-lang-nursery/rustfmt#1044]
Here's a very odd one for you: `else if` lines of length between 102 and 124 columns crash `cargo fmt`.

It complains that it can't deal with the lines because they are too long, but if you try to break them up into multiple lines it will put them back into a single line, and then complain again about the length. This behaviour does not seem to occur with `if` lines, oddly enough.

```rust
// This works
fn main() {
    if false {
        println!("No");
    } else if true {
        println!("Yes");
    }
}

// Making the if line really long works
fn main() {
    if false && false && false && false && false && false && false && false && false && false && false && false {
        println!("No");
    } else if true {
        println!("Yes");
    }
}

// Making the else if line 102 cols long does not work (but up to 101 seems fine).
// If I break up the long line, cargo fmt will put it back together and then complain again
fn main() {
    if {
        println!("No");
    } else if true && true && true && true && true && true && true && true && true && 1234 != 12345 {
        println!("Yes");
    }
}

// Once we get to 125, all is fine again!
fn main() {
    if false {
        println!("No");
    } else if true && true && true && true && true && true && true && true && true && true && 1234567 == 1234567 && 1 == 1 {
        println!("Yes");
    }
}
```

I have tested this on rust 1.9 with rustfmt 0.5.0 (via `cargo fmt`), and with the Rust Playground in debug mode on the stable channel.

**Comment by marcusklaas** [comment]
Weird! I tinkered with this a few days back. I'll try to figure out what's going on.

**Comment by marcusklaas** [comment]
Please note that `cargo fmt` doesn't crash. It just returns with errors to signal that not everything went according to plan. @nrc: other people have had the same confusion - anything we could do to communicate this more clearly?

**Comment by marcusklaas** [comment]
I can confirm that this has been fixed in https://github.com/rust-lang-nursery/rustfmt/pull/1032. We just haven't bumped rustfmt's version yet. Should be fine after that.

**Comment by nrc** [comment]
Hmm, maybe we can be clearer about the formatting or wording of the messages?
