### ISSUE TITLE
short args, long return type looks bad

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1047]
```
pub fn ascend
        (self)
         -> Result<Handle<NodeRef<BorrowType, K, V, marker::Internal>, marker::Edge>, Self> {
```

easy fix - put the args on one line and the return type, block indented, on the next line.

**Comment by gereeter** [comment]
Note that the reason that rustfmt split the lines like this (I think) is because if the args were on the function definition line and the return type were aligned with the beginning of the argument list, then the result would be overlong.

**Comment by nagisa** [comment]
https://github.com/rust-lang-nursery/rustfmt/issues/1036

**Comment by marcusklaas** [comment]
@gereeter correct. I think figuring out sane heuristics for this is actually not trivial.

**Comment by nrc** [comment]
assigning to myself for mentoring

**Comment by imjacobclark** [comment]
I'll pick this issue up with some help from @nrc!

**Comment by topecongiro** [comment]
Closing since this is no longer an issue with the RFC style.
```rust
pub fn ascend(
    xxxx: i32,
) -> Result<Handle<NodeRef<BorrowType, K, V, marker::Internal>, marker::Edge>, Self> {
}
```
