### ISSUE TITLE
Overlong impl

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1048]
```
impl<BorrowType, K, V, NodeType, HandleType> Handle<NodeRef<BorrowType, K, V, NodeType>, HandleType> {
```

I assume this is an off by n error.

**Comment by nagisa** [comment]
https://github.com/rust-lang-nursery/rustfmt/issues/1037

**Comment by nrc** [comment]
This isn't a dup of #1037 - that is poor formatting where we split the type rather than the impl, here we are not splitting at all and cause an overflow.

**Comment by brson** [comment]
See https://github.com/rust-lang-nursery/rustfmt/issues/1049#issuecomment-228641089 for hints about how to fix.
