### ISSUE TITLE
Overlong function signature

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1049]
```
    pub unsafe fn reborrow_mut(&mut self) -> Handle<NodeRef<marker::Mut, K, V, NodeType>, HandleType> {
```

**Comment by nrc** [comment]
Another example:

```
    pub fn merge(mut self) -> Handle<NodeRef<marker::Mut<'a>, K, V, marker::Internal>, marker::Edge> {
```

**Comment by marcusklaas** [comment]
How is this possible?

**Comment by brson** [comment]
Since this is tagged easy, how might one go about fixing it (and https://github.com/rust-lang-nursery/rustfmt/issues/1048)?

**Comment by nrc** [comment]
I would start here: https://github.com/rust-lang-nursery/rustfmt/blob/master/src/items.rs#L1221 and insert a bunch of printlns (or use a debugger) to figure out the path the code is taking and the widths being passed down to the helper functions, at some point it should be clear that a helper is being asked to format into a width that is one larger than it ought to be. Whilst not being a lot of fun, this is usually quite easy to figure out. Exactly how to fix it depends on what the problem looks like. It might be as simple as adding a constant `1` to something.

**Comment by dawirstejeck** [comment]
Tried to reproduce it by writing a test with your first example. To make it accept the function I adapted the signature a bit. The output looks good:
`pub unsafe fn reborrow_mut(&mut AAAAAAAAA: Test)
                           -> Handle<NodeRef<marker::Mut, K, V, NodeType>, HandleType> {
}`
Am I missing something?

**Comment by juicejitsu** [comment]
whoops sorry made a mistake

**Comment by brson** [comment]
@juicejitsu Great! @nrc can you help @juicejitsu land this fix? Looks like they've got a patch ready to go.

**Comment by dawirstejeck** [comment]
@juicejitsu I had the same idea like you but there are at least two corner cases which have to be considered. Please have a look at #1089. Maybe you want to finish that PR? Sadly I have nearly no spare time right now...

**Comment by juicejitsu** [comment]
@dawirstejeck Sure! Taking a look

**Comment by dawirstejeck** [comment]
This can be closed now, right?
