### ISSUE TITLE
Weird indentation for match arms in chain

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/rustfmt#1056]
``` rust
fn default_user_agent_string(agent: UserAgent) -> String {
    match agent {
        UserAgent::Desktop => {
            DESKTOP_UA_STRING
        }
        UserAgent::Android => {
            "Mozilla/5.0 (Android; Mobile; rv:37.0) Servo/1.0 Firefox/37.0"
        }
    }.to_owned()
}

fn main() {}
```

yields

``` rust
fn default_user_agent_string(agent: UserAgent) -> String {
    match agent {
            UserAgent::Desktop => DESKTOP_UA_STRING,
            UserAgent::Android => "Mozilla/5.0 (Android; Mobile; rv:37.0) Servo/1.0 Firefox/37.0",
        }
        .to_owned()
}

fn main() {} main() {}⏎
```

**Comment by jdm** [comment]
It works fine if the `.to_owned()` isn't present in the original.

**Comment by marcusklaas** [comment]
This is sort-of by design. Didn't you want to hold off the default settings discussion until after 1.0 @nrc?

**Comment by nrc** [comment]
How is it by design? I do want to hold off on getting the defaults exactly right, but this seems like a bug.

**Comment by marcusklaas** [comment]
This is the exact discussion we had [here](https://github.com/rust-lang-nursery/rustfmt/pull/1016) if I'm not mistaken.

**Comment by nrc** [comment]
Oh yes, it is! I thought this would be fixed by #1016, but apparently not?

**Comment by marcusklaas** [comment]
This isn't question mark related. I'm glad you seem to agree now that it needs fixing though ;-)

**Comment by nrc** [comment]
Oh right, it is this thing. Yeah, looking at it with fresh eyes, it is pretty bad. Still don't like the alternative though.

**Comment by topecongiro** [comment]
Closing since this is fixed on the current master.
