### ISSUE TITLE
Projections of nested tuple structs turn into syntax errors

### ISSUE THREAD

**Issue by sorear** [rust-lang-nursery/rustfmt#1063]
Start with this valid code (playpen: https://is.gd/rPUytX):

``` rust
fn main() {
    let x = ((1u8, 2), 3);
    println!("{}", x.0 .0);
}
```

Click "format"; rustfmt will delete the space in `.0 .0`, but `.0.0` is a syntax error because the lexer interprets `0.0` as a float literal.

**Comment by marcusklaas** [comment]
Hmmm.. not sure how we should format this. Perhaps the best solution is just to force a multi-line format when two consecutive tuple accesses are detected.

**Comment by sorear** [comment]
My preference would be to inject a single space as in the example above, although I have no idea how difficult that'd be.  Requiring a newline seems weird, given that it'd make extremely short lines.

**Comment by srinivasreddy** [comment]
I would prefer this way though,
```
fn main() {
    let x = ((1u8, 2), 3);
    println!("{}", (x.0).0);
}

```

**Comment by sorear** [comment]
@srinivasreddy That's what I wound up doing to make the present rustfmt accept my code, and I'd be 100% OK with rustfmt generating that if it's as easy or easier than my proposal.
