### ISSUE TITLE
long method chain in if condition gives confusing formatting

### ISSUE THREAD

**Issue by Apanatshka** [rust-lang-nursery/rustfmt#1069]
Input:

``` rust
                if let Some(&state) = nfa.states[cur_state].transitions.get(&byte).unwrap().get(&0) {
                    cur_state = state;
                }
```

Output:

``` rust
                if let Some(&state) = nfa.states[cur_state]
                    .transitions
                    .get(&byte)
                    .unwrap()
                    .get(&0) {
                    cur_state = state;
                }
```

I know the code is messy, but that's the current state of my project. 
What I find confusing about the output here is that the method chain is aligned with the body of the if. My suggestion would be either double indent the chain or put the curly brace on a new line:

``` rust
                if let Some(&state) = nfa.states[cur_state]
                        .transitions
                        .get(&byte)
                        .unwrap()
                        .get(&0) {
                    cur_state = state;
                }
```

``` rust
                if let Some(&state) = nfa.states[cur_state]
                    .transitions
                    .get(&byte)
                    .unwrap()
                    .get(&0)
                {
                    cur_state = state;
                }
```

**Comment by killercup** [comment]
Personally, I would prefer to move the first part into the new block as well,

```rust
if let Some(&state) =
    nfa.states[cur_state]
    .transitions
    .get(&byte)
    .unwrap()
    .get(&0)
{
    cur_state = state;
}
```

But it would be even better to just make a new binding for this, e.g. `let state = ...` and shadow `state` in the if-let.

**Comment by dhardy** [comment]
This still needs fixing. My vote would be to *both* double-indent any hanging parts of the `if` condition and put the opening `{` on a new line where the `if` condition is longer than a single line.

**Comment by topecongiro** [comment]
Closing since on the current master rustfmt puts the opening brace on the next line when the condition goes multi line.
