### ISSUE TITLE
Weird alignment of documentation comments

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#1070]
The documentation comments of my whole crate are aligned to the beginning of the line instead of having the proper indentation of the item they document: 

https://github.com/gnzlbg/bitwise/blob/master/src/lib.rs#L58

**Comment by ambaxter** [comment]
Same for me. Neither rustdoc comments nor regular comments are immune. It also appears haphazardly throughout my codebase :/

**Comment by BenjaminGill-Metaswitch** [comment]
I'm getting the same problem. I suspect that it's being triggered by long (> 1 line's worth) trait constraints - my minimal repro is below. I'll have a dive in and see if I can work out what's causing this...

```rust
pub trait ATrait
    : std::fmt::Display
    + std::fmt::Display
    + std::fmt::Display
    + std::fmt::Display
    + std::fmt::Display
{
    /// A comment
    fn do_something();
}
```

**Comment by BenjaminGill-Metaswitch** [comment]
My repro appears to now be working correctly. I suspect this issue has been fixed by https://github.com/rust-lang-nursery/rustfmt/releases/tag/v0.7
