### ISSUE TITLE
Deal with merge conflicts

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#1072]
Rustfmt should at least detect that it is being run on files with merge conflicts:

``` rust
<<<<<<< HEAD
...
=======
...
>>>>>>> commit hash / branch name
```

and probably bail out gracefully (this would be a good start). 

I don't know if it is possible to indent code within the different "merge branches" but even if it were possible I don't think it is sensible to do so (what should happen is that the user fixes the merge conflict).

**Comment by nrc** [comment]
We can't really do this because we use the Rust parser, we'd need to implement it there.
