### ISSUE TITLE
Have a way to easily avoid performing semantic transformations

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#1074]
I execute rustfmt _a lot_ while writing code.

I hate that it removes the `mut` from variables / function arguments just because I don't need `mut` yet.

I appreciate a tool that fixes / lints on these issues _at the points in the development process in which I want them fixed_, but there is nothing more annoying than writing a function prototype or block with some `mut` variable, hitting `tab` for it to get automatically indented using `rustfmt`, and seeing the `mut` from a variable removed just because I haven't written the line that mutates it yet... Having to either undo or retype it again is annoying.

A flag would probably be enough, although `rustfmt --format`, `rustfmt --format-only`, `rustfmt --please-change-the-format-only` sound creepily tautological too me. 

I've argued this before but in my opinion the root of the problem is that `rustfmt` tries to solve many (hard) problems as if they were one intertwined problem instead of solving single hard problems separately (and as a consequence does a poor job in solving some of them). 

A way healthier tooling ecosystem would be built on top of:

- a formatting-only tool (that ensures code is well indented),
- a rewrite engine (that ensures that code transformations compile),
- an AST matching engine (to detect things to be rewritten), and
- an AST transformation engine (to specify how the AST should be transformed). 

Tools like clippy, the semantic parts of rustfmt, some other rustfix tool, a tool that rewrites variables/types/traits names to conform to coding conventions, extra static analysis,  _and many others_, could then easily be written on top of these primitive tools that do one hard thing and one hard  thing only (maybe one can write a tooling framework on top of these primitives as well to make writing tools even easier).

**Comment by marcusklaas** [comment]
I'm surprised that rustfmt does this at all. Could you give an example of code where the `mut` modifier is removed?

**Comment by gnzlbg** [comment]
Am I dreaming? I would swear this happened to me yesterday a couple of times and today but I cannot reproduce it so I'm closing this. Weird.
