### ISSUE TITLE
Removes the `default` keyword for specialization

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang-nursery/rustfmt#1079]
```
impl<T, N, Ty> VectorImpl<T, N, Ty> for Vector<T, N, Ty>
    where T: Float + Zero,
          N: ArrayLength<T>,
          N::ArrayType: Copy,
          Vector<T, N, Ty>: Copy
{
    default fn dot(self, other: Self) -> T {
            Iterator::zip(self.data.into_iter(), other.data.into_iter())
            .fold(T::zero(), |acc, (x, y)| acc + x * y)
    }
}
```
to

```

impl<T, N, Ty> VectorImpl<T, N, Ty> for Vector<T, N, Ty>
    where T: Float + Zero,
          N: ArrayLength<T>,
          N::ArrayType: Copy,
          Vector<T, N, Ty>: Copy
{
    fn dot(self, other: Self) -> T {
        Iterator::zip(self.data.into_iter(), other.data.into_iter())
        .fold(T::zero(), |acc, (x, y)| acc + x * y)
    }
}
```

I am using version 0.5.0

**Comment by nrc** [comment]
This is fixed on master. You could either build from source or wait for the next release, which should be later this week or early next week.

**Comment by nrc** [comment]
This is fixed on master. You could either build from source or wait for the next release, which should be later this week or early next week.

**Comment by coriolinus** [comment]
@nrc There doesn't appear to have been a release fixing this as yet; the last release is still 0.5.0 at https://github.com/rust-lang-nursery/rustfmt/commit/67edc325c6c35475593ac54d3704f474c09d059e. Do you have an updated schedule for the release?

**Comment by nrc** [comment]
@coriolinus I made a 0.6 release today: https://crates.io/crates/rustfmt
