### ISSUE TITLE
Trailing commas on where clauses

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustfmt#1085]
Right now rustfmt formats where clauses like:

```rust
pub struct A<T, U>
    where T: Bar, 
          U: Baz  
{                 
    a: usize,     
}                 
```

Perhaps though there could be a trailing comma after `U: Baz`? (similar to struct fields and such)

**Comment by nrc** [comment]
You just need to set the `where_trailing_comma` option and then you shall have it.

**Comment by alexcrichton** [comment]
Aha, thanks!
