### ISSUE TITLE
No formatting for match arms containing /*...*/ comments

### ISSUE THREAD

**Issue by aleksander** [rust-lang-nursery/rustfmt#1087]
rustfmt 0.5.0

this code:

``` rust
fn test(value: u8) {
    match value {
    0 => {
            fn1();
        }
            _ /*comment*/ => {
            fn2();
        }
    }
}
```

should be formatted as follows:

``` rust
fn test(value: u8) {
    match value {
        0 => {
            fn1();
        }
        _ /*comment*/ => {
            fn2();
        }
    }
}
```

but it's not.

**Comment by nrc** [comment]
Guessing that the comment makes us unable to format the match arm and we just give up. Long term, if we had more spans this is an easy fix. Short term, could search for text `=>` and carry on formatting the rest of the match arm.

**Comment by nrc** [comment]
Closing as a dup of #2188

**Comment by aleksander** [comment]
@nrc this issue is still reproducible, but now rustfmt is unable to format with the following `internal error: not formatted because a comment would be lost`.

**Comment by nrc** [comment]
We only catch comments after the `=>`, so you could move the comment as a work around. Catching the comments before the `=>` is much harder and not going to happen soon (there are lots of places we currently can't catch comments, unfortunately). The new warning highlights where that happens.
