### ISSUE TITLE
Do not reformat ////////////

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rustfmt#1094]
Before:

```rust
////////////////////////////////////////////////////////////////////////////////
```

After:

```rust
/// /////////////////////////////////////////////////////////////////////////////
```

Rustfmt puts a space after the first 3 which incorrectly turns this into a doc comment.

**Comment by srinivasreddy** [comment]
This i am taking

**Comment by nrc** [comment]
dup of #652 

@srinivasreddy If you want to look at #652, please do! If you need any help please ping me on irc.
