### ISSUE TITLE
Unclosed comment after empty type parameter bound

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rustfmt#1095]
Before:

``` rust
struct S<T: /* comment */> {
    t: T,
}
```

After:

``` rust
struct S<T /* : /* comment */> {
    t: T,
}
```

**Comment by nrc** [comment]
With default options, this now gives:

```
struct S<T : /* comment */> {
    t: T,
}
```

Which is not great formatting around the `:`, but at least it is not changing the source meaningfully. With `normalize_comments = true`, there is still the buggy behaviour.
