### ISSUE TITLE
Tests fail under Windows

### ISSUE THREAD

**Issue by studoot** [rust-lang-nursery/rustfmt#1097]
The source tests involving non-empty `file_lines` (that's `file-lines-1.rs`, `file-lines-2.rs` and `file-lies-3.rs`) fail when run under Windows. This is because the path in the test files is specified entirely with forward slashes as path separators, while the file paths supplied to the `check_files` function have a backslash separating directory from filename.

I have a pull request (#1098) that implements _a_ fix - whether or not it's an appropriate fix is anther matter - I am a Rust noob!

**Comment by studoot** [comment]
Maybe adding an Appveyor build to run the tests under Windows would complement the Travis one?

**Comment by nrc** [comment]
Thanks for reporting and fixing this!

Adding Appveyor is kind of on my radar - we've discussed it in the context of generating binaries for distribution, but of course having testing for Windows would be really good.

**Comment by nrc** [comment]
Tests now work on Windows, closing.
