### ISSUE TITLE
Comments are not correctly formatted in macro_rules if rule has long line

### ISSUE THREAD

**Issue by natemara** [rust-lang-nursery/rustfmt#1105]
If any of the rules in a `macro_rules!` block have a line that is more than rustfmt's 100 character limit, then rustfmt will put all comments to the far left edge of the file: as a minimum example, the following file is correctly formatted:

``` rust
macro_rules! foo {
    // This is a comment
    () => {
        let a_very_long_identifier_name_that_is_certainly_going_to_make_this_line_too_long_for_rustfmt = 2u8;
    };
}
```

But if you run it through rustfmt, you get this:

``` rust
macro_rules! foo {
// This is a comment
    () => {
        let a_very_long_identifier_name_that_is_certainly_going_to_make_this_line_too_long_for_rustfmt = 2u8;
    };
}
```

Making line 4 shorter will yield the expected formatting. For the lazy, here is a playground link that you can format to see this issue: https://is.gd/QgFH3Z

**Comment by nrc** [comment]
This example is fixed on master now
