### ISSUE TITLE
Add an option to leave a space between a variable name and a colon

### ISSUE THREAD

**Issue by HighCommander4** [rust-lang-nursery/rustfmt#1109]
When a variable or parameter has a type annotation, I prefer to leave a space between the variable name and the colon:

`let variable : Type = expr;`

However, rustfmt removes that space and doesn't seem to have an option to preserve it. I would like to suggest adding such an option.

**Comment by nrc** [comment]
This would be pretty easy to add, if you'd like to have a go I'd be happy to mentor.

**Comment by HighCommander4** [comment]
Sure, why not :)

**Comment by HighCommander4** [comment]
Here's a first attempt at a patch: https://github.com/HighCommander4/rustfmt/commit/2b4ccab9957b3554e2e51b564df019137d4c3f38

It handles local variables, global variables, function parameters, and trait bounds. There are no tests yet, but I'll write some for the next iteration of the patch. (I did test the changes by running the modified rustfmt on an example file.)

 Couple of questions:

- The name and description of the config option mention "type annotations", but the option also applies to trait bounds. Is there an umbrella term that would encompass both type annotations and trait bounds?
- Are there other syntactic constructs in the language, similar to type annotations and trait bounds, that the option should apply to?

**Comment by nrc** [comment]
I would have separate options for types in decls and trait bounds.

I would probably apply the variable option to fields too (assuming you do that in your code), and the trait bounds one to other type and lifetime bounds.

**Comment by HighCommander4** [comment]
Updated patch to handle fields and lifetime bounds, with the trait and lifetime bounds controlled by a separate option as suggested. Also added tests: https://github.com/rust-lang-nursery/rustfmt/pull/1110

**Comment by HighCommander4** [comment]
I realized there is an additional context in which I'd like to have a space: when constructing a struct, e.g.:

```
struct Point {
  x : i32,
  y : i32
}
fn main() {
  let pt = Point {
    x : 42,   //  <-- here
    y : 42    //  <-- and here
  };
}
```

However, that's neither a "type annotation", nor a "bound"; should I introduce yet another option for it?

**Comment by nrc** [comment]
I would include it with type annotation, since I imagine one would always want a struct decl and a struct ctor to look the same.

**Comment by HighCommander4** [comment]
> I would include it with type annotation, since I imagine one would always want a struct decl and a struct ctor to look the same.

Sounds good - implemented in https://github.com/rust-lang-nursery/rustfmt/pull/1119

**Comment by HighCommander4** [comment]
Thanks for the reviews! The patches that were merged implement this option as I envisioned it, so I think the issue can be closed.
