### ISSUE TITLE
rustfmt incorrectly strips the "default" keyword from speciallized functions

### ISSUE THREAD

**Issue by tupshin** [rust-lang-nursery/rustfmt#1112]
With the beginning of specialization in nightly, per https://github.com/rust-lang/rust/issues/31844 it is now possible to do things like
```
impl<T, C> Foo<T, C> for () {
    default fn len(&self) -> isize {
        2
    }
}

impl<T> Foo<T, ()> for () {
    fn len(&self) -> isize {
        0
    }
}
impl Foo<i32, ()> for i32 {
    fn len(&self) -> isize {
        1
    }
}
```
Unfortunantely running rustfmt breaks compilation by removing default`

**Comment by nrc** [comment]
This is fixed on master, but I guess not in the latest realease. I should do a new release soon that includes this fix.

**Comment by tupshin** [comment]
Oh great. Thanks.

**Comment by gnzlbg** [comment]
+1 . I've been scratching my head for a while because of this. I thought I was going crazy.
