### ISSUE TITLE
Don't save *.rs.bk if VCS is detected

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustfmt#1114]
We've gotten a few issues on Cargo to add `*.rs.bk` to the default gitignore, but I personally like to keep that pretty clean and I'd prefer if rustfmt just didn't generate these files by default. Especially if git is detected, _and_ perhaps if the working directory is clean, could bk files not be generated by default?

**Comment by tikue** [comment]
hear! hear!

**Comment by konstin** [comment]
Any progress on that? This should be as simple as checking whether `git status --porcelain` prints anything to stdout.

**Comment by nrc** [comment]
This is not really on my radar, priority-wise. If anyone would like to have a go at this I'd be happy to mentor.

**Comment by nrc** [comment]
We're on our way to emitting backup files by default, so I don't think this will be so much of an issue

**Comment by tshepang** [comment]
@nrc is this rejected?

**Comment by nrc** [comment]
@tshepang We don't create bk files by default any more, so I don't think it is that useful (if the user turns on the option, I assume they really want it, not VCS-dependent).

**Comment by tshepang** [comment]
oh, that's fine
