### ISSUE TITLE
rustfmt not no-op on empty braces in Rust repository

### ISSUE THREAD

**Issue by matthew-piziak** [rust-lang-nursery/rustfmt#1125]
Running `rustfmt` on `src/libstd/primitive_docs.rs` produces the following changes:

```
diff --git a/src/libstd/primitive_docs.rs b/src/libstd/primitive_docs.rs
index de891ea..0cfc38d 100644
--- a/src/libstd/primitive_docs.rs
+++ b/src/libstd/primitive_docs.rs
@@ -56,7 +56,7 @@
 ///
 /// Also, since `bool` implements the [`Copy`](marker/trait.Copy.html) trait, we don't
 /// have to worry about the move semantics (just like the integer and float primitives).
-mod prim_bool { }
+mod prim_bool {}
...
```

The ideal is for `rustfmt` to be a no-op on files from the official Rust repository. I am aware that this is not the case in practice. 

I searched the following:
- `rustfmt --config-help` configuration options
- the rustfmt issue tracker
- the Rust issue tracker

I was unable to find relevant configuration options or tickets. It is highly likely that I simply missed it, in which case I would appreciate this issue being marked as a duplicate.

**Comment by nrc** [comment]
We are a long way off rustfmt'ing the Rust repo being a no-op. In particular, we need to do an initial pass of formatting before that will be the case.

This specific behaviour is expected, and is idempotent (once you run Rustfmt once, it won't change it the second time around).

**Comment by matthew-piziak** [comment]
Acknowledged. Thanks, @nrc.
