### ISSUE TITLE
`cargo fmt` for examples, tests, benches

### ISSUE THREAD

**Issue by dpc** [rust-lang-nursery/rustfmt#1126]

**Comment by nrc** [comment]
This would be kind of a big project, there's quite a bit of infrastructure to implement to make this work. On the other hand, it wouldn't require any fundamental changes to Rustfmt, so I don't think it is a high risk piece of work.

**Comment by conradkdotcom** [comment]
Same as in #803, this seems to work as expected now. Code in `tests`, `examples` and `benches` gets formatted with `cargo fmt`.
