### ISSUE TITLE
rustfmt stops formatting once a macro with a '<' is encountered

### ISSUE THREAD

**Issue by Bobo1239** [rust-lang-nursery/rustfmt#1128]
[repro demo with output and comments](https://github.com/Bobo1239/rustfmt_bug_demo)

When a macro uses the literal `<` in its pattern (e.g. [in nom](http://rust.unhandledexpression.com/nom/macro.named!.html)), and it gets used, every line after that line doesn't get formatted.
Interestingly that doesn't only affect the file in which the call happens. Depending on the order the files are formatted, all files after the file which contains the macro invocation don't get formatted. (see repro demo)

**Comment by nrc** [comment]
It is somewhat expected that we might fail to format the macro use, but that should not stop us formatting anything else.
