### ISSUE TITLE
Add support for the Rustic Style Guide

### ISSUE THREAD

**Issue by ubsan** [rust-lang-nursery/rustfmt#1130]
Preferably, it should be a single flag in the `rustfmt.toml`, and easy to use.

**Comment by nrc** [comment]
We've generally shied away from having meta-flags for configuration, although with the new style RFC process we should probably start for RFC PRs. For complete styles like this, I think we should make sure that flags exist for all options necessary, then have a single rustfmt.toml with all the correct options set and make that available either in the Rustfmt repo or elsewhere. We could add tests using that toml file too (which might need a little code in the test infra to use a config file outside the test directory, but nothing rocket science).

**Comment by ubsan** [comment]
Well, there would have to be a lot of options added :)

**Comment by euclio** [comment]
@ubsan Can you link to the "Rustic style guide"?

**Comment by ubsan** [comment]
@euclio ubsan.github.io/style/

Dunno how I forgot that...

**Comment by russmack** [comment]
+1 for alternate format - rustfmt converting my block comments to line comments gets my goat.
