### ISSUE TITLE
Actually write down the rustfmt style guide

### ISSUE THREAD

**Issue by ubsan** [rust-lang-nursery/rustfmt#1131]
Currently the spec is the implementation, afaict. This means it's not possible to find bugs, nor is it possible to work on the style guide separately from rustfmt.

**Comment by nrc** [comment]
I'm hoping that to some extent this will be addressed by the style RFC process. I tried to start this in the past, but I found that the detail needed for a Rustfmt spec was way, way more than was reasonable for a style guide. I'm pretty sure we won't get a single document that is both useful to human programmers and to implementers of Rustfmt.

I hope that we can put a style guide together as part of the style RFC process (probably later in the process, tbh. I expect the primary artefact to be more spec-like and less style guide). Doing that early, assuming we make many changes, seems like wasted effort.

**Comment by ubsan** [comment]
I disagree. Currently, we have no idea what the rustfmt style guide is beyond "what rustfmt spits out". I *don't* think a specification is necessary, just a style guide. It took me a few hours, plus a few hours of editing, and talking to other people, to create the Rustic style guide. I doubt the rustfmt guide would even take that long.

The importance of this is that we can look at a real style when deciding on style RFCs.
