### ISSUE TITLE
reorder-imports can lead to leading empty newlines that serve no purpose

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#1137]
``` Rust
use b1;
use b2;
use b3;
// Logical empty line to separate 2 groups of imports
use a1;
use a2;
use a3;

fn foo() {}

```

gets reformatted to

``` Rust
// empty line at the beginning that serves no logical purpose
// empty line at the beginning that serves no logical purpose
use a1;
use a2;
use a3;
use b1;
use b2;
use b3;

fn foo() {}

```

Empty lines at the beginning of a block serve no separation purposes, since they are before the first item on the list.

cc @studoot

**Comment by dzamlo** [comment]
I think this is related to the following issue:

When formatting this with reorder_imports = true:
```rust
use b;
use a;
use c;
```

The result is this
```rust

use a;use b;
use c;
```

Note the empty line at the start and the  missing newline between a and b.

**Comment by crumblingstatue** [comment]
@dzamlo That would be #1124

**Comment by studoot** [comment]
Yep - I've just tested formatting @dzamlo's case with version 0.6.0 and with HEAD, and PR #1133 has fixed that problem.

**Comment by crumblingstatue** [comment]
This is definitely a bug, even if keeping the empty line is intended, as running rustfmt a second time actually removes the empty line in this example:

Original:
```Rust
use b;
use a;

fn foo() {}

```

Rustfmt  pass 1:
```Rust
// empty line
use a;
use b;

fn foo() {}

```

Rustfmt pass 2:
```Rust
use a;
use b;

fn foo() {}

```

**Comment by tomwhoiscontrary** [comment]
This still seems to happen:

```
use std::io;

use SomeTopLevelStruct;

pub fn foo() {}
```

Becomes:

```


use SomeTopLevelStruct;
use std::io;

pub fn foo() {}
```

I'm on the latest released version:

```
$ cargo fmt -- --version
0.8.0 ()
```

**Comment by crumblingstatue** [comment]
This now also occurs with extern crates. It sounds to me like the same issue, except that `reorder_extern_crates` is a default setting now, so it's not `only-with-option`.
