### ISSUE TITLE
A line-broken struct literal is indented one level too deep if followed by a method call

### ISSUE THREAD

**Issue by nabijaczleweli** [rust-lang-nursery/rustfmt#1139]
Happens on: v0.5, v0.6, `master` (https://github.com/rust-lang-nursery/rustfmt/commit/59e199b4393cb261865538944b527438eeb40a97)

Example code follows.

Expected:

``` rust
struct Struct {
    i: i32,
    j: i32,
    k: i32,
    l: i32,
    m: i32,
}

impl Struct {
    fn err(self) -> ! {}
}

fn main() {
    Struct {
        i: 0,
        j: 0,
        k: 0,
        l: 0,
    }
    .err();
}
```

Actual:

``` rust
struct Struct {
    i: i32,
    j: i32,
    k: i32,
    l: i32,
    m: i32,
}

impl Struct {
    fn err(self) -> ! {}
}

fn main() {
    Struct {
            i: 0,
            j: 0,
            k: 0,
            l: 0,
        }
        .err();
}
```

**Comment by nabijaczleweli** [comment]
Any updates on this?

**Comment by sinkuu** [comment]
Isn't this an intended behavior?  https://github.com/rust-lang-nursery/rustfmt/issues/816#issuecomment-223745478

**Comment by nabijaczleweli** [comment]
It looks ugly so I'd guess no :P

**Comment by nrc** [comment]
It kind of is intended behaviour, but it does look a bit ugly. I'm not sure what is preferable though? The constraint is that if there is a method chain, it should be indented, it would be nice, I guess to put the method call on the same line as the `}`, and then indent further items in the chain by a single space. I seem to remember there were issues with this approach though.

**Comment by topecongiro** [comment]
Closing since this is fixed on the current master.
