### ISSUE TITLE
Minimal Travis config not working

### ISSUE THREAD

**Issue by brettcannon** [rust-lang-nursery/rustfmt#1143]
I tried the minimal config as outlined in the README and I'm [getting an error](https://travis-ci.org/brettcannon/riscv-harmony/builds/156876008) about "Could not run rustfmt, please make sure it is in your PATH." (here is [my Travis config](https://github.com/brettcannon/riscv-harmony/blob/master/.travis.yml) but it matches the README exactly)

**Comment by palfrey** [comment]
I added `export PATH=$PATH:~/.cargo/bin &&` to the beginning of the `script` block which fixed it. See https://github.com/palfrey/potboiler/blob/master/.travis.yml (but ignore the "cd core &&" line)

**Comment by brettcannon** [comment]
Thanks, @palfrey , that did it!
