### ISSUE TITLE
Update Guidelines around Syntex_syntax/nightly strategy

### ISSUE THREAD

**Issue by josephDunne** [rust-lang-nursery/rustfmt#1145]
Hi, I am trying to find information around how rustfmt handles changes on nightly. Is the policy to only support stable/beta? If so can I get the official policy so that I can update the guidelines. If not can we update syntex_syntax so that rustfmt can support impl traits. Thank you!

**Comment by nrc** [comment]
We want to be able to run on stable. Theoretically, we could `cfg` ourselves to success using nightly-only features, but I don't think it is worth it and I don't think that would work for something like `impl Trait`.

If, on the other hand, you're talking about formatting on code which only compiles on nightly, then we *do* want to support that. I expect we'd just need to `cargo update` to update Syntex, and then handling `impl Trait` would be a fairly easy patch.

If you'd like to do that, let me know if you need any more info.

**Comment by josephDunne** [comment]
Ok I spent a long time on this and got to upgrading to version 37 and gave up. There have been so many changes that I have no visibility around. So I can't rewrite rustfmt to handle 3 version upgrades nevermind 10. I recommend a issue to be created to do this upgrade and assign to someone familiar with both rustfmt and the multitude of syntax changes that have happened in the last 3 months.

**Comment by tikue** [comment]
This would be nice, as I'm hitting errors because of `!`:

```rust
$ cargo fmt
...
error: expected type, found `!`
pub struct Never(!);
                 ^
expected one of `&`, `(`, `)`, `*`, `;`, `<`, `[`, `_`, `extern`, `fn`, `for`, `pub`, `unsafe`, or `where`, found `!`
pub struct Never(!);
```

**Comment by josephDunne** [comment]
I am closing this issue in favour of #1154
