### ISSUE TITLE
Comments within macro invocations de-indented

### ISSUE THREAD

**Issue by hsivonen** [rust-lang-nursery/rustfmt#1149]
At some point between recent-ish releases installable via `cargo install`, rustfmt has started to de-indent comments within macro invocations that rustfmt otherwise decides not to touch.

Steps to reproduce:

1. Clone [encoding_rs](https://github.com/hsivonen/encoding_rs)
2. Checkout revision `2d67eca87631293efe6fc3906c0ef341ffa565e6` (the most recent one at the time of writing this bug report)
3. Run `cargo fmt`
4. Run `git diff`

Actual results:
Output previously produced by rustfmt is changed like this:

```
diff --git a/src/utf_16.rs b/src/utf_16.rs
index d2dbefe..7dd09e6 100644
--- a/src/utf_16.rs
+++ b/src/utf_16.rs
@@ -97,11 +97,11 @@ impl Utf16Decoder {
                                    };
                                    let high_bits = code_unit & 0xFC00u16;
                                    if high_bits == 0xD800u16 {
-                                       // high surrogate
+    // high surrogate
                                        if self.lead_surrogate != 0 {
```

Expected results:
Expected rustfmt not to format comments within macro invocations that rustfmt otherwise doesn't reformat.

**Comment by hsivonen** [comment]
The regression happened between 0.4.1 and 0.5.0.

**Comment by tikue** [comment]
I `cargo install`'d from git but this issue doesn't appear to be fixed.
