### ISSUE TITLE
Rust style guidelines link on README.md is broken

### ISSUE THREAD

**Issue by vinipsmaker** [rust-lang-nursery/rustfmt#1153]

**Comment by ubsan** [comment]
it was removed in https://github.com/rust-lang/rust/pull/35124

**Comment by vinipsmaker** [comment]
I'm just trying to find out what the default style say about column limit. Could you help me with that?

**Comment by ubsan** [comment]
@vinipsmaker There is no default style. There are two styles for Rust which are official-ish, mine (at https://ubsan.github.io/style ), and rustfmt's, which is what you get when you just run rustfmt on your code.
