### ISSUE TITLE
Format unions

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1157]
Not trivial, but a good first issue for someone who wants to get into Rustfmt.

**Comment by bekh6ex** [comment]
As far as I understood there is an RFC for unions (https://github.com/rust-lang/rfcs/blob/master/text/1444-union.md) which has some unresolved issues and they are not implemented in Rust yet. 

Also, https://github.com/serde-rs/syntex can not parse unions yet, so I guess this issue can be postponed.

**Comment by nrc** [comment]
Unions are implemented in Rust and the RFC is accepted. I'm not sure about the status of Syntex, but I would expect it to cover unions since they have been in the parser for a little while now. If not, we should nag the Syntex maintainers.
