### ISSUE TITLE
Macros in trait item position

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1158]
(I'm somewhat surprised we allow macros as trait items, but not impl items).

**Comment by bekh6ex** [comment]
Could you please give some examples or describe problem in more detailed manner?

I searched tests for anything that could give me a clue, but did not succeed...

**Comment by nrc** [comment]
Something like:

```
trait T {
    fn f();
    foo!(this is a macro);
}
```

We should format `foo!`.

**Comment by shioju** [comment]
@nrc i'll give this a shot if no one else is working on it.
