### ISSUE TITLE
file_lines with a comment is broken

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1159]
I think this is because we lose the distinction between a statement and expression and file-lines only bails from statements, not expressions. Not exactly sure why, but we then get the wrong indents for comments. I couldn't find a fix for this, so I had to delete the comments from the file-lines tests.

cc @kamalmarhubi

**Comment by nrc** [comment]
See https://github.com/rust-lang-nursery/rustfmt/commit/4418fab4f24e6497aa2a1f71bb4cf963c2971a28#diff-6d90fa32fee7e3049006a36424f5bad4

**Comment by kamalmarhubi** [comment]
Urg. I completely dropped this, didn't I? The implementation of the feature was never done after the initial PR.  I'll try to take a look this week.

**Comment by kamalmarhubi** [comment]
Oh and what do you mean by "only bails from"?

**Comment by nrc** [comment]
bails == early return (without doing any formatting)
