### ISSUE TITLE
Weird formatting for Type { ... }.method() inside an assert_eq!

### ISSUE THREAD

**Issue by glandium** [rust-lang-nursery/rustfmt#1167]
Take the following code:

``` rust
fn func() {
    assert_eq!(foo, bar.map(|&m| Type { field: m.into(), field2: "foo" }.into()).collect::<Vec<_>>());
}
```

rustfmt turns it into:

``` rust
fn func() {
    assert_eq!(foo,
               bar.map(|&m| {
            Type {
                    field: m.into(),
                    field2: "foo",
                }
                .into()
        })
                   .collect::<Vec<_>>());
}
```

Note how `Type {` and `})` are under-indented.

This may or may not be related to the fact that:

``` rust
Type { field: m.into(), field2: "foo" }.into()
```

is turned into:

``` rust
Type {
        field: m.into(),
        field2: "foo",
    }
    .into()
```

I don't know if it's intentional that the closing bracket is indented and the method call on the next line, with the fields being over-indented, but it seems like it's when it deals with this formatting that rustfmt goes awry on the original code.

**Comment by topecongiro** [comment]
Closing since this is fixed on the current master.
