### ISSUE TITLE
rustfmt converts vertically aligned function call to  hortizal aligned with new line 

### ISSUE THREAD

**Issue by srinivasreddy** [rust-lang-nursery/rustfmt#1171]
```
-        let obligation = traits::Obligation::misc(span,
-                                                  self.body_id,
-                                                  poly_trait_ref.to_predicate());
+        let obligation =
+            traits::Obligation::misc(span, self.body_id, poly_trait_ref.to_predicate());

```

https://github.com/rust-lang/rust/pull/36736/files/1d1168ccea6ee1ede476cefb424c384ba7904bb5#r80407232

another example is here: 
https://github.com/rust-lang/rust/pull/36736/files/1d1168ccea6ee1ede476cefb424c384ba7904bb5#r80407292

and here too. https://github.com/rust-lang/rust/pull/36736/files/1d1168ccea6ee1ede476cefb424c384ba7904bb5#r80407395

**Comment by jseyfried** [comment]
I don't think this is a bug -- the new formatting looks better to me.

**Comment by nrc** [comment]
Yeah, I'm not sure which I prefer. We'll decide in the style process at some point, I guess.

**Comment by topecongiro** [comment]
Closing because this is intended behavior.
