### ISSUE TITLE
Checkstyle output from crate with bin and lib targets produces separate, concatenated XML

### ISSUE THREAD

**Issue by BenjaminGill-Metaswitch** [rust-lang-nursery/rustfmt#1174]
I have a crate containing both binary and library targets (main.rs and lib.rs). cargo-fmt mostly copes with this fine. However, when asked to produce checkstyle output, it produces the following:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3"><file name="/a_crate/src/lib.rs"></file></checkstyle><?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3"><file name="/a_crate/src/main.rs"></checkstyle>
```

It looks as if it is producing separate output for the bin and lib targets and concatenating both. When I later attempt to parse this, the XML parsing fails due to the repetition of `<?xml version="1.0" encoding="utf-8"?>`.

Might it make sense to have a unified checkstyle output in the case where there are multiple targets in one crate?

**Comment by sharksforarms** [comment]
Having the same issue.

**Comment by sharksforarms** [comment]
For now I have this python script to combine them...

``` 
from bs4 import BeautifulSoup

output = '<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3">{file_tags}</checkstyle>'
with open('checkstyle.xml', 'r') as f:
    content = f.read()
    sections = content.split("<?xml")

    file_tags = ""
    for section in sections:
        section = "<?xml" + section
        soup = BeautifulSoup(section)
        for file_tag in soup.find_all("file"):
            file_tags += str(file_tag)

print(output.format(file_tags=file_tags))
```
