### ISSUE TITLE
Default option for `normalize_comments`

### ISSUE THREAD

**Issue by nokaa** [rust-lang-nursery/rustfmt#1176]
I think the default option for `normalize_coments` should be changed to `false`.
In my experience with Rust, I only use block comments (`/* ... */`) to temporarily disable a block of code.

If this issue has come up before and this is not the common case, feel free to close this issue.

**Comment by nrc** [comment]
> I only use block comments (/* ... */) to temporarily disable a block of code.

That is the intention really, and why Rustfmt tries to normalise comments at all. I have been meaning to do something with comments for some time, but haven't had much time to play with Rustfmt recently. I'm not entirely sure that setting normalize_comments to false gives great results all the time, and so I'm hesitant to flip the switch without proper testing.
