### ISSUE TITLE
Hangs in command prompt if you forget to add filename and flags. (in bash)

### ISSUE THREAD

**Issue by tommyshem** [rust-lang-nursery/rustfmt#1190]
Type rustfmt and enter in command prmpt and it hangs. Use bash command prompt.
I did this by mistake as you should put a filename or flags on the end of the command.

version used 0.6.2.
Most commands just print help instructions or exit with an error code.

**Comment by TimNN** [comment]
When no filename is given to `rustfmt`, it will read the source code to format from standard input. That is, the hang you observe is `rustfmt` waiting for input (and then the end of the input). The same happens when you execute eg. `cat` without arguments.
