### ISSUE TITLE
rustfmt removes empty lines between block and doc comments

### ISSUE THREAD

**Issue by nokaa** [rust-lang-nursery/rustfmt#1196]
With `normalize_comments` set to `false`, running rustfmt can lead to empty lines between a block comment and a doc comment being removed.

Here is some example code:

``` rust
/// Doc comment for func1
/*fn func1() {
    let a = 5;
}*/

/// Doc comment for func2
fn func2() {
    let b = 5;
}
```

When rustfmt is run, the fifth line will be deleted. This line is only deleted if line 6 is a doc comment; normal and block comments work properly. 
It seems that an arbitrary number of empty lines can be between the block comment and the doc comment, they will all be deleted.

**Comment by nokaa** [comment]
If I can help fix this let me know. I don't really want to just open issues that relate to features that I'm the only one using. It would probably be better if I could do the work and submit a pull request for bugs I come across.

**Comment by nrc** [comment]
Are you using master? We merged a few commits recently that might address this issue.

**Comment by nokaa** [comment]
Yes, I saw that #1185 had been merged when I went to file an issue; so I made sure to use the latest commit for testing.

**Comment by topecongiro** [comment]
Closing as this if fixed on the current master.
