### ISSUE TITLE
cargo fmt doesn't understand all crate types

### ISSUE THREAD

**Issue by jethrogb** [rust-lang-nursery/rustfmt#1202]
cargo fmt doesn't understand the `rlib` and `cdylib` crate types. This makes cargo fmt hang in some cases #1201

https://github.com/rust-lang-nursery/rustfmt/blob/a3c63fd/src/bin/cargo-fmt.rs#L173

**Comment by bjgill** [comment]
Looking at master (https://github.com/rust-lang-nursery/rustfmt/blob/master/src/bin/cargo-fmt.rs#L283), it looks as if `rlib` and `cdylib` may now be supported.
