### ISSUE TITLE
Cargofmt changing return type to the literal string TODO

### ISSUE THREAD

**Issue by lespea** [rust-lang-nursery/rustfmt#1204]
Using this example:

```
#![feature(conservative_impl_trait)]

pub fn test() -> impl std::iter::Iterator<Item = u32> {
    (0..10)
}

fn main() {
    for i in test() {
        println!("{}", i)
    }
}
```

When `cargo fmt` is run, the output is changed to this:

```
#![feature(conservative_impl_trait)]

pub fn test() -> impl TODO {
    (0..10)
}

fn main() {
    for i in test() {
        println!("{}", i)
    }
}
```

Maybe returning impl isn't yet supported by cargofmt but it's pretty shocking that a source formatting tool would change a signature type if it doesn't understand it.

Version info:

```
cargo fmt -- --version
0.6.2 ()
````

```
rustc --version
rustc 1.14.0-nightly (3f4408347 2016-10-27)
```

Highly doubtful it matters but I'm on windows 10.

**Comment by nrc** [comment]
This should be fixed on master now, I'll roll a new release this week which should include this fix.

**Comment by nrc** [comment]
Oh, please re-open if this is not fixed on master

**Comment by Michael-F-Bryan** [comment]
I just encountered this issue as well. Luckily, the fix is fairly easy and uninstalling the `rustfmt` from cargo then re-installed from source worked for me. 

@nrc do you know when the next release will be?

**Comment by nrc** [comment]
> do you know when the next release will be?

I can do one later this week
