### ISSUE TITLE
Weird newline in string literal

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1210]
```
     fn cxx(&self, target: &str) -> &Path {
         match self.cxx.get(target) {
             Some(p) => p.path(),
-            None => panic!("\n\ntarget `{}` is not configured as a host,
-                            only as a target\n\n", target),
+            None => {
+                panic!("\n\ntarget `{}` is not configured as a host,
+                            \
+                        only as a target\n\n",
+                       target)
+            }
         }
     }
```

**Comment by topecongiro** [comment]
In `0.8.3 ()`, rustfmt formarts
```rust
impl Foo {
    fn cxx(&self, target: &str) -> &Path {
        match self.cxx.get(target) {
            Some(p) => p.path(),
            None => panic!("\n\ntarget `{}` is not configured as a host,
                            only as a target\n\n", target),
        }
    }
}
```
to
```rust
impl Foo {
    fn cxx(&self, target: &str) -> &Path {
        match self.cxx.get(target) {
            Some(p) => p.path(),
            None => {
                panic!("\n\ntarget `{}` is not configured as a host,
                            only as a target\n\n",
                       target)
            }
        }
    }
}
```
so the weird newline is gone.

**Comment by nrc** [comment]
This only reproduces with the `format_strings` option set.

**Comment by topecongiro** [comment]
Just setting `format_strings` does not reproduce the above bug anymore.
However, when the `max_width` is set to smaller value, the bug gets reproduced.


rustfmt.toml:
```toml
format_strings = true
max_width = 50
```
Output:
```rust
impl Foo {
    fn cxx(&self, target: &str) -> &Path {
        match self.cxx.get(target) {
            Some(p) => p.path(),
            None => {
                panic!("\n\ntarget `{}` is not \
                        configured as a host,
                        \
                        only as a target\n\n",
                       target)
            }
        }
    }
}
```

**Comment by scampi** [comment]
@nrc @topecongiro I am having a look at this issue and I was wondering if you could clarify the signature of `rewrite_string` which takes in addition to a format specification an optional `max_width`: https://github.com/rust-lang-nursery/rustfmt/blob/f711078126f95bd580c69c39af9fc16e3f83c859/src/string.rs#L47-L51

However, it seems that the `fmt.width` property is enough:

- `None` is passed as argument: https://github.com/rust-lang-nursery/rustfmt/blob/cc2afeca9eda9d85c088479335c3c664d449a7f4/src/expr.rs#L1394-L1398

- the `max_chars` value is actually assigned to `fmt.width` too: https://github.com/rust-lang-nursery/rustfmt/blob/604764abe15c2742af85c1461e6f8055083e3c0b/src/comment.rs#L441-L452

Could it be that argument is a left-over of a previous refactoring ? Could it be removed ?
