### ISSUE TITLE
Space around operator not always ideal for macros

### ISSUE THREAD

**Issue by anowell** [rust-lang-nursery/rustfmt#1213]
I just wanted to point out that I found the [mime! macro](http://hyper.rs/mime.rs/mime/macro.mime!.html) formatting less-than-ideal:

`mime!(Application/Json);`

gets formatted as:

`mime!(Application / Json);`

Probably not a deal breaker, but it stood out as a non-ideal edge case of #29

**Comment by nrc** [comment]
Hmm, I don't see a good way to solve this - the macro is really abusing the syntax by pretending to take Rust code, but not. I don't think Rustfmt can ever distinguish this case from e.g., `x / y` in a normal expression.
