### ISSUE TITLE
Implement field_init_shorthand feature

### ISSUE THREAD

**Issue by MoSal** [rust-lang-nursery/rustfmt#1215]
``` Rust
#![feature(field_init_shorthand)]

struct AA{}
struct BB{}

struct CC {
    a: AA,
    b: BB
}

impl CC {
    fn new(a: AA, b: BB) -> Self {
        Self { a, b }
    }
}
```

`cargo fmt` error:
```
error: expected `:`, found `,`
  --> /tmp/foo/src/lib.rs:13:17
   |
13 |         Self { a, b }
   |                 ^

```

**Comment by bekh6ex** [comment]
The message is created in one of the following places:
  * https://github.com/serde-rs/syntex/blob/master/syntex_syntax/src/parse/parser.rs#L446
  * https://github.com/serde-rs/syntex/blob/master/syntex_syntax/src/parse/parser.rs#L733
  * https://github.com/serde-rs/syntex/blob/master/syntex_syntax/src/parse/parser.rs#L3530

Should this issue be in this repository? 
Probably it belongs to https://github.com/serde-rs/syntex

**Comment by matthew-piziak** [comment]
Weird. Looks like it doesn't error anymore on master. [This works](https://github.com/rust-lang-nursery/rustfmt/compare/master...matthew-piziak:field-init-shorthand?expand=1). Instead it just inserts the field names. I don't see the commit changing it though.

**Comment by clarcharr** [comment]
Is there any progress on this?

**Comment by clarcharr** [comment]
It appears that this works in the latest rustfmt, but it defaults to expanding out the shorthand. I think that the default should be to always use the shorthand when possible.

**Comment by nrc** [comment]
Fixed by https://github.com/rust-lang-nursery/rustfmt/commit/fad74c8ac9dcf9cd0f9db5439a30e5cadf5d6542
