### ISSUE TITLE
Weird indentation for question mark

### ISSUE THREAD

**Issue by leshow** [rust-lang-nursery/rustfmt#1217]
```rust
    pub fn create(&self) -> Result<Mnemonic, Error> {
        let random_chars: String = OsRng::new()
            ?
            .gen_ascii_chars()
            .take(self.bit_length)
            .collect();

        Ok(Mnemonic::new(&random_chars))
    }
```

rustfmt moves that `?` to the line on it's own whenever I save this file. Is that normal? It stands in contrast with what it does with the `?` operator elsewhere

**Comment by nrc** [comment]
It should not do that. We have some special handling for `?` in method chains and this seems to not get along with it.
