### ISSUE TITLE
Spurious error message on encountering trailing whitespace in a multi-line string literal

### ISSUE THREAD

**Issue by bjgill** [rust-lang-nursery/rustfmt#1220]
The following code isn't formatted (which is probably correct[?]) by `cargo fmt`...

```rust
fn main() {
    let a = "I'm followed by two spaces:  
           see?";
}
```

...but emits an error message:
```
>cargo fmt -- --write-mode=diff
Rustfmt failed at <...>\src\main.rs:2: left behind trailing whitespace (sorry)
```

**Comment by nrc** [comment]
This does not seem spurious, in that there is still trailing whitespace. It might be a bit much to expect Rustfmt to fix this, but it could be fixed manually, so the warning seems appropriate.

**Comment by bjgill** [comment]
Ok, that makes sense
