### ISSUE TITLE
Git integration?

### ISSUE THREAD

**Issue by rednum** [rust-lang-nursery/rustfmt#1223]
Hi,

I'd like to suggest adding features for integration with git. Those would allow rustfmt to pick up relevant files based on state of git repo. I imagine something like this would be useful:

1. `--git-files=[none|local|ahead|recent:N]` - specifies which files should be formatted. `local` stands for uncomitted changes (both staged and unstaged for commit), `ahead` for commits ahead of upstream, `recent:N` for files form last N commits, `none` for not using this feature. This could be also abbreviated as `-gf=[n|l|a|r:N]`.

1. `--git-action=[none|ammend|commit]` - specifies whether git should do anything after sucesfully formatting files. `ammend` stands for ammending last commit, `commit` creates a new commit (possibly with default message like "Formatted with rustfmt") containing reformatted files, `none` (default) does nothing. This could be also abbreviated as `-ga=[n|a|c]`. `--git-files` must be other than `none` to use this.

I'm not very attached to this design, but I think I would use it like this:
When working on something I'd ocasionally run `rustfmt -gf=l`. Then I'd run `rustfmt -gf=a -ga=c` before pushing or `rustfmt -gf=r:1 -ga=a` (when it's a personal project I'm not putting on github). I imagine different people may have different workflows so we can probably make changes to this proposal to make it useful.

I'd also be interested in implementing those when we agree what the best API should be.

**Comment by dhardy** [comment]
I'm just a by-passer, but disagree with both ideas.

1.  Doesn't `cargo fmt` do what you need already?
2.  I regard git as the last line of defence between what changes my tools make to my code and what I want to commit. I'd hate to have a tool like `rustfmt` auto-tweak my commits for me. (Of course, I see that this is optional — but not why anyone would want it.)

**Comment by rednum** [comment]
1. I guess it does and I should read docs more carefully next time before opening an issue. Thanks.
2. I found similar feature useful when working with some other toolchain. I understand other people may have different approach to development and some may not want that.
