### ISSUE TITLE
Option to not insert spaces at beginning of comment lines

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang-nursery/rustfmt#1224]
Examples:

```
-//TODO something
+// TODO something

-//debug!("{}", foo);
+// debug!("{}", foo);
```

I'd prefer to tell rustfmt to just leave those comments alone.

**Comment by dhardy** [comment]
Seems a bit odd that it will do this when it doesn't remove spaces inside comments. Because it also does this (note that my editor puts the `//` at the start of the line when I tell it to comment-out code, then rustfmt indents again instead of just moving the `//`):
```
 fn foo() {
-//    do_something();
+    //    do_something();
     another_fn_call()
 }
```
