### ISSUE TITLE
Command line option to only check (warning mode), not write any changes

### ISSUE THREAD

**Issue by dhardy** [rust-lang-nursery/rustfmt#1232]
We've started using `rustfmt` in Travis and are looking at pre-commit hooks. We use `cargo fmt -- --write-mode=diff` but really would like an option that doesn't try to make any changes, but _does_ print warnings and exit with status 1 if the formatting is not clean.

**Comment by michaelsproul** [comment]
Found this issue when looking into #1977, and think it's probably out of date now with respect to `rustfmt`'s current behaviour?

> would like an option that doesn't try to make any changes

From the README:

> diff: Will print a diff between the original files and formatted files to stdout. Will also exit with an error code if there are any differences.

This would appear to satisfy your suggestion, or am I misinterpreting, and you actually don't want any diff displayed at all..?

(p.s. Hi Diggory!)

**Comment by dhardy** [comment]
Hi Michael!

Yes, I suppose that works well enough for CI. The only time it doesn't is when running `rustfmt` from the command line manually and not wanting a lot of output in the terminal.

But I don't have to use `rustfmt` any more so I don't particularly care ;)

**Comment by nrc** [comment]
We now have `--check`
