### ISSUE TITLE
Some comments get strangelly uncommented

### ISSUE THREAD

**Issue by Razican** [rust-lang-nursery/rustfmt#1233]
I've been searching for this particular issue in the repo and I cannot find anything similar. The thing is that I have the following (simplified) code:
```
fn somefunc(&self, param1: u32) -> Result<()> {
        let mut whatever = [0u32; 20];
        whatever[0] = 0xe59f0020.to_le(); // `ldr  r0, [pc, #32] ; ldr r0,[write_addr]`
        whatever[1] = 0xe28f1024.to_le(); // `ldr  r0, [pc, #32] ; ldr r0,[write_addr]`
}
```
Which gets transformed to this:
```
fn somefunc(&self, param1: u32) -> Result<()> {
        let mut whatever = [0u32; 20];
        whatever[0] = 0xe59f0020.to_le();; ldr r0,[write_addr]`
        whatever[1] = 0xe28f1024.to_le();; ldr r0,[write_addr]`
}
```
The point is that some assembly code that I'm writing in comments next to some initialization code (it's actually ARM assembly word by word, that I need in that array) gets corrupted. I don't know if it's a comment formatting issue or an assembly formatting issue, but it shouldn't change anything in that comment :/

**Comment by nrc** [comment]
Fixed by https://github.com/rust-lang-nursery/rustfmt/commit/29e89136957b9eedf54255c8059f8a51fbd82a68
