### ISSUE TITLE
rustfmt 0.6.3 ignores normalize_comments=false to the point of changing // into //!

### ISSUE THREAD

**Issue by ssokolow** [rust-lang-nursery/rustfmt#1240]
With the following `rustfmt.toml`...

    normalize_comments = false

I've observed this test behaviour...

## Case 1

Before:
```rust
//! Blah blah blah
/* TODO: Lorem ipsum dolor sit amet */
```

After:
```rust
//! Blah blah blah
//! TODO: Lorem ipsum dolor sit amet
```

## Case 2

Before:
```rust
//! Blah blah blah
// Yakkety Yak
/* TODO: Lorem ipsum dolor sit amet */
```

After:
```rust
//! Blah blah blah
//! Yakkety Yak
//! TODO: Lorem ipsum dolor sit amet
```

## Case 3

Before:
```rust
//! Blah blah blah

// Yakkety Yak
/* TODO: Lorem ipsum dolor sit amet */
```

After:
```rust
//! Blah blah blah

// Yakkety Yak
// TODO: Lorem ipsum dolor sit amet
```

## Case 4

Before:
```rust
//! Blah blah blah

/* Yakkety Yak */
// TODO: Lorem ipsum dolor sit amet
```

After: **No Change**

## Consequences

1. `rustfmt` will unavoidably **change the semantics of the code** by converting `/* ... */` or `//` to `//!` if one follows the other without a blank line.
2. `rustfmt` will unavoidably normalize a `/* ... */` comment into `//` form if it follows a `//` comment without a blank line.
3. `rustfmt` will **not** convert a `//` comment into `/* ... */` form if it follows a `/* ... */` comment.

My take-away: Thank goodness I habitually use `git gui` to do my committing.

**Comment by nrc** [comment]
This is, I think, a known bug where a comment immediately following a doc comment is treated (by rustfmt) as part of that doc comment. The examples seem to extend the buggy behaviour to non-doc comments too.

**Comment by nrc** [comment]
This is fixed on master now
