### ISSUE TITLE
reorder_imported_names shouldn't force lexicographic sort order

### ISSUE THREAD

**Issue by ssokolow** [rust-lang-nursery/rustfmt#1242]
Currently, I have to keep my multiple-import lines ordered manually because `reorder_imported_names` forces all of the constants to sort first, despite being the least significant part of an API and I really don't like this kind of suggested correction:

```diff
- use self::libc::{access, c_char, c_int, W_OK};
+ use self::libc::{W_OK, access, c_char, c_int};
```

This is clearly because it's using the same kind of naive lexicographic sort you see from things like Apache's `mod_autoindex` and, while that would be annoying normally, it's flat-out grating here. With all-caps names sorting first, the import feels top-heavy and more difficult to skim.

**Comment by nrc** [comment]
cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/24. Closing this issue since it is more of a spec'ing issue rather than an implementation one.

**Comment by ssokolow** [comment]
Ahh. I didn't notice the existence of `fmt-rfcs`... but now I suspect my participation will drop because I have this thing about never feeling competent enough to do more than commenting on someone else's RFCs.
