### ISSUE TITLE
normalize_comments=false messes up formatting on left-bordered block comments

### ISSUE THREAD

**Issue by ssokolow** [rust-lang-nursery/rustfmt#1243]
Given this `rustfmt.toml`...

```toml
write_mode = "Diff"
normalize_comments = false
```

...and this test case...

```rust
/*
 * TODO: Task
 *  - http://resource/
 *  - http://resource/
 *  - http://resource/
 *  - http://resource/
 *
 * TODO: Task 2
 *  - http://resource/
 *  - http://resource/
 *  - http://resource/
 *  - http://resource/
 */
```

...rustfmt produces this output:

```diff
Diff in testcase.rs at line 1:
-/*⏎
- * TODO: Task⏎
+/* TODO: Task⏎
  *  - http://resource/⏎
  *  - http://resource/⏎
  *  - http://resource/⏎
Diff in testcase.rs at line 9:
  *  - http://resource/⏎
  *  - http://resource/⏎
  *  - http://resource/⏎
- */⏎
+ * */⏎
```

This only occurs in non-documentation comments. (Which I use to keep internal TODO notes out of the generated docs on hobby projects without a more formalized plan for recording localized "make this more idiomatic as detailed/taught/caveat'd at these URLs" TODOs.)

While it offends my DRY sensibilities, I'm willing to throw a "header" like "TODO Notes:" into that first line to preserve the semantics of the comment content (Line 1 is a "header" and exists at a higher outline level than the other content), so that first hunk is OK.

The problem is that second hunk. The way it mangles the closing line is unacceptable.

**Comment by nrc** [comment]
Fixed
