### ISSUE TITLE
Support ‘cargo fmt -p PACKAGE1 -p PACKAGE2’ in a workspace with several packages

### ISSUE THREAD

**Issue by andersk** [rust-lang-nursery/rustfmt#1244]
`cargo fmt` should support `-p`/`--package`, like most other `cargo` subcommands, so that one can run `cargo fmt -p PACKAGE1 -p PACKAGE2` in a [Cargo workspace](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md) with several packages.

**Comment by imp** [comment]
And may be `cargo fmt --all` to act on all the workspace members defined in the `Cargo.toml`

**Comment by Emilgardis** [comment]
This feature would be very useful to have as rustfmt is a must-have cargo plugin and not having support for workspaces is a major inconvenience.

**Comment by nrc** [comment]
I suspect this would be relatively easy to implement. The `cargo fmt` stuff is fairly self-contained (in https://github.com/rust-lang-nursery/rustfmt/blob/master/src/bin/cargo-fmt.rs) and IIUC, workspace support just comes down to specifying a different 'start file' for rustfmt.

If anyone wants to tackle this, I'd more than happy by answering questions or pointing towards parts of the system.

**Comment by Emilgardis** [comment]
I am willing to implement this.

**Comment by Emilgardis** [comment]
This has been fixed now 🎉

**Comment by pravic** [comment]
> so that one can run `cargo fmt -p PACKAGE1 -p PACKAGE2` in a Cargo workspace with several packages.

It is strange: `$ cargo fmt -p package` results

> Invalid argument: `package`.
usage: cargo fmt [options]

Several combinations revealed the accepting form: `cargo fmt -ppackage` o_O
