### ISSUE TITLE
Odd wrapping with slice as a function parameter

### ISSUE THREAD

**Issue by marshallpierce** [rust-lang-nursery/rustfmt#1247]
With rustfmt 0.6.3 and a max line length of 80, 

```
        polyfill::slice::fill(
            &mut self.pending[padding_pos..(self.algorithm.block_len - 8)], 0);
```

becomes 

```
        polyfill::slice::fill(&mut self.pending[padding_pos..(self.algorithm
                                  .block_len -
                                                              8)],
                              0);
```

Extracted from https://github.com/briansmith/ring/pull/385/files/91cafacb247788cfbfb272491b39dad01f0b152e#diff-cfa8551ffcaa4c8160640b8a137d65bdL167. https://github.com/briansmith/ring/pull/385/files/91cafacb247788cfbfb272491b39dad01f0b152e#diff-f04d651d07eebb6c674b7f647d8bd37eL33 may be the same issue.

**Comment by topecongiro** [comment]
In 0.8.4 we get 
```rust
fn foo() {
    polyfill::slice::fill(&mut self.pending[padding_pos..
                               (self.algorithm.block_len - 8)],
                          0);
}
```
Should `(self.algorithm.block_len - 8)],` get aligned to `padding_pos..` like the follwing?
```rust
fn foo() {
    polyfill::slice::fill(&mut self.pending[padding_pos..
                                            (self.algorithm.block_len - 8)],
                          0);
}
```

**Comment by nrc** [comment]
> Should (self.algorithm.block_len - 8)], get aligned to padding_pos.. like the follwing?

It probably should, but I don't think it is super-important, the current formatting seems OK.

**Comment by topecongiro** [comment]
Thanks! It was easy to fix, so I will create a PR at some point.
