### ISSUE TITLE
Add an option to format despite other modules being missing from the filesystem.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang-nursery/rustfmt#1253]
I am editing some files in a project that will all be placed back together before the compilation happens, but I still want to format them on the local machine as I'm editing. I thought that the `--skip-children` option did this, but apparently it does not. Example:

```
pi@blueberry:~ $ rustfmt --skip-children main.rs
error: file not found for module `point`
 --> main.rs:9:5
  |
9 | mod point;
  |     ^^^^^
  |
  = help: name the file either point.rs or point/mod.rs inside the directory ""
```

However, if I simply comment out that line and change nothing else about `main.rs` it will format the entire rest of the file just fine, even though the very next line is a (now invalid) `use point::Point;` statement.

Clearly the fact that the file *actually* exist is not important to the rest of the job. So, can an option be added to have rustfmt just ignore the fact that the file is "missing"? Or like, give a warning but just get on with the task anyway?

**Comment by nrc** [comment]
This would be nice to have but a bit difficult to do because we rely on the parser from rustc to load files and walk them.
