### ISSUE TITLE
Default annotation incorrectly removed on associated types

### ISSUE THREAD

**Issue by mwolting** [rust-lang-nursery/rustfmt#1255]
Similar to #945. Occurs when formatting e.g. code equivalent to the following:
```
#![feature(specialization)]

trait Trait {
    type Type;
}
impl<T> Trait for T {
    default type Type = u64;
}
```
The default annotation on Type in the generic implementation of Trait disappears, even though it is meaningful and correct in that position.

**Comment by gypsydave5** [comment]
I'm going to (try) and take a look at this over the next few days - I'm new to Rust but I'd like to try and get a bit more involved.
