### ISSUE TITLE
`use` declaration has extra colons added, making code incorrect

### ISSUE THREAD

**Issue by allengeorge** [rust-lang-nursery/rustfmt#1269]
I have a few modules with lines like this:

```
use ::{ProtocolError, ProtocolErrorKind};
```

After running rustfmt via `cargo fmt` the above line is turned into:

```
use ::::{ProtocolError, ProtocolErrorKind};
```

**Comment by nrc** [comment]
Is this using master or the latest release?

**Comment by allengeorge** [comment]
It's whatever cargo version `cargo 0.15.0-nightly (298a012 2016-12-20)` is
calling. How do I find out which version of `rustfmt` is being invoked?

**Comment by nrc** [comment]
It depends how you installed it. If you used `cargo install` or something similar it will be a release, if you built it yourself from source, then it will be whatever you built (usually master).

**Comment by mrwiggles** [comment]
It's from a release. That said, `rustfmt --version` returns `0.5.0`.

**Comment by allengeorge** [comment]
It's from a release. That said, `rustfmt --version` returns `0.5.0`.

**Comment by nrc** [comment]
This is fixed on master. The current version of Rustfmt is 0.6.3, so this might be fixed just by updating your version of Rustfmt. Otherwise, you can build from master, or wait for the next release (which should be in the next or so).
