### ISSUE TITLE
Over-long line with an array

### ISSUE THREAD

**Issue by nwin** [rust-lang-nursery/rustfmt#1273]
I just encountered an off-by-one error in a list in a function call. The [line](https://github.com/PistonDevelopers/image_buffer/blob/ff5bba3ed36f84cee0dc7038576602addf598346/src/color_model/rgb.rs#L117) is 101 chars long. It was nicely wrapped before until I ran rustfmt. 😒

 If I change the length to 102 chars rustfmt correctly recognizes this.

**Comment by nrc** [comment]
Code:

```
impl From<Rgb<f32>> for Rgb<u8> {
    fn from(other: Rgb<f32>) -> Self {
        let rgb = other.0;
        Rgb([srgb_compress_gamma(rgb[0]), srgb_compress_gamma(rgb[1]), srgb_compress_gamma(rgb[2])])
    }
}
```

**Comment by nrc** [comment]
That line is actually 100 chars long. Changing it to 101, by increasing the length of the outer fucntion call, a name in the array or by adding a semi-colon all cause Rustfmt to wrap it as expected.

**Comment by nwin** [comment]
This is interesting, seems to be a bug  in atom then, it counts it as 101.
