### ISSUE TITLE
Remove unnecessary new lines at start or end of block

### ISSUE THREAD

**Issue by johnthagen** [rust-lang-nursery/rustfmt#1274]
For example:

```rust
fn main() {




    let x = 1;




}
```

Could be formatted to:

```rust
fn main() {
    let x = 1;
}
```

**Comment by nrc** [comment]
We deliberately preserve vertical whitespace since it is sometimes significant (e.g., whether there is an empty line between statements or not). However, it looks like we could do better in this example since it is the end of the block.

**Comment by nrc** [comment]
We could also normalise multiple blank lines to a single blank line, which I think we do elsewhere.

**Comment by johnthagen** [comment]
> We could also normalise multiple blank lines to a single blank line, which I think we do elsewhere.

I think simply doing that and then trimming trailing newlines at the end of braces would be great!
