### ISSUE TITLE
rustfmt deleting a bunch of code after upgrading to 0.7

### ISSUE THREAD

**Issue by bgourlie** [rust-lang-nursery/rustfmt#1277]
I just upgraded to rustfmt 0.7.  Running `cargo fmt` deletes a bunch of code in some files while (weirdly enough) also inserting code from other files.  To reproduce:

- Clone https://github.com/bgourlie/asm6502.git
- run `cargo fmt`
- see `git diff`

**Comment by mulkieran** [comment]
Having a similar problem:

```
-#![allow(dead_code)] // only temporary, until more stuff is filled in⏎
+ // only temporary, until more stuff is filled in⏎
```

Note that the ```#![allow(dead_code)]``` is simply removed.

**Comment by nrc** [comment]
This sounds like #1229. I investigated that, see https://github.com/rust-lang-nursery/rustfmt/issues/1229#issuecomment-273326447

@mulkieran's thing sounds like a separate issue.

**Comment by mulkieran** [comment]
@nrc you must be right. My problem seems to have been introduced by the 0.7.0 release; 0.6.3 makes no change.
