### ISSUE TITLE
pub_restricted formatting breaks code with "Block" fn args

### ISSUE THREAD

**Issue by alexmaco** [rust-lang-nursery/rustfmt#1278]
rustfmt generates invalid code after formatting code that uses the pub_restricted feature.
The breakage is new in the 0.7 release; in the 0.6.3 release the same erroneous line would be inserted, but it was commented out

input:
```
#![feature(pub_restricted)]

mod inner_mod {
    pub(super) fn func_name(
        abc: i32
    ) -> i32 {
        abc
    }
}
```
rustfmt.toml:
```
fn_args_layout = "Block"
````

incorrect 0.7 output:
```
#![feature(pub_restricted)]

mod inner_mod {
    pub(super) fn func_name(
        super) fn func_name(
        abc: i32
    ) -> i32 {
        abc
    }
}
```
incorrect 0.6.3 output:
```
#![feature(pub_restricted)]

mod inner_mod {
    pub(super) fn func_name(
        // super) fn func_name(
        abc: i32
    ) -> i32 {
        abc
    }
}
```

**Comment by ahti** [comment]
This also happens without `fn_args_layout = "Block"`, using the same example code.

**Comment by topecongiro** [comment]
Closing since this is fixed on the current master.
