### ISSUE TITLE
rustfmt removes module-level attributes when there are comments

### ISSUE THREAD

**Issue by Wilfred** [rust-lang-nursery/rustfmt#1280]
Given the Rust code:

```rust
#![allow(dead_code)] // bar
```

rustfmt 0.7 produces:

```rust
 // bar
```

**Comment by Wilfred** [comment]
Duplicate of #1277.

**Comment by mulkieran** [comment]
@Wilfred Could you reopen? This might be related to #1284, but #1277 was actually a different issue.

**Comment by Wilfred** [comment]
@nrc would you be able to tag a new release? We'd love to integrate rustfmt into the CI for the Remacs project, but we're seeing this issue.

**Comment by nrc** [comment]
@Wilfred I just released v0.8 (it took a while because I did some large refactoring and wanted to give it a little time for testing).

**Comment by Wilfred** [comment]
Thanks :)
