### ISSUE TITLE
overlong match arm with long string lit

### ISSUE THREAD

**Issue by Razican** [rust-lang-nursery/rustfmt#1282]
I have this very curious diff, that changes a well formatted code to a badly formatted one on `cargo fmt`:

https://github.com/SUPERAndroidAnalyzer/super/commit/0bc90fd24aec63330e5aec0a80a4272b15be173c#diff-3c9fa36f880ef244906c900e873ba0e8

The thing is that the formatting was done by a previous version of `rustfmt`, and when running `cargo fmt` I get a ton of errors (all those lines are more than 100 characters long) and the file gets formatted as shown.

**Comment by nrc** [comment]
example:

```
-            Permission::AndroidPermissionAccessLocationExtraCommands => {
-                "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS"
-            }
+            Permission::AndroidPermissionAccessLocationExtraCommands => "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS",
```

**Comment by Razican** [comment]
This was closed but with the current master code is still happening.

**Comment by nrc** [comment]
Do you have a test case where it fails? The code in my comment is in a passing test (https://github.com/rust-lang-nursery/rustfmt/commit/1f3100d7bb2e4889ec243d2781b77e252fb29c5c#diff-fac879c6e7baf913e3e582e46d84ce85R49) so we at least work for that.

**Comment by Razican** [comment]
If you try to `rustfmt` this file: https://github.com/SUPERAndroidAnalyzer/super/blob/master/src/static_analysis/manifest.rs you will get a ton of errors.

**Comment by Razican** [comment]
@nrc were you able to reproduce?

**Comment by nrc** [comment]
@Razican I haven't looked into this, sorry. Could you try and reduce that file down to a <10 line test case I can try please?

**Comment by Razican** [comment]
@nrc  So I wrote this example, which is the same you seem to have in the repo:

```rust
fn issue_1282() {
    {
        match foo {
            Permission::AndroidPermissionAccessLocationExtraCommands => "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS",
        }
    }
}
```

And rustfmt cannot format it, it shows:
```
Rustfmt failed at test.rs:6: line exceeded maximum length (maximum: 100, found: 124) (sorry)
```

**Comment by nrc** [comment]
@Razican thanks, I'll look into it...
