### ISSUE TITLE
How to configure rustfmt to align types of struct fields?

### ISSUE THREAD

**Issue by flosse** [rust-lang-nursery/rustfmt#1287]
Readability is quite important, so instead of
```rust
struct Foo {
    this_is_filed: f64,
    foo: String,
    another_field: u32,
    baz: bool,
    and_some_more: i8,
}
```
I'd like to use the much cleaner variant:

```rust
struct Foo {
    this_is_filed : f64,
    foo           : String,
    another_field : u32,
    baz           : bool,
    and_some_more : i8
}
```
How can I say to rustfmt that it should use the latter one?

**Comment by nrc** [comment]
It is not possible at the moment, sorry. It is somewhat tricky to implement and would need some deep changes to implement generally, but might be easier to do in restricted cases like this. If you're interested in implementing, I can mentor.

This is a dup of https://github.com/rust-lang-nursery/rustfmt/issues/1103, so closing.

**Comment by wasd96040501** [comment]
Is it now be possible? @nrc

**Comment by ytmimi** [comment]
@wasd96040501 please see the [struct_field_align_threshold](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#struct_field_align_threshold) option.
