### ISSUE TITLE
Reorder inline use functions

### ISSUE THREAD

**Issue by andreastt** [rust-lang-nursery/rustfmt#1289]
Given

```rust
use my_package::{A, C, B};
```

it would be helpful if rustfmt could reorder them lexicographically to

```rust
use my_package::{A, B, C};
```

**Comment by nrc** [comment]
This should work if you set `reorder_imported_names` to true. Feel free to re-open if it does not.

**Comment by andreastt** [comment]
Excellent, thank you. How do I set this option? `rustfmt --help` is not being helpful.

**Comment by nrc** [comment]
you need a config file - "rustfmt.toml", then set that option like in any other toml file. There are some examples in tests/configs
