### ISSUE TITLE
Regression: Formatting re-export exceeds line length

### ISSUE THREAD

**Issue by azriel91** [rust-lang-nursery/rustfmt#1293]
In Rustfmt 0.6.3, this was the formatting for one of my re-exports:

```rust
pub use activity::{Activity, ExitResult, ExitResultBuilder, ExitStatus, PrintActivity,
                   NoOpActivity};
```

When I updated to 0.7.1, it puts the last item on the same line, which causes the line length to be 101 characters (the last semicolon `;` is the 101th character):

```rust
pub use activity::{Activity, ExitResult, ExitResultBuilder, ExitStatus, PrintActivity, NoOpActivity};
```

**Comment by topecongiro** [comment]
Closing since this is fixed on the current master.
