### ISSUE TITLE
Weird placement of indexing bracket

### ISSUE THREAD

**Issue by CryZe** [rust-lang-nursery/rustfmt#1296]
After upgrading to the latest rustfmt, it reformatted my code in a fairly weird way:
![http://puu.sh/tLuNA.png](http://puu.sh/tLuNA.png)

A few lines later I have a similar statement and the bracket is tabbed in a bit less, for no apparent reason:
![http://puu.sh/tLvd8.png](http://puu.sh/tLvd8.png)

**Comment by nrc** [comment]
This is a method chain + something bug, where the something here is an array index. The problem is the weird indent, which I imagine is due to the `let` and then not setting the indent properly somewhere.

**Comment by TheKevJames** [comment]
Just saw something similar, posting a snippet here in case it helps to debug this.

```
        let mut param = declaration.children[1]
                .clone()
                .children
                            [2]
            .clone();
```
