### ISSUE TITLE
Rustfmt fails in rustfmt_skip-blocks with line exceeded maximum length

### ISSUE THREAD

**Issue by MackieLoeffel** [rust-lang-nursery/rustfmt#1298]
If I try to format the following code:
```Rust
#[cfg_attr(rustfmt, rustfmt_skip)]
fn test() {
    let a = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25];
}
```
Rustfmt fails with the following error:
`Rustfmt failed at stdin:3: line exceeded maximum length (maximum: 100, found: 108) (sorry)`

I would expect, that rustfmt doesn't complain about lines, which it shouldn't format in the first place.

**Comment by nrc** [comment]
This is expected behaviour - the logic is that even where Rustfmt does not format, the user is still interested to know if their formatting satisfies the constraints they have given Rustfmt.

We should probably have a command line flag or config option to change this bahaviour.

**Comment by MackieLoeffel** [comment]
Ok, your argument makes sense. A config option or command line flag for changing this behavior would probably be nice, but I can live with the current behavior.

And by the way: Thanks for creating such an awesome tool. I really enjoy using it. 👍

**Comment by MackieLoeffel** [comment]
Maybe an additional attribute would be the best solution, something like:
`#[cfg_attr(rustfmt, rustfmt_skip_dont_check)]`

This would give the developer finer grained control over which parts should be checked, whether they satisfy the constraints.

**Comment by mjhanninen** [comment]
I would vote for an additional attribute giving finer control. I can easily imagine a scenario in which you have a painstakingly handcrafted source layout that you want to maintain manually in which case you would want to be informed about style violations. However, right now I'm getting bogus warnings for **raw string literals** (in my case big regular expressions) that just force the too long lines on me. When you really cannot split the line the warnings are unhelpful and worsens the signal-to-noise ratio.
