### ISSUE TITLE
Rustfmt spins for hours on large serde-derived implementation

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/rustfmt#1301]
I was looking into an issue that someone asked about on #rust with a large struct (284 fields) and a serde Deserialize implementation. I ran it through cargo-expand, which calls into rustfmt 0.7.1, and ended up spinning for ~2 hours before I gave up and killed it. There is quite a lot of code here (20,356 lines) but it's fairly straightforward.

https://gist.github.com/sfackler/ffe9e7ee45f83dd50479020de960fa05

I think this is distinct from #1265 since there don't appear to be any large chains in the expanded output.

**Comment by topecongiro** [comment]
rustfmt could not parse the original file, so I have done s/$crate/krate/ and tested with rustfmt-nightly 0.2.13. rustfmt managed to format the file without an error, within 2 seconds 🦀

**Comment by nrc** [comment]
Thanks for testing!
