### ISSUE TITLE
Option to sort imports in isort-like order?

### ISSUE THREAD

**Issue by sid0** [rust-lang-nursery/rustfmt#1302]
Python's [isort](https://pypi.python.org/pypi/isort) tool sorts imports with the following order:

* Future
* Python Standard Library
* Third Party
* Current Python Project
* Explicitly Local (. before import, as in: from . import x)
* Custom Separate Sections (Defined by forced_separate list in configuration file)

Could `rustfmt` gain an option somewhere to reorder imports with similar rules?

**Comment by Vurich** [comment]
I would love this if there were newlines between each group. I was about to file a request for a `regroup_imports` option that would do this exact thing.

**Comment by sanmai-NL** [comment]
Very useful indeed. Can this issue be closed in favor of #298 though?

**Comment by nrc** [comment]
Yeah, let's track in #298
