### ISSUE TITLE
Update style for function definitions

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1303]
Following https://github.com/rust-lang-nursery/fmt-rfcs/issues/39. This will be mostly possible by changing default values for options, but will also require some tweaks and bug fixes.

**Comment by topecongiro** [comment]
I am currently working on this. My work is incomplete, though it would be great if I could get any feedback. Is it possible to create a PR for that purpose?

**Comment by topecongiro** [comment]
The problems are:

1. I do not know how to `rustfmt` files in the `tests` directory. `rustfmt src/lib.rs` worked for files in `srcs`, are there similar way for formating `tests`?
2. Most of the failures from `cargo test`  just needs reformatting function definitions. However, I am having trouble handling hard tabs. Specifically, 
```rust
fn foo(a: i32, a: i32, a: i32, a: i32, a: i32, a: i32, a: i32, a: i32, a: i32, a: i32, a: i32) {}
```
in `tests/source/hard-tabs.rs` is formated to
```rust
fn foo(⏎
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
        a: i32,⏎                                                                                                                                                                                                                      
) {⏎                                                                                                                                                                                                                            
```

**Comment by nrc** [comment]
Hi @topecongiro I think this issue is mostly resovled, if you use the rfc rustfmt.toml, then I think we match the RFC pretty well (although perhaps there are still issues in the details). I should have closed it, probably, but I didn't remember it was open.

To answer your questions

1 - you can use https://github.com/rust-lang-nursery/rustfmt/blob/master/bootstrap.sh to reformat the tests, but this only works if there are no config options needed, otherwise you just have to do it manually.

2 - The new formatting should be behind an option(s) and I'm basically not too bothered about interactions between options, except for the RFC ones with each other (or *really* common options). https://github.com/rust-lang-nursery/rustfmt/issues/1427 is tracking this problem.

BTW, I've noticed you've been sending a lot of PRs recently, thank you! I'm going to be away from work for the next two weeks or so and will be much less responsive here - in particular reviews will probably be slow. Apologies in advance, and please don't be discouraged, I'll get to everything as soon as I can :-)

**Comment by topecongiro** [comment]
@nrc Thank you for you detailed explanation! Also sorry for asking questions hastily...it is embarassing that both `rustfmt.toml` and `bootstrap.sh` are in the root direcotry. I should have checked those files before asking questions or working on this issue. 

I am looking forward to contributing to rustfmt. Please enjoy your holidays :smile:
