### ISSUE TITLE
Add an option for newline braces in expressions/statements

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#131]
E.g., to render loops as:

```
loop
{
    let foo = bar();
}
```

(I believe there is already an option for functions, there should probably be three options in the end - one each for non-item blocks, functions, and non-function items).

**Comment by heinrich5991** [comment]
Don't know if this is the right thread, but an option for "newline before brace if argument list/pattern is multiline" would be really nice.

    fn foo(long: Args,
           meh: Foo) {
    }

to

    fn foo(long: Args,
           meh: Foo)
    {
    }

**Comment by nrc** [comment]
@heinrich5991 that is pretty much a separate issue, but it should be pretty easy to do - all the pieces are implemented already, you'd just need to add an option to the config system and then check it. If you'd like to have a go, you can just put a PR together, if you need some help feel free to ping me on irc. If you don't want to, then please file a separate issue, thanks!

**Comment by jaredmichaelsmith** [comment]
@nrc Will you still welcome changes to this? If so, I think I can tackle the first, and then I can submit @heinrich5991's as a separate PR.

**Comment by nrc** [comment]
@jaredmichaelsmith yes, that would be great! I think @heinrich5991 's request is the same as #999.

**Comment by Tsild** [comment]
This option seems to be present now, so shouldn't this issue be closed?
