### ISSUE TITLE
Method chain formatting produces long long first line

### ISSUE THREAD

**Issue by casey** [rust-lang-nursery/rustfmt#1314]
I was going to title this issue "long expression has weird formatting", but then I realized that 99% of rustfmt issues could probably be described thusly :P

I got the following from rustfmt today:

```
  let matches = App::new(env!("CARGO_PKG_NAME")).version(concat!("v", env!("CARGO_PKG_VERSION")))
    .author(env!("CARGO_PKG_AUTHORS"))
    .about(concat!(env!("CARGO_PKG_DESCRIPTION"),
                   " - ",
                   env!("CARGO_PKG_HOMEPAGE")))
    .setting(AppSettings::ColoredHelp)
    .get_matches_from_safe(args)?;
```

This strikes me as fine except for the first line, which seems weird, even though it's under my ideal width of 100 characters.

I would have expected and preferred:

```
  let matches = App::new(env!("CARGO_PKG_NAME"))
    .version(concat!("v", env!("CARGO_PKG_VERSION")))
    .author(env!("CARGO_PKG_AUTHORS"))
    .about(concat!(env!("CARGO_PKG_DESCRIPTION"),
                   " - ",
                   env!("CARGO_PKG_HOMEPAGE")))
    .setting(AppSettings::ColoredHelp)
    .get_matches_from_safe(args)?;
```

This seems like a bug to me.

**Comment by nrc** [comment]
This is somewhat intentional, though is likely to change with the new fmt RFCs.

**Comment by nrc** [comment]
Closing since it is not really a bug, and is only actionable as part of larger, already tracked work

**Comment by casey** [comment]
Ah, I see.

Can you link to the RFC (or RFC PR) in question?

**Comment by nrc** [comment]
Discussion of how to format should be discussed here: https://github.com/rust-lang-nursery/fmt-rfcs/issues/66

I'm doing a lot of refactoring in this area which is not really tracked anywhere.
