### ISSUE TITLE
Unused LicensePolicy configuration option

### ISSUE THREAD

**Issue by indiv0** [rust-lang-nursery/rustfmt#1320]
Does the `LicensePolicy` configuration enum do anything? I can't seem to find any references to it in the code other than [its definition](https://github.com/rust-lang-nursery/rustfmt/blob/f2c867d067eac285201e53672dcc5e42c2065785/src/config.rs#L118-L125).

**Comment by nrc** [comment]
probably not? I don't recall when or why it was added

**Comment by indiv0** [comment]
Would it be possible to make it do what it advertises? :)

I came across it accidentally but I'd really like that functionality.

**Comment by nrc** [comment]
It is possible (there is an early issue open about, iirc), but it is not clear to me exactly how it would work and is pretty low priority. If you'd like to work on it, I'd be happy to mentor though.

**Comment by indiv0** [comment]
I'd be willing to give it a try. Any place you could point me to to get started?

**Comment by nrc** [comment]
The first thing to do would be to figure out how this would work. You would need to select a license for a project and be able to check that with some kind of regex (e.g., to make sure different copyright years are OK). You might look at Rust's `make tidy` function to see how we do it there.

**Comment by indiv0** [comment]
Selecting the license could be done based on the license field in the `Cargo.toml`, as it could probably be assumed the name follows the SPDX format. As for the copyright years, I'll take a look at `make tidy`.
