### ISSUE TITLE
A few cases where ideal_width is not respected

### ISSUE THREAD

**Issue by C4K3** [rust-lang-nursery/rustfmt#1321]
There are several cases where I think it would make sense to respect ideal_width but where rustfmt only takes into account max_width. This causes lines that IMO should be broken to be put into a single line exceeding ideal_width but not max_width. I've got 4 examples here of that, using the default rustfmt configuration.

Example 1: When breaking function arguments only max_width and fn_call_width is taken into account, but it would be nice for it to break arguments into multiline if it would keep the line length under the ideal_width.
```
    some_nested_functions(that_take_two_arguments("abcdefghijklmnop",
                                                  "qrstuvwxyz"));
```
which is within 80 columns, but unless max_width = 80 or fn_call_width is sufficiently small, gets formatted as
```
    some_nested_functions(that_take_two_arguments("abcdefghijklmnop", "qrstuvwxyz"));
```
which is over 80 columns.

Example 2: Lists that without splitting into multiple lines exceed ideal_width but not max_width.
```
    let ab = ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
              "bbbbbbbbbbbbbbbbbbbbb"];
```
which gets formatted as
```
    let ab = ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbb"];
```
(unless doing so would exceed max_width.

Example 3: Long function definitions
```
fn long_fn_name_so_we_dont_exceed_default_fn_max_width(argument1: A,
                                                       argument2: B,
                                                       argument3: C)
```
which gets formatted as
```
fn long_fn_name_so_we_dont_exceed_default_fn_max_width(argument1: A, argument2: B, argument3: C)
```

Example 4: The same as above but with the return type.
```
fn long_fn_name_so_we_dont_exceed_default_fn_max_width(argument1: A,
                                                       arg2: B)
                                                       -> i32 {
```
which is formatted as
```
fn long_fn_name_so_we_dont_exceed_default_fn_max_width(argument1: A, arg2: B) -> i32 {
```

**Comment by C4K3** [comment]
In general from reading the source code it seems ideal_width is hardly used. IMO it would make more sense to try to rewrite a node using ideal_width first, and then if that fails try with max_width, across everything.

**Comment by nrc** [comment]
ideal width is only used for comments (it is badly named), and that only happens if an option is set. I did try an approach similar to this in the early days of rustfmt, but it ended up not working because we basically never using the ideal width (for nearly every AST node, if it fails at some width, it will fail at all widths, as a first approximation (assuming ideal and max widths are relatively close, etc)). It also led to inconsistent loooking formatting when it did get used.

**Comment by C4K3** [comment]
I see, would it make sense to rename ideal_width to comment_width or similar?

**Comment by nrc** [comment]
> would it make sense to rename ideal_width to comment_width or similar?

yes
