### ISSUE TITLE
Support directives to control whether rustfmt runs on a section of code

### ISSUE THREAD

**Issue by sid0** [rust-lang-nursery/rustfmt#1322]
`clang-format` allows you to disable formatting on a piece of code temporarily with special `clang-format off` and `clang-format on` comments.

http://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code

Sometimes the output of `rustfmt` isn't to my liking -- in those cases I'd like the ability to disable it for a section of code.

**Comment by nrc** [comment]
you can use #[rustfmt_skip] to skip items

**Comment by sid0** [comment]
Hmm, that sounds very promising! Is that documented anywhere?

And does Rust make it possible for that attribute to be applied to individual blocks or lines of code?

**Comment by nrc** [comment]
Documented here: https://github.com/rust-lang-nursery/rustfmt#tips

You can apply attributes to blocks and statements (but not individual expressions)

**Comment by sid0** [comment]
Thanks!

**Comment by behnam** [comment]
For future visitors here who don't click on the link before trying out the suggestion: that only works in nightly. From there link:

> 
> ## Tips
> 
> * For things you do not want rustfmt to mangle, use one of
> 
>     ```rust
>     #[rustfmt_skip]  // requires nightly and #![feature(custom_attribute)] in crate root
>     #[cfg_attr(rustfmt, rustfmt_skip)]  // works in stable
>     ```
> * When you run rustfmt, place a file named `rustfmt.toml` or `.rustfmt.toml` in
>   target file directory or its parents to override the default settings of
>   rustfmt.
> * After successful compilation, a `rustfmt` executable can be found in the
>   target directory.
> * If you're having issues compiling Rustfmt (or compile errors when trying to
>   install), make sure you have the most recent version of Rust installed.
>

**Comment by HossainAdnan** [comment]
Sorry for bumping this so late. I am aware of `#[rustfmt::skip]` directive. However How can I disable and re-enable rustfmt within a certain portion of a block? 

```rust
fn main() {
    // rustfmt off
    println!(
                  "something"
    );
    // rustfmt on
}
```

This is helpful when I am constructing a big gtk Box, makes my code more readable: 
Example:
```rust
use {gtk::prelude::*, crate::consts::INNER_SPACE};

#[rustfmt::skip]
pub struct PrimaryWindow {
pub header_bar: gtk::HeaderBar,
    pub header_bar_hbox: gtk::Box,
        pub window_title: gtk::Label, // never really used
        pub stack_switcher: gtk::StackSwitcher,
pub window: gtk::ApplicationWindow,
    pub outer_hbox: gtk::Box,
        pub inner_vbox: gtk::Box,
            pub stack: gtk::Stack,
}

impl PrimaryWindow {
    pub fn new(gtk_application: &gtk::Application) -> Self {
        // init
        // ...
        // return

		// rustfmt off
        Self {
            header_bar: header_bar,
                header_bar_hbox: header_bar_hbox,
                    window_title: window_title,
                    stack_switcher: stack_switcher,
            window: window,
                outer_hbox: outer_hbox,
                    inner_vbox: inner_vbox,
                        stack: stack,
        }
		// rustfmt on
    }
}
```

**Comment by sinkuu** [comment]
You can just stick `#[rustfmt::skip]` attribute to statements.

```rust
fn main() {
    #[rustfmt::skip]
    println!(
                  "this will not be formatted"
    );
    println!(
                  "this will be formatted"
    );
}
```

**Comment by HTG-YT** [comment]
Could `rustfmt` be skipped on the file header of a Rust file (as in license information, if any)?

**Comment by calebcartwright** [comment]
> Could `rustfmt` be skipped on the file header of a Rust file (as in license information, if any)?

There's several existing ways to skip an entire file:

- Inner attributes, e.g. `#![rustfmt::skip]` within the file, https://github.com/rust-lang/rustfmt#tips
- Via a commented `@generated` marker, which yes can be within license headers/comments present at the top of the file, along with the corresponding configuration option https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#format_generated_files
- Adding the file path to your `ignore` list in the config file, https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#ignore

**Comment by pauschuu** [comment]
What if I have something like this:
```
const QR_MASK: u8     = 0b10000000;
const OPCODE_MASK: u8 = 0b01111000;
const AA_MASK: u8     = 0b00000100;
const TC_MASK: u8     = 0b00000010;
const RD_MASK: u8     = 0b00000001;

const RA_MASK: u8     = 0b10000000;
const AD_MASK: u8     = 0b00100000;
const CD_MASK: u8     = 0b00010000;
const RCODE_MASK: u8  = 0b00001111;
```

And I don't want to use `#[rustfmt::skip]` on every line?

Is there a way to also specify a multi-line skip like `#[rustfmt::skip_start]...<more lines>...#[rustfmt::skip_end]`?
Or would there be another solution that I am just missing here?

**Comment by DrewTChrist** [comment]
> Is there a way to also specify a multi-line skip like `#[rustfmt::skip_start]...<more lines>...#[rustfmt::skip_end]`? Or would there be another solution that I am just missing here?

I was also looking for a solution to this. I have some code with a somewhat large list of constants. The best option I could find is putting the constants in a module and then adding `#[rustfmt::skip]` to the module. Not particularly ideal, but it works.

**Comment by Visne** [comment]
> Is there a way to also specify a multi-line skip

Is there a way to do this in late 2023?

**Comment by Rot127** [comment]
The following works for me on stable:

```
#[cfg_attr(rustfmt, rustfmt_skip)]
{
<code>
}
```
