### ISSUE TITLE
Refactor write_list

### ISSUE THREAD

**Issue by cassiersg** [rust-lang-nursery/rustfmt#133]
I would like to refactor write_list:
- integrate it with the Rewrite semantics
- make it simpler

That would fix some problems with the current write_list:
- It can't fail, so we doesn't have a way to cleanly handle corner-cases. (This is needed to have a clean (and always respected) "pattern" like Rewrite.)
- It hasn't distinction between the width of the last line and the width of the other lines.
- It always puts a space between items on the same line.
- Each call needs work to rewrite items : it could be automatically done for Rewrite items.
- The code is complicated.

This proposal is very simple, cutting a lot of corner-cases, or not frequently used features. I think it's better to avoid complex layouts, because they are complicated to read. This is maybe too simple, see Complements section for ideas of what can be added.
## Main changes
- Add a `supp_separator: &str` parameter : this will be placed after the separator, if the next item is on the same line. That adds flexibility and allows to format Paths (mod::submod::fn).
- Add distinction `width` / `max_width` : that's the same semantics as Rewrite
- Remove distinction `h_width`/ `v_width` : it doesn't seem to be useful
  - Horizontal and Vertical tactics: irrelevant
  - Mixed tactic: it's not used, and doesn't appear to be useful
  - HorizontalVertical: usefulness of this distinction seems to be uncertain (see https://github.com/nrc/rustfmt/issues/82#issuecomment-105314265) 
- Make items no longer strings, but rewrite : this allows to automatically rewrite with the right width (which is different for the last item).
- Keep a function that works with strings as items, and check (or debug_assert if too costly) that items respect width conditions.
- Add ability for write_list to fail (return an Option)
## Interface changes

``` rust
pub struct ListItem<T> {
    pub pre_comment: Option<String>,
    // Item should include attributes and doc comments
    pub item: T,
    pub post_comment: Option<String>,
}

pub struct ListFormatting<'a> {
    pub tactic: ListTactic,
    pub separator: &'a str,
    pub supp_separator: &'a str,
    pub trailing_separator: SeparatorTactic,
    pub offset: usize,
    pub width: usize,
    pub max_width: usize,
    pub ends_with_newline: bool,
}   

pub fn write_list<'a, T>(items: &[ListItem<T>], formatting: &ListFormatting) -> Option<String>;

pub fn write_list_str<'a>(items: &[ListItem<String>], formatting: &ListFormatting) -> Option<String>;
```
## Implementation

This is a quick description of the algorithm for the different tactics.

HorizontalVertical:
- if any comment => Vertical (better for readability)
- if it doesn't fit in width => Vertical
- else => Horizontal

Horizontal
- if any comment => return None
- if it doesn't fit in width => return None
- else: join items with separator + supp_separator (and add separator at the end if trailing_sep == Always)

Vertical
- reformat pre_comment in max_width, line-style ("//")
- For all items except last one:
  - reformat item in max_width
  - add separator
  - add post-comment on the same line, with line-style if it fits on the rest of the line, else block_style
  - newline
- For last item
  - reformat item in width
  - add separator if trailing_sep != Never
  - add post-comment on the same line, with line-style if it fits on the rest of the line and !ends_with_newline, else block_style

Mixed
- if any comment => Vertical
- if any element is multi-line => Vertical
- fill lines with items, using max_width (width for last line), and separator + supp_separator for items on the same line, only separator at the end of the line
## Complements
- Default less frequently to Vertical mode in Horizontal and Mixed layouts.
- Keep distinction between max_h_width and max_v_width. max_h_width would be used for Horizontal and Mixed (if only one line) layouts. max_v_width for all other cases.

Thoughts about this ?

cc @nrc @marcusklaas

**Comment by marcusklaas** [comment]
You're on fire lately!

I agree with your criticisms of the current `write_list`. It needs work.

A few thoughts about your proposal:
- returning `Option<String>`: yes!
- taking `&[ListItem<T>]` where `T: Rewrite` is also a great idea. I think this would even enable us to take `IntoIterator<T>` where `T: Rewrite` because we would no longer need to compute the total width. Naturally, we should aim to minimize the code duplication between this variant and the `&[ListItem<String>]` variant.
- is a `supp_separator` really adding needed flexibility? I'm not sure the paths example that you mentioned is a natural fit for `write_list`. There's no comments involved or line breaks.
- returning `None` on any comment in Horizontal mode is a bit too strong, I think.
- any specific ideas on how to reduce complexity? There's still many many cases.
- a special case for the last item would be sweet!

Can we incorporate https://github.com/nrc/rustfmt/issues/123 at the same time?

**Comment by nrc** [comment]
@cassiersg overall sounds like a good move, and thanks for the detailed plan - it's better than most work on the compiler gets! I have a lot of questions though, I'll try and start with the high level stuff...

It seems that being able to handle paths is a goal here, that was kind of a non-goal for me in writing this - I make the distinction (and this might not be a good idea) between 'lists' which are obviously many things and each thing can be moved around (so, lists of fields, arguments, etc.) and joined up things such as paths and chains of calls, etc., which really want to be one thing all together and splitting is kind of a last resort. Obviously there is some overlap, e.g., 

```
foo.bar
   .baz()
   .qux();
```

Layouts like this are list-like but operating on a joined thing. I'm not sure how often we get cases like these and how much code is worth sharing. My guess is that the high level rewrite_list interface should not handle stuff like this, but lower level stuff should be shared.

You mention in your requirements the difference between first line, last line, other lines widths. I've also been thinking about this. There seems to be some fundamental options for formatting, allow me to demonstrate with some ascii art:
```
|..........+------------+   |
|          |            |   |
|          |            |   |
|          |            |   |
|          |            |   |
|          |            |   |
|          +------------+...|
|                           |
|..........+------------+   |
|    +-----|            |   |
|    |                  |   |
|    |                  |   |
|    |                  |   |
|    |                  |   |
|    +------------------+...|
|                           |
|..........+---------------+|
|          |               ||
|          |               ||
|          |               ||
|          |               ||
|          |            +__||
|          +------------+...|
|                           |
|..........+---------------+|
|    +-----|               ||
|    |                     ||
|    |                     ||
|    |                     ||
|    |                  +--+|
|    +------------------+...|
```
Here the outermost `|`s indicate the page width (given by the width/max width/whatever) and the `...`s indicate other text around the block being formatted. I started off just handling the first case, but I think we want to be able to handle the last two. I'm not sure there is ever any point in handling the first two. That means we probably want a first line pre-indent, a last line post-indent, a general indent and a general width.

Talking of width, I'm not happy with having a width and max-width in general. I think it would be better to have a single width. We probably need to make an exception for comments (100 wide comments hurt my eyes, but perhaps I'm just being sensitive). Do you think there is a pressing need to have the width/max width concept here?

(more in another comment...)

**Comment by nrc** [comment]
In detail, replies to changes:


Hmmm, this is an interesting change, I had kind of wanted to keep write_list out of this business, i.e., its just a way to arrange strings. But the argument that the caller might not know the space for each item is convincing (and I have felt this pain before). This is a somewhat important change to the design here - we are moving away from write_list being a way to arrange strings and into it being a full part of reformatting, albeit, rather abstract. I think that is OK, it might inform some other changes in the design.

> Keep a function that works with strings as items

Depends on the above one, it would be nice to minimise the API and use one or the other, but if they're both necessary then we need them both.

> Add ability for write_list to fail (return an Option)

Yes!

**Comment by nrc** [comment]
Sorry, bad copy&paste, needed to edit the previous comment

**Comment by nrc** [comment]
> Default less frequently to Vertical mode in Horizontal and Mixed layouts.

I'm not sure what this means, could you explain?

**Comment by nrc** [comment]
And in reply to @marcusklaas:

> returning None on any comment in Horizontal mode is a bit too strong, I think.

I agree. We should only return None where the caller might be able to recover some how (by passing more flexible parameters or reformatting an outer item or something). In this case, I don't think it can, so rewrite_list needs to cope as best it can. I think the best thing is either to ignore the comment and emit a warning, stick the comment inline in `/* */`, or just panic.

**Comment by cassiersg** [comment]
@nrc I don't see much distinction between 'lists' and 'joined up things', I don't think the "strongness" we want to keep them grouped will change the algorithms used, but I didn't worked on this so I might be wrong. The only thing closely related to this distinction is the `supp_separator`, the rest is more general.

*Layouts* @nrc If I understand correctly your ascii-art, the three first patterns are just special cases of the fourth pattern ? I think this assembles concepts already used:
- first line pre-indent is `offset` (semantics of `Rewrite`)
- last line post-indent is equivalent to `width` (semantics of `Rewrite`)
- general indent is equivalent to `block-indent`.
-  general width is equivalent to the max_width in some cases
That to say this formatting pattern isn't specific to lists and we should decide conventions how to name these things and what are the references for the values (eg: in Rewrite, the width is a based on the offset, it might also be defined as absolute (as max_width parameters are)). I welcome ideas of conventions.
@nrc The width/max_width were expressing last line width / general width (but names weren't clear) ;)

**Abstraction levels** This wasn't specified in the proposal, and questions raising shows that we need some ability to work with Strings and with Rewrite. I think working with Strings (*a bit* like the current write_list) is low-level: we don't have all degrees of freedom, like for the width/indent partterns discussed above. The low-level would take only already formatted strings, for items and for comments. High level interface would take Rewrite, and work well with width/indent patterns.
We might add another high level interface that would be close of the current write_list : take items as strings, but reformat comments. That might be handy for some cases harder to handle with Rewrite.



        Default less frequently to Vertical mode in Horizontal and Mixed layouts.

    I'm not sure what this means, could you explain?

In HorizontalVertical and Mixed modes, if there is any comment, I propose to switch to Vertical mode. This is radical (I think it's justified by readability.), maybe too. We might want to keep Horizontal with comments inside `/* ¨*/`, or in Mixed mode, format only the commented item as Vertical, and keep other in Mixed mode, etc.

The issue with Horizontal and comments is related to it:
- I think Horizontal mode will never be used: if it fails, we will probably try with Vertical or Mixed... so we should directely try with HorizontalVertical or Mixed. I thought it more as a mode used internally, derived from HorizontalVertical.
- The Horizontal mode is never used when there are comments (see above), so it might fail. Propositions of @nrc makes sense: if we consider comment in Horizontal mode readable, let's format it with `/* */` (and use that if possible in HorizontalVertical). If not, ignore+warning or panic look good. Another possibility is to remove Horizontal mode from public interface.

@marcusklaas Agree for iterators, maybe simply `Iterator` will do the job.

Complexity: I hope clear semantics and high/low level distinction will help. Handle comments only in Vertical mode (while not thought for simplicity of code, but for readability) would also help (a lot ?).

#123 should be easy to add.

    a special case for the last item would be sweet!

I don't understand that, could you explain ?

I hope I didn't miss any comment ;)
