### ISSUE TITLE
Allow block formatting for arguments in function call

### ISSUE THREAD

**Issue by ThermalSpan** [rust-lang-nursery/rustfmt#1333]
First, I apologize if this is a duplicate issue, or a configuration option that's already available. I've looked through the issues here and the configuration settings and was unable to find something like what I had in mind.

Currently, when rustfmt breaks a function call across multiple lines, all arguments are spaced to match the indentation level first argument. I would prefer that if the function call is to be broken across multiple lines, that all arguments are tabbed in only one level.

For example, here is a function call as rustfmt would break it up currently:

```rust
let result = foo::bar(arg1,
                      arg2,
                      arg3);
```

However, I would prefer (to have the option for) formatting like:

```rust
let result = foo::bar(
    arg1,
    arg2,
    arg3
);
```

While it is a matter of personal preference, my justification is that the former (current) formatting introduces a great deal of visual discrepancy in the code as most unique function calls will end up with their arguments being indented to different levels. My preferred formatting makes the argument indenting the same across unique function calls, and also makes for cleaner diffs when changing function arguments, and function interfaces.

**Comment by stepancheg** [comment]
Seems to be the same as #1305.

**Comment by nrc** [comment]
Indeed
