### ISSUE TITLE
Line exceeded maximum length warning caused by CRLF

### ISSUE THREAD

**Issue by iliekturtles** [rust-lang-nursery/rustfmt#1335]
The code block below gives the following warning when the file is saved with Window's native CRLF line ending: `Rustfmt failed at S:\uom\src\system.rs:143: line exceeded maximum length (maximum: 100, found: 101) (sorry)`. Saving the file with a LF line ending silences the warning. `rustfmt` must be counting the CR (`\r`) as part of the line length.

```rust
                impl<$($name,)+ $($symbol,)+ V> $crate::stdlib::ops::$Trait<BaseUnits<$($name,)+ V>>
```

**Comment by Insomgla** [comment]
@iliekturtles It indeed does : https://github.com/rust-lang-nursery/rustfmt/blob/master/src/lib.rs#L473

However, since there's a special case for `\r`, it seems it's done on purpose. I don't know why, not familiar with this package, let's hope someone more experienced with this package can help us :)

**Comment by iliekturtles** [comment]
After digging through the blame I see that commit 598fcdddc39fb9ca088e21191e35aeae51ed626e, which references #717, added the `line_len` increment. This brings up a bigger question about why `len_utf8` is being used which reports character width in bytes. What should really be counted graphemes? How does that handle combining characters?

**Comment by Insomgla** [comment]
@iliekturtles Good catch ! It does handle them poorly, actually.

This code (length of the line is 70 graphemes):
```
fn main() {
    println!("ééééééééééééééééééééééééééééééééééééééééééééééééééééé");
}
```

produces :

```
Rustfmt failed at combined_characters.rs:2: line exceeded maximum length (maximum: 100, found: 123) (sorry)
```

Let's open an issue for that and link it to this one ?

**Comment by nrc** [comment]
The special case code for `\n` should also count `\r`. That should be an easy fix.

Rustfmt just doesn't handle unicode > 8 bits well at all (currently the oldest issue in this repo - #6).

**Comment by Insomgla** [comment]
Thanks for the info @nrc
