### ISSUE TITLE
Include tests into archive on crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang-nursery/rustfmt#1339]
In fedora, we run `cargo test` on archive from crates.io, so having tests would be useful for us.

**Comment by nrc** [comment]
Hmm, is it common or best practice to include tests in crates.io crates? It seems like adding a bunch of stuff that most users would not need to me. I wonder if we could make it easier to get code from the repo if you want to run tests?

**Comment by ignatenkobrain** [comment]
Usually, people don't use `include` or `exclude`, so they just push everything what's in repo. From my POV, if tests are not more than megabyte or couple of them -- it's fine to include.

**Comment by nrc** [comment]
Fixing this (by removing the `include` line) roughly doubled the size of the cargo crate, but it is still < 300kb, so I think that's OK.
