### ISSUE TITLE
please include LICENSE files into archive on crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang-nursery/rustfmt#1340]
ASL 2.0 requires text license to be present along with source. MIT doesn't require, but it's required by Fedora policies and it would not hurt as well.

**Comment by vbmade2000** [comment]
I can take this one if you don't mind.

**Comment by nrc** [comment]
@vbmade2000 sure, that would be great

**Comment by vbmade2000** [comment]
Thanks. Please provide some details on it.

**Comment by vbmade2000** [comment]
I see there are two license file LICENSE-APACHE and  	LICENSE-MIT in https://github.com/rust-lang/crates.io repo. Do we still require any other license file ?

**Comment by vbmade2000** [comment]
Ah I misunderstood issue. 
@ignatenkobrain We can close this issue as @andylibrian addressed this issue already.
