### ISSUE TITLE
rustfmt_skip is ignored on expressions

### ISSUE THREAD

**Issue by CraZySacX** [rust-lang-nursery/rustfmt#1346]
Before:
```
#[cfg_attr(rustfmt, rustfmt_skip)]
Box::new(self.inner.call(req).then(move |result| {
    match result {
       Ok(resp) => Box::new(future::done(Ok(resp))),
       Err(e) => {
           try_error!(clo_stderr, "{}", e);
           Box::new(future::err(e))
       }
   }
}))
```

Run `cargo fmt`

After:
```
#[cfg_attr(rustfmt, rustfmt_skip)]
Box::new(self.inner.call(req).then(move |result| match result {
                                       Ok(resp) => Box::new(future::done(Ok(resp))),
                                       Err(e) => {
    try_error!(clo_stderr, "{}", e);
    Box::new(future::err(e))
}
                                   }))
```

I would expect nothing to happen to the original structure.

**Comment by Insomgla** [comment]
Could you create a small working reproducer ?

**Comment by CraZySacX** [comment]
Will do.

**Comment by Insomgla** [comment]
Cool. 

That being said, `rustfmt_skip` is not _absolutely_ ignored, it usually works, but it seems there are still some cases which falls through the net :)

**Comment by nrc** [comment]
This is an attribute on an expression - it is an unstable Rust feature and may be deprecated. Rustfmt ignores these attributes. I'm not sure whether putting the attribute on a statement would work or not? Hopefully it does. I'm leaving this issue open for that.
