### ISSUE TITLE
Function call arguments on newline

### ISSUE THREAD

**Issue by yongqli** [rust-lang-nursery/rustfmt#1358]
Currently `rustfmt` formats the below code as:

    pub fn main() {
        DVector::from_iterator(v.len(),
                               v.into_iter().map(|a| {
                                                     let b = a;
                                                     println!("{:?}", b);
                                                     b
                                                 }))
    }

I would prefer it to look like:

    pub fn main() {
        DVector::from_iterator(
            v.len(), v.into_iter().map(|a| {
                let b = a;
                println!("{:?}", b);
                b
            })
        )
    }

What settings do I need to use? I'm currently using:

    fn_brace_style = "PreferSameLine"
    fn_args_layout = "Block"
    use_try_shorthand = true
    match_block_trailing_comma = true

**Comment by nrc** [comment]
I don't think you can currently get that, but I intend to land some settings in the next week or so that will help.
