### ISSUE TITLE
cannot format string in match case

### ISSUE THREAD

**Issue by tspiteri** [rust-lang-nursery/rustfmt#1365]
```
fn foo() {
    match i {
        1 => {
            "string_1234567890123456789012345678901234567890123456789012345678901234567890123456789"
        }
        _ => {
            identifier_45678901234567890123456789012345678901234567890123456789012345678901234567890
        }
    };
}
```

There is no issue with `identifier_...`, but rustfmt tries to remove the braces around `"string_..."`, resulting in a line that is too long. The same happens with something like `Some("string_...")`. This happens whenever the length of the match pattern (`1` in this case) plus the length of the string expression is too long to fit on a single line.

This is using rustfmt 0.8.0.

**Comment by nrc** [comment]
Closed by #1488
