### ISSUE TITLE
Returning Ok(Struct { }) has extra indent in rustfmt 0.8.0.

### ISSUE THREAD

**Issue by daboross** [rust-lang-nursery/rustfmt#1372]
What I would expect, and what rustfmt 0.7.1 outputs:
```rust
fn returns_result() -> Result<Struct, ()> {
    Ok(Struct {
    	var1: 2,
    	var2: 3,
    	var3: 4,
    })
}
```

0.8.0 now outputs:

```rust
fn returns_result() -> Result<Struct, ()> {
    Ok(Struct {
           var1: 2,
           var2: 3,
           var3: 4,
       })
}
```

If this is a duplicate, or if this is the new preferred style and there's a configuration option that I missed, my apologies.

**Comment by nrc** [comment]
This is expected. Function arguments are visually indented, which means the indent for `Struct` here starts after `Ok(`. I hope to support block indented args properly soon.

**Comment by daboross** [comment]
Thank you!

I really need to look into the internals of what rustfmt is doing more, this is quite interesting.
