### ISSUE TITLE
struct member + comma + comment on following line fails

### ISSUE THREAD

**Issue by khuey** [rust-lang-nursery/rustfmt#1378]
```rust
struct Foo {
    bar: u32,
    // TODO more stuff                                                                                                       
}
```

Formatting this will print "Rustfmt failed at /home/khuey/dev/scratch/struct-member-whitespace/src/lib.rs:2: left behind trailing whitespace (sorry)" and add a single space immediately after the comma.

Judging by what happens when I remove the comma, it seems like it's trying to move the comment after the member.

**Comment by khuey** [comment]
And note that this happens even with a blank line between the member and the comment.

**Comment by dhardy** [comment]
Yes, without the comma the comment gets moved. Rustfmt has no justification for doing that (reformatting doc is one thing, comments are quite another).

**Comment by nrc** [comment]
> Rustfmt has no justification for doing that

Rustfmt often has to *move* comments. It won't change comments, but moving them is sometimes necessary (in this case it is kind of a side-effect of moving them in other situations).

**Comment by topecongiro** [comment]
In 0.8.3, the above code gets formatted successfully:
```rust
struct Foo {
    bar: u32, // TODO more stuff
}
```

**Comment by dhardy** [comment]
More to the point, this gets formatted correctly:
```
struct Foo {
    bar: u32,
    // TODO more stuff
}
```
Issue can be closed.
