### ISSUE TITLE
Merge imports from the same module

### ISSUE THREAD

**Issue by tomwhoiscontrary** [rust-lang-nursery/rustfmt#1383]
I would like two imports from the same module:

```
use std::time::Duration;
use std::time::Instant;
```

To become a single import list:

```
use std::time::{Duration, Instant};
```

Relatedly, i'd like this a duplicate import:

```
use std::time::Duration;
use std::time::Duration;
```

To become single:

```
use std::time::Duration;
```

!

And finally, it would be nice if there was an option to have turn an import of a module and some things from inside it:

```
use std::thread;
use std::thread::{Builder, JoinHandle};
```

Into a single import list using self for the module:

```
use std::thread::{self, Builder, JoinHandle};
```

**Comment by sergeysova** [comment]
Any progress here?
