### ISSUE TITLE
Questionable indenting of structs inside simple expressions

### ISSUE THREAD

**Issue by mernen** [rust-lang-nursery/rustfmt#1387]
v0.8 output:

```rust
fn test1() {
    Ok(Foo {
           x: 1_000_000,
           y: 2_000_000,
       })
}

fn test2() {
    let x = Some(Foo {
                     x: 1_000_000,
                     y: 2_000_000,
                 });
}
```

v0.7.1 feels much more natural to me:

```rust
fn test1() {
    Ok(Foo {
        x: 1_000_000,
        y: 2_000_000,
    })
}

fn test2() {
    let x = Some(Foo {
        x: 1_000_000,
        y: 2_000_000,
    });
}
```

I'm not sure what would be the ideal rule, but I think this is a starting point: if a certain logical line fits in a single physical line except for the last function/method call's last argument's block, expand just that final argument, aligning its block to the whole line (rather than to the argument).

For example:

```rust
fn demo() {
    let w = foo().bar().and_then(|x| {
        // ...
    });
}
```

v0.7.1 agrees with my proposed rule, but v0.8 wants to indent this block all the way to the `|x|`.

**Comment by nrc** [comment]
This is intentional (though I agree imperfect) - the old behaviour was an odd mix of block and visual indenting, the new behaviour is a clean visual indent inside a block indent. I intend to change to pure block indent soon which will give something like the 0.7 behaviour for these examples.
