### ISSUE TITLE
Complex indices wrapping unnecessarily to multiple lines

### ISSUE THREAD

**Issue by jonhoo** [rust-lang-nursery/rustfmt#1396]
```rust
fn main() {
    let nodes = Vec::new();
    let index = Some(Some(Some(Some(3))));
    let n = nodes[index.unwrap().unwrap().unwrap().unwrap()];
}
```
turns into
```rust
fn main() {
    let nodes = Vec::new();
    let index = Some(Some(Some(Some(3))));
    let n = nodes[index.unwrap()
        .unwrap()
        .unwrap()
        .unwrap()];
}
```
Despite the non-wrapped version fitting easily on one line. One fewer `Option` does not cause a wrap, so this seems like it might be intentional ("always break if there are five or more segments")? I feel like that might be overly aggressive, as five can be pretty easily run into if you have, say, an `Option` of a struct with a tuple member, one of whose elements has a method you want to call to get the index. Is there a particular reason why `rustfmt` doesn't instead choose to break only if the line wouldn't otherwise fit?

**Comment by nrc** [comment]
This controlled by the `chain_one_line_max` option.

**Comment by jonhoo** [comment]
@nrc is there a reason for the limit to be so low, or for the default not to be "break when line becomes too long"?

**Comment by nrc** [comment]
@jonhoo when each element is something complex, then it doesn't seem low to me. Unfortunately when each element is just a field (or `unwrap`, etc) then it does end up a bit silly. I plan to replace with a character limit soon-ish, which is tracked on an issue somewhere, though I don't recall exactly where.
