### ISSUE TITLE
rustfmt_skip should have the same effect on warnings when inside and outside a module

### ISSUE THREAD

**Issue by 8573** [rust-lang-nursery/rustfmt#1399]
I'm using [LALRPOP], which generates a Rust file from a build script,
which file I then reference with a `mod <filename>` item.

The generated file is large and, relative to the style used by
rustfmt, densely formatted, and has many long lines, at which rustfmt
always emits error messages about being unable to shorten them.
rustfmt does, however, manage to format much of the file — expanding
it from 3010 lines to 8265.

How, if at all, could I instruct rustfmt to ignore this file?

[LALRPOP]: <https://github.com/nikomatsakis/lalrpop>

**Comment by nrc** [comment]
You can add a `rustfmt_skip` annotation to the mod declaration and then the file will be skipped. See the README for more info on the annotation.

**Comment by 8573** [comment]
Ah! I had put the attribute inside the file (as `#![cfg_attr(rustfmt, rustfmt_skip)]`), noted that this resulted in more overlong-line messages, saw that that's intentional (#1298), and didn't think that the behavior would be different were I to put the attribute on the `mod` item; thanks, and my apologies for not trying that earlier.

**Comment by solson** [comment]
@nrc If `#[rustfmt_skip] mod foo;` works, then `#![rustfmt_skip]` at the top-level inside `foo.rs` should work, too, IMO. It'd be better if a module can be self-contained in that way.

**Comment by nikomatsakis** [comment]
I agree with @solson on this point -- also, to me, it's just plain surprising for `#![foo]` in `mod.rs` and `#[foo] mod` to have distinct effects.

**Comment by topecongiro** [comment]
Confirmed that this is supported in 0.3.1-nightly.
