### ISSUE TITLE
blank lines between definitions

### ISSUE THREAD

**Issue by jaheba** [rust-lang-nursery/rustfmt#1410]
If I'm not mistaken, rustfmt does not *enforce* the number of blank line between definitions (structs, enums, functions).

What I've seen in many rust code bases is to use one blank line between definitions. Other languages have slightly different rules, e.g. [Python](https://www.python.org/dev/peps/pep-0008/#blank-lines):

> Surround top-level function and class definitions with two blank lines.
> 
> Method definitions inside a class are surrounded by a single blank line.
>
> Extra blank lines may be used (sparingly) to separate groups of related functions. Blank lines may be omitted between a bunch of related one-liners (e.g. a set of dummy implementations).
> 
> Use blank lines in functions, sparingly, to indicate logical sections.

Example:

```rust
// Python style (2 blank lines)
struct X {
    ...
}


struct Y {
    ...
}
```

```rust
// default style (1 blank line)
struct X {
    ...
}

struct Y {
    ...
}
```

---

What are your thoughts on this topic?

**Comment by nrc** [comment]
This is discussed here: https://github.com/rust-lang-nursery/fmt-rfcs/issues/57 In general style guidelines should be discussed on that repo and this one used for implementation issues.
