### ISSUE TITLE
Chain with multi-line parent has bad indenting of first child

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1420]
E.g.,

```
    given(
        r#"
        # Getting started
        ...
    "#,
    )
            .running(waltz)
```

I would expect `.running` to be indented once deeper than `given`. However, even that looks odd because the previous line is shorter than the tab width.

**Comment by killercup** [comment]
cf. https://github.com/rust-lang-nursery/fmt-rfcs/issues/66#issuecomment-289882009 and https://github.com/rust-lang-nursery/fmt-rfcs/issues/66#issuecomment-289886281
