### ISSUE TITLE
Formatting with RFC settings results in compilation error in assert_eq!()

### ISSUE THREAD

**Issue by VictorGavrish** [rust-lang-nursery/rustfmt#1425]
Here is a snippet of code that gets formatted badly:

```rust
assert_eq!(
    1,
    hashmap
        .values()
        .filter(|v| v.upgrade().is_some())
        .count()
);
```

`rustfmt` adds a comma after `.count()`, which results in "unexpected end of macro invocation".

**Comment by nrc** [comment]
dup of #1499, but this is an actual example of it causing harm, so will leave open

**Comment by Dushistov** [comment]
> dup of #1499, but this is an actual example of it causing harm, so will leave open

You mean dup of #1419 ?

**Comment by nrc** [comment]
yes, thanks

**Comment by nrc** [comment]
Fixed by https://github.com/rust-lang-nursery/rustfmt/pull/1436
