### ISSUE TITLE
config-path should allow pointing to a file

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1429]
As well as (or instead of) a directory. I imagine if you give a directory, rustfmt looks for rustfmt.toml in that directory, it you give a file, it looks for that specific file.

I'm also not sure if it is a good idea to walk up from the given directory. That seems like a good idea for the default directory, but not for a specified one.

**Comment by shepmaster** [comment]
Yes. I was very confused because I wanted to say `--config-path rfc-format.toml` and it didn't work **and** didn't provide an error, just kept using the defaults.

I'd suggest that if I say "use this file", it better use that file or else blow up real loud.
