### ISSUE TITLE
Why two different approaches?

### ISSUE THREAD

**Issue by AlirezaEsmailzad** [rust-lang-nursery/rustfmt#1437]
Hi.
I am just learning rust and trying to write "Guess the number" software.
I installed rustfmt in atom. but I have a question:
why rustfmt turns this:

    io::stdin().read_line(&mut guess).expect("Failed to read input.");
into this:

    io::stdin()
        .read_line(&mut guess)
        .expect("Failed to read input.");`
but it acts exactly other wise and turns this one:

    let mut guess: u32 = guess
        .trim()
        .parse()
        .expect("We need a number");
into this:

    let mut guess: u32 = guess.trim().parse().expect("We need a number");

Is it on purpose or is it a bug?

**Comment by nrc** [comment]
It is intentional. There is a config option `chain_one_line_max` which is the max number of characters in a chain of method calls and field accesses that Rustfmt will put on one line. Your first example is greater than that limit, your second is less than it.
