### ISSUE TITLE
Running rustfm removes comments in the where clause.

### ISSUE THREAD

**Issue by roSievers** [rust-lang-nursery/rustfmt#1439]
In this playground example, running Format removes the only comment.

https://play.rust-lang.org/?gist=226e64a85eaac43329dd1cba932f5290&version=stable&backtrace=0

```rust
impl<V> Test<V>
    where V: Clone // This comment is removed by formating!
{
    pub fn new(value: V) -> Self {
        Test {
            cloned_value: value.clone(),
            value: value,
        }
    }
}
```

Steps to reproduce: Open the linked example and press `Format`.

**Comment by nrc** [comment]
In general, there are places like this where Rustfmt can't 'see' comments. There is not much we can do about this because it is due to insufficient information from the parser. I have a plan to fix this one day, but it is not likely to happen soon, sorry.
