### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by clarcharr** [rust-lang-nursery/rustfmt#1440]
It would be nice if rustfmt had a changelog every time it did a release, somewhere. It doesn't have to be overly fancy or specific, but it'd be nice to have.

**Comment by nrc** [comment]
This is a good idea and I should do it, but it is quite a lot of work to start doing. I will do my best to do this from the next point release (i.e., there won't be a changelog for v0.9, but there should be for everything after that).

**Comment by topecongiro** [comment]
We now have a changelog, though not updated consistently.
