### ISSUE TITLE
FnArgLayoutStyle::BlockAlways removed

### ISSUE THREAD

**Issue by mathstuf** [rust-lang-nursery/rustfmt#1443]
It was removed in c986e895bbe856ffafd6999cc1d4418330e47f86, without any ceremony or (linked) discussion. Is there somewhere this was discussed so I can at least see *why* this was removed? IMO, the other options aren't nearly as nice: `Block` ends up with oddball indentation that editors don't help with and `Visual` moves things right way too fast.

In general, finding out why things changed from the git history isn't easy since there aren't even PRs referenced and commit messages tend to be…terse.

Cc: @nrc

**Comment by nrc** [comment]
Sorry, about that, it was part of streamlining the options available. We do need to change the options and unfortunately I have no idea about if they are actually being used or by how many people. Starting from v0.9 I intend to track changes like this and report them in release notes from 0.9.1 onwards. That should improve visibility.

`fn_args_layout = "Block"` should give you similar (hopefully, better, more reliable formatting). Do you have an example of the oddball indentation you see?

**Comment by mathstuf** [comment]
On mobile, so no example right now, but I see that an if block in an Ok call gets three space indent on the closing curly braces and 4 for the inner blocks. It used to be 4 for the inners and the closing braces lined up with the Ok indentation.

**Comment by nrc** [comment]
If it is the actual argument formatting which is causing issues, then you need `fn_call_style = "Block"` too. It might just be a bug formatting an `if` inside a call, in which case I'll try to fix it soon.
