### ISSUE TITLE
Wrong indentation with match for struct field

### ISSUE THREAD

**Issue by leoschwarz** [rust-lang-nursery/rustfmt#1456]
I use rustfmt to keep my code tidy and found [this error](https://github.com/leoschwarz/musicbrainz_rust/blob/c002de6596701379582d8c40f1da12e4eba895cd/src/entities/recording.rs#L36-L48).

~~Here's a [full minimal failing example](https://gist.github.com/leoschwarz/a36a8f9e534257e7d7fb630b80f62823) contrasted with a non-failing example.~~

I'm not sure if this is a duplicate of #1371 ?

rustfmt 0.8.3 / b4833a8

**Comment by leoschwarz** [comment]
Ok I just saw #1454 and my minimal example is fixed by it, but my actual code is not it ends up looking [like this](https://github.com/leoschwarz/musicbrainz_rust/blob/5a2a80802f1aeef2629a9ee204c61afa6e97c7ed/src/entities/recording.rs#L36-L48). (Which is a bit better than before but still wrong.)

**Comment by topecongiro** [comment]
@leoschwarz Hi, I added a commit to the PR to fix this issue. I appreciate if you could confirm that nothing is going wrong with your code. Thanks!

**Comment by leoschwarz** [comment]
@topecongiro Thanks, your new commit fixes all issues for me.
