### ISSUE TITLE
excessive indentation in a spawned thread closure

### ISSUE THREAD

**Issue by oconnor663** [rust-lang-nursery/rustfmt#1458]
Here's an example from a project of mine: https://github.com/oconnor663/duct.rs/blob/0.8.1/src/lib.rs#L1192-L1194

```rust

        let background_waiter = std::thread::spawn(move || {
                                                       Ok(clone.wait(WaitMode::Blocking)?.expect("blocking wait can't return None"))
                                                   });
```

This result also causes `cargo fmt` to print an error: `line exceeded maximum length (maximum: 100, found: 132) (sorry)`. If I was doing this by hand I'd prefer:

```rust
        let background_waiter = std::thread::spawn(move || {
            Ok(clone.wait(WaitMode::Blocking)?.expect("blocking wait can't return None"))
        });
```

**Comment by arthurprs** [comment]
It's expected (not sure why though), you can add  `closure_block_indent_threshold=1` to your rustfmt.toml to force block ident.

**Comment by nrc** [comment]
THis is expected and should be fixed if you use the RFC formatting style.
