### ISSUE TITLE
fn_call_style: middle ground between Visual and Block

### ISSUE THREAD

**Issue by commonquail** [rust-lang-nursery/rustfmt#1465]
```sh
$ rustfmt --version
0.8.3 ()
```

I am aware of the discussions surrounding *visual* versus *block* alignment for chaining, as well as certain limitations in rustfmt's internal indentation handling. I identify far more with *block* alignment but I think both miss the mark. I created a separate ticket because the existing ones are primarily "either/or" and don't seem to address "neither", but feel free to close with a reference to an explanation for why this case is impossible. #1387 does say that "this is by design", but only because *visual* and *block* have strict contextual meanings without acknowledging a third option.

Here is a block of code formatted with `fn_call_style = "Visual"`:

```rust
        let result = run(Config {
                             input: "index.html".into(),
                             output: &mut buf,
                         });
```

Here is the result of switching to *block*:

```diff
-        let result = run(Config {⏎
-                             input: "index.html".into(),⏎
-                             output: &mut buf,⏎
-                         });⏎
+        let result = run(⏎
+            Config {⏎
+                input: "index.html".into(),⏎
+                output: &mut buf,⏎
+            },⏎
+        );⏎
 ```

In the *visual* case the arguments for rightward drift and text editor indentation apply: any length-change in the `let` line spills across the entire rest of the block. The *block* case has neither of those problems but instead consumes two extra lines and introduces an unwanted trailing comma because of `trailing_comma = "Vertical"` which otherwise behaves how I want (in particular, the trailing comma after `buf`).

Here is what I wanted this block to look like (one additional level of *continuation indentation* would be acceptable, perhaps even ideal for VCS churn):

```rust
        let result = run(Config {
            input: "index.html".into(),
            output: &mut buf,
        });
```

But perhaps more importantly, and just to make things difficult, were I to decide later on to manually apply the current *block* style -- with or without trailing comma after `}` -- to this block (e.g. if the `let` line became too long), I would not want that to be changed.

Complementary *neither*-to-*visual*, *neither*-to-*block*, and *deep-neither*-to-*block* diffs:

```diff
         let result = run(Config {⏎
-                input: "index.html".into(),⏎
-                output: &mut buf,⏎
-        });⏎
+                             input: "index.html".into(),⏎
+                             output: &mut buf,⏎
+                         });⏎
```

```diff
-        let result = run(Config {⏎
-            input: "index.html".into(),⏎
-            output: &mut buf,⏎
-        });⏎
+        let result = run(⏎
+            Config {⏎
+                input: "index.html".into(),⏎
+                output: &mut buf,⏎
+            },⏎
+        );⏎
```

```diff
-        let result = run(Config {⏎
+        let result = run(⏎
+            Config {⏎
                 input: "index.html".into(),⏎
                 output: &mut buf,⏎
-        });⏎
+            },⏎
+        );⏎
```

**Comment by nrc** [comment]
This should be discussed over on the fmt-rfcs repo: https://github.com/rust-lang-nursery/fmt-rfcs/issues/65
