### ISSUE TITLE
Inconsistent indentation with closure using a single while loop

### ISSUE THREAD

**Issue by Mange** [rust-lang-nursery/rustfmt#1467]
Running `rustfmt` on code with some combinations of closures, `while` loops, and `match` expressions result in incorrect indentations. I've managed to close it down to a pretty small sample that reproduces the problem.

[EDIT]: Updated after the fact with code that will compile.

**Example: Before rustfmt**

```rust
fn maybe_bool() -> Option<bool> {
    Some(true)
}

fn example() {
    thread::spawn(move || {
        while true {
            let optional = maybe_bool();
            match optional {
                Some(bool) => {
                    println!("Hello world!");
                }
                None => {
                    println!("Good bye world!");
                }
            }
        }
    })
}
```

**Example: After rustfmt**

```rust
fn maybe_bool() -> Option<bool> {
    Some(true)
}

fn example() {
    thread::spawn(move || while true {
                      let optional = maybe_bool();
                      match optional {
                          Some(bool) => {
            println!("Hello world!");
        }
                          None => {
            println!("Good bye world!");
        }
                      }
                  })
}
```

**Note:**
* The `{ ... }` around the closure body is removed and it's folded up as a single expression. (Perfectly valid, but a bit unexpected in this case)
* The `match` line is in a weird indentation level: not matching either original, `thread::spawn` + 1, `thread::spawn(` parenthesis, or the `while` body's indentation level.
* The match bodies are indented in a completely different level: before expression and even before the `match` itself.
* As soon as the closure has more than one expression / statement, the problem goes away.
* **[EDIT:]** Adding a semicolon after the closing brace of the `while` indents everything as expected, but it also removes the semi-colon so the next run will restore the problem again.

I know the code makes little sense. I extracted this from something larger are more complex (where the issue makes this very bad).

---

`rustfmt --version`: `0.8.1 ()`
`rustc --version`: `rustc 1.16.0 (30cf806ef 2017-03-10)`

---

Is there anything else I can assist with? I'd love to help the community grow! Thank you for all your hard work! It's very appreciated! :heart:

**Comment by Mange** [comment]
My current workaround is to add a comment inside the closure that links back to this issue after describing why it's there.

So there's a workaround if anyone else hits this. :-)

**Comment by nrc** [comment]
I can't reproduce this on master right now, formatting gives me:

```
fn example() {
    thread::spawn(
        move || while true {
            let optional = maybe_bool();
            match optional {
                Some(bool) => {
                    println!("Hello world!");
                }
                None => {
                    println!("Good bye world!");
                }
            }
        },
    )
}
```

**Comment by Mange** [comment]
Still happening on `rustfmt 0.8.3`, but after upgrading to `0.8.4` the output looks a lot better, just like you showed.

That output it pretty fine by me, so I accept this as solved.

Sorry for not getting back to you sooner!
