### ISSUE TITLE
Support 'use *' and 'use ::*' syntax

### ISSUE THREAD

**Issue by joshlf** [rust-lang-nursery/rustfmt#1472]
Rust currently allows `use *` and `use ::*` to indicate using all items in the crate's root module. However, `rustfmt` doesn't recognize this syntax, and its presence in a file will prevent rustfmt from working on the rest of the file:

```
$ echo 'use *' | rustfmt
error: expected identifier, found `*`
 --> stdin:1:5
  |
1 | use *
  |     ^
```

```
$ echo 'use ::*' | rustfmt
error: expected `{`, found `*`
 --> stdin:1:7
  |
1 | use ::*
  |       ^
```

**Comment by nrc** [comment]
This probably needs us to use a more recent version of the parser.
