### ISSUE TITLE
rustfmt undoes field init shorthand with rust 1.17

### ISSUE THREAD

**Issue by burtonageo** [rust-lang-nursery/rustfmt#1476]
When formatting code using the [stable 1.17 release](https://blog.rust-lang.org/2017/04/27/Rust-1.17.html), field shorthand init syntax is re-formatted to use the original syntax, e.g.:

```
Diff in src/geometry.rs at line 321:
     #[inline]⏎
     pub fn new(width: N, height: N) -> Self {⏎
         Size {⏎
-            width,⏎
-            height,⏎
+            width: width,⏎
+            height: height,⏎
         }⏎
     }⏎
 }⏎
```

This option is not configurable in rustfmt.toml either.

(No playground link because the release is too recent)

**Comment by nrc** [comment]
This is fixed on master.
