### ISSUE TITLE
Add newlines after standalone attributes

### ISSUE THREAD

**Issue by whitequark** [rust-lang-nursery/rustfmt#1478]
The quote crate currently outputs the following rather pathological header, which rustfmt leaves nearly verbatim:
```rust
# ! [ doc = "Peripheral access API for TM4C1294NCPDT microcontrollers (generated using svd2rust v0.7.0)" ] # ! [ deny ( missing_docs ) ] # ! [ deny ( warnings ) ] # ! [ feature ( const_fn ) ] # ! [ no_std ]extern crate cortex_m ;
```
The whitespace inside attributes is handled by #984 (but this could provide another testcase), whereas the newline *after* the attribute doesn't seem to be mentioned anywhere.

**Comment by nrc** [comment]
I think we do insert newlines in some cases, Rustfmt is probably tripping up somewhere gives up formatting, thus not inserting the newlines.

**Comment by myfreeweb** [comment]
I'd actually like to have an option to **not** insert newlines into e.g.

```rust
#[cfg(feature = "filesystem")] use fuse::*;
````

**Comment by topecongiro** [comment]
Closing as this is fixed on the current master.
