### ISSUE TITLE
Option to force color output on/off

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/rustfmt#1479]
When running `cargo fmt -- --write-mode diff | less -R` to get an overview of changes the colorization of the diff is disabled (presumably through terminal/pipe detection). It would be useful to have a `--color=always|never|auto` flag to be able to force colored output on or off for situations like this, while retaining the output detection by default.

**Comment by clippered** [comment]
Hi, can I give this a crack? Thanks.

**Comment by nrc** [comment]
@clippered yes, please do! I'm not actually sure how to tackle this because I'm not familiar with terminal code. I would start by looking in https://github.com/rust-lang-nursery/rustfmt/blob/master/src/rustfmt_diff.rs

**Comment by clippered** [comment]
Thanks @nrc ! Same with me, but I'll try to understand the terminal code, and practice Rust as well. I'll let you know if I hit some bumps.
