### ISSUE TITLE
`where_indent` appears to be ignored completely by rustfmt

### ISSUE THREAD

**Issue by regexident** [rust-lang-nursery/rustfmt#1484]
Running `$ cargo fmt` on [rust-lang/rust/src/librustc/](https://github.com/rust-lang/rust/tree/master/src/librustc/) with:

```toml
where_indent = "Block"
```

followed by another run with:

```toml
where_indent = "Block"
```

resulted in no code changes at all. This got me suspicious and I checked the code:

Turns out rustfmt appears to never actually read from `config.where_indent`.

**Comment by nrc** [comment]
Fixed

**Comment by regexident** [comment]
Cool, I've fixed PRs https://github.com/rust-lang-nursery/rustfmt/pull/1482 and https://github.com/rust-lang-nursery/rustfmt/pull/1474 accordingly.
