### ISSUE TITLE
`where_density = "Vertical"` behaves like `where_density = "Tall"`

### ISSUE THREAD

**Issue by regexident** [rust-lang-nursery/rustfmt#1485]
There doesn't seem to be a difference between:

```toml
where_density = "Tall"
```
and:

```toml
where_density = "Vertical"
```

Looking at the code the latter doesn't even appear to be taken into account for `where_density` at all (only for `fn_args_density`).

**Comment by nrc** [comment]
1.0 as part of the options audit.

**Comment by mathstuf** [comment]
See also #2133.

**Comment by nrc** [comment]
Removed the option
