### ISSUE TITLE
Put tests for config options in their own subdirectory

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1492]
Apparently we need to make subdirectory tests work first.

CC https://github.com/rust-lang-nursery/rustfmt/pull/1482

**Comment by davidalber** [comment]
We now have the infrastructure in place to do this. Does anyone have strong feelings about how to organize the config option tests? Here's what I was thinking: every test in tests/[source|target]/configs-* gets moved into a configs/CONFIG-NAME subdirectory. Take these tests, for example:
- configs-comment_width-above.rs
- configs-comment_width-below.rs
- configs-comment_width-ignore.rs
- configs-condense_wildcard_suffices-false.rs
- configs-condense_wildcard_suffices-true.rs

These will be moved as follows:
- configs/comment_width/above.rs
- configs/comment_width/below.rs
- configs/comment_width/ignore.rs
- configs/condense_wildcard_suffixes/false.rs (note I did suffices --> suffixes here to match the config name)
- configs/condense_wildcard_suffixes/true.rs  (note I did suffices --> suffixes here to match the config name)

If we wanted to get fancy we could have a test to ensure only real config names are subdirectories in the configs directory. Maybe that should be a different issue, though.

**Comment by nrc** [comment]
that organisation sounds good to me!
