### ISSUE TITLE
indent_match_arms unnecessary?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang-nursery/rustfmt#1498]
Is indent_match_arms necessary? Who wants to format a match in that flat way?

**Comment by regexident** [comment]
It's the default format for Swift, but I'd argue it's rather "interesting".

**Comment by C4K3** [comment]
I personally like the style, you can read the commit (abca1dededc504eeff7fb31fb2f92e54c7ddae0e) for my reasoning.

**Comment by nrc** [comment]
I think we'll leave it there for now, it does not (afaik) complicate anything too much internally. At some point there will be an audit of options and we might remove or merge them, but till then I think it is ok to keep it.
