### ISSUE TITLE
Set the exit code

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#150]
Return an error code if there are tidy errors or Rustfmt failed to format something, OK otherwise.

I think this is easy, not 100% sure of that.

**Comment by matklad** [comment]
Both `cargo-fmt` and `rustfmt` should return non-zero status if an error happens. I will try to implement this, it's rather important for IDE integration.

**Comment by matklad** [comment]
Hm, what exactly are the error conditions which should lead to non-zero exit status? 

I've managed to identify three kinds:

* IO error during [writting](https://github.com/rust-lang-nursery/rustfmt/blob/5b11d2e80f33e3355c42eaeffa4c49fe2014a5f7/src/lib.rs#L438).

* Errors during parsing. For this, I should check `parse_sess.handler.has_errors()` [here](https://github.com/rust-lang-nursery/rustfmt/blob/5b11d2e80f33e3355c42eaeffa4c49fe2014a5f7/src/lib.rs#L417).

* Non-empty [FormatReport](https://github.com/rust-lang-nursery/rustfmt/blob/5b11d2e80f33e3355c42eaeffa4c49fe2014a5f7/src/lib.rs#L236).

**Comment by nrc** [comment]
I think that covers it. The only other class of error is where there is code we can't format and we use the original code. However, that is not tracked, and I don't think that should be an error that is exposed to the user.
