### ISSUE TITLE
fn_args_layout not applied to functions with 1 argument

### ISSUE THREAD

**Issue by Susurrus** [rust-lang-nursery/rustfmt#1508]
Works properly on all other functions, but setting `rustfmt.toml`to:
```
fn_args_layout = "Block"
fn_call_width = 0
```

Results in functions of a single argument still being formatted onto a single line.

cc @retep998

**Comment by topecongiro** [comment]
@nrc Should `fn_call_width` restrict the length of parameters?

**Comment by nrc** [comment]
`fn_call_width` restricts the number of chars we allow on one line within the `()` of a function call. So, if set to 0, then all function calls should be multi-line, e.g,

```
some_function(
    x,
)
```

I don't actually mind if this only works for two or more arguments, or one argument, or even 0 arguments.

**Comment by Susurrus** [comment]
As a user, I was surprised at this behavior. I'd expect it to apply to all function parameters, **especially** since in the docs it isn't specified to only work on > 1 parameter function calls.
