### ISSUE TITLE
Move off Syntex

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1527]
And use libsyntax directly. This means we stop working on stable Rust. However, we can address this by distributing via Rustup instead of Cargo (#1526).

**Comment by nrc** [comment]
I have a branch that uses libsyntax, not sure if to land or not. Would mean the end of stable rustfmt in the short term.

**Comment by nrc** [comment]
There are a few test failures due to #1541 and #1542, otherwise seems to be working. Branch is https://github.com/rust-lang-nursery/rustfmt/tree/libsyntax

**Comment by nrc** [comment]
If we don't merge going to have to keep rebasing that branch :-(

**Comment by nrc** [comment]
Awesome, please PR it! I think we should leave the MacroDef issue open and the FIXME in place - we should at some point fix that properly.

**Comment by topecongiro** [comment]
Thanks! I will create a PR shortly.

**Comment by topecongiro** [comment]
Should I create a PR against master branch?

**Comment by nrc** [comment]
> Should I create a PR against master branch?

No, against libsyntax branch

**Comment by topecongiro** [comment]
Thanks!

**Comment by sanmai-NL** [comment]
@nrc: ten days ago you published [this blog announcing the transition to `libsyntax`](http://www.ncameron.org/blog/rustfmt-changes/). Your blog has been spread further in the [This Week in Rust newsletter](https://this-week-in-rust.org/). 

After some careful experimentation and review, which cost me an hour or so, my conclusion is this:
* The new `rustfmt-nightly` crate cannot be installed yet, at least not with Cargo using a conventional invocation.
* No guidance in the `README` of the default branch of this repo (nor on the `libsyntax` branch, for that matter) on how to actually install/use the `libsyntax` branch, or what the transition path is (when will it be merged into the default branch, etc.).
* Lots of open issues that relate to this, with the promises/suggestions about the pending transition.

I personally can imagine some technical tricks get started, but the transition should be documented.

I hope you understand this can appear a bit disorganized and disappointing in general. You probably tried to avoid this impression. Can you please elucidate the current status? Do you recognize the issues I point out or not? Thanks for your efforts anyway.

**Comment by nrc** [comment]
@sanmai-NL the transition hasn't happened yet. I'll start today and it should be well-documented by the time I'm done.

**Comment by sanmai-NL** [comment]
@nrc: Thanks for your effort! The time planning was unclear to me from the announcement.
