### ISSUE TITLE
rustfmt is running slow with long binop

### ISSUE THREAD

**Issue by yjh0502** [rust-lang-nursery/rustfmt#1531]
Here's a problematic case:

https://play.rust-lang.org/?gist=e6abea7fe0b9ebaaade53f6b585cd786&version=stable

You can reproduce the issue by clicking `format` button. The issue could be reproduced locally with rustfmt `0.8.3`.

**Comment by nrc** [comment]
Test case is very deeply nested (415 elements) binop, `let v = (-1 - 2 - 3 - ...)`. This seems a bit pathological, but it would be nice to fix if possible. I suspect we're hitting some O(n^2) behaviour of something.

**Comment by topecongiro** [comment]
Fixed on `0.2.16-nightly`, closing.
