### ISSUE TITLE
Support --all flag

### ISSUE THREAD

**Issue by BusyJay** [rust-lang-nursery/rustfmt#1532]
It will be nice if cargo fmt --all will format all the projects in workspace just like cargo test -all will run all the tests in workspace.

**Comment by jtojnar** [comment]
Duplicate of #1244, which was already fixed.

**Comment by BusyJay** [comment]
Yes.

**Comment by bjadamson** [comment]
I can't get this to work, running cargo fmt --all I get the following:

> cargo fmt --all
>
> Unrecognized option: 'all'.
> usage: cargo fmt [options]
> 
> Options:
>     -h, --help          show this message
>     -q, --quiet         no output printed to stdout
>     -v, --verbose       use verbose output
> 
> This utility formats all bin and lib files of the current crate using rustfmt. Arguments after `--` are passed to rustfmt.

Maybe I'm perhaps using it wrong? I'm trying to run this from within the root directory of a cargo virtual workspace.
Here's the link to my Cargo.toml I'm working with, if that's useful:
https://github.com/bjadamson/gfx/blob/mod-support/Cargo.toml

**Comment by emilio** [comment]
You probably want `cargo fmt -- --all`, I think.

**Comment by bjadamson** [comment]
Thank you @emilio  I will give that a shot. Color me super surprised that's the syntax the cargo fmt team went with for this...

**Comment by nrc** [comment]
> I'm sure there's a good reason

I think it is because of Cargo, rather than rustfmt - arguments before the `--` are passed to Cargo, arguments after the `--` are passed to the plugin.

**Comment by BusyJay** [comment]
Are you using the latest version of rustfmt? I can run `cargo fmt --all` directly.

**Comment by bjadamson** [comment]
You get the latest version by just running "rustup update" right?
