### ISSUE TITLE
Using rustfmt programmatically

### ISSUE THREAD

**Issue by kardeiz** [rust-lang-nursery/rustfmt#1534]
Unless I am missing something, there isn't a super nice way to use `rustfmt` programmatically&mdash;

For example, I have a project where I am generating some repetitive Rust code with `syn` and `quote` in `build.rs`. The output is missing newlines, etc., so it is desirable to run the code through `rustfmt`.

Currently I am writing the generated string to a file and then using `rustfmt::format_input` to format and overwrite that file. This works, and is really not so bad, I was mostly just surprised to find that there was no function like `fn(config: Config, input: &str) -> String`.

Is there some reason not to support this simple case? Or am I missing something?

**Comment by nrc** [comment]
You should be able to pass `format_input` an `Input::Text(String)`, but it looks like this does not quite work since it relies on stdin.

There are a few technical problems here, but I have to fix them for IDE support too, so hopefully we'll have something soon.

**Comment by kardeiz** [comment]
Right, I tried the `Input::Text(String)` first, but couldn't get it to work. Thanks for the reply!

**Comment by nrc** [comment]
You could look at how the RLS calls Rustfmt as an example of how to do this.

**Comment by aep** [comment]
does it work now? i cant figure out how to get the actual output when using Input::Text(String)

**Comment by nrc** [comment]
@aep it does. Look at the code around https://github.com/rust-lang-nursery/rls/blob/master/src/actions/requests.rs#L769 for an example.

**Comment by SOF3** [comment]
@nrc' link broke. Use a canonical link instead: https://github.com/rust-lang/rls/blob/66c78983717c998c29e876777782d74a1e96e983/src/actions/requests.rs#L769
