### ISSUE TITLE
Fix Appveyor

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1536]

**Comment by ThomasdenH** [comment]
Is this about the Appveyor build of rustfmt failing or about rustfmt not working on Appveyor?

**Comment by nrc** [comment]
The former (I did not realise the latter was a problem)

**Comment by ThomasdenH** [comment]
Thanks for the clarification. I just noticed my [Appveyor build failing](https://ci.appveyor.com/project/ThomasdenH/iban-validate/build/1.0.18/job/qjhas4tgobf3eri0) for some reason while Travis works and I thought this might be the cause, but it's probably something else then.

**Comment by topecongiro** [comment]
Appveyor is using old version of rustc (1.16 for statble) and complains about elided `'static`, which is only allowed after 1.17~.
