### ISSUE TITLE
Cleanup new lines

### ISSUE THREAD

**Issue by rushmorem** [rust-lang-nursery/rustfmt#1545]
Currently `rustfmt` doesn't seem to try to format new lines at all. For example, where a blank line is necessary there should only be one such line. If there are more than one then they should be collapsed. Where blank lines aren't necessary (e.g. between `use` statements) they should be removed.

For example:-

```rust
fn run() -> Result<()> {
    // ...
}



fn main() {
    run().unwrap();
}
```

should be

```rust
fn run() -> Result<()> {
    // ...
}

fn main() {
    run().unwrap();
}
```

**Comment by euclio** [comment]
See #983.

**Comment by rushmorem** [comment]
Thanks. Closing this duplicate...
