### ISSUE TITLE
Trailing comma added to method arguments

### ISSUE THREAD

**Issue by Razican** [rust-lang-nursery/rustfmt#1548]
This code:
```rust
App::new("SUPER Android Analyzer")
    .arg(Arg::with_name("verbose")
             .short("v")
             .long("verbose")
             .conflicts_with("quiet")
             .help("If you'd like the auditor to talk more than necessary"))
    .arg(Arg::with_name("force")
             .long("force")
             .help("If you'd like to force the auditor to do everything from the beginning"));
```

Gets formatted to this:
```rust
App::new("SUPER Android Analyzer")
    .arg(Arg::with_name("verbose")
             .short("v")
             .long("verbose")
             .conflicts_with("quiet")
             .help("If you'd like the auditor to talk more than necessary"))
    .arg(Arg::with_name("force")
             .long("force")
             .help("If you'd like to force the auditor to do everything from the beginning",));
```

Note the comma at the end of the second argument. Don't even understand why it compiles. The thing is it only adds it to the second one, and not to the first one (in `.help`). Also, in the complete example I have a bunch of arguments before and after these two, so seems it's not because it's the last one.

**Comment by Razican** [comment]
The thing is that the line is 93 characters long, including indenting, and the max_width is 100, right? I can confirm in any case that it's resolved in master.

**Comment by topecongiro** [comment]
You are right. I am not sure why, rustfmt is sometimes over-conservative though.
Thank you for pointing out!

**Comment by nrc** [comment]
Rustfmt has a limit on the length of the args between the `()`, you might be hitting that.
