### ISSUE TITLE
[regression] method call that fits within width limit gets split on new line

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#1579]
Input:
```rust
fn main() {
    while cond {
        if cond {
            match var {
                "foo" => {
                    match opt {
                        None => writeln!(&mut reply, "this is a message. yes.....").unwrap(),
                    }
                }
                "bar" => {
                    match opt {
                        None => writeln!(&mut reply, "this is another message. yep").unwrap(),
                    }
                }
            }
        }
    }
}

```

Output:
```rust
fn main() {
    while cond {
        if cond {
            match var {
                "foo" => {
                    match opt {
                        None => writeln!(&mut reply, "this is a message. yes.....").unwrap(),
                    }
                }
                "bar" => {
                    match opt {
                        None => {
                            writeln!(&mut reply, "this is another message. yep")
                                .unwrap()
                        }
                    }
                }
            }
        }
    }
}

```

rustfmt 0.8.4 (93c556c)

**Comment by crumblingstatue** [comment]
Here is another case:

Input:
```Rust
fn main() {
    match get_user_choice_from_menu(client_id.is_some(), &viewers).unwrap() {
		Foo => bar(),
    }
}

```

Output:
```rust
fn main() {
    match get_user_choice_from_menu(client_id.is_some(), &viewers)
              .unwrap() {
        Foo => bar(),
    }
}

```

**Comment by crumblingstatue** [comment]
Note that this is a regression, these code samples are all lifted from projects formatted with a previous version of rustfmt.

**Comment by topecongiro** [comment]
I think this is because these chains exceed `chain_one_line_max`.

**Comment by crumblingstatue** [comment]
> I think this is because these chains exceed `chain_one_line_max`.

You are right, that does seem to be the case.

Is `chain_one_line_max` really intended to be only 60 by default though? Was it decided by an RFC or something? I feel like the above changes only make the code less readable. And rustfmt only started formatting like this recently. Is it due to a bugfix that it now started respecting `chain_one_line_max`?

**Comment by topecongiro** [comment]
Until recently rustfmt did not split chain with a single child unless it exceeds `max_width`.
Now rustfmt does when the chain exceeds `chain_one_line_max` and the parent (or the first element of the chain) is 'large'.
Maybe it should be configurable whether to split chain with a single child.

I do not know how the value 60 was decided.

**Comment by nrc** [comment]
> Maybe it should be configurable whether to split chain with a single child.

I think I agree? The intention is to catch things like `foo.bar.baz(an_arg).qux(another_arg, and_another_arg)` which can look pretty bad when stretched to >60 chars. However, I agree that examples like this look better without splitting.
