### ISSUE TITLE
control_style does not have a visual guide in Configurations.md

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#1605]
I think we should include it since it is used in `rfc-rustfmt.toml`.

**Comment by theotherphil** [comment]
I've accidentally duplicated this issue here https://github.com/rust-lang-nursery/rustfmt/issues/1722 and am fixing it here https://github.com/rust-lang-nursery/rustfmt/pull/1709

**Comment by topecongiro** [comment]
Thanks, I will close this issue in favor of #1722.
