### ISSUE TITLE
Match arm variables are broken onto multiple lines, even when not necessary

### ISSUE THREAD

**Issue by YorickPeterse** [rust-lang-nursery/rustfmt#1611]
Sorry if this is already reported else where or fixed, but I had a hard time finding an issue that matched the behaviour described here.

This code:

```rust
impl Bla {
    fn bla(&self) {
        match something {
            &Some::Variant { value, line, column } => {
                self.some_function()
            }
        }
    }
}
```

Gets formatted into this:

```rust
impl Bla {
    fn bla(&self) {
        match something {
            &Some::Variant {
                value,
                line,
                column,
            } => self.some_function(),
        }
    }
}
```

The same happens with this:

```rust
fn foo() {
    match something {
        &Some::Variant { value, line, column } => self.some_function(),
    }
}
```

which becomes:

```rust
fn foo() {
    match something {
        &Some::Variant {
            value,
            line,
            column,
        } => self.some_function(),
    }
}
```

Again here it all fits fine, but rustfmt for whatever reason decides to break the variables across multiple lines.

**Comment by topecongiro** [comment]
You could set `struct_lit_width` to larger value to put struct literal in a single line.
With `struct_lit_width = 30`, we get
```rust
fn foo() {
    match something {
        &Some::Variant { value, line, column } => self.some_function(),
    }
}
```

**Comment by YorickPeterse** [comment]
Aha, this seems to work nicely. Thanks!

**Comment by pickfire** [comment]
Shouldn't this be the default? Should I open an issue for this. I just noticed this behavior and it seemed weird, it would be best to allow a large value here I guess?
