### ISSUE TITLE
rustfmt doesn't work on Windows anymore

### ISSUE THREAD

**Issue by CryZe** [rust-lang-nursery/rustfmt#1612]
I'm not entirely sure what happened, but I just updated rustfmt and now it doesn't work anymore. It spits out a weird error message about it not being able to write to the terminal or something:

```
$ RUST_BACKTRACE=1 cargo fmt
thread 'main' panicked at 'failed to emit error: operation not supported by the terminal', C:\Users\Christopher\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_errors-0.58.1\src\emitter.rs:1043
stack backtrace:
   0: std::sys_common::backtrace::_print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: <syntex_errors::emitter::EmitterWriter as syntex_errors::emitter::Emitter>::emit
   7: syntex_errors::diagnostic_builder::DiagnosticBuilder::emit
   8: rustfmt::format_input
   9: rustfmt::run
  10: rustfmt::execute
  11: rustfmt::main
  12: _rust_maybe_catch_panic
  13: std::rt::lang_start
  14: _tmainCRTStartup
  15: mainCRTStartup
  16: unit_addrs_search
```

The version in use is 0.8.4

**Comment by CryZe** [comment]
This is extremely weird: ![http://puu.sh/w61sh.png](http://puu.sh/w61sh.png)

**Comment by nrc** [comment]
Could you try using the libsyntax branch? I fear Syntex has stopped working on Windows.

**Comment by CryZe** [comment]
I'm not entirely sure how syntex should've stopped working. rustfmt 0.8.3 works just fine (just tested it again) and 0.8.4 doesn't. Both of these versions use the same version of syntex, so that can't really be it.

**Comment by CryZe** [comment]
Okay, so I git bisected it and this is the commit that broke rustfmt: https://github.com/rust-lang-nursery/rustfmt/pull/1446

**Comment by CryZe** [comment]
Seems like syntex can't handle Windows' canonicalized paths.

**Comment by CryZe** [comment]
Seems like some other people are getting hit by this bug now (over in the VSCode Rust plugin repo). Can we maybe gate the canonicalization to not happen on Windows and release a 0.8.5?

**Comment by nrc** [comment]
We got an update of Syntex, so this should be fixed on master. Could someone on Windows test please?

**Comment by ricardopieper** [comment]
I don't know if this is related to the problem or not, but I'm having this on Windows 10:

![image](https://user-images.githubusercontent.com/4030858/27011288-e08f07a4-4e8e-11e7-9fb3-82625868447c.png)

this happens when I run cargo install rustfmt.

Those are the packages:

![image](https://user-images.githubusercontent.com/4030858/27011305-247ea3d4-4e8f-11e7-92eb-06f1245f2c57.png)

**Comment by ricardopieper** [comment]
`rustup run nightly cargo install rustfmt` works fine.

I guess I did download some nightly stuff for Rust, but as far as I know, I'm running the stable version.

**Comment by CryZe** [comment]
@ricardopieper Your stable version is outdated. static_in_const is stable.

@nrc I just built master and seems to work fine on Windows 😄

**Comment by ricardopieper** [comment]
Oh, yeah... it's definitely outdated.

I'm new to Rust, I did download it in February, and I thought downloading rustup again from the website would update everything.

Seems like I was running 1.15. `rustup update` updated it to 1.18.

**Comment by nrc** [comment]
Thanks @CryZe ! I'll make a release later today.
