### ISSUE TITLE
long function name and return type push opening bracket onto new line for fn block style

### ISSUE THREAD

**Issue by tspiteri** [rust-lang-nursery/rustfmt#1624]
Without block style, a function with a long name and long return type will push the opening bracket to a new line like this:
```
pub unsafe fn some_long_function_name
    (arg1: Type1,
     arg2: Type2)
     -> (SomeLongTypeName, AnotherLongTypeName, AnotherLongTypeName) {
}
```
If this function is formatted with block style, it becomes:
```
pub unsafe fn some_long_function_name
    (
    arg1: Type1,
    arg2: Type2,
) -> (SomeLongTypeName, AnotherLongTypeName, AnotherLongTypeName) {
}
```

**Comment by topecongiro** [comment]
Could you try `fn_args_paren_newline = false`?

**Comment by tspiteri** [comment]
With `fn_args_paren_newline = false`, rustfmt produces this:
```
pub unsafe fn some_long_function_name(
    
    arg1: Type1,
    arg2: Type2,
) -> (SomeLongTypeName, AnotherLongTypeName, AnotherLongTypeName) {
}
```
and fails with `left behind trailing whitespace`.

**Comment by topecongiro** [comment]
Thanks! That is definitely a bug...

**Comment by topecongiro** [comment]
Closing since this is fixed on the current master.
