### ISSUE TITLE
Don't insert line breaks in macro invokations

### ISSUE THREAD

**Issue by torkleyy** [rust-lang-nursery/rustfmt#1625]
My macro

```rust
impl_data!(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z);
```

get's split up so that every letter is on its own line which is very annoying. I'm not sure why it formats the line because it doesn't exceed the maximum length.

**Comment by topecongiro** [comment]
The macro is hitting `fn_call_width` which is 60 by default. You could set it to a larger value to avoid getting split up.

**Comment by torkleyy** [comment]
Maybe `rustfmt` could have a separate setting for macro calls which is higher by default?

**Comment by topecongiro** [comment]
Maybe at some point. For now, please try `#[cfg_attr(rustfmt, rustfmt_skip)]`. rustfmt should leave the expression as is.
