### ISSUE TITLE
rustfmt writes to files even if they weren't changed

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#1632]
This means that if you for example run `cargo fmt`, it will write to all files in the project, meaning `cargo build` will have to recompile your project, even though nothing changed.

I'm not sure what effects this has on incremental compilation. Does it matter what files were changed, or does it work on the semantic data?

**Comment by est31** [comment]
AFAIK incremental compilation bases on hashing, so there should be no effect on that front. However, incr comp will be turned off by default on release builds, so it does have an effect here.
