### ISSUE TITLE
Add `fn_return_indent = "Double"`

### ISSUE THREAD

**Issue by torkleyy** [rust-lang-nursery/rustfmt#1641]
If the return type has to be on a new line, I find it hard to read because the code has the same indention. Therefore, I'd like to have just a double indention in case it's on a new line. I cannot use

```rust
fn_return_indent = "WithArgs"
```

because my args are in `"Block"`-style.

**Comment by nrc** [comment]
For the RFC style we use block formatting and if there is return type we do not indent it at all so that it stands out. E.g.,

```
fn extract_one(
    &mut self,
    m: FxHashMap<PathBuf, PathKind>,
    flavor: CrateFlavor,
    slot: &mut Option<(Svh, MetadataBlob)>,
) -> Option<(PathBuf, PathKind)> {
    ...
}
```
