### ISSUE TITLE
Iterator transformations used in control statement

### ISSUE THREAD

**Issue by 0x7CFE** [rust-lang-nursery/rustfmt#1653]
So, it's either question or suggestion depending on whether such setting exist.

I have a following code:
```Rust
if let Some(mineral) = self.game
    .minerals()
    .min_by_key(|m| unit.distance_to(m)) 
{
    unit.right_click(&mineral, false);
}
```

Depending on the settings rustfmt tries to reformat it like this
```Rust
if let Some(mineral) = self.game.minerals().min_by_key(
    |m| unit.distance_to(m)),
{
    unit.right_click(&mineral, false);
}
```
…or even like this:
```Rust
if let Some(mineral) = self.game
        .minerals()
        .min_by_key(|m| unit.distance_to(m)) {
    unit.right_click(&mineral, false);
}
```

I believe that original formatting puts more emphasis on the purpose of the whole code chunk. Could it be possible to detect such pattern and format it differently from others?

The pattern may be described as iterator transformations that are directly used in a control statement, like `if let` or `for`.

Another real world example [may be found](https://github.com/0x7CFE/cortex/blob/master/src/sound.rs#L207-L213) in my other project:
```Rust
for (first, second) in reader
    .samples::<i16>()
    .map(|s| Cplx::new(s.unwrap() as f32 / i16::max_value() as f32, 0.0))
    .collect_chunks::<Samples>(NUM_POINTS / 2)
    .map(Arc::new) // Wrap each chunk into Arc for cheap cloning
    .tuple_windows()
{
    // stuff to do
}
```

**Comment by topecongiro** [comment]
Currently rustfmt does not go deep to detect specific patterns from source code.
However, the above examples should be fixed on the current master.

**Comment by nrc** [comment]
Assuming this is fixed on nightly. Closing (please comment if not and I'll re-open).
