### ISSUE TITLE
Parse error with rustfmt 0.8.5 and multiple macro invocations containing "unsafe" keyword

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/rustfmt#1660]
Running `rustfmt src/lib.rs` on this repo: https://github.com/sfackler/rustfmt-error

```
error: expected one of `!`, `(`, `::`, `;`, `<`, or `}`, found `.`
 --> /Volumes/git/foo/src/bar/foo/fizz.rs:2:29
  |
2 |     error!(unsafe { error: e.display() });
  |                             ^ expected one of `!`, `(`, `::`, `;`, `<`, or `}` here
```

**Comment by nrc** [comment]
My guess is the `unsafe` is causing problems when we are parsing macros out of context. The fact that this requires multiple macros suggests it is also something wrong with our state handling. Perhaps tied to the error count setting?

cc @topecongiro (who has been working on some PRs which changed the parser state) - do you have a guess what might be happening here?

**Comment by topecongiro** [comment]
#1646 creates a new `span_diagnostic` using `Handler::with_tty_emitter`, but actually we should have used `Handler::with_emitter`.
