### ISSUE TITLE
Multi-line str literals not formatting correctly.

### ISSUE THREAD

**Issue by cedenday** [rust-lang-nursery/rustfmt#1661]
See https://github.com/cedenday/rshare/blob/acf3c3df98b05a5396012a749c85e42c6bc00833/src/main.rs#L268-L274.

**Comment by nrc** [comment]
Have you set the `format_strings` or `force_format_strings` options?

**Comment by cedenday** [comment]
No, but it did format the first line as seen here: https://github.com/cedenday/rshare/blob/acf3c3df98b05a5396012a749c85e42c6bc00833/src/main.rs#L269.

**Comment by nrc** [comment]
We will move strings even if those options are not selected (and I don't recommend using them). I think here we should also change the indent so the start of the string lines are aligned, but I'm not actually sure if we even try.
