### ISSUE TITLE
Get tests passing again

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1665]
This is fallout from moving to the RFC style by default. I fixed all tests where there is a difference between source and target. However, there are a few where lines overflow and somehow rewriting lifetimes is causing an addition to overflow.

**Comment by nrc** [comment]
This blocks the 0.9 release (with RFC style).

**Comment by topecongiro** [comment]
I tested a little, and chanding `usize::max_value()` to `context.config.max_width()` and `block_unindent` to use `checked_sub` fixed the overflow/subflow issues.

**Comment by topecongiro** [comment]
General problem seems to be that when using block indent rustfmt tends to lose the width constraints for the last line.
