### ISSUE TITLE
rustfmt-nightly doesn't install cargo-fmt binary

### ISSUE THREAD

**Issue by robinst** [rust-lang-nursery/rustfmt#1670]
Output from cargo install:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rustfmt-nightly v0.1.0
  Installing rustfmt-nightly v0.1.0
 Downloading env_logger v0.4.3
 Downloading strings v0.1.0
 Downloading toml v0.4.1
   Compiling unicode-segmentation v1.2.0
   Compiling num-traits v0.1.39
   Compiling term v0.4.5
   Compiling itoa v0.3.1
   Compiling diff v0.1.10
   Compiling void v1.0.2
   Compiling getopts v0.2.14
   Compiling quote v0.3.15
   Compiling dtoa v0.4.1
   Compiling log v0.3.8
   Compiling serde v1.0.8
   Compiling libc v0.2.23
   Compiling rustfmt-nightly v0.1.0
   Compiling unicode-xid v0.0.4
   Compiling regex-syntax v0.4.1
   Compiling utf8-ranges v1.0.0
   Compiling unreachable v0.1.1
   Compiling strings v0.1.0
   Compiling synom v0.11.3
   Compiling memchr v1.0.1
   Compiling thread-id v3.1.0
   Compiling syn v0.11.11
   Compiling aho-corasick v0.6.3
   Compiling thread_local v0.3.3
   Compiling serde_json v1.0.2
   Compiling toml v0.4.1
   Compiling regex v0.2.2
   Compiling serde_derive_internals v0.15.1
   Compiling serde_derive v1.0.8
   Compiling env_logger v0.4.3
    Finished release [optimized] target(s) in 118.6 secs
  Installing ~/.cargo/bin/rustfmt
```

You can see that the `cargo-fmt` binary wasn't installed.

I think the problem is that there's an explicit `[[bin]]` section now, so all the binaries now need to be listed: https://github.com/rust-lang-nursery/rustfmt/commit/65d1e950a9e03c41ee2c8cd0b6f0f2201ecc0104?diff=unified#diff-80398c5faae3c069e4e6aa2ed11b28c0R17

Quoting crates.io docs:

> Do note, however, once you add a [[bin]] section (see below), Cargo will no longer automatically build files located in src/bin/*.rs. Instead you must create a [[bin]] section for each file you want to build.

**Comment by robinst** [comment]
Did you accidentally push the wrong thing to the `libsyntax` branch? This doesn't look like it has the `rustfmt-nightly` stuff: https://github.com/rust-lang-nursery/rustfmt/blob/libsyntax/Cargo.toml

**Comment by nrc** [comment]
libsyntax branch is an older version we need to keep around. Current versions are master (libsyntax) and syntex (using syntex)

**Comment by robinst** [comment]
Master looks like this: https://github.com/rust-lang-nursery/rustfmt/blob/master/Cargo.toml#L3

I'm confused, shouldn't it read `rustfmt-nightly` there?

**Comment by nrc** [comment]
It should, I forgot to push my local master, fixed now.

**Comment by robinst** [comment]
Ok, looking into raising a PR.

**Comment by robinst** [comment]
Thanks! `cargo +nightly install rustfmt-nightly && cargo fmt` works nicely now!
