### ISSUE TITLE
Use block indent for tuple pattern

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#1676]
Or not?
For example,
```rust
// Visual indent
ast::WherePredicate::EqPredicate(ast::WhereEqPredicate {
    ref lhs_ty,
    ref rhs_ty,
    ..
}) => {
```
```rust
// Block indent
ast::WherePredicate::EqPredicate(
    ast::WhereEqPredicate {
        ref lhs_ty,
        ref rhs_ty,
        ..
    },
) => {
```

**Comment by nrc** [comment]
The first example looks like block indent with combining, the second without combining. I think visual indent would align the `r` or `ref` wit the second `:` of `ast::WhereEqPredicate`.

I think we should use the first example. In general patterns should follow the rules for expressions, and with expressions we would combine

**Comment by topecongiro** [comment]
Thanks for your comment! I agree with the above example.
Just to make sure, in general where there is no combining, we do
```rust
if let (
    some_very_large,
    tuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuple,
) = 1 + 2 + 3
{
}

```
instead of
```rust
if let (some_very_large,
        tuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuple) = 1 + 2 + 3
{
}
```
is this correct? (rustfmt currently does the latter)

**Comment by nrc** [comment]
I would say that this is a block vs visual issue (first example is block indented second is visual indented). We should do the former, but I think the opening brace should be on the same line as `1 + 2 + 3`
