### ISSUE TITLE
rustfmt --version reports nightly even on syntex branch

### ISSUE THREAD

**Issue by kw217** [rust-lang-nursery/rustfmt#1682]
`rustfmt --version` on 0.9.0 reports `0.9.0-nightly ( )`. I think it should report `0.9.0 ( )`, since this is the stable version of rustfmt not the nightly version (at least according to my reading of http://ncameron.org/blog/rustfmt-changes/ ).

Thanks.

**Comment by nrc** [comment]
For some reason we have always reported the `-nightly` part of the version (it is hard-coded in). We should omit it on the Syntex branch.

**Comment by topecongiro** [comment]
Closed via #1699.

**Comment by kw217** [comment]
Super, thanks!
