### ISSUE TITLE
Neatly-aligned multi-line expression folded into a single line

### ISSUE THREAD

**Issue by pornel** [rust-lang-nursery/rustfmt#1684]
I know it's a tough edge case, but rustfmt is not aware of multi-line formatting patterns/regularities in expressions.

I work with image processing and my code is full of expressions repeated for R, G, and B. Laying out such expressions this way:

```rust
let diff = (r as i32 - r2 as i32).pow(2) +
           (g as i32 - g2 as i32).pow(2) +
           (b as i32 - b2 as i32).pow(2);
```

makes it much easier to understand, spot errors, and edit them (with sublime's multiple carets). 

However, rustfmt treats it as just a one long expression, and always unwraps it given a chance:

```rust
let diff = (r as i32 - r2 as i32).pow(2) + (g as i32 - g2 as i32).pow(2) + (b as i32 - b2 as i32).pow(2);
```

Would it be possible to preserve such aligned blocks of code? e.g. if parens and operators are aligned, and/or if there's a small edit distance between the lines.

**Comment by pornel** [comment]
Here's another case of a compact and IMHO very readable matrix notation exploded into multiple unaligned lines:

```rust
let custom_primaries = CIExyYTRIPLE{
    Red:   CIExyY{x:0.630, y:0.340, Y:1.0},
    Green: CIExyY{x:0.310, y:0.595, Y:1.0},
    Blue:  CIExyY{x:0.155, y:0.070, Y:1.0},
};
```
&rarr;
```rust
let custom_primaries = CIExyYTRIPLE {
    Red: CIExyY {
        x: 0.630,
        y: 0.340,
        Y: 1.0,
    },
    Green: CIExyY {
        x: 0.310,
        y: 0.595,
        Y: 1.0,
    },
    Blue: CIExyY {
        x: 0.155,
        y: 0.070,
        Y: 1.0,
    },
};

**Comment by topecongiro** [comment]
Unfortunately rustfmt is not smart enough to do these types of formatting. For now, please try `#[rustfmt_skip]` or `#[cfg_attr(rustfmt, rustfmt_skip)]` (more on README.md).

**Comment by kestred** [comment]
This is one of the the larger pains I have with code formatting tools in most languages, where I otherwise love being able to automatically enforce style consistency.

@topecongiro: Is there an architectural reason that rustfmt can't (or would have a difficult time) supporting this behavior?

Would a pull request implementing it be likely to be accepted? (Any other issues specific to preserving well aligned code?)

**Comment by nrc** [comment]
@kestred we basically can't do this - the architecture of rustfmt is that it rewrites the AST, not the source, and we don't take hints from the source in general. We found that if we do take hints from the source then we end up with non-idempotency.

**Comment by kestred** [comment]
Tangentially, I suspect this closed issue may not be the right place for a slightly more involved discussion ^; happy to move somewhere else if it makes sense (rustfmt RFC? internals forum?)
