### ISSUE TITLE
Align enum values in consecutive lines

### ISSUE THREAD

**Issue by pornel** [rust-lang-nursery/rustfmt#1686]
Related to #1684

```rust
pub enum ColorimetricIntentImageState {
    SceneColorimetryEstimates =              0x73636F65,
    SceneAppearanceEstimates =               0x73617065,
    FocalPlaneColorimetryEstimates =         0x66706365,
    ReflectionHardcopyOriginalColorimetry =  0x72686F63,
    ReflectionPrintOutputColorimetry =       0x72706F63,
}
```

is changed to:

```rust
pub enum ColorimetricIntentImageState {
    SceneColorimetryEstimates = 0x73636F65,
    SceneAppearanceEstimates = 0x73617065,
    FocalPlaneColorimetryEstimates = 0x66706365,
    ReflectionHardcopyOriginalColorimetry = 0x72686F63,
    ReflectionPrintOutputColorimetry = 0x72706F63,
}
```

and IMHO it looks sloppy. I'd prefer all numbers to be in the same column. Of course maintaining such alignment by hand is tedious, so rustfmt would be especially useful in this case.

I also have enums where the values are related (e.g. ranges of consecutive numbers, powers of two, unions of flags), so having the values exactly one under another helps seeing the patterns.

**Comment by nrc** [comment]
This is a dup of https://github.com/rust-lang-nursery/rustfmt/issues/1103 (and I think one or two other issues). It is somewhat complex for Rustfmt to implement and isn't part of the RFC style, so is unlikely to get implemented soon.
