### ISSUE TITLE
Bound split unnecessarily, and issues with function types

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1689]
```
impl<M, S, F, X> SubSelectDirect<M, S, F, X>
where
    M: select::Selector,
    S: event::Stream,
    F: for<'t> FnMut(transform::Api<
        't,
        Stream<ContentStream<S>>,
     >)
                   -> transform::Api<'t, X>,
    X: event::Stream,
{
    ...
}
```

The bound for F looks like it should fit on one line, even if not, we should split function types at the `->` without splitting the args (and in this case there is only a single arg). Finally, the indent for the return type should be block indented, not visually indented.

**Comment by topecongiro** [comment]
Closed via #1717.
