### ISSUE TITLE
Strange line breaks in method chains with 0.9

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/rustfmt#1691]
Here are a couple of diffs we found when upgrading from rustfmt 0.8 to 0.9:

```diff
-        let inserted = self.map
-            .entry(key)
-            .or_insert_with(HashSet::new)
-            .insert(value);
+        let inserted = self.map.entry(key).or_insert_with(HashSet::new).insert(
+            value,
+        );
```

```diff
-        self.cache
-            .open(id, kind.storage_size())
-            .map(|o| o.map(|s| RawTimeSeries::new(kind, s)))
+        self.cache.open(id, kind.storage_size()).map(|o| {
+            o.map(|s| RawTimeSeries::new(kind, s))
+        })
```

```diff
-        self.series
-            .into_points((range.start().cloned(), range.end().cloned()))
+        self.series.into_points(
+            (range.start().cloned(), range.end().cloned()),
+        )
```

The old structure of breaking on each portion of the chain seems more readable than breaking as late as possible - in particular for the second example.

**Comment by nrc** [comment]
This is discussed in https://github.com/rust-lang-nursery/fmt-rfcs/issues/66 and I think the implementation matches the result of that discussion. There is an option for the maximum length of a chain that we will put on one line and we might want to make that shorter, or possibly we need to ensure that it applies to the chain prefix when only the last item is multi-lined. (I agree that the first two examples looked better before and we should try and preserve that. The third example I'm not sure about).

**Comment by sfackler** [comment]
I don't feel particularly strongly about the last example either, yeah.
