### ISSUE TITLE
vec![] macro indented strangely when split across multiple lines

### ISSUE THREAD

**Issue by cessen** [rust-lang-nursery/rustfmt#1693]
It seems that in some cases rustfmt indents the `vec![]` macro in a visually confusing way if it's split across multiple lines.  For example, this code:

```rust
extern crate half;
use half::f16;

fn main() {
    let pixel_data = vec![(f16::from_f32(0.82), f16::from_f32(1.78), f16::from_f32(0.21)); 256 * 256];
}
```

Gets formatted like this:

```rust
extern crate half;
use half::f16;

fn main() {
    let pixel_data = vec![
        (
        f16::from_f32(0.82),
        f16::from_f32(1.78),
        f16::from_f32(0.21)
    );
        256 * 256
    ];
}
```

This makes it visually appear like the `);` ends the `vec![]` macro, when in fact the end is the `];`.  Something more along these lines is what I expected:

```rust
extern crate half;
use half::f16;

fn main() {
    let pixel_data = vec![
        (
            f16::from_f32(0.82),
            f16::from_f32(1.78),
            f16::from_f32(0.21)
        );
        256 * 256
    ];
}
```

**Comment by BusyJay** [comment]
Following looks better for me.

```
extern crate half;
use half::f16;

fn main() {
    let pixel_data = vec![(
        f16::from_f32(0.82),
        f16::from_f32(1.78),
        f16::from_f32(0.21)
    ); 256 * 256];
}
```

**Comment by cessen** [comment]
Yeah, I agree that looks better.  I was just trying to make the minimal sensible change from the current output, because I actually don't know what it's supposed to look like according to the style guide.  The important thing is that right now it's obviously broken. :-)
