### ISSUE TITLE
format rust code examples inside docs

### ISSUE THREAD

**Issue by sagiegurari** [rust-lang-nursery/rustfmt#1695]
is there a way to format the code examples inside the comment blocks?

**Comment by nrc** [comment]
I don't think there is a good way. It would be nice to support, I expect it would be a bit tricky but not too huge. I don't have much of a plan for doing it though.

**Comment by sagiegurari** [comment]
Thanks. Hope it will be in the plan at dome point

**Comment by killercup** [comment]
This might coincide with the idea to have a markdown formatter for doc comments (that e.g. always adds an empty line after headlines, and tries to breaks lines at 80 cols).
