### ISSUE TITLE
rustfmt removes a comment between argument lists and return type

### ISSUE THREAD

**Issue by yjh0502** [rust-lang-nursery/rustfmt#1700]
Here's testcase: https://play.rust-lang.org/?gist=16cdae004de4318b87a84d5c4905678f&version=stable&backtrace=0

before format
```rust
fn foo() // hello
-> Option<()> {
    Some(())
}
fn main() {
    format!("{:?}", foo());
}
```

after format
```rust
fn foo() -> Option<()> {
    Some(())
}
fn main() {
    format!("{:?}", foo());
}
```

**Comment by topecongiro** [comment]
This looks like a duplicate of #458 and #1643.

**Comment by nrc** [comment]
closing as dup (this is a limitation of the AST that Rustfmt uses, it is very annoying, but any fix is difficult).
