### ISSUE TITLE
Rustfmt changing the meaning of && by removing whitespace

### ISSUE THREAD

**Issue by SamWhited** [rust-lang-nursery/rustfmt#1702]
I have something similar to the following:

```rust
        if match foo(bar) {
            Err(_) => false,
            Ok(p) => { // p is a 3-tuple: (Option<&str>, &str, Option<&str>)
                match p.0 {
                    None => self.local.is_none(),
                    Some(s) => self.local.is_some() && self.local.unwrap() == s,
                }
                && p.1 == self.domain &&
                    match p.2 {
                        None => self.resource.is_none(),
                        Some(s) => self.resource.is_some() && self.resource.unwrap() == s,
                    }
            }
        }
        { …
```

Rustfmt currently formats one line as:

```rust
                &&p.1 == self.domain &&
```

and now building complains that I am trying to compare an `&&&str` (rustfmt removed the space between the `&&` and the `p.1`).

Running rustfmt 0.9.0-nightly for 2016-06-15.

**Comment by topecongiro** [comment]
It seems like rustfmt's parser parses the following code
```rust
{
    { foo() } && x && y
}
```
as a block with 2 statements(`{ foo() }` and `&& x && y`), not as a block with a single statement(`{ foo() } && x && y`).
For a workaround, please surround the block and the next expression with parens:
```rust
(match p.0 {
         None => self.local.is_none(),
         Some(s) => self.local.is_some() && self.local.unwrap() == s,
     } && p.1 == self.domain) &&
```

**Comment by nrc** [comment]
Is this a problem with the nightly rustfmt? I feel like we can't have an issue here is the parser does not. I'm also somewhat surprised that whitespace is ever significant in Rust. That seems like a bug in the Rust parser.

**Comment by karyon** [comment]
i reproduced this and the error exists before rustfmt runs.

this minimal example here:
```
    let str1 = "asdf";
    let bar = { 
        match Some(5) {
            None => true,
            Some(_s) => false,
        } && str1== str1
    };
```
produces
```
   |
75 |         } && str1== str1
   |                  ^^ can't compare `&&str` with `str`
   |
   = help: the trait `std::cmp::PartialEq<str>` is not implemented for `&&str`
   = note: required because of the requirements on the impl of `std::cmp::PartialEq<&str>` for `&&&str`
```

but also 
```
   |
72 | /         match Some(5) {
73 | |             None => true,
74 | |             Some(_s) => false,
75 | |         } && str1== str1
   | |_________^ expected (), found bool
   |
   = note: expected type `()`
              found type `bool`
```
which hints at the problem: the match is a statement, not an expression, and you can't just put && behind a statement. removing the whitespace does not change the compilation errors.

**Comment by topecongiro** [comment]
@karyon Thanks!

I am going to close this PR as this is not a rustfmt issue.

**Comment by SamWhited** [comment]
This example may be bad, but in whatever I was doing originally it compiled fine until rustfmt was run. I will attempt to come up with a new example, but this was definitely a problem with rustfmt moving the &&.

**Comment by karyon** [comment]
hm, i actually started with your example and tried to do minimal changes to make it compile! only then i reduced it to the example i posted above.

yes that felt weird to me too. i asked in IRC and the result was that if a statement begins with if or match or the like, it automatically ends when the block closes. if it wouldn't end there automatically, it would require to put a kinda redundant semicolon behind the closing brace, which would be redundant ;)

**Comment by SamWhited** [comment]
Let's not be redundant and repeat ourselves.
