### ISSUE TITLE
trailing_commas should maybe deal with more than usual lists?

### ISSUE THREAD

**Issue by dragostis** [rust-lang-nursery/rustfmt#1710]
Having set `trailing_commas` to `Never`, the following trailing commans are still applied:

```rust
pub struct FileInput {
    input: StringInput,
    file_name: OsString,
}
```

```rust
match len {
    Some(len) => Ok(new(self.input, self.pos + len)),
    None => Err(self),
}
```

I'm personally not a big fan of trailing commas especially when using formatting software, so I'm basically asking whether the `trailing_commas` config should apply to every possible instance of enumarating items. I don't know the internals of rustfmt, so I have no idea how easy this would be to implement.

**Comment by nrc** [comment]
I agree that `trailing_commas` should apply everywhere and it is basically a bug where it does not.
