### ISSUE TITLE
Two closures as function call arguments

### ISSUE THREAD

**Issue by stjepang** [rust-lang-nursery/rustfmt#1713]
I'm using Rayon and have code that looks like this:
```rust
rayon::join(
    || recurse(left, is_less, pred, limit),
    || recurse(right, is_less, Some(pivot), limit),
);
```

Rustfmt formats it to:
```rust
rayon::join(|| recurse(left, is_less, pred, limit), || {
    recurse(right, is_less, Some(pivot), limit)
});
```

This looks quite inconsistent. Why would the first closure be kept in the first line, but the other is split accross multiple lines?

It seems that we need another rule with regards to the closure-as-last-argument in functions calls:
If the argument list contains multiple closures, then each argument is placed on a dedicated line.

**Comment by nrc** [comment]
> It seems that we need another rule with regards to the closure-as-last-argument in functions calls

Agreed
