### ISSUE TITLE
Formatting of {v}.split_at_mut(mid)

### ISSUE THREAD

**Issue by stjepang** [rust-lang-nursery/rustfmt#1714]
The following code:

```rust
v = &mut {v}[mid..];
let (left, right) = {v}.split_at_mut(mid);
```

gets formatted to:

```rust
v = &mut {
    v
}[mid..];
let (left, right) = {
    v
}.split_at_mut(mid);
```

Perhaps we need a rule saying that if a single identifier is inside the braces, it shouldn't be treated as a multiline code block?

**Comment by nrc** [comment]
We already have such a rule for closures and unsafe blocks, iirc we don't apply it to regular blocks. It looks like we should apply it if the block appears in expression context (c.f., statement context).
