### ISSUE TITLE
Short impl's wrap leaving "where" dangling on a line by itself

### ISSUE THREAD

**Issue by SamWhited** [rust-lang-nursery/rustfmt#1718]
Consider the following formatting (from the current nightly build as of 2017-06-17) for a generic `Set` trait:

```rust
impl<T> Set<T> for T
where
    T: PartialEq,
{
    default fn contains(&self, c: T) -> bool {
        *self == c
    }
}
```

This feels unnecessary to me. When it's this short, and could always fit on a line, there's no reason to wrap:

```rust
impl<T> Set<T> for T where T: PartialEq,
```

If we always want to wrap for consistency with longer types, it feels poor to leave the "where" on a line all by itself, the following would look better (and extra generic parameters could still be added underneath and tabbed out to line up with the first one):

```rust
impl<T> Set<T> for T
    where T: PartialEq,
```

**Comment by sgrif** [comment]
This was pretty exhaustively discussed in the RFC: https://github.com/rust-lang-nursery/fmt-rfcs/issues/38

You can always write `impl<T: PartialEq> Set<T>` instead

**Comment by SamWhited** [comment]
Thanks; it's hard to find any formatting / code things with GitHub's search. If this is intended then there's no issue. By itself anyways, this is suprising and "looks like" a bug to me, but of course, maybe it's just me.

**Comment by nrc** [comment]
and here https://github.com/rust-lang-nursery/fmt-rfcs/issues/74 too (closing because it is an RFC issue, not a Rustfmt one)
