### ISSUE TITLE
Why does our try_opt macro require &&?

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#172]
If `foo` wants a `&str` and `bar: Option<String>`, I would expect `foo(&try_opt!(bar)` to work, but we need `foo(&&try_opt!(bar)`. Which is odd looking.

**Comment by marcusklaas** [comment]
It is odd! I noticed this as well, and I have no explanation for it.

**Comment by cassiersg** [comment]
This is caused by rust-lang/rust#26978.
