### ISSUE TITLE
improve test coverage for defaults

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1720]
We've managed to end up with a lot of the tests setting options and I worry that there is not enough coverage of the defaults. It is probably worth auditing the tests and where they are not deliberately testing an option, removing any options they set.

**Comment by afshinm** [comment]
@nrc can you send me an example of those default settings? I'm assuming we want to increase test coverage for default configs, right?

**Comment by nrc** [comment]
@afshinm if you look at config.rs, towards the end of the file is a macro which lists every option with a description and the default.

**Comment by klnusbaum** [comment]
Does this still need help? If so, I'd be willing to take a stab at it. I'm just not really sure where to start here. Can someone point me in the right direction? Which tests should I be looking at specifically?

**Comment by nrc** [comment]
> Does this still need help?

I think it does, but to be honest I haven't checked recently. I guess a good place to start would be to count the tests with options vs those without

> Which tests should I be looking at specifically?

Look at the integration tests, they are in https://github.com/rust-lang-nursery/rustfmt/tree/master/tests, .../source and .../target. The way they work is that a filename in source must match one in target. If you run rustfmt on the source file, the test passes if you end up with the target file. We also test that if you run on the target file, you get back the target file (i.e., rustfmt is idempotent). There are some target files without matching source files and they only test for idempotence.

Look for comments like `// rustfmt-max_width: 100` (from https://github.com/rust-lang-nursery/rustfmt/blob/master/tests/source/associated-types-bounds-wrapping.rs). Such comments indicate options which are passed to Rustfmt when testing. If there are no comments of that form, then we use the defaults (in this case we are using a default value for the option, so the comment may as well be removed - it might be good to detect that and warn about it when running tests).

I'm not sure of the next step - perhaps look for tests which are testing a specific thing and an option is set, but it not really necessary to test that thing? Or look for options which are over-tested and remove the option from some of those tests?

**Comment by scampi** [comment]
@klnusbaum if you don't mind, I'm giving this a try
