### ISSUE TITLE
Add options for trailing commas in match expressions

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#173]

**Comment by steveklabnik** [comment]
:+1:

**Comment by nrc** [comment]
Note we should have options for adding the trailing commas to single line branches and also for removing them from block arms.

**Comment by Ms2ger** [comment]
CC me

**Comment by marcusklaas** [comment]
Fixed by https://github.com/rust-lang-nursery/rustfmt/issues/663.
