### ISSUE TITLE
Comment before `} else {` is incorrectly indented

### ISSUE THREAD

**Issue by stjepang** [rust-lang-nursery/rustfmt#1737]
Code:

```rust
fn main() {
    if true {
        // Create a guard.
        let guard = create_guard();
        // The guard goes out of scope.
    } else {
    }
}
```

After rustfmt:

```rust
fn main() {
    if true {
        // Create a guard.
        let guard = create_guard();
    // The guard goes out of scope.
    } else {
    }
}
```

Perhaps *all* lines within blocks (even comments) should always be indented *more* than the lines with block boundaries?

**Comment by topecongiro** [comment]
This is intended behavior (cc #1575, #1619).
You can set `format_if_else_cond_comment` to `false` to indent the comment.

**Comment by stjepang** [comment]
@topecongiro Would it make sense for rustfmt to simply leave indentation of such comments intact?

To illustrate, I'm suggesting that rustfmt formats the following:
```rust
if true {
    foo();
        // a
} else if true {
    bar();
    // b
} else  if true {
    baz();
// c
} else {
    quux();
}
```

Into this:

```rust
if true {
    foo();
// a
} else if true {
    bar();
    // b
} else  if true {
    baz();
// c
} else {
    quux();
}
```

That strategy would do the right thing in almost all cases and make the flag `format_if_else_cond_comment` pretty much useless.

**Comment by sphynx** [comment]
> You can set format_if_else_cond_comment to false to indent the comment.

It looks like this option has been removed from `rustfmt` and now there is no way to override this behaviour.
