### ISSUE TITLE
Add a way to suppress the rustfmt write-mode warning

### ISSUE THREAD

**Issue by sid0** [rust-lang-nursery/rustfmt#1751]
I assume this warning will stick around for a while. Could you add a way to suppress it?

I started working on a patch to add it to rustfmt.toml, but I realized that this actually is a per-user setting, not a per-repository setting :(

**Comment by sid0** [comment]
Specifically referring to:

```
Warning: the default write-mode for Rustfmt will soon change to overwrite - this will not leave backups of changed files.
```

**Comment by nrc** [comment]
@sid0  You can suppress it by specifying a write mode

**Comment by sid0** [comment]
@nrc setting `write_mode` in `rustfmt.toml` doesn't do it. Having to specify `--write-mode` on the command line every time is inconvenient.

**Comment by sid0** [comment]
Also, at least to me it seems like `rustfmt.toml` is not the right place to configure `write_mode` in any case. This is a per-user setting, not a per-repository setting. Maybe an environment variable might work better?
