### ISSUE TITLE
rustfmt swallows comments inside `impl` ... `where`

### ISSUE THREAD

**Issue by mbr** [rust-lang-nursery/rustfmt#1758]
Example:

```rust
trait Foo {}

impl<T> Foo for T
// goodbye, cruel world
where T: Copy + Clone {}
```

`rustfmt` turns this into:

```rust
trait Foo {}


impl<T> Foo for T
where
    T: Copy + Clone,
{
}

```

```
$ rustfmt --version
0.9.0-nightly ( )
```

**Comment by sgrif** [comment]
This also happens with comments after `where`.

<img width="586" alt="screen shot 2017-07-05 at 2 03 50 pm" src="https://user-images.githubusercontent.com/1529387/27878007-cd10a48a-618a-11e7-87ae-db8ac9d1030f.png">
