### ISSUE TITLE
Vec Formatting is missing trailing comma

### ISSUE THREAD

**Issue by CryZe** [rust-lang-nursery/rustfmt#1761]
```rust
let test = Field::new(
    "Show Attempt Count".into(),
    self.settings.show_attempt_count.into(),
);

SettingsDescription::with_fields(vec![
    Field::new(
        "Show Finished Runs Count".into(),
        self.settings.show_finished_runs_count.into()
    ),
    Field::new(
        "Show Attempt Count".into(),
        self.settings.show_attempt_count.into()
    ),
])
```

As you can see, rustfmt adds a trailing comma to the second argument of `Field::new()` outside of the vec! macro, but it's missing inside the vec! macro.

**Comment by topecongiro** [comment]
rustfmt preserves the presence of trailing comma inside macro. However, it treats some known macros like `vec!` differently.

I think this is fixed on the current master. Could you try please?

**Comment by CryZe** [comment]
Looks like it's indeed fixed :)
