### ISSUE TITLE
How do I get rustfmt to stop complaining about lines it can't fix?

### ISSUE THREAD

**Issue by sgrif** [rust-lang-nursery/rustfmt#1770]
I'm trying to get Diesel using rustfmt. We have a comment [that is a long link](https://github.com/diesel-rs/diesel/blob/38038f6bbfd7247a03d765fc5b64de0c89f2bd8e/diesel/src/pg/types/money.rs#L25). Rustfmt can't break it up (It seems like it doesn't actually try to touch comments at all?). I wouldn't want it to. There is no way to make that line shorter. How do I make rustfmt not complain about that line every time I run it?

**Comment by nrc** [comment]
There's basically no way right now. Somewhat related is https://github.com/rust-lang-nursery/rustfmt/issues/584. But even if we skipped formatting (which we do anyway) we would still complain about the line length. I'm not sure what a solution here looks like - an option to not complain about overlong comments? A skip comment which also turns off warnings? Something else?

**Comment by sgrif** [comment]
Frankly I'm not sure why rustfmt needs to complain that it couldn't fix a line in the first place? All of the cases in Diesel are a combination of long comment lines (usually links), poorly formatted doc comments (which I'm actually surprised weren't handled), and macros which I wouldn't expect it to touch. It's not valuable information to me as a user that rustfmt couldn't do anything to those lines.

**Comment by topecongiro** [comment]
You could set `error_on_line_overflow = false` to prevernt rustfmt from complaining about lines exceeding max_width.

**Comment by kirs** [comment]
This doesn't really help with rustfmt, but I usually use URL shortener for long links in the code.

**Comment by killercup** [comment]
@kirs, please note that this makes you depend on the continued existence of that link shortener.

@sgrif, you can in the meantime also use `cargo fmt -q` to omit any output :)

**Comment by topecongiro** [comment]
Closing this since we now have `error_on_line_overflow_comments` configuration option to suppress warnings against single line comments.
