### ISSUE TITLE
Closures starting with an if block with a multiline condition are misformatted

### ISSUE THREAD

**Issue by isaacg1** [rust-lang-nursery/rustfmt#1771]
Here's an example program that is formatted badly, with the following cargo version:

```
$ cargo fmt -- --version
0.9.0-nightly ( )
```
---
```
fn main() {
    let partially_doubled: Vec<i32> = (0..5)
        .map(|long_number| if long_number % 2 == 0 ||
            long_number % 3 == 0
        {
            long_number * 2
        } else {
            long_number
        })
        .collect();
    println!("{:?}", partially_doubled);
}
```
This is hard to read due to the way the if condition is split up onto two lines, which end up very far from each other. It's much easier to read if the conditions are at the same indentation.

To solve this issue, whenever the if condition is split across multiple lines, we could introduce a block, resulting in the following for the above example:
```
fn main() {
    let partially_doubled: Vec<i32> = (0..5)
        .map(|long_number| {
            if long_number % 2 == 0 || long_number % 3 == 0 {
                long_number * 2
            } else {
                long_number
            }
        })
        .collect();
    println!("{:?}", partially_doubled);
}
```
This approach solves the above problem, by putting both conditions on the same line. Additionally, even if the condition is extremely long, the sub-expressions would end up at close to the same indentation, which is better than the current outcome.

**Comment by topecongiro** [comment]
We already have a similar heuristic (cc #1688).
Could you please try the most recent version?

**Comment by isaacg1** [comment]
That explains it - I hadn't switched to the correct method of installation. Thanks, and sorry for the trouble.
