### ISSUE TITLE
Trailing comma for last argument missing in some standard library macros

### ISSUE THREAD

**Issue by CryZe** [rust-lang-nursery/rustfmt#1790]
```rust
write!(
    time,
    " / {}",
    PossibleTimeSave::with_accuracy(self.settings.accuracy).format(previous_possible)
).unwrap();
```
write! is one of them, others are probably missing the trailing comma too.

**Comment by nrc** [comment]
We don't add or remove trailing commas in macros since that can affect semantics. I do not think we should try and add that knowledge to Rustfmt, so I think this is intentional behaviour. If you manually add a trailing comma here, it should be preserved.

**Comment by CryZe** [comment]
Why is it done in vec! though?

**Comment by CryZe** [comment]
Ohhh, that's actually very broken. I'll reopen a new issue, as I've found an actual bug.
