### ISSUE TITLE
nightly/unstable required?

### ISSUE THREAD

**Issue by jeffallen** [rust-lang-nursery/rustfmt#1793]
Hello. I am a new Rust user coming from Go. I wanted auto-formatting first thing as I started the tutorial, so I got it working using "cargo install rustfmt" (I'm a beginner, I'm not interested in bleeding edge nightly, just something that works...)

I was surprised that the format wasn't the same as the tutorial uses.

OK, so the README.md explains why. I upgraded to rustfmt-nightly, and I got this:

error[E0554]: #[feature] may not be used on the stable release channel
  --> /home/jra/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.1.9/src/lib.rs:11:1
   |
11 | #![feature(rustc_private)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

To me a stable code formatter is a critical thing to have available for beginners using the tutorial, so that they can start learning the best practices of the community, both in terms of tools and format. It is really frustrating/discouraging that I immediately ran into stability problems before I got off the first page of the tutorial.

Am I doing it wrong? Is Rust stable not used by real rust programmers? Should I have filed an issue with the rust project itself suggesting that the Install instructions should put people on the nightly channel?

**Comment by killercup** [comment]
I feel your frustration.

> To me a stable code formatter is a critical thing to have available for beginners using the tutorial, so that they can start learning the best practices of the community, both in terms of tools and format.

Absolutely agreed. But sadly, rustfmt is not yet there, and there are still code style discussions to be had before selling this as stable, 1.0 software. So this is at odds with:

> I'm a beginner, I'm not interested in bleeding edge nightly, just something that works...

Feel free to stay with the regular `rustfmt`. You can just format your files when the next stable release comes out. The 'old' style is different, but not completely broken or anything :)

As you guessed correctly, `rustfmt-nightly` requires Rust's nightly channel. Assuming you have installed Rust using `rustup`, I think you can just `cargo +nightly install rustfmt-nightly`.

Please note that this is a temporary thing: rustfmt is currently using some compiler internals for quicker development. <http://www.ncameron.org/blog/rustfmt-changes/> gives a few more details.

**Comment by jeffallen** [comment]
Ok, got it. Looks like I just picked the wrong time to learn Rust. No biggie.

**Comment by killercup** [comment]
Huh? You can still learn Rust. Having a formatting tool with a not-yet finished style is really no deal breaker, right?

**Comment by jeffallen** [comment]
Yes, no big deal. I should have said "chose the wrong time to compare
rustfmt to the tutorial".
