### ISSUE TITLE
Trailing comma in the macro invocation could break compilation

### ISSUE THREAD

**Issue by DarkEld3r** [rust-lang-nursery/rustfmt#1794]
The following unformatted code [compiles](https://play.rust-lang.org/?gist=c54bce459614bd924e5dc8f949f25c73&version=stable):
```rust
struct ReallyReallyReallyReallyVeryLongStructureName;

fn foo(
    _: ReallyReallyReallyReallyVeryLongStructureName, 
    _: ReallyReallyReallyReallyVeryLongStructureName, 
    _: &bool) {
}

macro_rules! call {
    ( $($function:ident)::*( $( $arg:expr ),* ) ) => ({
        let mut b = false;
        let _ = $($function)::*($($arg),*, &mut b);
    })
}

fn main() {
    call!(foo(
        ReallyReallyReallyReallyVeryLongStructureName, 
        ReallyReallyReallyReallyVeryLongStructureName));
}
```
Formatting adds trailing comma into the macro invocation:
```rust
    call!(foo(
        ReallyReallyReallyReallyVeryLongStructureName,
        ReallyReallyReallyReallyVeryLongStructureName,
    ));
```
which gives an [error](https://play.rust-lang.org/?gist=90119e18ff02817cae133cd73fd48fea&version=stable):
```
18 | /     call!(foo(
19 | |         ReallyReallyReallyReallyVeryLongStructureName,
20 | |         ReallyReallyReallyReallyVeryLongStructureName,
21 | |     ));
   | |_____^_- in this macro invocation
```

(I  have found that issue in the [rocksdb crate](https://github.com/spacejam/rust-rocksdb/blob/d87897ca660b66e0db429d4d583e46e29113a191/src/ffi_util.rs#L36).)

**Comment by topecongiro** [comment]
I think this is fixed on the latest `rustfmt-nightly`. Could you try with it?

**Comment by DarkEld3r** [comment]
@topecongiro You are right, `rustfmt-nightly` doesn't have this issue.
