### ISSUE TITLE
Incorrect formatting with long tuples

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang-nursery/rustfmt#1795]
rustfmt appears to be adding a comma after the last item in a tuple if it breaks the tuple construction over multiple lines:

```rust
   fn update_lambda_n(&mut self) {
       let (obs, avg) = self.pstate.num_clients;
       self.pstate.num_clients = (
           obs_prime,
           update_running_avg(avg, obs, self.pstate.unique_clients.len()), // <--- This comma is wrong
       );
   }
```

This is mildly annoying because it causes code not to compile after being formatted.

**Comment by nrc** [comment]
> This is mildly annoying because it causes code not to compile after being formatted.

I can't reproduce this - the compiler seems happy with training commas in tuple literals. Are you using a very old compiler by any chance.

**Comment by mark-i-m** [comment]
> I can't reproduce this

:confused: Hmm... neither can I... I was using 1.18 from a few weeks ago. I keep a short log of bugs/annoyances I come across while working, and this was on that log, but I'm not getting the same error I was a few days ago. Sorry for the noise :no_bell:
