### ISSUE TITLE
Inconsistent formatting of method calls

### ISSUE THREAD

**Issue by djc** [rust-lang-nursery/rustfmt#1797]
The way these get formatted doesn't make sense to me:

```diff
diff --git a/src/main.rs b/src/main.rs
index 7824cad..0254a95 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -46,19 +46,21 @@
 fn check_folder(ctx: Context, label: Label) -> Box<ContextFuture> {
     let Context { client, conn } = ctx;
-    Box::new(client.call(CommandBuilder::select(&label.name))
+    Box::new(
+        client
+            .call(CommandBuilder::select(&label.name))
     )
 }

@@ -70,20 +72,25 @@
 fn sync_folders(ctx: Context) -> Box<Future<Item = Context, Error = io::Error>> {
     let Context { client, conn } = ctx;
-    Box::new(conn.prepare("SELECT id, name, mod_seq FROM labels")
+    Box::new(
+        conn.prepare("SELECT id, name, mod_seq FROM labels")
+    )
 }
```

Why does the former get an extra newline, and the latter does not? To me, the latter looks more readable -- wasting an entire line on an atomic expression doesn't make that much sense to me.

**Comment by nrc** [comment]
The reason we change this at all is that there is a width heuristic for the arguments of a function call (we're currently discussing at https://github.com/rust-lang-nursery/fmt-rfcs/issues/47). I'm not sure why the two cases get formatted differently, I agree they probably should both be formatted like the latter. But I think the optimal formatting is probably staying on one line.

**Comment by topecongiro** [comment]
@djc I could not reproduce this on the latest `rustfmt-nightly`. Could you please try with it?

**Comment by djc** [comment]
@topecongiro I still see it with rustfmt-nightly v0.1.9:

```diff
diff --git a/src/main.rs b/src/main.rs
index 0254a95..2fed8de 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -47,12 +47,14 @@ type ContextFuture = Future<Item = Context, Error = std::io::Error>;
 fn check_folder(ctx: Context, label: Label) -> Box<ContextFuture> {
     let Context { client, conn } = ctx;
     Box::new(
-        client.call(CommandBuilder::select(&label.name))
+        client
+            .call(CommandBuilder::select(&label.name))
             .collect()
             .and_then(|(_, client)| {
                 let cmd = CommandBuilder::fetch()
```

You can test with https://github.com/djc/mailsync if you want. https://github.com/djc/mailsync/commit/be792c26ccbf7e4a48b835bcbe2348bd7bb1a675 applied most of rustfmt's suggestions, with the exception of this case; rustfmt-nightly-0.1.9 then still wants to make this change.

**Comment by topecongiro** [comment]
@djc Thank you for more information!
So rustfmt splits long chain and puts each element on its own line. However, if the first element is small (<= tab width), rustfmt puts the second element next to the first one.
```rust
// Do this
conn.bar()
    .baz();
// Instead of this
conn
    .bar()
    .baz();
```
When the chain is shorter than `chain_one_line_max` and is not multi-lined, rustfmt will keep it on a single line.
