### ISSUE TITLE
Inconsistent use of commas after match arms

### ISSUE THREAD

**Issue by djc** [rust-lang-nursery/rustfmt#1798]
See these two formatting choices made with the default config:

```diff
@@ -73,14 +80,14 @@
             match future.poll() {
                 Ok(Async::Ready(transport)) => {
                     self.transport = Some(transport);
-                },
+                }
                 Ok(Async::NotReady) => {
                     self.future = Some(future);
                     return Ok(Async::NotReady);
-                },
+                }
                 Err(e) => {
                     return Err(e);
-                },
+                }
             }
         }
         if !self.transport.is_some() {
@@ -438,10 +438,8 @@
 
 pub fn parse(msg: &[u8]) -> Option<(Response, usize)> {
     match response(msg) {
-        IResult::Done(remaining, res) =>
-            Some((res, msg.len() - remaining.len())),
+        IResult::Done(remaining, res) => Some((res, msg.len() - remaining.len())),
         IResult::Incomplete(_) => None,
-        IResult::Error(err) =>
-            panic!("error {} during parsing of {:?}", err, msg),
+        IResult::Error(err) => panic!("error {} during parsing of {:?}", err, msg),
     }
 }

```

The inconsistency of including commas after non-block arms and not including commas after block arms does not make sense to me, at all. It seems like these should be consistent (with my preference going to including the commas). I briefly read over https://github.com/rust-lang-nursery/fmt-rfcs/issues/42 which seems to end in a resolution that trailing commas should be used, but not sure if that's what's in effect here?

**Comment by nrc** [comment]
That RFC did not explicitly cover match arms, it was about *trailing* commas in lists. The justification for not using commas for block match arms is here: https://github.com/rust-lang-nursery/fmt-rfcs/issues/34#issuecomment-256157887
