### ISSUE TITLE
Match expansion when arms have many variants

### ISSUE THREAD

**Issue by anowell** [rust-lang-nursery/rustfmt#1807]
I had this match block:

```rust
match &*ext.to_lowercase() {
    "bmp" | "gif" | "ico" | "jpe" | "jpeg" | "jpg" | "png" | "svg" | "tif" | "tiff" |
     "webp" | "xcf" | "psd" | "ai" => FileType::Image,

    "3g2" | "3gp" | "avi" | "divx" | "flv" | "mov" | "mp4" | "mp4v" | "mpa" | "mpe" |
    "mpeg" | "ogv" | "qt" | "webm" | "wmv" => FileType::Video,

    "7z" | "rar" | "tgz" | "gz" | "zip" | "tar" | "xz" | "dmg" | "iso" | "lzma" |
    "tlz" | "bz2" | "tbz2" | "z" | "deb" | "rpm" | "jar" => FileType::Archive,

    "aac" | "flac" | "ogg" | "au" | "mid" | "midi" | "mp3" | "mpc" | "ra" | "wav" |
    "axa" | "oga" | "spz" | "xspf" | "wma" | "m4a" => FileType::Audio,

    _ => FileType::Unknown,
}
```

and it was reformatted, one-match per arm, into [this 64-line gist](https://gist.github.com/anowell/27388ed235e5ad529da0a634ac40b771) which seems less than ideal. In general, I like rustfmt's current match formatting, but this feels like a case where insert, reflow, and deal with the strange diff seems better than the really long expanded form.

**Comment by nrc** [comment]
Commented on https://github.com/rust-lang-nursery/fmt-rfcs/issues/34. Not sure if/how to handle this, but agree the current formatting is not great.
