### ISSUE TITLE
reorder_imports_in_group=true has no effect

### ISSUE THREAD

**Issue by doxxx** [rust-lang-nursery/rustfmt#1812]
My rustfmt.toml looks like this:

```
reorder_imports = true
reorder_imports_in_group = true
reorder_imported_names = true
```

I have a `.rs` file with a section of imports that looks like this:

```
use std::fs::File;
use std::path::Path;

use material::{Checkerboard, Color};
use object::Object;
use shapes::Sphere;
use system::{Camera, cast_ray};
use vector::Vector3f;
```

After formatting, it looks like this:

```
use material::{Checkerboard, Color};
use object::Object;
use shapes::Sphere;
use std::fs::File;
use std::path::Path;
use system::{Camera, cast_ray};
use vector::Vector3f;
```

Unless I'm misunderstanding what the `reorder_imports_in_group` option is supposed to do, I would expect there to be no change since the two groups are already sorted within themselves.

rustfmt v0.7.1

**Comment by topecongiro** [comment]
Please update your rustfmt to the latest version. Also I would highly recommend using `rustfmt-nightly`.

**Comment by doxxx** [comment]
Thanks, that fixes it!
