### ISSUE TITLE
Add option for indented binary operations

### ISSUE THREAD

**Issue by marcusklaas** [rust-lang-nursery/rustfmt#182]
We may want indent multi-line binary expressions an extra level:

``` rust
if some_check() ||
       other_check() ||
       charm() {
}
```

I believe this style is used in servo and/ or rustc.

**Comment by jdm** [comment]
I believe servo tends to indent more like
```rust
if some_check() ||
   other_check() ||
   charm() {
}
```
but probably inconsistently.
