### ISSUE TITLE
method definition not being wrapped

### ISSUE THREAD

**Issue by radix** [rust-lang-nursery/rustfmt#1825]
I suspect this is a similar issue to #1802

Here's my config:

```
single_line_if_else_max_width = 100
max_width = 100
tab_spaces = 2
fn_args_density = "Compressed"
chain_one_line_max = 100
fn_call_width = 100
struct_lit_width = 100
struct_variant_width = 100
```

Here's some code that's too long:

```rust
impl Game {
  pub fn path_creature_distance(&self, scene_id: SceneID, cid: CreatureID, pt: Point3, max_distance: Distance)
    -> Result<(ChangedGame, Distance), GameError> {
    panic!()
  }
}
```

specifically the `pub fn path_creature_distance` line is too long (the colon in `max_distance: Distance` is right on the 100th character).

**Comment by topecongiro** [comment]
Looks like `fn_args_layout = "Block"` and `fn_args_density = "Compressed"` does not interact very well.
I wonder which of the following (or others?) is expected output:
```rust
// 1
impl Game {
  pub fn path_creature_distance(&self, scene_id: SceneID, cid: CreatureID, pt: Point3,
    max_distance: Distance)
    -> Result<(ChangedGame, Distance), GameError> {
    panic!()
  }
}

// 2
impl Game {
  pub fn path_creature_distance(&self, scene_id: SceneID, cid: CreatureID, pt: Point3,
    max_distance: Distance,
  ) -> Result<(ChangedGame, Distance), GameError> {
    panic!()
  }
}

// 3
impl Game {
  pub fn path_creature_distance(
    &self, scene_id: SceneID, cid: CreatureID, pt: Point3, max_distance: Distance,
  ) -> Result<(ChangedGame, Distance), GameError> {
    panic!()
  }
}
```

**Comment by radix** [comment]
I'm not sure if you're asking me, but I think I would prefer option 3 given this combination of options :)

**Comment by radix** [comment]
In fact, I am seeing *some* code get formatted like option 3 already. I'm not sure exactly which circumstance is causing it, but I just hacked on some of my code and ran cargo fmt and it replaced this (which is longer than my max_width of 100):

```
impl X {
  pub fn resolve_creature_targets(&self, creature: &DynamicCreature, scene: &Scene, target: CreatureTarget, decision: DecidedTarget)
    -> Result<Vec<CreatureID>, GameError> {
    ...
  }
}
```

with this (which fits within 100 columns):

```
impl X {
  pub fn resolve_creature_targets(
    &self, creature: &DynamicCreature, scene: &Scene, target: CreatureTarget,
    decision: DecidedTarget,
  ) -> Result<Vec<CreatureID>, GameError> {
    ...
  }
}
```

At first I thought rustfmt somehow auto-updated in the middle of the night with a fix, but it's not applying this formatting universally, so I think this method must just be hitting a case that rustfmt is deciding to wrap (and using the formatting you described as number 3).

**Comment by topecongiro** [comment]
@radix Thank you for more information, and sorry for the late reply. On the latest master, the above issue seems to be fixed, at least with the above example. Could you please try with your code and see if everything works fine?

**Comment by radix** [comment]
@topecongiro lovely, the latest master gets rid of all but one of the "sorry" warnings on my codebase! Thanks very much, I'll close this issue :)
