### ISSUE TITLE
Line-splitting breaks macro invocation because of added comma

### ISSUE THREAD

**Issue by cmbrandenburg** [rust-lang-nursery/rustfmt#1834]
Sometimes `rustfmt` will format a macro invocation in a way that causes a compiler error where none existed before formatting. This happens when the macro expects parentheses as part of its parameters and the parameters are just the right length to cause `rustfmt` to line-wrap _within_ the parentheses.

Example macro:

```rust
macro_rules! faking_a_tuple_syntax {
    ($a:expr, ($b:expr, $c:expr)) => {
        println!("{}, ({}, {})", $a, $b, $c);
    };
}
```

Pre-formatted invocation:

```rust
faking_a_tuple_syntax!("short", ("The quick brown fox jumped over the lazy dog.", "This is another long argument."));
```

Post-formatted invocation:

```rust
faking_a_tuple_syntax!("short", (
    "The quick brown fox jumped over the lazy dog.",
    "This is another long argument.",
));
```

The problem with the post-formatted version is the trailing comma after the `$c` argument. The macro expects no comma there, but `rustfmt` inserted a comma before the newline it also added.

Here's the compiler error:

```
error: no rules expected the token `,`
  --> src/main.rs:10:41
   |
8  | /     faking_a_tuple_syntax!("short", (
9  | |         "The quick brown fox jumped over the lazy dog.",
10 | |         "This is another long argument.",
   | |                                         ^
11 | |     ));
   | |_______- in this macro invocation
```

**Comment by topecongiro** [comment]
Thanks for filing an issue! Fortunately this is fixed on the latest `rustfmt-nightly`. Could you please update your rustfmt?

**Comment by cmbrandenburg** [comment]
I do my edit-compile-run cycle using a stable Rust toolchain, and updating to `rustfmt-nightly` is not an option. Will there not be a v0.9.1 release?

In the meantime, I'm using `#[rustfmt_skip]` as a workaround. Feel free to close this issue if the v0.9.x branch is dead.

**Comment by nrc** [comment]
We can do a 0.9.1 release - I don't fundamentally object, however, someone would need to do the backport from the master branch and I expect that is non-trivial. I'm not planning on doing that. We plan to get rustfmt distributed via rustup in the next few months in order to support stable users. Sorry to make you wait for a solution.
