### ISSUE TITLE
--file-lines (range formatting) seems to be broken in a couple of ways

### ISSUE THREAD

**Issue by sid0** [rust-lang-nursery/rustfmt#1835]
Hey -- I'm trying to integrate RLS and rustfmt with our IDE, and it looks like range formatting is broken in a couple of ways. Here's a repro with 19bd5ea7b3feafe3eac1b6a033ca6db44d40ab32, with these settings:

```
condense_wildcard_suffixes = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
```

1. Download `lz4.rs` from [this gist](https://gist.github.com/sid0/4164a202cc976b0b48f76ad4c706ad29) somewhere.
2. `rustfmt lz4.rs --file-lines '[{"file": "lz4.rs", "range": [20, 27]}]' --write-mode display`
3. What you get back looks like `lz4_output.rs`.

Note a couple of things:

1. Imports were reordered even though none of the imports were in the range.
2. Line 32 got formatted even though it isn't in the range.

**Comment by nrc** [comment]
Looks like we are 'rounding up' to the whole module, rather than just the `impl`, so we end up reformatting a lot more than we should.

**Comment by sid0** [comment]
Hmm, I don't know much about rustfmt's internal logic, but would it make sense to round up to the surrounding block?

**Comment by nrc** [comment]
> would it make sense to round up to the surrounding block?

Depends what you mean by block.

So, just for a bit of context: we have to parse the whole file, so when we are rounding, we are rounding AST nodes, not text or tokens. Currently Rustfmt can only operate on module-level items (functions, impls, etc) so we have to round up to the nearest one of those. (In fact, I think we may always round up to the nearest module, which would explain this bug). In the future we should be able to format items within traits/impls as well.
