### ISSUE TITLE
Error message when formatting already formatted code?

### ISSUE THREAD

**Issue by LeoTindall** [rust-lang-nursery/rustfmt#1851]
I have Format On Save on in VSCode, and it is a reflex of mine to save a _lot_. Therefore, I often end up formatting already formatted code, and when I do, I get output like the following. Output from the tool automatically switches my bottom Toolbox view away from the Terminal or Problems tab, and is thus is quite annoying.

```
Request textDocument/formatting failed.
  Message: Reformat failed to complete successfully
  Code: -32603 
```

**Comment by nrc** [comment]
This is probably a bug in the RLS, rather than rustfmt, but not 100% sure.

**Comment by LeoTindall** [comment]
Definitely a RLS bug - rustfmt is emitting a perfectly sensible error message and RLS is suppressing it in favor of an undocumented error code. Thanks for pointing me that way.
