### ISSUE TITLE
Add reorder_extern_crates?

### ISSUE THREAD

**Issue by drager** [rust-lang-nursery/rustfmt#1857]
Would it be possible to add reordering of extern crate statements alphabetically:

- **Default value**: `false`
- **Possible values**: `true`, `false`

#### `false`:

```rust
extern crate futures;
extern crate chrono;
extern crate dotenv;
```

#### `true`:

```rust
extern crate chrono;
extern crate dotenv;
extern crate futures;
```

Thanks

**Comment by nrc** [comment]
I think this was part of the fmt RFC, so yes we should do it, and the default should be true, I think

**Comment by drager** [comment]
Oh I see, great! Thank you!
