### ISSUE TITLE
Don't erase a use with attributes attached

### ISSUE THREAD

**Issue by porglezomp** [rust-lang-nursery/rustfmt#1858]
I'm writing some platform code, and I have code like the following:

```rust
#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "linux")]
pub use self::linux::{};
```

the `pub use self::linux::{};` is a placeholder to match the uses that are on the other platforms (currently the Linux matches the macOS implementation, so they're both under the `unix` config…)

Running rustfmt erases the `use` line, producing:

```rust
#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "linux")]
```

which in addition to being annoying, also changes the semantics of the program because now the attribute will attach to the next available item.

**Comment by nrc** [comment]
hmm, I think we need to either delete the attribute if we delete the import, or not delete an import if it has an attribute. The latter sounds both easier and like it would be more helpful for you.

**Comment by porglezomp** [comment]
I'm interested in trying to contribute a fix for this.
