### ISSUE TITLE
assert_eq! line too long on master 

### ISSUE THREAD

**Issue by radix** [rust-lang-nursery/rustfmt#1868]
rustfmt version: master @ 7da776423a84ff3844cc546ecdc97c6c2c948c77

I only have one line-too-long "sorry" bug in my codebase now, and it's on an `assert_eq!` line. rustfmt seems to be able to format these normally.

config:

```
chain_one_line_max = 100
fn_args_density = "Compressed"
fn_call_width = 100
max_width = 100
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100
tab_spaces = 2
```

line:

```
mod test {
  #[test]
  fn folderpath_from_str() {
    assert_eq!(FolderPath::from_str("/foo").unwrap(), FolderPath::from_vec(vec!["foo".to_string()]));
  }
}
```

and the warning:

```
Rustfmt failed at foo.rs:652: line exceeded maximum length (maximum: 100, found: 101) (sorry)
```

**Comment by radix** [comment]
I'm sorry, I guess this is a dupe of https://github.com/rust-lang-nursery/rustfmt/issues/611

**Comment by topecongiro** [comment]
This may be hitting #1742.
