### ISSUE TITLE
Unhelpful error when trying to format read-only files

### ISSUE THREAD

**Issue by ivandardi** [rust-lang-nursery/rustfmt#1880]
I used LALRPOP to generate a parser file. It's a Rust read-only file. When I try to run `cargo fmt`, it displays the error

```
Error writing files: Permission denied (os error 13)
```

which is really unhelpful, because I have no idea if all the files were formatted, or if the error was encountered and all formatting was stopped.

It would be nice if instead we could have something like:

```
Couldn't format the following files:
    - src/lang.rs (File is read only)
15 files formatted. 1 file failed.
```

**Comment by nrc** [comment]
Fixed by #2069.
