### ISSUE TITLE
Formatting of "block" macros in let assignments

### ISSUE THREAD

**Issue by slyrz** [rust-lang-nursery/rustfmt#1881]
I call some macros with curly braces and pretend they are blocks. In `let` assignments, *rustfmt* turns these macros from

```rust
fn main() {
    let x = {
        a();
        b();
        c()
    };
    let y = something!{
        a();
        b();
        c()
    };
}
```
into
```rust
fn main() {
    let x = {
        a();
        b();
        c()
    };
    let y =
        something!{
        a();
        b();
        c()
    };
}
```
I think it would look better if the macro names were kept on the same line as the `let` statement, similar to the formatting of real code blocks.

Here's a [Playground link](https://play.rust-lang.org/?gist=9adb5970eb8f43844908c8d61acc26c8&version=stable) of the above example.

**Comment by topecongiro** [comment]
Could you tell us which version you are using please? I think this is fixed on the latest `rustfmt-nightly`.

**Comment by slyrz** [comment]
Oh wow, that's embarrassing. I thought I was running *rustfmt* from git, but it was just the latest published version on crates.io. Current master branch has this issue fixed. Sorry for wasting your time.
