### ISSUE TITLE
Option to block indent arrays with 'mixed' multi-lining

### ISSUE THREAD

**Issue by Vurich** [rust-lang-nursery/rustfmt#1882]
Essentially, you currently have to choose between:

```rust
const SomeArray: &[usize] = &[1, 2, 3, 4, 5, 6, 7, 8,
                              9, 10, 11, 12, 13];
```

and 

```rust
const SomeArray: &[usize] = &[
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
];
```

While I personally prefer the former, we use tabs at work and I'm not allowed spaces for visual indent (under pain of PR rejection). This is preventing me from using rustfmt at work, which is really annoying. If there was a `"VisualNewLine"` option that indented more like:

```rust
const SomeArray: &[usize] = &[
    1, 2, 3, 4, 5, 6, 7, 8,
    9, 10, 11, 12, 13,
];
```

it would mean that people who use tabs can indent arrays, since neither of the current options are satisfactory for users of tabs. Yeah, I know, I've tried convincing them to switch to RFC styling.

**Comment by nrc** [comment]
Edited the title for clarity - this is block indent, but with 'mixed' multilining (I don't know good terminology for the style of layout where we fit as many items on each line before line-breaking, rather than one item per line).
