### ISSUE TITLE
Broken macro indentation

### ISSUE THREAD

**Issue by stjepang** [rust-lang-nursery/rustfmt#1885]
Before formatting:
```rust
fn main() {
    let threads = people.into_iter().map(|name| {
        chan_select! {
            rx.recv() => {}
        }
    }).collect::<Vec<_>>();
}
```

After formatting:
```rust
fn main() {
    let threads = people
        .into_iter()
        .map(|name| {
            chan_select! {
            rx.recv() => {}
        }
        })
        .collect::<Vec<_>>();
}
```

What I expected:

```rust
fn main() {
    let threads = people
        .into_iter()
        .map(|name| {
            chan_select! {
                rx.recv() => {}
            }
        })
        .collect::<Vec<_>>();
}
```

**Comment by nrc** [comment]
In general macros are hard to format, because there is no AST, only tokens. For macros which parse as functions, we format them like that, but this macro example won't parse like anything really (Maybe the internals of a `match` but that isn't actually an AST node).

If you reformat the macro, it should keep your formatting and not revert it to the bad formatting though.

**Comment by stjepang** [comment]
That makes sense.

However, why did the 1st line of the macro got shifted to the right, but 2nd and 3rd were unmodified? By your reasoning, shouldn't all three lines be unmodified?

I was hoping that at least we could indent (to the left or right) all lines of the macro by the same amount, but otherwise preserve the formatting inside the macro.

**Comment by nrc** [comment]
That is kind of our default behaviour when we can't format stuff - we know where to start the first line, but then we don't know anything about the following lines.

We might be able to better here - for comments we treat them like an opaque block and move every line by the same indent, we might be able to do that same for macros that we can't format too. (Thanks for the idea!)
