### ISSUE TITLE
`cargo fmt` is not using rustfmt.toml on the root directory

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#1890]
Confirmed with `0.2.1-nightly (c166004 2017-08-16)`.
I think it used to and it should, though I am not sure.

**Comment by gyscos** [comment]
I just tried with `0.2.8-nightly (23be63f 2017-10-13)` and `/rustfmt.toml` (the only accessible config file) was correctly used.

I suppose if any intermediate directory contains a `rustfmt.toml`, it'll take precedence on the root one - maybe that's what's happening?

**Comment by nrc** [comment]
Testing today and there seems to be no problem, at least on Mac OS
