### ISSUE TITLE
Blockers for cargo fmt adoption for the GFX repository.

### ISSUE THREAD

**Issue by bjadamson** [rust-lang-nursery/rustfmt#1891]
Hello cargo format team!

In the GFX project, I propsed running cargo fmt --all on the project, and it seems it was very easy to find instances where executing the command reduces code clarity for the reader. I'm opening this issue so you have a way to track blockers for us, if that's something your interested in. If it's not useful, please feel free to open.

Since we're leaving the issue open in the GFX repository, I'll leave a link here for your reference.
https://github.com/gfx-rs/gfx/issues/1427

**Comment by nrc** [comment]
Most of the issues look like they'd be addressed by using nightly. Closing (please comment if not and I'll re-open).
