### ISSUE TITLE
rustfmt (0.9.0) creates broken code from enum comments

### ISSUE THREAD

**Issue by donhcd** [rust-lang-nursery/rustfmt#1893]
my comments got shoved uncompilably into a `#[doc ]` thing 😦 

![screen shot 2017-08-17 at 8 03 48 pm](https://user-images.githubusercontent.com/902007/29442551-20e61de2-8387-11e7-81ce-4bc337ac7a3c.png)

**Comment by topecongiro** [comment]
I think this is fixed on `rustfmt-nightly` as well 😃

**Comment by donhcd** [comment]
is there a "stable" version of `rustfmt-nightly`? I just installed it with `rustup default nightly && cargo install -f rustfmt-nightly` and rustfmt crashes on my codebase

**Comment by donhcd** [comment]
actually, `rustfmt` doesn't seem to run at all for me right now:

```
 %   rustfmt /tmp/bad.rs
dyld: Library not loaded: @rpath/libsyntax-dd119228887eb140.dylib
  Referenced from: /Users/don/.cargo/bin/rustfmt
  Reason: image not found
[1]    55716 trace trap  rustfmt /tmp/bad.rs
```
could this be due to a bug in nightly? I don't use it often...

**Comment by nrc** [comment]
You need to setup your LD_LIBRARY_PATH, see the last tip: https://github.com/rust-lang-nursery/rustfmt#tips

There will be a stable version via Rustup in a few months.

**Comment by donhcd** [comment]
thanks! I tested this again today and now it replaces

```
    /** No error. */
    NO_ERROR = 0,
```

with 
```
    /** No error. */ NO_ERROR = 0,
```

I liked it better before formatting it, but now it doesn't get broken 😄
