### ISSUE TITLE
Fallback

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#19]
Where formatting produces an item or statement which exceeds the max width, we should warn the user and fallback to using the original source code. The aim should be to never make things worse, so we should assume the users failure is better than our failure.

Fallback should pretty much only be done at the highest level (i.e., not on sub-expressions). but we might want to be able to give up pre-emptively in some cases.

**Comment by marcusklaas** [comment]
This is fixed now, I think.
