### ISSUE TITLE
single_line_if_else_max_width doesn't apply to if-only expressions?

### ISSUE THREAD

**Issue by Sushisource** [rust-lang-nursery/rustfmt#1908]
If I've got a nasty blob like:
```
  fn neighbor_count(&self, x: usize, y: usize) -> i32 {
    let mut count = 0;
    if x >= 1 {
      if y >= 1 && self.ca_grid[x - 1][y - 1] {
        count += 1
      }
      if self.ca_grid[x - 1][y] {
        count += 1
      }
      if self.ca_grid[x - 1][y + 1] {
        count += 1
      }
    }
    if y >= 1 && self.ca_grid[x][y - 1] {
      count += 1
    }
    if self.ca_grid[x][y + 1] {
      count += 1
    }
    if y >= 1 && self.ca_grid[x + 1][y - 1] {
      count += 1
    }
    if self.ca_grid[x + 1][y] {
      count += 1
    }
    if self.ca_grid[x + 1][y + 1] {
      count += 1
    }
    count
  }
```

Ideally those ifs would get flattened if I they fit under single_line_if_else_max_width, but rustfmt seems intent on breaking them up. Am I missing something, or is this expected?

**Comment by topecongiro** [comment]
This is intentional. `single_line_if_else_max_width` only applies to `if` which appears inside nested expressions. Please see https://github.com/rust-lang-nursery/rustfmt/pull/1783#issuecomment-314652752 for more.

**Comment by Sushisource** [comment]
Is there a setting that'll get these types of lines to flatten out? I wasn't able to find one.

**Comment by topecongiro** [comment]
Unfortunately no, there is not.

**Comment by nazzacode** [comment]
This is a feature I would find extremely useful and am amazed it does not exist. 
This is probably my biggest hate in rustfmt. 
Any chance we can get it added as an option?
