### ISSUE TITLE
Weird formatting when calling a function with long arguments

### ISSUE THREAD

**Issue by LordZane** [rust-lang-nursery/rustfmt#1912]
original code (bad):
```rust
.window("Wyvernwarp", TILESIZE * TILES_ACROSS * RESOLUTION_SCALE, TILESIZE * TILES_DOWN * RESOLUTION_SCALE)
```

rust fmt'd code (bad):
```rust
.window(
    "Wyvernwarp",
    TILESIZE * TILES_ACROSS * RESOLUTION_SCALE,
    TILESIZE * TILES_DOWN * RESOLUTION_SCALE,
)
```

what the code should look like after fmt'ing (good):
```rust
.window("Wyvernwarp",
        TILESIZE * TILES_ACROSS * RESOLUTION_SCALE,
        TILESIZE * TILES_DOWN * RESOLUTION_SCALE)
```

**Comment by topecongiro** [comment]
This is expected, as rustfmt uses block indent for function call with the default setting. You could change this by setting `fn_call_style = "Visual"`, although the option could be a bit fragile when expressions get complex.
