### ISSUE TITLE
rustfmt is removing a static variable when `max_width` is set

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rustfmt#1914]
Given this file:

`input.rs`:

```rust
extern "C" {
    #[link_name = "_ZN7MyClass26example_check_no_collisionE"]
 pub static mut  MyClass_example_check_no_collision  :  * const :: std :: os :: raw :: c_int ;
}
```

Running the most recently published `rustfmt` on it:

```
$ rustup run nightly rustfmt < input.rs > output.rs
```

Results in this file:

`output.rs`:

```rust
extern "C" {
    #[link_name = "_ZN7MyClass26example_check_no_collisionE"]
    ;
}
```

Note that the `pub static mut MyClass_example_check_no_collision` variable has disappeared and there is only a semicolon in its place.

The above only happens if I am running `rustfmt` inside a directory with the following `rustfmt.toml`:

```toml
max_width = 80
```

------------------------------------------------

```
$ rustup run nightly rustfmt --version
0.2.2-nightly ( )
$ rustup run nightly rustc --version
rustc 1.21.0-nightly (469a6f9bd 2017-08-22)
```

**Comment by topecongiro** [comment]
I could not reproduce this with the latest master(`0.2.2-nightly (1a02c35 2017-08-25)`). It still exceeds max width, though.

**Comment by topecongiro** [comment]
My bad, I could.
