### ISSUE TITLE
fn type aliases formatted visually even with 'fn_args_layout = "Block"'

### ISSUE THREAD

**Issue by edmccard** [rust-lang-nursery/rustfmt#1926]
rustfmt used to do this:

```
type SomeFFIProc = unsafe extern "C" fn proc(
    type1,
    type2,
    type3,
);
````

and now (rustfmt 0.9.0 nightly) it does this:

```
type SomeFFIProc = unsafe extern "C" fn proc(type1,
                                             type2,
                                             type3);
````

I don't know when this changed since I noticed it when editing a file that I hadn't touched for a month or so.

**Comment by nrc** [comment]
Can you check using rustfmt-nightly, rather than rustfmt? Or with a build from master please? I can't reproduce - I get a parse error: `error: expected `(`, found `proc``, if I fix that by removing `proc` then everything gets put on one line, reducing the line width I get a break after the `=`.

**Comment by edmccard** [comment]
Sorry, the `proc` was a typo. And I thought I was using nightly, but I guess the last time I updated the nightly compiler I pulled in rustfmt again instead of rustfmt-nightly. It works correctly now (using block indent for loooong parameter lists).
