### ISSUE TITLE
Methods with restricted pub modifier cause weird behaviour

### ISSUE THREAD

**Issue by SynthScore** [rust-lang-nursery/rustfmt#1935]
I tried to make a method public only to its parent module using the notation specified in the following RFC: https://github.com/rust-lang/rfcs/blob/master/text/1422-pub-restricted.md

Apparently, this doesn't work when the formatter is run. This is the faulty snippet before formatting:

```
pub(super) fn from(path: &Path) -> Self {
    Self { path: path.to_owned() }
}
```

And this is the same snippet after formatting:

```
pub(super) fn from(super) fn from(
                   path: &Path)
                   -> Self {
    Self { path: path.to_owned() }
}
```

Any idea about that weird `fn from(super)` that automatically gets inserted?
Moreover, even the linebreaking strategy got  messed up: I set a very long maximum line length, so it shouldn't have broken my code in such a weird way.

Many thanks in advance to whoever is going take to care of this! (-:

**Comment by nrc** [comment]
Are you using the latest version of rustfmt-nightly (note this is not the same crate as rustfmt)? I believe this problem is fixed there.

**Comment by nrc** [comment]
Current version is nightly-0.2.4

**Comment by SynthScore** [comment]
Thank you, it is fixed indeed and it works like a charm!
