### ISSUE TITLE
single-line where clauses should be behind an option

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1936]
`where_single_line`, false by default. And we can probably remove `where_density`.

cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/74

**Comment by afshinm** [comment]
hey @nrc 

I'd like to work on this. Do we want to enable `where` clause to be formatted in a new line (with an option)?

**Comment by nrc** [comment]
Hi @afshinm, that's great! So, where clauses should be formatted by default on multiple lines. The current Rustfmt behaviour is correct if there are mutliple items in the `where` clause (e.g., `where T: Foo, U: Bar`). Where there is just a single item (e.g., `where T: Bar`), Rustfmt uses a short form. We should only use that short form if the `where_single_line` option is true.

**Comment by afshinm** [comment]
Great. I think I should be able to send a PR soon.

**Comment by afshinm** [comment]
Ok, just to make sure we are on the same page. I have added this source / target test. Just wanted to make sure my assumption is correct.

Source: 

```
// rustfmt-where_single_line: true

fn lorem<Ipsum, Dolor, Sit, Amet>() -> T where Ipsum: Eq {
    // body
}
```

Target:

```
fn lorem<Ipsum, Dolor, Sit, Amet>() -> T 
where Ipsum: Eq {
    // body
}
```

**Comment by nrc** [comment]
Yep, that looks correct (and no trailing comma).

When `rustfmt-where_single_line: false` I'd expect

```
fn lorem<Ipsum, Dolor, Sit, Amet>() -> T 
where
    Ipsum: Eq,
{
    // body
}
```

**Comment by afshinm** [comment]
@nrc awesome, thanks.
