### ISSUE TITLE
Declarative Macros 2.0 and Source Corruption

### ISSUE THREAD

**Issue by valff** [rust-lang-nursery/rustfmt#1949]
Declarative macros 2.0 were landed recently (https://github.com/rust-lang/rust/pull/40847), and I want to try them. The problem is that rustfmt corrupts the source. Consider this simple example:
```rust
pub macro reg() {}
```
Rustfmt converts it to:
```rust
pubmacro reg() {}
```
Which makes it uncompilable. Version of rustfmt: `0.2.5-nightly`.

**Comment by topecongiro** [comment]
This is now fixed by using the latest nightly toolchain. Please run `rustup update && cargo install rustfmt-nightly --force`.
