### ISSUE TITLE
Should block expressions nested in expressions vs statements be formatted differently

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#195]
It seems to me that in a `let` statement with a nested match or closure expression, we want to use block indenting, whereas if these expressions are in a function argument, we want to use visual indenting.

Possibly how we format struct literals is different too (first argument on the same line as the opening brace (and visual indenting) vs next line (and block indenting)).

**Comment by marcusklaas** [comment]
Agreed. Perhaps we could add a `recursion_depth` parameter to `RewriteContext`. We should probably start passing that by value then.
