### ISSUE TITLE
Attribute creates extra space between field name and type

### ISSUE THREAD

**Issue by sbstp** [rust-lang-nursery/rustfmt#1950]
I'm using the vscode-rust extension. I have an enum with a struct-like variant, inside of which there's a field with a serde attribute. It seems like it's trying to align the field with the attribute. I have ```attributes_on_same_line_as_field = false``` in my `rustfmt.toml`.

```
#[derive(Deserialize, Serialize)]
pub enum Response {
    Failure {
        #[serde(rename = "failure reason")]
        reason:                             String,
        //      ^ issue here
    },
    Ok {
        #[serde(rename = "warning message")]
        warning: Option<String>,
        interval: i64,
        #[serde(rename = "min interval")]
        min_interval: Option<i64>,
        tracker_id: String,
        complete: u64,
        incomplete: u64,
        peers: ByteBuf, // only supports the compact format for now
    },
}
```

**Comment by nrc** [comment]
This seems to be fixed on master. Should have this on the RLS in the next week or so. Please let us know if you don't think this is fixed.
