### ISSUE TITLE
Option to split chain based on number of method calls

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang-nursery/rustfmt#1953]
I typically split my chains into multiple lines after the first method call, not dependent on the length of some chain. So something like:

```diff
- some_item.method_a().method_b().then_c().also_d();

+ some_item.method_a()
+     .method_b()
+     .then_c()
+     .also_d();
```

But I _don't_ split them up if there are, for instance, just three methods being chained:

```rust
some_item.method_a().method_b();
```

I'd like to be able to control:
  1. How many methods need to be called for a split to happen (in my case, > 2).
  2. When a split happens, how many calls should stay on the first line (in my case, 1).

Of course, if the setting for 2) exceeds max-width (or perhaps another setting), then the first method call should be moved to the next line regardless:

```diff
- some_item.this_is_some_really_long_method_name_that_definitely_exceeds_max_width();
+ some_item
+     .this_is_some_really_long_method_name_that_definitely_exceeds_max_width();

- some_item_name_here_that_definitely_results_in_exceeding_max_width().in_first_method();
+ some_item_name_here_that_definitely_results_in_exceeding_max_width()
+     .in_first_method();
```

**Comment by nrc** [comment]
We experimented with this in the past, but it worked really badly in practice - long method calls, etc. caused problems and we found the character based version (`chain_one_line_max`) much better. Given that experience, we're unlikely to re-add the old count-based prefs (we might decide something else in the fmt-rfcs process too).
