### ISSUE TITLE
macro call parameter layout

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang-nursery/rustfmt#1955]
Are there any options to control the layout of parameters in macro calls? At the moment, the following occurs when `rustfmt` is called, which I'd like to prevent:

```diff
-impl_with_fromstr!(f32, f64, isize, i8, i16, i32, i64, usize, u8, u16, u32, u64, bool,⏎
-                   IpAddr, Ipv4Addr);⏎
+impl_with_fromstr!(f32,⏎
+                   f64,⏎
+                   isize,⏎
+                   i8,⏎
+                   i16,⏎
+                   i32,⏎
+                   i64,⏎
+                   usize,⏎
+                   u8,⏎
+                   u16,⏎
+                   u32,⏎
+                   u64,⏎
+                   bool,⏎
+                   IpAddr,⏎
+                   Ipv4Addr);⏎
```

**Comment by nrc** [comment]
macros are styled in exactly the same way as function calls (or arrays if they are `[]` macros). BTW, it looks like you might be using a very old version of rustfmt.

I've been vaguely thinking about how to format macros in general. Given the variety of syntax, it might want to be something that macro authors specify somehow using an attribute or data file or something. But I have no idea how that would work in practice

**Comment by topecongiro** [comment]
Closing as the above example is fixed.
