### ISSUE TITLE
Error on formatting when line length exceeds 100 (possibly only on macros)

### ISSUE THREAD

**Issue by leshow** [rust-lang-nursery/rustfmt#1958]
My rustfmt-nightly will error out on line length. Anything over 100 chars, adding the error_on_line_overflow = false will suppress the error, but I'd rather the line be formatted to the proper width and indentation
```
>  ~/dev/rust/rust_mnemonic [master] ⚡ rustfmt --version
0.2.5-nightly ( )
>  ~/dev/rust/rust_mnemonic [master] ⚡ rustc --version
rustc 1.22.0-nightly (ca94c75c5 2017-09-10)
```

I have a feeling it might have to do with macros specifically, it seems to have shortened other lines. Specifically, the line is

```
impl fmt::Debug for Mnemonic {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Generated: \n random characters: {:?} \n mnemonic: ", String::from_utf8_lossy(&self.mnemonic[..self.mnemonic.len()-1]))
    }
}
```

that `write!` is one big line I expected rustfmt to break up and align properly.

when I split up the line manually to make it under 100 chars, it doesn't format the second part properly (I expected some kind of indentation)
```
        write!(f, "Generated: \n random characters: {:?} \n mnemonic: ",
        String::from_utf8_lossy(&self.mnemonic[..self.mnemonic.len()-1]))
```

**Comment by topecongiro** [comment]
Thank you for filing an issue! I will be closing this since this is fixed on the latest master via #1937.
