### ISSUE TITLE
Libsyntax mismatch

### ISSUE THREAD

**Issue by whmountains** [rust-lang-nursery/rustfmt#1959]
I have already already followed the [instructions](https://github.com/rust-lang-nursery/rustfmt#tips) for how to fix this, but to no avail.

```shell
$ rustfmt main.rs
dyld: Library not loaded: @rpath/libsyntax-197d3f04d0b6edbf.dylib
  Referenced from: /Users/mmc/.cargo/bin/rustfmt
  Reason: image not found
```

The library is actually not there.  I checked myself:

```shell
$ ls /Users/me/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/libsyntax-*
/Users/me/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/libsyntax-73faf534df7a6fbc.dylib
```
rustfmt is looking for `libsyntax-197d3f04d0b6edbf` but what actually is there is `libsyntax-73faf534df7a6fbc`

I am running the latest version of rust nightly, and I installed rustfmt a few minutes ago.

```shell
$ rustc --version
rustc 1.22.0-nightly (eba374fb2 2017-09-11)
```

**Comment by nrc** [comment]
Have you re-installed rustfmt after doing a rustfmt update?
