### ISSUE TITLE
rustfmt destroyed code snippets in doc comments

### ISSUE THREAD

**Issue by prertik** [rust-lang-nursery/rustfmt#1960]
While running rustfmt-nightly on [azerupi/mdBook](https://github.com/azerupi/mdBook) repository. Rustfmt seems to have destroyed code snippets in doc comments which failed the test on: [https://github.com/azerupi/mdBook/pull/437](https://github.com/azerupi/mdBook/pull/437).

**Comment by topecongiro** [comment]
This is caused by `wrap_comments = true`, probably. Please try setting it to `false` and see if it works fine.

**Comment by prertik** [comment]
Thanks! It did solve my problem.
