### ISSUE TITLE
Struct field init shorthand not supported

### ISSUE THREAD

**Issue by huwwynnjones** [rust-lang-nursery/rustfmt#1961]
I have some code that uses the [Struct field init shorthand](https://doc.rust-lang.org/reference/expressions.html#struct-field-init-shorthand).

However rustfmt does not recognise it as valid syntax:

`        Ok(Column {
            handle: parameter,
            sql_type: data_type,
            column_ptr_holder,
        })
`

Produces the following error:

``error: expected `:`, found `,`
--> /home/xxxxxx/statement.rs:498:30  
    |
498 |             column_ptr_holder,
    |                              ^
``

Rustfmt is expecting me to write out my struct initialisation code as follows:

`        Ok(Column {
            handle: parameter,
            sql_type: data_type,
            column_ptr_holder: column_ptr_holder,
        })
`

**Comment by nrc** [comment]
I think this is fixed in the most recent version - are you using the rustfmt-nightly crate?

**Comment by huwwynnjones** [comment]
No, i am not. I will try that.

**Comment by huwwynnjones** [comment]
Yep, this is fixed in rustfmt-nightly. thanks
