### ISSUE TITLE
How to format code containing HTML?

### ISSUE THREAD

**Issue by prertik** [rust-lang-nursery/rustfmt#1970]
Recently, while formatting some code containing HTML `r##"blah blah <a class="header" href="./some_chapter/some_section.html#foo" id="foo"><h1>Foo</h1></a>"##,`
rustfmt alerted `line exceeded maximum width (maximum: 100, found: 121)`. 
**How to format this code without abusing rustfmt default settings?**

**Comment by nrc** [comment]
I would either split the string manually or use a rustfmt skip attribute. I don't think Rustfmt will (or should) try to format such a string.

**Comment by prertik** [comment]
Thank you for answering!
