### ISSUE TITLE
add 'unstable options' command line option

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#1975]

**Comment by ssilva** [comment]
Hi Nick, this might be something I can tackle. Where can I find more info about this bug (rationale/context)?

**Comment by nrc** [comment]
So the motivation here is that when we are distributed with Rustup there will be both nightly (unstable) and other (stable) versions of Rustfmt. To get the unstable features, the user will have to opt-in by running `rustfmt --unstable-features`. This flag will only be available to nightly users (much like the feature flag system in Rust).

In terms of implementation there are a few steps:
* add the flag itself (this should be pretty easy)
* ensure the flag can be set programmatically when rustfmt is used as a library
* decide what should be unstable (this can be ongoing, but needs to be done by the time we use Rustup)
* for each unstable feature, ensure that you need the `--unstable-features` flag. This includes any unstable configuration options (we would need some mechanism for marking options as stable or unstable)
* only allow the flag to be set if we are run with nightly (see the RLS for an example of how to do this)

**Comment by tmahmood** [comment]
Hi Nick, I have sent a PR for this issue. Sorry for not communicating beforehand. 

I have question about this one.

> only allow the flag to be set if we are run with nightly (see the RLS for an example of how to do this)

I have used CFG_RELEASE_CHANNEL to detect which version of rust we are using. Is this right approach? I didn't felt it was very reliable.

**Comment by nrc** [comment]
> I have used CFG_RELEASE_CHANNEL to detect which version of rust we are using. Is this right approach?

Yes, that is good.

**Comment by nrc** [comment]
Closed by #1998
