### ISSUE TITLE
Line exceeded maximum length

### ISSUE THREAD

**Issue by thomas-jeepe** [rust-lang-nursery/rustfmt#1987]
So, I am using emscripten and need to do a link args and it looks like this:

```rust
#![feature(link_args)]

#[link_args = "-s NO_FILESYSTEM=1 -s NO_EXIT_RUNTIME=1 -s EXPORTED_RUNTIME_METHODS=[\"_malloc\"] -s NO_DYNAMIC_EXECUTION=1 -s ELIMINATE_DUPLICATE_FUNCTIONS=1 -s EVAL_CTORS=1"]
extern "C" {}
```

I get this when running rustfmt on the file:

```
line exceeded maximum length (maximum: 120, found: 175) (sorry)
```

I don't necessarily know what to do with this error, technically I could increase the maximum length, however it isn't a good way of handling it as I want everything else to follow the line length.

**Comment by nrc** [comment]
Can you use a skip attribute before the `link_args` attribute?

**Comment by thomas-jeepe** [comment]
No, tried this:

```rust
#![feature(link_args)]

#[rustfmt_skip]
#[link_args = "-s NO_FILESYSTEM=1 -s NO_EXIT_RUNTIME=1 -s EXPORTED_RUNTIME_METHODS=[\"_malloc\"] -s NO_DYNAMIC_EXECUTION=1 -s ELIMINATE_DUPLICATE_FUNCTIONS=1 -s EVAL_CTORS=1"]
extern "C" {}
```

it failed again.

**Comment by nrc** [comment]
I hope we can fix that so it works

**Comment by thomas-jeepe** [comment]
Thanks

**Comment by nrc** [comment]
This is partially addessed by #2017 and I filed #2033 specifically for the skip/attribute thing.
