### ISSUE TITLE
`--dump-default-config` does not have a default argument

### ISSUE THREAD

**Issue by ssilva** [rust-lang-nursery/rustfmt#1988]
## Steps to reproduce
`$ rustfmt --dump-default-config`

## Expected behaviour
The path defaults to "rustfmt.toml".
As per #1558. Also see [this comment](https://github.com/rust-lang-nursery/rustfmt/pull/1982#discussion_r139875215).

## Actual behaviour
Error:
```
~/dev/rust/hello_cargo/src (master #)$ rustfmt --dump-default-config
Argument to option 'dump-default-config' missing
...
```
## More info
```
~$ rustfmt --version
0.2.6-nightly ( )
```

**Comment by japaric** [comment]
Alternatively, omitting the path could make `rustfmt` print the configuration to stdout then the user can redirect the output to a file (`rustfmt --dump-default-config > foo.toml`). The advantage over having a default path is that the default path may end overwriting an existing file if the default path is something common like `rustfmt.toml`. Of course rustfmt could ask the user "heads up! do you really want to overwrite the existing rustfmt.toml file?" but that would complicate the implementation. With the stdout approach the task of checking for file overwrites falls on the user.

Thoughts @nrc? I can take a stab at either implementation.

**Comment by nrc** [comment]
stdout sounds good to me!

**Comment by remram44** [comment]
This doesn't seem to work anymore after cbd3608c30cfdee4954820d8ee1f940a4f1abf08 #2579
