### ISSUE TITLE
Two comments in a row with hard_tabs has a single space of indentation

### ISSUE THREAD

**Issue by andy-hanson** [rust-lang-nursery/rustfmt#1989]
Input code:
```rust
fn main() {
	// Comment one
	// Comment two
}
```

Output:
```rust
fn main() {
	// Comment one
 // Comment two
}
```

My `Rustfmt.toml` is just `hard_tabs = true`.

**Comment by matthew-mcallister** [comment]
This is actually a problem with the [strings crate](https://github.com/nrc/strings.rs), which is not tab- or unicode-aware. Neither is `rustfmt` itself, for that matter.
