### ISSUE TITLE
All Bindings Removed from Match Arm if `..` is Used

### ISSUE THREAD

**Issue by iwillspeak** [rust-lang-nursery/rustfmt#1994]
With the minimal example:

```rust
pub enum Foo {
    Bar(usize, usize),
}

pub fn foo(f: Foo) {
    match f {
        Foo::Bar(i, ..) => i < 100,
    };
}
```

If formatted with rustfmt `0.6.0` the pattern `Foo::Bar(i, ...)` ends up being replaced with `Foo::Bar(..)`. This means the example no longer compiles after formatting when it did before.

After formatting:

```rust
pub enum Foo {
    Bar(usize, usize),
}

pub fn foo(f: Foo) {
    match f {
        Foo::Bar(..) => i < 100,
    };
}
```

**Comment by nrc** [comment]
Could you try with a recent version of rustfmt-nightly please (or master)? 0.6 is very old.

**Comment by iwillspeak** [comment]
Tried it with 0.9.0 and it works. Sorry about that.
