### ISSUE TITLE
Chaining.

### ISSUE THREAD

**Issue by wavded** [rust-lang-nursery/rustfmt#1999]
Given default configuration I wonder if `rustfmt` could be smarter at this:

```rust
fn main() {
    let s = "What is by the river?";
    s.replace("What is ", "").replace(" by ", "").replace(
        "?",
        "",
    );
}
```

Although many more columns are allowed, it stops early and does the weirdness above.  Would expect either the `replace` calls are all on their own line, or the all remain on the same line.

**Comment by topecongiro** [comment]
I think this and related issues are fixed on the latest version of rustfmt-nightly (0.2.7). Please update and see if that works.

**Comment by wavded** [comment]
Attempted to get the nightly but ran into this issue https://github.com/rust-lang-nursery/rustfmt/issues/2002.  But was able to install from source to get around it and it appears to be much better, I get:

```
fn main() {
    let s = "What is by the river?";
    s.replace("What is ", "")
        .replace(" by ", "")
        .replace("?", "");
}
```

**Comment by topecongiro** [comment]
Great, thank you!
