### ISSUE TITLE
rustfmt skip does not work on macros

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2006]
from `stdsimd`; line width set to 79 characters:

```rust
#[cfg_attr(rustfmt, rustfmt_skip)]
// #[rustfmt_skip] // does not work either
macro_rules! __unstable_detect_feature {
    ("sse") => { $crate::vendor::__unstable_detect_feature($crate::vendor::__Feature::sse{})  };
}
```

shows:

```shell
("sse") => { $crate::vendor::__unstable_detect_feature($crate::vendor::__Feature::sse{})  };
   |                                                                                ^^^^^^^^^^^^^^^^^

error: line exceeded maximum width (maximum: 79, found: 85)
```

**Comment by nrc** [comment]
Is it just the warning that is the issue? We don't seem to be formatting the macro itself.

**Comment by gnzlbg** [comment]
The issue is that the error is emitted but the macro is not formated. It is possible to make this particular macro fit into 79 charactes lines, but the tool is not doing it. I had to format it manually, and then the tool doesn't emit the error.

IMO I shouldn't need to format anything manually unless I turn `rustfmt` off for a particular snippet of code.

**Comment by nrc** [comment]
But you are turning rustfmt off by using the skip attribute?

**Comment by gnzlbg** [comment]
No, I keep it on. This happens here: https://github.com/gnzlbg/stdsimd/blob/master/src/x86/runtime.rs#L30

If I put one of those lines in a single line, the tool emits an error but does not reformat the line properly (or at least did not do so when I filled this issue).
