### ISSUE TITLE
rustfmt skip does not work on inner doc comments

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2007]
Example 

```rust
#[cfg_attr(rustfmt, rustfmt_skip)]
//! Some inner doc comment
//! ...
```

**Comment by topecongiro** [comment]
Is it even possible to put any kind of attributes on inner doc comments?

**Comment by topecongiro** [comment]
I think skipping inner doc comments works on 0.3.2. Would you please try with it? Also you may need to use `#![rustfmt_skip]` due to rust syntax.

**Comment by gnzlbg** [comment]
I don't even know what this was about. Can't reproduce, and no reproducer available.
