### ISSUE TITLE
fn_call_style has no "Compressed" variant

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2010]
Check this out. Before: 

```rust
let a = i8x32::new(
             0, 1, -1, 2,	
             -2, 3, -3, 4,
             -4, 5, -5, std::i8::MAX,	
             std::i8::MIN + 1, 100, -100, -32,	
             0, 1, -1, 2,	
             -2, 3, -3, 4,	
             -4, 5, -5, std::i8::MAX,	
             std::i8::MIN + 1, 100, -100, -32);
```

After

```rust
let a = i8x32::new(
            0,
            1,
            -1,
            2,
            -2,
           3,
            -3,
            4,
             -4,
             5,
             -5,
             std::i8::MAX,
             std::i8::MIN + 1,
             100,
            -100,
            -32,
             0,
            1,
             -1,
             2,
             -2,
             3,
             -3,
             4,
             -4,
             5,
             -5,
             std::i8::MAX,
             std::i8::MIN + 1,
             100,
             -100,
             -32,
         );
```

**Comment by nrc** [comment]
Should probably just skip calls like this.

**Comment by gnzlbg** [comment]
@nrc is this fixed, or should I just not have this method? we are using `rustfmt` in `stdsimd`, and... if you have an `u8x32 then the `new` constructor really does take 32 arguments... such is life :D

**Comment by nrc** [comment]
You should use a skip attribute on a call like this.I think it is unlikely that rustfmt ever will (or even could) format a call like this nicely.

**Comment by gnzlbg** [comment]
This is what I ended up doing. This issue was filled because I thought that adding a `Compressed` variant to `fn_call_style` would fix this everywhere for us. Turning such a feature on would probably eliminate 90% of the skips in the `stdsimd` code base.

**Comment by nrc** [comment]
The trouble is that for most function calls, compressed is a pretty bad formatting style and we have no way of forcing an option on for some calls. We'd need to be 'smart' about when to apply different styles and people generally don't like these kind of 'heuristic' changes.

**Comment by gnzlbg** [comment]
I personally like to maximize use of vertical space so compressing function arguments is not that bad. 

I agree that it doesn't look very nice, but nice-looking code is not what I expect from an automatic formatting tool, the only thing I expect is that the resulting code doesn't need to be horrible. I am willing to live with overall worse looking code if that saves me having to write a lot of `skip` annotations (because for me the most important thing is to not have to worry about formatting at all). 

The `stdsimd` crate is not a typical crate, so such an option shouldn't be the default, and probably it is not worth it to implement it, but I would personally find it handy for this particular crate.
