### ISSUE TITLE
Unwanted reformatting of large string literals

### ISSUE THREAD

**Issue by Wilfred** [rust-lang-nursery/rustfmt#202]
Given the Rust code:

``` rust
#[test]
fn compile_empty_program() {
    let result = get_result();
    let expected = "; ModuleID = \'foo\'

; Function Attrs: nounwind
declare void @llvm.memset.p0i8.i32(i8* nocapture, i8, i32, i32, i1) #0

declare i32 @write(i32, i8*, i32)

declare i32 @putchar(i32)

declare i32 @getchar()

define i32 @main() {
entry:
  ret i32 0
}

attributes #0 = { nounwind }
";
    assert_eq!(result, CString::new(expected).unwrap());
}
```

Rustfmt produces:

``` rust

#[test]
fn compile_empty_program() {
    let result = get_result();
    let expected = "; ModuleID = \'foo\'\n\n; Function Attrs: nounwind\ndeclare void \
                    @llvm.memset.p0i8.i32(i8* nocapture, i8, i32, i32, i1) #0\n\ndeclare i32 \
                    @write(i32, i8*, i32)\n\ndeclare i32 @putchar(i32)\n\ndeclare i32 \
                    @getchar()\n\ndefine i32 @main() {\nentry:\n  ret i32 0\n}\n\nattributes #0 = \
                    { nounwind }\n";
    assert_eq!(result, CString::new(expected).unwrap());
}
```

The two strings are equivalent, but the initial string is much more readable. What do you think?

**Comment by nrc** [comment]
I think we should avoid formatting strings where the formatting is intentional. I think an indicator of that might be non-escaped newlines. There are probably other heuristics we could use too. There should also be an option for whether to reformat strings (if there isn't already).

**Comment by marcusklaas** [comment]
The option was added by @sinhpham. Should we keep this open to track progress on heuristics?

**Comment by nrc** [comment]
Yeah, lets keep it open, I would like to add that heuristic.

**Comment by marcusklaas** [comment]
Just thinking: maybe we should return `None` instead of `Some(original_lit)` to prevent reformatting parent expressions and possibly messing things up.

**Comment by sinhpham** [comment]
Should we have a format_strings option of "All", "None" and "Auto"? "Auto" should be the default but we let the user choose to force format all he has really badly formatted code.

**Comment by nrc** [comment]
We could, it sounds useful. OTOH, I would be happy to wait and see if it is needed before adding it.

**Comment by Wilfred** [comment]
Dumb question: do we need to add the heuristic?

If the default heuristic is "don't reformat strings when they contain non-escaped newlines", how is that different from a default of "don't reformat strings"?

**Comment by nrc** [comment]
Fixed with no options set.
