### ISSUE TITLE
Skip attribute should apply to attributes

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#2033]
e.g, https://github.com/rust-lang-nursery/rustfmt/issues/1987#issuecomment-330995380

**Comment by jugglerchris** [comment]
Hi.  I started to look at this as an issue to dip into.  As far as I can tell `#[rustfmt_skip]` *does* apply to attributes (at the same time as the item the attributes apply to).  For example, running rustfmt over:

```rust
#[cfg(
"foo")]
fn
main() {}
```

turns into:

```rust
#[cfg("foo")]
fn main() {}
```

But adding the skip attribute:

```rust
#[rustfmt_skip]
#[cfg(
"foo")]
fn
main() {}
```

causes rustfmt not to change anything.  (Apparently the `#[rustfmt_skip]` can come after the other attribute).

Should it be doing something different?

**Comment by nrc** [comment]
Ah, right, no skipping does not (yet) skip the width check.

We just need a test to close this issue.
