### ISSUE TITLE
Option for always indenting match arm body?

### ISSUE THREAD

**Issue by osa1** [rust-lang-nursery/rustfmt#2039]
I recently realized that inconsistent indentation in match arm bodies make reading harder. Here are some examples of this:

```rust
match ... {
    Some(...) => expr1,
    None => expr2
}

match ... {
    Some(...) => {
        body
    }
    None => expr2
}
```

What I'd really like is consistently indenting all bodies:

```rust
match ... {
    Some(...) =>
        expr1,
    None =>
        expr2
}

match ... {
    Some(...) => {
        body
    }
    None =>
        expr2
}
```

I'm wondering if adding a configuration option for this would be acceptable. Because we don't need to check anything about the body for deciding to indent it in a new lines it won't add any costly checks (just a flag check).

**Comment by nrc** [comment]
In general, we try to avoid indentation without blocks (e.g., we always require a block for an `if` statement), so I'd rather not do this. We could though have a flag for always using a block with a match arm

**Comment by osa1** [comment]
> In general, we try to avoid indentation without blocks

Hmm, this is interesting. It seems like rustfmt currently doesn't indent this expression (but indents subexpressions):

```
    match foo {
        Some(x) => foo.bar.baz.test.x.y.z.a.s.d.fasdfasdf.asdfads.fasd.fasdfasdf.dfasfdsaf()
    }
```

output:

```
    match foo {
        Some(x) => foo.bar
            .baz
            .test
            .x
            .y
            .z
            .a
            .s
            .d
            .fasdfasdf
            .asdfads
            .fasd
            .fasdfasdf
            .dfasfdsaf(),
    }
```

I'd argue that this is hard to read and I'd rather have the whole expression indented. (FWIW my flag does this because it indents all right-hand sides consistently)

What's wrong with indenting non-blocks?

> We could though have a flag for always using a block with a match arm

This adds a lot of noise when you have a match like:

```rust
        let cursor_x =
            match self.nibble_cursor {
                NibbleCursor::MS =>
                    cursor_x,
                NibbleCursor::LS =>
                    cursor_x + 1,
            };
```

it becomes:

```rust
        let cursor_x =
            match self.nibble_cursor {
                NibbleCursor::MS => {
                    cursor_x
                }
                NibbleCursor::LS => {
                    cursor_x + 1
                }
            };
```

but it's still better than inconsistent indentation IMO. I don't know what makes this flag more welcome than my flag but I'm fine with implementing this if my flag is unacceptable for some reason.
