### ISSUE TITLE
Different formatting for equal "where" bounds

### ISSUE THREAD

**Issue by omni-viral** [rust-lang-nursery/rustfmt#2040]
I have a few impls with equal "where" bounds and I'd like to see equal output of rustfmt for them.
Here the code: https://gist.github.com/omni-viral/aa658f12f6d82b928e6ab65aafd4a102
Rustfmt makes each bound on separate line for impls with `'a`.
If I remove `'a` rustfmt produce same result as for 3rd impl. Which should be (IMHO) produced for first two impls with `'a`

**Comment by topecongiro** [comment]
I think this if fixed on the latest rustfmt-nightly (nightly-0.2.8). Could you please try with it?

**Comment by omni-viral** [comment]
`rustfmt --version` tells me `nightly-0.9.0`

**Comment by omni-viral** [comment]
Yeap. Thanks!
