### ISSUE TITLE
braces on same line as where clause for empty struct

### ISSUE THREAD

**Issue by tspiteri** [rust-lang-nursery/rustfmt#2053]
For the empty `struct` below, the braces are on the same line as the `where` clause, after the comma. I think they should be on a new line.

```rust
struct Empty<T>
where
    Constraint: T, {}
```

**Comment by dangets** [comment]
This seems to go against this test:
https://github.com/rust-lang-nursery/rustfmt/blob/master/tests/target/item-brace-style-same-line-where.rs#L36
(Correct me if I'm wrong)

**Comment by tspiteri** [comment]
Yes, it seems to be intentional. I think it looks strange, but that's subjective, and if it's intentional it's not really a bug. So I'm closing this.
