### ISSUE TITLE
Support for rpath instead of DYLD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang-nursery/rustfmt#2054]
I don't know if this is actually a `cargo` issue rather than `rustfmt` issue, but here goes...

Supposedly (https://github.com/rust-lang/cargo/issues/4421#issuecomment-326110997) `DYLD_LIBRARY_PATH` is no longer the approved way to link libraries, as it requires turning off System Integrity Protection, and `@rpath` is the mandated way to accomplish such dynamic linkage going forward.

Is there a way that `rustfmt` can adapt to such a world? E.g. by invoking [`install_name_tool`](https://blogs.oracle.com/dipol/dynamic-libraries,-rpath,-and-mac-os) to point to the installed version of libsyntax during installation?

**Comment by pnkfelix** [comment]
(Full disclosure: I did not read the [tips](https://github.com/rust-lang-nursery/rustfmt#tips) in the readme when I first tried to use `rustfmt` after doing `cargo install rustfmt`; the error I subsequently got is what led me to discover `install_name_tool` which I successfully used to get `rustfmt` working on my own system. but of course that was manual hacking, not a general purpose patch to `rustfmt` and/or `cargo` to automate such a process for all users...)

**Comment by nrc** [comment]
The plan for rustfmt is to install with rustup, which I think addresses this issue. That is tracked elsewhere. It would be nice if we could work when build from source too.

**Comment by topecongiro** [comment]
rustfmt does not use `rustc_private` anymore, so this should not be an issue anymore.
