### ISSUE TITLE
cargo fmt --all does not execute on procedural macro crates

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2056]
For example in the https://github.com/rust-lang-nursery/stdsimd library there are a couple of procedural macro crates inside `stdsimd-test`. Executing `cargo fmt --all` on the root directory does not run `rustfmt` inside these crates.

**Comment by topecongiro** [comment]
rustfmt uses `cargo metadata --no-deps` to search for targets. Currently it only reads crates under the `"targets"` key. It should format the crates with the "dependencies" key which are local as well.
