### ISSUE TITLE
Error: Decoding config file failed

### ISSUE THREAD

**Issue by valarauca** [rust-lang-nursery/rustfmt#2057]
### What I did

```
cargo install rustfmt --force
cargo fmt
```

### What I expected:

cargo fmt to run

### What I got

```
Error: Decoding config file
```

I don't have a `rustfmt.toml`, I mean I _do_ in my `~/.cargo/registry/src/github.com-[base64]` for a few projects, but nowhere else.

What is up?

**Comment by nrc** [comment]
We look in all directories up from the current directory to the root for a config file, but I expect you're not in a subdir of the directory you give.

You could try using nightly rustfmt (`cargo install rustfmt-nightly --force`), see if that helps.

**Comment by valarauca** [comment]
Issue is on my end. Sorry for opening this :\
