### ISSUE TITLE
rustfmt behavior with generated code

### ISSUE THREAD

**Issue by ameets** [rust-lang-nursery/rustfmt#2059]
I've been using [`prost`](https://github.com/danburkert/prost) recently, and found that `rustfmt` complains about the generated code (particularly around documentation format). I would have expected rustfmt to ignore the generated code added to the project with `include!()`. 

The proto files I'm using are shared so it doesn't make sense to enforce rust-style on the `.proto` files. Is there a way to exclude certain modules from format checking?

**Comment by nrc** [comment]
Interesting. Rustfmt runs on pre-macro-expanded code, so it should ignore anything brought in by `include!`.

**Comment by nrc** [comment]
Could you try and create a minimal test case please?

**Comment by ameets** [comment]
Will do!
