### ISSUE TITLE
rustfmt takes way too long to format a long chain of binary operations

### ISSUE THREAD

**Issue by saethlin** [rust-lang-nursery/rustfmt#2065]
Programming along, and suddenly I notice that rustfmt isn't fixing my horrible formatting. I opened up `top` and found a few rustfmt processes at 100%. I think it's something to do with this bunch of `|`:
https://github.com/saethlin/tinygui/blob/master/src/window.rs#L23

**Comment by saethlin** [comment]
I think this is a case of exponential blowup. With 20 operands in the chain rustfmt takes ~7 seconds to run, at 21 operands it takes ~15, at 22  it takes ~30, at 23 it takes ~1 minute...

**Comment by saethlin** [comment]
I can confirm, this is gone on the latest nightly. Guess maybe I should just use all nightly tools by default...

**Comment by topecongiro** [comment]
Awesome, thank you!
