### ISSUE TITLE
rustfmt-nightly transforms code so that it doesn't compile

### ISSUE THREAD

**Issue by dimbleby** [rust-lang-nursery/rustfmt#2085]
Recent versions of `bindgen` produce highly unformatted code, in the expectation that if you care about this you'll `rustfmt` it.

However, doing so transforms compiling code into non-compiling code.

In particular, this line:

```
# [ repr ( C ) ] # [ derive ( Copy , Clone ) ] pub union ares_in6_addr__bindgen_ty_1 { pub _S6_u8 : [ :: std :: os :: raw :: c_uchar ; 16usize ] , _bindgen_union_align : [ u8 ; 16usize ] , } # [ repr ( C ) ] pub struct ares_addrttl { pub ipaddr : in_addr , pub ttl : :: std :: os :: raw :: c_int , }
```

is transformed into this:

```
#[repr(C)]
#[derive(Copy, Clone)]; 16usize ] , }#[repr(C)]
  pub struct ares_addrttl {
      pub ipaddr: in_addr,
      pub ttl: ::std::os::raw::c_int,
  }
```

Oops.

```
$ rustfmt --version
0.9.0-nightly ( )
```

**Comment by topecongiro** [comment]
This is a known issue, and should be fixed by using the latest rustfmt-nightly. Could you plese try with it?

**Comment by dimbleby** [comment]
Ack.

Please publish!  It's too late for me, but no-one else need spend time on this...

**Comment by topecongiro** [comment]
Thanks!

It is published as `rustfmt-nightly` :)
You could install it via `cargo install rustfmt-nightly --force`. For more info, please read README.md.

**Comment by dimbleby** [comment]
aargh, that's exactly what I thought I did ... but checking my command history I see that indeed I installed `rustfmt` and not `rustfmt-nightly`.  Crap.

Thanks anyway!
