### ISSUE TITLE
Latest version (0.2.10) either hangs or crashes

### ISSUE THREAD

**Issue by torkleyy** [rust-lang-nursery/rustfmt#2094]
After updating my Rust version (nightly, `rustc 1.23.0-nightly (d9f124965 2017-10-27)`) and force installing `rustfmt-nightly`, I can't use `cargo fmt` anymore.

After running `cargo fmt`, I sometimes get

```
No such file or directory (os error 2)
usage: cargo fmt [options]

Options:
    -h, --help          show this message
    -q, --quiet         no output printed to stdout
    -v, --verbose       use verbose output
    -p, --package <package>
                        specify package to format (only usable in workspaces)
        --all           format all packages (only usable in workspaces)

This utility formats all bin and lib files of the current crate using rustfmt. Arguments after `--` are passed to rustfmt.
```

or in most cases it just runs forever.

**Comment by topecongiro** [comment]
Published 0.2.11.

**Comment by torkleyy** [comment]
Unfortunately, it still doesn't work. While there's no IO error anymore, it does not complete.

**Comment by topecongiro** [comment]
Thank you, just published 0.2.12.

**Comment by torkleyy** [comment]
Thanks, it works now. One thing I have noticed is that it seems to take longer than before (6 seconds for `cargo fmt --all` and one second for `cargo fmt`).

**Comment by torkleyy** [comment]
@nrc Could you fix the issue with long formatting times?
