### ISSUE TITLE
A struct with `where` but no generic type parameters confuses rustfmt

### ISSUE THREAD

**Issue by xfix** [rust-lang-nursery/rustfmt#2103]
The following code:

```rust
struct X where i32: Sized {
    x: i32,
}
```

Generates following output on the Rust Playground:

```rust
struct X
struct X
where
    i32: Sized,
{
    x: i32,
}
```

Which is invalid. This code isn't particularly useful due to lack of generic type parameters, but the original code is valid Rust code that is transformed into an invalid one.

**Comment by adeschamps** [comment]
I think I've fixed this. I'm just tidying up and running tests.
