### ISSUE TITLE
Explicitly enumerate limitations

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#2109]
In the README or somewhere similarly prominent we should enumerate the known limitations of Rustfmt.

For 1.0, the limitations I'm aware of:

* code must parse
* whole programs only (we can do better than this, but this is all we 'guarantee'
* we don't touch comments
* macros might be sub-optimally formatted
* no guarantees if there are wide unicode chars (#6), but things should mostly work
* there might be bugs, of course, because software

**Comment by topecongiro** [comment]
* we cannot format some expressions (e.g. method chain and binary operations) with comments
