### ISSUE TITLE
Visibility clause duplicated into named unit struct

### ISSUE THREAD

**Issue by stoklund** [rust-lang-nursery/rustfmt#2110]
Examples with `rustfmt` 0.9.0-nightly:

```
$ echo "pub(super) struct Foo();" | rustfmt
pub(super) struct Foo(super);
$ echo "pub(crate) struct Foo();" | rustfmt
pub(crate) struct Foo(crate);
$ echo "pub(in self) struct Foo();" | rustfmt
pub(self) struct Foo(in self);
```

**Comment by nrc** [comment]
Could you try this with rustfmt-nightly please? 0.9 is rather old now. (You'll need to force install `rustfmt-nightly` from Cargo).

**Comment by topecongiro** [comment]
This still happens with both rustfmt-nightly 0.2.13 and the latest master.
