### ISSUE TITLE
format of import names with trailing line comment breaks code

### ISSUE THREAD

**Issue by Zteve** [rust-lang-nursery/rustfmt#2111]
```
use super::{
    SCHEMA_VERSIONS,
    LodaModel,
    ModelProperties,
    StringMap,
    ModelSelector,
    RequestDescription,
    MethodDescription,
    ModelBehaviour,
    ModelRequestGraph,
    DelayChoice,
    Holding,
    Destinations,
    ModelEdges,
    Switch,
    //    ModelMetaData,
    //    Generated,
    //    SecondsString,
    //    DateString,
    //    ModelConfiguration,
    //    ModelRequests,
    //    RestResponse,
    //    RestResponseCode,
    //    UniformHolding
};
```
got reformatted to:
```
use super::{DelayChoice, Destinations, Holding, LodaModel, MethodDescription, ModelBehaviour, ModelEdges,
            ModelProperties, ModelRequestGraph, ModelSelector, RequestDescription, SCHEMA_VERSIONS, StringMap,
            Switch 
    //    ModelMetaData,
    //    Generated,
    //    SecondsString,
    //    DateString,
    //    ModelConfiguration,
    //    ModelRequests,
    //    RestResponse,
    //    RestResponseCode,
    //    UniformHolding};
```
with polite error message:
```
Rustc version 1.21.0 is current.

Rustfmt failed at /Users/spowell/sj/loda-runna/src/model/accessors/mod.rs:10: left behind trailing whitespace (sorry)
```
which apologises for the minor offence but fails to notice the code now won't compile.

Problem appears to be that floating the closing brace up should by-pass any intervening trailing line comments.  If the last lines were
```
    Switch,  //    UniformHolding
};
```
then it works (but rather peculiarly):
```
use super::{DelayChoice,
            Destinations,
            Holding,
            LodaModel,
            MethodDescription,
            ModelBehaviour,
            ModelEdges,
            ModelProperties,
            ModelRequestGraph,
            ModelSelector,
            RequestDescription,
            SCHEMA_VERSIONS,
            StringMap,
            //    ModelMetaData,
            //    Generated,
            //    SecondsString,
            //    DateString,
            //    ModelConfiguration,
            //    ModelRequests,
            //    RestResponse,
            //    RestResponseCode,
            Switch /*    UniformHolding */};
```
With no grouping of names and converting the comment.

Possibly relevant fmt non-default options:
```
                  item_brace_style = "AlwaysNextLine"
            reorder_imported_names = true
                   reorder_imports = true
```

**Comment by topecongiro** [comment]
The options are irrelevant here. From the error message, looks like you are using the older version of rustfmt (in the latest rustfmt, there are no apologies, but with slightly detailed error messages).

With the latest rustfmt-nightly (0.2.13), we have a different error:
```rust
use super::{DelayChoice, Destinations, Holding, LodaModel, MethodDescription, ModelBehaviour,
            ModelEdges, ModelProperties, ModelRequestGraph, ModelSelector, RequestDescription,
            StringMap,
            Switch 
    //    ModelMetaData,
    //    Generated,
    //    SecondsString,
    //    DateString,
    //    ModelConfiguration,
    //    ModelRequests,
    //    RestResponse,
    //    RestResponseCode,
    //    UniformHolding,
            SCHEMA_VERSIONS};
```
there is a trailing whitespace after `Switch`, and the code won't compile anymore.

**Comment by topecongiro** [comment]
@Zteve FWIW you may be interested in the following options:
```toml
imports_indent = "Block"
imports_layout = "Vertical"
```

**Comment by Zteve** [comment]
Thanks @topecongiro : hmm, I thought I was running with the nightly build of rustfmt.  Must check my setup again :-(

**Comment by Zteve** [comment]
I have updated my nightly toolchain (not my default, which is a stable toolchain). Then I build rustfmt as follows:
```
rustup run nightly cargo install rustfmt --force
```
and (after a few minutes and some encouraging messages saying rustfmt and cargo-fmt have been replaced) I see this:
```
$ rustfmt --version
0.9.0-nightly ( )
```
Why isn't this the latest nightly version?  What have I forgotten to do?

**Comment by topecongiro** [comment]
To get the latest, you need to install `rustfmt-nightly`, not `rustfmt`. More on README.md.

**Comment by Zteve** [comment]
OK I'm there now.  Just a note: why is `SCHEMA_VERSIONS` placed at the end of the list? In the previous version of `rustfmt` it collated before `StringMap`.  Have the order rules changed?

**Comment by topecongiro** [comment]
Yes, we split items into four groups and sort them in the following order:

1. `self`
2. `lower_snake_case`
3. `CamelCase`
4. `UPPER_CASE`

and within each group items are sorted alphabetically.
