### ISSUE TITLE
[syntex] space between type and ; breaks formatting

### ISSUE THREAD

**Issue by buntpfotenkatzchen** [rust-lang-nursery/rustfmt#2122]
The following code `union foo { bar: [ char ; 4usize ] }` is formatted to `; 4usize ] }`.
Removing the space between `char` and `;` fixes it.

The issue originates from trying to run bindgen with a library including `/usr/include/bits/pthreadtypes.h`.

**Comment by nrc** [comment]
Is this a problem with rustfmt-nightly, or only the Syntex branch?

**Comment by sycoso** [comment]
It's only the Syntex-branch, rustfmt-nightly works

**Comment by topecongiro** [comment]
Now that rustfmt-nightly is available on the stable channel via rustup, I am going to close this issue.
