### ISSUE TITLE
wrap_comments does not respect normalize_comments

### ISSUE THREAD

**Issue by mqudsi** [rust-lang-nursery/rustfmt#2123]
When `rustfmt test.rs` is executed on the following file with `wrap_comments = true`, the results are not correct.

Input:

```rust
//this comment is not more than 80 characters long
//interestingly enough, this line isn't either.

fn main() {
    println!("Hello!");
    println!("Goodbye!");
}
```

Output:

```rust
// this comment is not more than 80 characters long
// interestingly enough, this line isn't either.

fn main() {
    println!("Hello!");
    println!("Goodbye!");
}
```

**Comment by topecongiro** [comment]
I see no problem here...  if you don't mind, could you explain what is expected please ?

**Comment by mqudsi** [comment]
Sure, sorry about that.

The default is `normalize_comments = false` and yet `rustfmt` takes `//comment` and changes it to `// comment`, injecting a space between the leading `//` and the comment body. That should strictly be within the domain of `normalize_comments` and not `wrap_comments`. 

`wrap_comments` should probably only kick in when the line length is exceeded, and even then, it should keep the existing comment style (i.e. `/* ... */` stays `/* ... */` and `// comment` stays `// comment`).

**Comment by nrc** [comment]
To put it another way, changing the comment from `//` to `// ` is a normalisation action, not a wrapping action.

**Comment by nrc** [comment]
To put it another way, changing the comment from `//` to `// ` is a normalisation action, not a wrapping action.

**Comment by topecongiro** [comment]
Ah, I see. Thank you for explaining!
