### ISSUE TITLE
won't parse generator `yield`

### ISSUE THREAD

**Issue by mikeyhew** [rust-lang-nursery/rustfmt#2163]
I was testing out the `futures-await` crate, and wanted to see what the macro-expanded code looks like. I tried to run rustfmt on the expanded code, but it looks like it doesn't support `yield` expressions yet.

Code:

```rust
#![feature(generators)]
fn main() {
    let g = || {
        yield;
    }
}
```

Errors:

```text
error: expected expression, found reserved keyword `yield`
 --> /Users/mikeyhew/Desktop/futures-await-stuff/foo.rs:4:9
  |
4 |         yield;
  |         ^^^^^

error: expected one of `.`, `;`, `?`, or an operator, found `}`
 --> /Users/mikeyhew/Desktop/futures-await-stuff/foo.rs:6:1
  |
5 |     }
  |      - expected one of `.`, `;`, `?`, or an operator here
6 | }
  | ^ unexpected token
```

rustfmt version: `0.9.0-nightly ( )`
rustc version: `rustc 1.23.0-nightly (aabfed5e0 2017-11-17)`

**Comment by mikeyhew** [comment]
For my case, I realized there were only 3 `yield` statements in the file, so I just commented them out for rustfmt's sake. It turns out the code that is generated by the `async` and `await` macros is actually pretty unreadable, even after you format it, because it has stuff like this:

```rust
let __e: Result<i32, i32> = {
    {
        Ok(
            1 + { // ... some huge block of code
```

So I guess this isn't a very motivating example. It probably makes sense to handle `yield` expressions at some point though, so I'll leave this issue open

**Comment by topecongiro** [comment]
Hi, thank you for filing an issue. `yield` is supported in rustfmt, you need to update to the latest version.
```
cargo install rustfmt-nightly --force
```

**Comment by mikeyhew** [comment]
Thanks @topecongiro! I vaguely recall reading that there were two versions of rustfmt, but must have forgotten. Should this issue be closed, then, or do you want to leave it open until it's implemented in the syntex version?

**Comment by topecongiro** [comment]
Yes, there is a syntex version and a libsyntax version. Most (or all) development goes to the latter. I am going to close this PR since the syntex version is unlikely to get updated. Thank you for trying rustfmt!
