### ISSUE TITLE
Compact where clause style

### ISSUE THREAD

**Issue by djc** [rust-lang-nursery/rustfmt#2168]
`rustfmt` currently reformats my code like this, which doesn't seem like an improvement to me:

```diff
-pub trait FetchBuilderMessages where Self: Sized {
+pub trait FetchBuilderMessages
+where
+    Self: Sized,
+{
```

I find the 3 extra lines a bad trade-off in this case for the length of the where clause. However, looking at the configurations relating to where clauses, keeping them on the same line for clauses below some length limit does not seem to be an option.

**Comment by nrc** [comment]
`where_single_line` gives you a more compact layout. We're unlikely to ever single-line a trait decl and `where` clause (though I think we do it if the body is empty too).

**Comment by djc** [comment]
The README states you're mostly willing to add config options to accomodate different styles. Can you explain why this case is different?

**Comment by nrc** [comment]
Ah, sorry, the README is somewhat out of date in this respect (I didn't even remember that was there). That certainly was the case, but now that we have mostly settled on an 'official' style and we are approaching a 1.0 release, we are trying to consolidate the options and reduce the overall number.

**Comment by LoganDark** [comment]
This is a blocker for me, preventing me from using rustfmt. I'm not sure if the official opinion in this has changed sometime in the last 5 years, but there is still no option for this so I'm just going to assume rustfmt intentionally does not support my code style.
