### ISSUE TITLE
Don't put function arguments that are easy to break up on separate lines

### ISSUE THREAD

**Issue by djc** [rust-lang-nursery/rustfmt#2169]
Here's a motivating example:

```diff
-        args.extend(match attr {
-            Attribute::Body => "BODY",
-            Attribute::Envelope => "ENVELOPE",
-            Attribute::Flags => "FLAGS",
-            Attribute::InternalDate => "INTERNALDATE",
-            Attribute::ModSeq => "MODSEQ",
-            Attribute::Rfc822 => "RFC822",
-            Attribute::Rfc822Size => "RFC822.SIZE",
-            Attribute::Uid => "UID",
-        }.as_bytes());
+        args.extend(
+            match attr {
+                Attribute::Body => "BODY",
+                Attribute::Envelope => "ENVELOPE",
+                Attribute::Flags => "FLAGS",
+                Attribute::InternalDate => "INTERNALDATE",
+                Attribute::ModSeq => "MODSEQ",
+                Attribute::Rfc822 => "RFC822",
+                Attribute::Rfc822Size => "RFC822.SIZE",
+                Attribute::Uid => "UID",
+            }.as_bytes(),
+        );
```

In this case, the top-level function call has a single argument, which itself has a clear way to lay out across multiple lines. In this case I'd prefer the more dense vertical style the initial line (like a `match` expression, a closure argument list or an `if-else` expression) is started on the same line. I'd prefer this to happen not only for single-argument calls, but probably in every place where this is true for the final argument and the rest of the invocation fits on a single line.

**Comment by djc** [comment]
Here's another, slightly more complicated example:

```diff
-            return Ok(Async::Ready((Client {
-                transport: wrapped.take().unwrap(),
-                state: ClientState::new(),
-            }, msg)));
+            return Ok(Async::Ready((
+                Client {
+                    transport: wrapped.take().unwrap(),
+                    state: ClientState::new(),
+                },
+                msg,
+            )));
```

**Comment by nrc** [comment]
The combining behviour is specified [here](https://github.com/rust-lang-nursery/fmt-rfcs/issues/61). There is a little bit of discussion at the end about doing this in function calls (we discussed further in a meeting).

There might be fine-grained ways we can improve formatting here, but there is nothing really actionable in this issue, so closing.
