### ISSUE TITLE
Even higher function argument density

### ISSUE THREAD

**Issue by djc** [rust-lang-nursery/rustfmt#2170]
This change does not seem like an improvement to me:

```diff
-    pub fn new(future: Send<ImapTransport>, state: ClientState,
-               request_id: RequestId, next_state: Option<State>) -> Self {
+    pub fn new(
+        future: Send<ImapTransport>, state: ClientState, request_id: RequestId,
+        next_state: Option<State>,
+    ) -> Self {
```

**Comment by nrc** [comment]
I assume you're already using some option here and you want a balanced number of items per line, rather than filling each line in turn? Or perhaps you want visual indent (set `indent_style` to `Visual`)?

**Comment by djc** [comment]
So is it possible to set `indent_style` to `Visual` for function arguments only?

**Comment by nrc** [comment]
> So is it possible to set indent_style to Visual for function arguments only?

No. We recently changed to having this option for lots of little places to being an all or nothing thing (there were lots of bugs where different options were used in different places, plus the list of options was getting overwhelming).
