### ISSUE TITLE
Combining short functions

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#2178]
This is a somewhat bad reformatting:

```
-        Ok(result.iter().map(|item| ls_util::rls_to_location(item)).collect())
+        Ok(
+            result
+                .iter()
+                .map(|item| ls_util::rls_to_location(item))
+                .collect(),
+        )
```

I would expect to have `Ok(result` on the first line to avoid orphaning `result`. I'm not sure under what circumstances we should do this. Maybe if the function name is <= the tab width? Or maybe if it is atomic (i.e., we wouldn't combine `foo.bar(` but would combine `foo(`.

cc @rust-lang-nursery/style

**Comment by steveklabnik** [comment]
Yeah, agreed.

> Maybe if the function name is <= the tab width? 

That wouldn't work here then :)

**Comment by nrc** [comment]
er, >, not <=, whoops
