### ISSUE TITLE
Only warn on TODOs in comments

### ISSUE THREAD

**Issue by marcusklaas** [rust-lang-nursery/rustfmt#219]
We currently warn on any match of `FIXME` or `TODO` in the source, even when they are part of code or string literals. Those shouldn't count.

**Comment by nrc** [comment]
What does `make tidy` do? I have a feeling it might pickup on TODOs in source code too. This should probably be an option. (My motivation is that I often put TODO in string literals which I want to get picked up).

**Comment by marcusklaas** [comment]
Ah, hadn't considered that. I do not know what tidy does. I'll figure it out.

**Comment by marcusklaas** [comment]
Let's close this until there is more expressed interest.

**Comment by oknozor** [comment]
I wish to express my interest. I am working on a Jira command line tool and this is picked up by rustfmt :

```rust
pub struct Workflow {
    pub wip: String,
    pub done: String,
    pub todo: String,
}
```

```
warning: found TODO
  --> /home/okno/_WORKSHOP/Rust/jetcli/jetlib/src/settings/shared.rs:30
   |
30 |     pub todo
   |

warning: found TODO
  --> /home/okno/_WORKSHOP/Rust/jetcli/jetlib/src/settings/shared.rs:36
   |
36 |             todo
   |

warning: rustfmt has failed to format. See previous 2 errors.
```

Would you consider fixing this ? I would be glad to help if you want to do it but I would need some guidance.
