### ISSUE TITLE
Apply 'small' heuristic to other expressions

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#2196]
We use a heuristic to use 'mixed' layout for match pattern when every clauses are 'small' ([fmt-rfcs/expressions.md](https://github.com/rust-lang-nursery/fmt-rfcs/blob/a5786c3cc8d0e42e9360a072b235c0635f691ae7/guide/expressions.md#line-breaking)). Could we apply a similar heuristic to other expressions, like function call or array? I think this is necessary especially for array now that `array_horizontal_layout_threshold` is gone.

**Comment by nrc** [comment]
I think we should be careful about using these heuristics, we often get comments from people who don't see why similar expressions get different formatting. We should only apply this where there is a clear win. I think for function calls we currently apply a simple width based heuristic and that could be improved by using a more involved 'small' heuristic.

I would like to apply something to arrays. Applying something close to the match heuristic might be a good start. Ideally we would do something to detect matrix-like arrays and e.g., format a 9 element array as 3 x 3. However, I don't know how this will work in practice (e.g., should a 6 element array be 2x3, 3x2, or 1x6?). Could be fun to investigate.

**Comment by nrc** [comment]
I think #2196 fixes everything we want to fix here
