### ISSUE TITLE
Text reflowing in comments breaks the formatting of doc examples

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2197]
For example, see [here](https://github.com/rust-lang-nursery/stdsimd/pull/218/files#diff-b4aea3e418ccdb71239b96952d9cddb6R67), where the code inside the documentation example is not properly indented anymore. `rustfmt` should either leave doc examples alone for now, or format their code properly. 

Image (proper text reflowing on the top, broken example on the bottom):

![screen shot 2017-11-27 at 21 49 54](https://user-images.githubusercontent.com/904614/33288544-f2e3ddf4-d3bc-11e7-8469-34fd37d7e136.png)

**Comment by nrc** [comment]
Are you using a config file, we should not be doing this by default.

**Comment by gnzlbg** [comment]
This one: https://github.com/rust-lang-nursery/stdsimd/blob/master/rustfmt.toml

**Comment by nrc** [comment]
`wrap_comments = true` is relevant here.

**Comment by nrc** [comment]
As an aside, given that stdsimd is an 'official' Rust project, I'd strongly suggest you use the default formatting style.

**Comment by gnzlbg** [comment]
> wrap_comments = true is relevant here.

Yes that's it.

> As an aside, given that stdsimd is an 'official' Rust project, I'd strongly suggest you use the default formatting style.

The reason it has a custom formatting style is that one maintainer argued that if we were going to use `rustfmt` he'd like it to reformat the library to fit in 79 columns.

The other maintainer did not have a strong opinion about this, and I don't care much about the formatting style as long as I don't have to think about it.

So if it would depend only on myself, I would just use the default style, but I must admit that I enjoy working on `stdsimd` more than on other libraries, and one of the reasons is the formatting style (or more accurately, I often get slightly annoyed at the 120 column wide formatting style in other libraries).
