### ISSUE TITLE
Rustfmt puts "C" ABI marker on extern type block

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#2204]
Input:

```Rust
#![feature(extern_types)]

extern {
    type Foo;
}

```

Output:

```Rust
#![feature(extern_types)]

extern "C" {
    type Foo;
}

```

I don't know if this is intentional/acceptable, but the [RFC](https://github.com/rust-lang/rfcs/blob/master/text/1861-extern-types.md) doesn't mention anything about specifying ABI for extern types.

**Comment by topecongiro** [comment]
It was discussed [here](https://github.com/rust-lang-nursery/fmt-rfcs/issues/52), and we already have a style  guide [here](https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/items.md#extern-items).
