### ISSUE TITLE
spaces_within_parens_and_brackets section is repeated 3 times

### ISSUE THREAD

**Issue by sunjay** [rust-lang-nursery/rustfmt#2220]
See: https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#spaces_within_parens_and_brackets

Each section has slightly different content. I'm not sure why that is or what is going on.

![screenshot from 2017-12-02 00-22-05](https://user-images.githubusercontent.com/530939/33512099-d9d5c8da-d6f6-11e7-97b6-d5b89d4a38f4.png)
![screenshot from 2017-12-02 00-21-43](https://user-images.githubusercontent.com/530939/33512100-d9e27ec2-d6f6-11e7-8e3a-ce639a6a53f1.png)

**Comment by nrc** [comment]
Three options got combined into one and I just did a blind search and replace here rather than merging the three sections. The examples ought to be combined.
