### ISSUE TITLE
error loading shared libraries libsyntax-e8e62c120d2d43f1.so

### ISSUE THREAD

**Issue by anna-liao** [rust-lang-nursery/rustfmt#2223]
On Ubuntu 16.04, I have tried running `cargo +nightly fmt` (it has worked for me this past week) and getting this error:

```
rustfmt: error while loading shared libraries: libsyntax-e8e62c120d2d43f1.so: cannot open shared object file: No such file or directory
```

**Comment by anna-liao** [comment]
And I have tried running: `export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH`

**Comment by thelearnerofcode** [comment]
Reinstall rustfmt with `cargo install --force rustfmt-nightly`.

**Comment by anna-liao** [comment]
This is the output I get:

<details>
  <summary>Click to expand</summary>
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rustfmt-nightly v0.2.17
  Installing rustfmt-nightly v0.2.17
 Downloading cargo_metadata v0.3.3
   Compiling cc v1.0.3
   Compiling getopts v0.2.15
   Compiling utf8-ranges v1.0.0
   Compiling num-traits v0.1.41
   Compiling unicode-segmentation v1.2.0
   Compiling libc v0.2.34
   Compiling lazy_static v0.2.11
   Compiling itoa v0.3.4
   Compiling dtoa v0.4.2
   Compiling term v0.4.6
   Compiling log v0.3.8
   Compiling diff v0.1.11
   Compiling serde v1.0.23
   Compiling regex-syntax v0.4.1
   Compiling void v1.0.2
   Compiling cfg-if v0.1.2
   Compiling semver-parser v0.7.0
   Compiling quote v0.3.15
   Compiling rustfmt-nightly v0.2.17
   Compiling rustc-demangle v0.1.5
   Compiling unicode-xid v0.0.4
   Compiling memchr v2.0.1
   Compiling strings v0.1.1
   Compiling backtrace-sys v0.1.16
   Compiling unreachable v1.0.0
   Compiling synom v0.11.3
   Compiling aho-corasick v0.6.4
   Compiling thread_local v0.3.4
   Compiling toml v0.4.5
   Compiling semver v0.8.0
   Compiling serde_json v1.0.7
   Compiling syn v0.11.11
   Compiling regex v0.2.3
   Compiling backtrace v0.3.4
   Compiling error-chain v0.11.0
   Compiling env_logger v0.4.3
   Compiling serde_derive_internals v0.17.0
   Compiling derive-new v0.5.0
   Compiling serde_derive v1.0.23
   Compiling cargo_metadata v0.3.3

  error[E0432]: unresolved import `syntax::ast::CrateSugar`
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/utils.rs:14:36
   |
14 | use syntax::ast::{self, Attribute, CrateSugar, MetaItem, MetaItemKind, NestedMetaItem,
   |                                    ^^^^^^^^^^ no `CrateSugar` in `ast`

error[E0432]: unresolved import `syntax::ast::CrateSugar`
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/items.rs:17:19
   |
17 | use syntax::ast::{CrateSugar, ImplItem};
   |                   ^^^^^^^^^^ no `CrateSugar` in `ast`

error[E0432]: unresolved import `ast::UseTreeKind`
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:44:14
   |
44 |     use ast::UseTreeKind::*;
   |              ^^^^^^^^^^^ Could not find `UseTreeKind` in `ast`

error[E0416]: identifier `Glob` is bound more than once in the same pattern
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:84:18
   |
84 |         (&Glob, &Glob) => Ordering::Equal,
   |                  ^^^^ used in a pattern more than once

error[E0408]: variable `Glob` is not bound in all patterns
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:85:9
   |
85 |         (&Simple(_), _) | (&Glob, &Nested(_)) => Ordering::Less,
   |         ^^^^^^^^^^^^^^^     ---- variable not in all patterns
   |         |
   |         pattern doesn't bind `Glob`

error[E0408]: variable `Glob` is not bound in all patterns
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:105:31
    |
105 |         (&Glob, &Simple(_)) | (&Nested(_), _) => Ordering::Greater,
    |           ----                ^^^^^^^^^^^^^^^ pattern doesn't bind `Glob`
    |           |
    |           variable not in all patterns

error[E0433]: failed to resolve. Could not find `UseTreeKind` in `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:142:18
    |
142 |             ast::UseTreeKind::Nested(ref items) => {
    |                  ^^^^^^^^^^^ Could not find `UseTreeKind` in `ast`

error[E0433]: failed to resolve. Could not find `UseTreeKind` in `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:145:18
    |
145 |             ast::UseTreeKind::Glob => {
    |                  ^^^^^^^^^^^ Could not find `UseTreeKind` in `ast`

error[E0433]: failed to resolve. Could not find `UseTreeKind` in `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:155:18
    |
155 |             ast::UseTreeKind::Simple(ident) => {
    |                  ^^^^^^^^^^^ Could not find `UseTreeKind` in `ast`

error[E0433]: failed to resolve. Could not find `UseTreeKind` in `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:187:18
    |
187 |             ast::UseTreeKind::Nested(ref items) if items.is_empty() && attrs.is_empty() => {
    |                  ^^^^^^^^^^^ Could not find `UseTreeKind` in `ast`

error[E0433]: failed to resolve. Could not find `UseTreeKind` in `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:301:17
    |
301 |     if let ast::UseTreeKind::Simple(rename) = tree.kind {
    |                 ^^^^^^^^^^^ Could not find `UseTreeKind` in `ast`

error[E0433]: failed to resolve. Could not find `UseTreeKind` in `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:331:22
    |
331 |     Some(if let ast::UseTreeKind::Simple(rename) = tree.kind {
    |                      ^^^^^^^^^^^ Could not find `UseTreeKind` in `ast`

error[E0412]: cannot find type `UseTree` in module `ast`
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:43:31
   |
43 | fn compare_use_trees(a: &ast::UseTree, b: &ast::UseTree, nested: bool) -> Ordering {
   |                               ^^^^^^^ not found in `ast`

error[E0412]: cannot find type `UseTree` in module `ast`
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:43:49
   |
43 | fn compare_use_trees(a: &ast::UseTree, b: &ast::UseTree, nested: bool) -> Ordering {
   |                                                 ^^^^^^^ not found in `ast`

error[E0531]: cannot find tuple struct/variant `Simple` in this scope
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:56:11
   |
56 |         (&Simple(ident_a), &Simple(ident_b)) => {
   |           ^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `Simple` in this scope
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:56:29
   |
56 |         (&Simple(ident_a), &Simple(ident_b)) => {
   |                             ^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `Simple` in this scope
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:85:11
   |
85 |         (&Simple(_), _) | (&Glob, &Nested(_)) => Ordering::Less,
   |           ^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `Nested` in this scope
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:85:36
   |
85 |         (&Simple(_), _) | (&Glob, &Nested(_)) => Ordering::Less,
   |                                    ^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `Nested` in this scope
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:86:11
   |
86 |         (&Nested(ref a_items), &Nested(ref b_items)) => {
   |           ^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `Nested` in this scope
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:86:33
   |
86 |         (&Nested(ref a_items), &Nested(ref b_items)) => {
   |                                 ^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `Simple` in this scope
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:105:18
    |
105 |         (&Glob, &Simple(_)) | (&Nested(_), _) => Ordering::Greater,
    |                  ^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `Nested` in this scope
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:105:33
    |
105 |         (&Glob, &Simple(_)) | (&Nested(_), _) => Ordering::Greater,
    |                                 ^^^^^^ not found in this scope

error[E0412]: cannot find type `UseTree` in module `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:139:23
    |
139 | impl Rewrite for ast::UseTree {
    |                       ^^^^^^^ not found in `ast`

error[E0412]: cannot find type `UseTree` in module `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:176:17
    |
176 |     tree: &ast::UseTree,
    |                 ^^^^^^^ not found in `ast`

error[E0412]: cannot find type `UseTree` in module `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:272:67
    |
272 |     pub fn format_import(&mut self, item: &ast::Item, tree: &ast::UseTree) {
    |                                                                   ^^^^^^^ not found in `ast`

error[E0412]: cannot find type `UseTree` in module `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:300:65
    |
300 | fn rewrite_nested_use_tree_single(path_str: String, tree: &ast::UseTree) -> String {
    |                                                                 ^^^^^^^ not found in `ast`

error[E0412]: cannot find type `UseTree` in module `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:330:46
    |
330 | fn rewrite_nested_use_tree_item(tree: &&ast::UseTree) -> Option<String> {
    |                                              ^^^^^^^ not found in `ast`

error[E0412]: cannot find type `UseTree` in module `ast`
   --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/imports.rs:421:20
    |
421 |     trees: &[(ast::UseTree, ast::NodeId)],
    |                    ^^^^^^^ not found in `ast`

error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.17/src/lib.rs:11:1
   |
11 | #![feature(rustc_private)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 29 previous errors

error: failed to compile `rustfmt-nightly v0.2.17`, intermediate artifacts can be found at `/tmp/cargo-install.wwHw5IwAPtrs`

Caused by:
  Could not compile `rustfmt-nightly`.

To learn more, run the command again with --verbose.
</details>

**Comment by sinkuu** [comment]
You are using stable compiler.

**Comment by anna-liao** [comment]
Thanks @sinkuu I switched to nightly as default with `cargo default nightly` and I don't get any errors.  I can just switch back to `cargo default stable` if I have any issues with `nightly`.  Previously, I had been running `cargo +nightly fmt` without any problems, but it just stopped working today.
