### ISSUE TITLE
Rename git-fmt

### ISSUE THREAD

**Issue by nox** [rust-lang-nursery/rustfmt#2230]
`rustfmt` is not a general tool, and thus `git-fmt` should be renamed to `git-rustfmt`.

**Comment by nrc** [comment]
This is a good idea, I'd also be amenable with merging it into cargo-fmt or rustfmt proper (or just removing it) - it is very much just an experiment at this stage.

**Comment by CaptainKraft** [comment]
Is this as simple as changing the bin name in Cargo.toml and renaming `git-fmt.rs` to `git-rustfmt.rs`?

Or should I remove that setting in Cargo.toml and the `.rs` file altogether?

**Comment by GabrielMajeri** [comment]
@nrc Can we close this issue now that #2335 has been merged?

**Comment by topecongiro** [comment]
@GabrielMajeri
