### ISSUE TITLE
An empty import + comment leaves a blank line

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#2256]
#### Input

```rust
// comment
use std::{};
use std::borrow::Cow;
```

#### Output

```rust
// comment

use std::borrow::Cow;
```

We should either remove the blank line or disallow removing an empty import with comment.

**Comment by Cyres** [comment]
```// comment
use std::borrow::Cow;```

Will also results in 
```// comment

use std::borrow::Cow;```

**Comment by topecongiro** [comment]
@Cyres Would you please tell us the version of rustfmt or any configuration option you used?

**Comment by topecongiro** [comment]
The first issue still persists. Moreover, the following example

```rust
/* comment */ use std::{};
/* comment */ use std::{};
```

will become

```rust
/* comment */
 
```

with comment removed and a trailing white-space on the second line.
