### ISSUE TITLE
Don't wrap block-like things in another block

### ISSUE THREAD

**Issue by vorner** [rust-lang-nursery/rustfmt#2262]
If I have a closure returning a struct literal, or a match arm producing a struct literal or a closure containing single match, all these things contain a natural block-like thing with a prefix. Rustfmt decides this is multi-line and wraps it in another block, like this:

```diff
             result⏎
                 .init(&mut result.slave.borrow_mut(), &mut (result.strategy)())⏎
-                .map_err(|factory| Error {⏎
-                    factory,⏎
-                    slave: None⏎
+                .map_err(|factory| {⏎
+                    Error {⏎
+                        factory,⏎
+                        slave: None,⏎
+                    }⏎
                 })?;⏎
```

That extra wrapping seems unneeded. Can I tell rustfmt to be content with just that block behind `Error`?

I'm not sure if go as far as accept a block inside a function or not, eg:

```rust
Err(Error {
  factory,
  slave: None,
})
```

**Comment by topecongiro** [comment]
FWIW rusfmt does combine a block-like expression inside a function if the function only has a single argument.
