### ISSUE TITLE
"PreferVisual" indent_style?

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang-nursery/rustfmt#2266]
I like the visual indent style:
```rust
fn main() {
    let v = something_short.do_stuff()
                           .do_more_stuff()
                           .map(|| {
                                    println!("Hello");
                                })
                           .collect()
                           .do_more_stuff();
}
```
But as the indentation and closures get longer, the closure body sometimes gets shifted all the way to the left and the following calls become "hanging in the air" (note the lack of `;` after `println!()` here, if I put `;` in the end rustfmt reports a line too long error):
```rust
fn main() {
    let v = something_very_long_and_complicated.do_stuff()
                                               .do_more_stuff()
                                               .map(|| {
        println!("An extremely long and informative message describing something interesting")
    })
                                               .collect()
                                               .do_more_stuff();
}
```
Perhaps a good idea would be to add a "PreferVisual" style which is able to fall back to the block style in these cases?
```rust
fn main() {
    let v = something_very_long_and_complicated
        .do_stuff()
        .do_more_stuff()
        .map(|| {
            println!("An extremely long and informative message describing something interesting")
        })
        .collect()
        .do_more_stuff();
}
```

**Comment by topecongiro** [comment]
We used to have a similar heuristic when the default style was visual. I think it got dropped when we switched the default indent style from visual to block, as it was fragile and complex.

**Comment by nrc** [comment]
Yeah, switching styles like this was pretty unpopular. It made formatting inconsistent and unpredictable. I don't think we'll bring back something like this.
