### ISSUE TITLE
Add `--version` to cargo-fmt

### ISSUE THREAD

**Issue by shepmaster** [rust-lang-nursery/rustfmt#2269]
I like to run `toolname --version` in my CI scripts to make future debugging easier. As I'm using `cargo fmt`, it would be nice to be able to run `cargo fmt --version`:

```
# cargo +nightly-2017-11-07 fmt --version
Unrecognized option: 'version'
usage: cargo fmt [options]
```

As a workaround, I can get the version of the `rustfmt` binary, but then all future readers have to remember that `rustfmt` ~= `cargo fmt`. I can also do `cargo +nightly-2017-11-07 fmt -- --version`, but the straight-forward way would be more obvious.

**Comment by topecongiro** [comment]
FWIW `cargo fmt -- --version` works.
