### ISSUE TITLE
Binary operator can duplicate itself in certain situations in a macro

### ISSUE THREAD

**Issue by xfix** [rust-lang-nursery/rustfmt#2290]
Example code:

```rust
m!(a: b!(c!) % f);
```

Is formatted into:

```rust
m!(a: b!(c!) % % f);
```

Which is not identical.

Noticed with https://github.com/xfix/advent-of-code-2017/blob/master/day18/src/main.rs with `>>` operator, and simplified.

This happens on playpen.

**Comment by topecongiro** [comment]
This is likely due to a bug in libsyntax parser.

**Comment by topecongiro** [comment]
Fixed on `rustc 1.24.0-nightly (7eb64b86c 2017-12-20)`.
