### ISSUE TITLE
Rustfmt adds extra semicolon after type_macro invocation

### ISSUE THREAD

**Issue by Marwes** [rust-lang-nursery/rustfmt#2294]
### Before
```rust
macro_rules! test {
    ($($t: expr)*) => { i32 }
}

type Test = test!{
    123
};
```

### After

```rust
macro_rules! test {
    ($($t: expr)*) => { i32 }
}

type Test = test!{
                123
            };;
```

This unfortunately breaks the code since `;;` is invalid.

**Comment by topecongiro** [comment]
This is similar to #2290. Once https://github.com/rust-lang/rust/pull/46835 gets merged this will be fixed by `rustup update nightly && cargo install --force rustfmt-nightly`.

**Comment by topecongiro** [comment]
Closed via https://github.com/rust-lang/rust/pull/46835 and #2297.
