### ISSUE TITLE
use_small_heuristics = false gives a mix of zero width and max width settings

### ISSUE THREAD

**Issue by philipc** [rust-lang-nursery/rustfmt#2299]
Previously I was using the individual width settings to stop rustfmt from splitting things across multiple lines at less than 100 characters width. This was changed for #1984. I'm fine with having a single setting to configure all of this, but the problem is that `WidthHeuristics::null()` specifies max width for half the settings, and 0 width for the others, which doesn't make much sense to me, because it means some things are put on a single line, and others are always split over multiple lines, whereas my goal is to stop needlessly splitting lines. Can we have an intermediate setting that only sets the max width values, and leaves the others at default width?

Also related, `rustfmt --config-help` documents `width_heuristics`, and you can set it in the config without any warnings about unknown settings, but the values have no effect.

**Comment by nrc** [comment]
The motivation for 0 vs max width is that for each heuristic, the effect is that the heuristic is turned off. If that is not the case, then there is a bug we should fix. So setting `use_small_heuristics` to `false` should give you what you want. Is that not the case?

**Comment by philipc** [comment]
It does turn the heuristics off, but there's two classes of heuristics:
- those where normally the line would be longer, but we use heuristics to break earlier
- those where normally it would be on separate lines, but we use heuristics to put it all on one line

I want an option to only disable heuristics for the first class.

**Comment by radix** [comment]
@philipc Hi, can you take a look at #2437 and #2447? Would you use the proposed idea in those?

**Comment by philipc** [comment]
@radix That's now cramming long if statements and structs on one line, so I'd probably go with the default heuristics still.

**Comment by nrc** [comment]
This is basically a dup of #2437. We've also changed the values to `off` and `default` which I hope is clearer
