### ISSUE TITLE
`rustfmt --config-help` should not display hidden options

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#2300]
such as `width_heuristics`.

reported in #2299

**Comment by kbacha** [comment]
@nrc How do we know which options are hidden?

**Comment by nrc** [comment]
@kbacha there are some comments in config.rs, iirc, it's only like three options

**Comment by vishalsodani** [comment]
I would like to take a shot at this. I see 3 options verbose, file_lines and width_heuristics mentioned under "not user facing". 

I have attempted to hide these 3 options on running 'config-help' by modifying print_docs(). I added a vector -
   `let bypass = vec!["verbose", "file_lines", "width_heuristics"];`
and just checked 
  `if !bypass.contains(&name_raw)`

Is this the way to go?

**Comment by nrc** [comment]
@vishalsodani sorry for the late reply, I think that approach is fine, however, I would make `bypass` a `const` in config.rs, rather than a local variable (which means using an array, rather than `Vec`).

**Comment by vishalsodani** [comment]
@nrc Thanks! Do I need to write test for this change? If yes, where or how do I go about writing the test?

**Comment by nrc** [comment]
@vishalsodani nah, I don't think this needs a test
