### ISSUE TITLE
Removal of two or more empty consecutive lines

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang-nursery/rustfmt#2312]
I am not sure if this was discussed before (I didn't find an issue...), but I am quite surprised that rustfmt is pretty aggressive in removing empty lines. I often use two or even three consecutive empty lines in my code to clearly separate different sections. But those are always shrunken to only one empty line. 

Is this expected behavior? Shouldn't this be at least configurable? :)

**Comment by topecongiro** [comment]
This could be configured via `blank_lines_upper_bound`. The default value is 1, hence empty lines are trimmed into a single line. Please set this to larger value.

We need an example on this in Configurations.md.

**Comment by CaptainKraft** [comment]
I will work on the Configurations.md example.
