### ISSUE TITLE
Sort order when one is a prefix of the next

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rustfmt#2315]
Rustfmt-nightly 0.3.4 swaps the following two lines.

```rust
extern crate proc_macro;
extern crate proc_macro2;
```

Maybe it's just me and this is not a common preference, but I find the original order (as shown) more pleasant.

**Comment by topecongiro** [comment]
The span for `ast::Item` includes the trailing comma, which makes the comparison wrong.
