### ISSUE TITLE
`intrinsics` -- `as *mut T` not always put on the same line in libarena/lib.rs (on Rust repo)

### ISSUE THREAD

**Issue by Kagamihime** [rust-lang-nursery/rustfmt#2324]
Hello,

I have tried to submit a PR ( https://github.com/rust-lang/rust/pull/47069 ) on the Rust repo after running rustfmt on the libarena crate but it seems like there are some formatting issues:
* on lines 136-137 the construct `intrinsics` -- `as *mut T` has been split on two lines
* but on line 367 the construct `intrinsics` -- `as *mut u8` has been put on the same line and there is a comma added after `as *mut u8`

It seems as if it is not an expected result, so I've decided to submit this issue (my very first issue).

I've used rustfmt-nightly 0.3.4 without options to get this.

**Comment by topecongiro** [comment]
Reduced example:

#### Input
```rust
fn main() {
    self.ptr.set(intrinsics::arith_offset(self.ptr.get() as *mut u8, 1) as *mut T);
    self.ptr.set(intrinsics::arith_offset(self.ptr.get(), mem::size_of::<T>() as isize) as *mut u8);
}
```

#### Output
```rust
fn main() {
    self.ptr
        .set(intrinsics::arith_offset(self.ptr.get() as *mut u8, 1)
            as *mut T);
    self.ptr
        .set(intrinsics::arith_offset(self.ptr.get(), mem::size_of::<T>() as isize) as *mut u8);
}
```
