### ISSUE TITLE
rustfmt working differently on OS X vs Linux?

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/rustfmt#2325]
Look at this build: https://travis-ci.org/steveklabnik/rustdoc/builds/323617392

It passes on Linux, but fails with a different diff on OS X. Very odd!

**Comment by topecongiro** [comment]
Looks like in macOS older version of rustfmt is being used. In rustfmt.sh, you are installing `rustfmt` (not `rustfmt-nightly`) when `rustfmt` binary is not found. Please update this script to install `rustfmt-nightly`.

I am not sure why there is a difference between two OS. It seems to me that in Linux rustfmt is included to nightly toolchain, whereas in macOS it is not.
Is there a time lag between two OS on when the nightly update occur? rustfmt had not been included to the recent nightly toolchain, but the PR to update rls and rustfmt got merged to rustc a few days ago. It could be the case that this change appeared in Linux earlier than macOS.

**Comment by steveklabnik** [comment]
>  In rustfmt.sh

This isn't being called; it's being installed as a component https://travis-ci.org/steveklabnik/rustdoc/jobs/323617394#L90

> rustfmt had not been included to the recent nightly toolchain, 

It does seem to be installing, via the logs, right?

**Comment by steveklabnik** [comment]
Deleting the cargo cache made the build pass. My guess is, rustfmt was cached, and for some reason it used the cached version instead of the real one? https://travis-ci.org/steveklabnik/rustdoc/jobs/323672242
