### ISSUE TITLE
Rustfmt wants to place pipe at the start of line with pattern alternative

### ISSUE THREAD

**Issue by vorner** [rust-lang-nursery/rustfmt#2333]
It's probably best seen with the diff:

```diff
@@ -97,15 +92,24 @@ impl Game {
         while let Some(event) = self.events.poll_event() {
             debug!("Event: {:?}", event);
             match event {
-                Event::Quit { .. } |
-                Event::KeyDown { keycode: Some(Keycode::Q), .. } => {
+                Event::Quit { .. }
+                | Event::KeyDown {
+                    keycode: Some(Keycode::Q),
+                    ..
+                } => {
                     if !self.state.stopped() {
                         self.state.stop();
                     }
                     return Ok(TopInstruction::Quit);
-                },
-                Event::KeyUp { keycode: Some(Keycode::Space), .. } |
-                Event::KeyUp { keycode: Some(Keycode::P), .. } => self.pause_toggle()?,
+                }
+                Event::KeyUp {
+                    keycode: Some(Keycode::Space),
+                    ..
+                }
+                | Event::KeyUp {
+                    keycode: Some(Keycode::P),
+                    ..
+                } => self.pause_toggle()?,
                 _ => (),
             }
         }
```

I believe it's nicer to place the `|` at the end of the preceding line, not at the start of the new one. It seems most of the examples everywhere seem to agree with me.

No rustfmt config (eg. all defaults), version `0.3.4-nightly (6714a44 2017-12-23)`.

It's this repository: https://github.com/vorner/thrust.

**Comment by nrc** [comment]
This was discussed in the formatting RFC process and we decided to always put binary operators (including `|` in match arms) at the start of the line.

**Comment by vorner** [comment]
Shouldn't the second following line be indented, then, if it's an operator? I mean, if I have a multiline statement with `+` operators, it'd look something like this:

```
stuff
    + stuff
    + stuff
```

not:

```
stuff
+ stuff
+ stuff
```

**Comment by nrc** [comment]
hmm, maybe it should. I filed https://github.com/rust-lang-nursery/fmt-rfcs/issues/115 to discuss

**Comment by cramertj** [comment]
Would it be possible to add a configuration option to disable this?

**Comment by cramertj** [comment]
@nrc That seems reasonable! Thanks for the explanation.
