### ISSUE TITLE
radare2 bindings + rust-bindgen - Error { repr: Custom(Custom { kind: Other, error: StringError("Internal rustfmt error") }) }

### ISSUE THREAD

**Issue by XVilka** [rust-lang-nursery/rustfmt#2334]
How to reproduce:
Download & install radare2: https://github.com/radare/radare2/blob/master/libr/include/r_core.h
```
cargo install rustfmt
cargo install rust-bindgen (from git)
bindgen --verbose /usr/local/include/libr/r_core.h -o /home/user/r_core.rs -- -I/usr/local/include/libr
Error { repr: Custom(Custom { kind: Other, error: StringError("Internal rustfmt error") }) }
```
See https://github.com/rust-lang-nursery/rust-bindgen/issues/1205

Rust file before formatting:
[r_core.rs.gz](https://github.com/rust-lang-nursery/rustfmt/files/1599414/r_core.rs.gz)

**Comment by topecongiro** [comment]
Would you please try with `rustfmt-nightly` instead of `rustfmt`? The former includes the latest updates, and should work with bindgen.

**Comment by XVilka** [comment]
This indeed fixed the issue.
