### ISSUE TITLE
How do we want to handle the scenarios where rustfmt overformats our strict strings

### ISSUE THREAD

**Issue by posix4e** [rust-lang-nursery/rustfmt#234]
https://github.com/Hoverbear/raft-rs/pull/108/files#diff-081cd1641766c14a997b0cdaf059fbcaR47             │
https://github.com/Hoverbear/raft-rs/pull/108/files#diff-dd3199debb92a22de8cd6431fe976573R42 

are examples

**Comment by topecongiro** [comment]
Triage: the above links are broken, so there is nothing we can do, unfortunately.
