### ISSUE TITLE
Two lines which are individually fine get merged into a line that is too long

### ISSUE THREAD

**Issue by shahn** [rust-lang-nursery/rustfmt#2342]
```
    #[cfg(feature = "serde")]
    bytes: [[u8; 17]; 5], // Same size as signature::ED25519_PKCS8_V2_LEN
```

gets turned into

`    #[cfg(feature = "serde")] bytes: [[u8; 17]; 5], // Same size as signature::ED25519_PKCS8_V2_LEN`

which violates rustfmt settings:

```
max_width = 80
comment_width = 80
```

**Comment by topecongiro** [comment]
cc #2201.

**Comment by nrc** [comment]
cc https://github.com/rust-lang-nursery/rustfmt/issues/2208#issuecomment-356172459
