### ISSUE TITLE
rustfmt does not work on Windows

### ISSUE THREAD

**Issue by olson-dan** [rust-lang-nursery/rustfmt#2343]
Following the instructions in the README, I run

```rustup run nightly cargo install --force rustfmt-nightly```

I'm on this nightly and hesitant to upgrade since nothing ever works when I upgrade: "rustc 1.24.0-nightly (cddc4a62d 2017-12-26)"

When I run `rustfmt` from a command line, I get a missing DLL error:

"The program can't start because syntax-91a64d18c2beb002.dll is missing from your computer.  Try reinstalling the program to fix this problem."

I believe this is the same issue clippy has (https://github.com/rust-lang-nursery/rust-clippy/issues/1815), where some folder must be added to the user's path, but no installation tools do this resulting in users being unable to run the program despite following install steps perfectly.

**Comment by Marwes** [comment]
Though the current behavior should be improved, you can get it working by running `rustup run nightly rustfmt` instead of just `rustfmt`
