### ISSUE TITLE
trailing whitespace added when `normalize_comments` is on

### ISSUE THREAD

**Issue by goffrie** [rust-lang-nursery/rustfmt#2346]
Test case:
```
// test
//
fn main() {}
```

With `normalize_comments` on, the empty comment `//` has a trailing space added to it.

This only happens if the empty comment is at the end; in this example
```
// test
//
// test2
fn main() {}
```
the middle line has any trailing spaces removed instead.

**Comment by karyon** [comment]
i tested this and couldn't reproduce, https://github.com/rust-lang-nursery/rustfmt/commit/fe30dab01785e047b98d89cb27aed84b8137adb2?

**Comment by goffrie** [comment]
I can still reproduce this. Did you turn on `normalize_comments`?

```
% ~/dev/rust/rustfmt/target/debug/rustfmt --version
0.4.0-nightly (197c3b44 2018-02-17)
```

**Comment by karyon** [comment]
thanks for testing again! indeed i did something wrong when testing this, to compensate for that i tried fixing this: #2465
