### ISSUE TITLE
Please considering remove '--force' when using rustfmt rather rustfmt-nightly

### ISSUE THREAD

**Issue by di3663** [rust-lang-nursery/rustfmt#2360]
Can not compile rustfmt-nightly in stable channel (i686-pc-msvc), and rustdt (https://github.com/RustDT/RustDT) will not use rustfmt with parameter '--force' appended

rustfmt-0.10.0/src/bin/rustfmt.rs

```
fn execute(opts: &Options) -> FmtResult<Summary> {
    let matches = opts.parse(env::args().skip(1))?;

    /*
    if !matches.opt_present("f") {
        return Err(FmtError::from("This version of rustfmt is deprecated. Use rustfmt-nightly. \
                                   Use --force to run deprecated rustfmt.".to_owned()))
    }
    */
```

**Comment by apiraino** [comment]
Hello,

I'm not sure this is relevant to this issue, but I suspect this has broken the ["rust-mode" plugin for Emacs](https://github.com/rust-lang/rust-mode/blob/cfb440810a010b099e7196f8701c9d990a3641d8/rust-mode.el#L1446).

I noticed that my code isn't formatted anymore when saving. `rustfmt` isn't executed anymore by Emacs, until I realized that now the command line required is `rustfmt --force`.

**Comment by nrc** [comment]
Using legacy `rustfmt` is a really bad idea - it is old and buggy. Having to use `--force` is a temporary measure before I remove it completely. Unfortunately we get too many users confused about which version of rustfmt they *should* be using.

You should be able to use rustfmt via rustup very soon (in fact, it should work today, but I think there are some wrinkles to iron out) and then the crates.io version should be irrelevant.
