### ISSUE TITLE
`...` operator spacing not enforced when `spaces_around_ranges=true`

### ISSUE THREAD

**Issue by davidalber** [rust-lang-nursery/rustfmt#2372]
Configurations.md has this to say about `spaces_around_ranges`:
> Put spaces around the .. and ... range operators

This is not working in the `true` case for `...`.

**Reproduction:**
1. Create a rustfmt.toml containing `spaces_around_ranges=true`.
1. Run rustfmt on the following file.
```rust
fn main() {
    match x {
        1...5 => foo(),
        _ => bar(),
    }
}
```

**Expected:**
The following diff.
```diff
 fn main() {⏎
     match x {⏎
-        1...5 => foo(),⏎
+        1 ... 5 => foo(),⏎
         _ => bar(),⏎
     }⏎
 }⏎
```

**Actual:**
rustfmt generates no diff.

Note: the reverse situation (`spaces_around_ranges=false`) with starting code containing spaces does generate a diff.

**Comment by davidalber** [comment]
From the code, it looks like this applies to `..=`. For instance, the following should generate a diff when `spaces_around_ranges=true`.
```rust
let lorem = 0..=10;
```

**Comment by davidalber** [comment]
Relevant commit: 2886000.

**Comment by daboross** [comment]
Since `...` is still legal rust, it would be nice if it is still formatted, especially for projects who need to support older rust versions. Could both be supported concurrently?

**Comment by davidalber** [comment]
Just testing now, I found that the `...` syntax is an error, as of [Rust v1.23](https://github.com/rust-lang/rust/releases/tag/1.23.0), which was tagged on January 4.

**Examples:**
Compiling this:
```rust
fn main() {
    let lorem = 0...5;
}
```

Gets this:
```
error: `...` syntax cannot be used in expressions
 --> /Users/davidalber/dev/rustfmt/c.rs:2:18
  |
2 |     let lorem = 0...5;
  |                  ^^^
  |
  = help: Use `..` if you need an exclusive range (a < b)
  = help: or `..=` if you need an inclusive range (a <= b)
```

Compiling this:
```rust
fn main() {
    for i in 1 ... 5 {
        // something
    }
}
```

Gets this:
```
error: `...` syntax cannot be used in expressions
 --> /Users/davidalber/dev/rustfmt/c.rs:2:16
  |
2 |     for i in 1 ... 5 {
  |                ^^^
  |
  = help: Use `..` if you need an exclusive range (a < b)
  = help: or `..=` if you need an inclusive range (a <= b)
```

**Comment by daboross** [comment]
@davidalber for ranges, sure, but it's always been supported in patterns, like the OP example.

This compiles with no warnings on stable rust:

```rust
fn main() {
    let x = 10;
    
    match x {
        1...5 => println!("1-5"),
        _ => println!("other"),
    }
}
```

https://play.rust-lang.org/?gist=0d3ee61a1486a12995e0053a36ed0792&version=stable

**Comment by nrc** [comment]
We can support `...` for as long as it can be parsed by the Rust parser. That is likely to be at least as long as it is a warning rather than an error, and maybe for some time afterwards, but we are somewhat at the mercy of the compiler.
