### ISSUE TITLE
rustfmt shouldn't remove match block

### ISSUE THREAD

**Issue by evmar** [rust-lang-nursery/rustfmt#2376]
Input code was in a match arm, and looked like (the -/+ here are from a diff):

```
-        ast::Stmt::Switch(ref sw) => {
-            for case in sw.cases.iter() {
-                for stmt in case.stmts.iter() {
-                    var_declared_names(&stmt, scope);
-                }
```

rustfmt nightly output was

```
+        ast::Stmt::Switch(ref sw) => for case in sw.cases.iter() {
+            for stmt in case.stmts.iter() {
+                var_declared_names(&stmt, scope);
```

I think the latter is strictly worse -- the very long match expression pushes the 'for' way over to the right when its body is way over to the left.

**Comment by evmar** [comment]
(PS since this is my first comment on the tracker -- I love rustfmt and code auto-formatting! Thank you for making this!)

**Comment by topecongiro** [comment]
I remember seeing similar complaints elsewhere. We probably should force block for expressions on match arms with condition and body block, e.g. `for`, `if` and `while`.
