### ISSUE TITLE
Cargo fmt doesn't work on stable compiler

### ISSUE THREAD

**Issue by Pzixel** [rust-lang-nursery/rustfmt#2381]
I' trying to use `rustfmt` on `stable-x86_64-pc-windows-gnu`. 
I added component via `rustup component add rustfmt-preview`. 
`cargo fmt` didn't work for some reason, however, I have found `rustfmt.exe` itself. 

Now when I run it it just hangs:

```
PS C:\Users\Alex\Documents\Rust\cv-rs> &"C:\Users\Alex\.rustup\toolchains\stable-x86_64-pc-windows-gnu\bin\rustfmt.exe"
-V
0.2.16-nightly (2bfcadf8 2017-11-21)
PS C:\Users\Alex\Documents\Rust\cv-rs> &"C:\Users\Alex\.rustup\toolchains\stable-x86_64-pc-windows-gnu\bin\rustfmt.exe"
-v
.. no output here for 1 hour, then I just closed the window
```

Maybe it happens because I used to use following feature
 

> Alternatively, you can use `cargo fmt` to format all binary and library targets of your crate.

How can I fix it? I'd like to run `rustfmt` on stable compiler. I can write my own script that would search for files in directory and run `rustfmt`, but probably there is some better way.

**Comment by topecongiro** [comment]
Would you please try the following?
```shell
rustup toolchain install nightly
rustup component add rustfmt-preview --toolchain=nightly

# should emit `0.3.6-nightly (e0e3e22 2018-01-18)`
cargo +nightly fmt -- --version
# should emit `0.3.6-nightly (e0e3e22 2018-01-18)`
rustup run nightly rustfmt --version
```

**Comment by Pzixel** [comment]
It was working on nightly compiler 1 month ago or something. I believe it still working on it today.
But the question is about stable compiler.

**Comment by topecongiro** [comment]
You can run above commands even when your default toolchain is stable.

**Comment by Pzixel** [comment]
Yep, it works.

**Comment by Venkipullela** [comment]
It's like even if your default toolchain is stable, you are telling the command to use nightly over the stable while executing this.
