### ISSUE TITLE
"operation not supported by the terminal" with rustfmt-preview inside Emacs's `M-x shell`

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rustfmt#2391]
This did not used to happen until I switched to `rustup component add rustfmt-preview` (which probably involved upgrading to a newer `rustfmt` version than I had since the last time I did `cargo +nightly install rustfmt-nightly`?)

```
$ RUST_BACKTRACE=1 cargo fmt --all
thread 'main' panicked at 'failed to emit error: operation not supported by the terminal', /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_errors-12.0.0/emitter.rs:1269:23
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit
   8: rustc_errors::Handler::emit_db
   9: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
  10: rustfmt_nightly::run
  11: rustfmt::execute
  12: rustfmt::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
  16: std::rt::lang_start_internal
  17: main
```

**Comment by nrc** [comment]
Does this happen on usage or only where there is some specific output or input? What platform and console are you using?

**Comment by fitzgen** [comment]
> Does this happen on usage or only where there is some specific output or input?

If I do `cargo fmt --help`, then it prints the usage just fine.

> What platform and console are you using?

I'm on Linux right now, but I suspect it happens whenever using `M-x shell` inside Emacs.

There is no console, just Emacs's `M-x shell`.

**Comment by Lokathor** [comment]
This same thing happens to me any time there's any formatting error that it wants to give a message for.

Windows 7 / cmd.exe

**Comment by topecongiro** [comment]
The same issue was reported in #1180. It was fixed when we switched from `syntex` crate to `libsyntax`. And now somehow this is reintroduced after we switched to `rustc-ap-*` crates.

I confirmed that using `libsyntax` fixes this issue. I have no idea why using `rustc-ap-*` crates causes this issue to resurface.

**Comment by LYP951018** [comment]
Cloned the repo and built an rustfmt exe but the issue remains....
