### ISSUE TITLE
rustfmt generating invalid syntax

### ISSUE THREAD

**Issue by sgrif** [rust-lang-nursery/rustfmt#2392]
`rustfmt` appears to be adding an extra `>` for no reason. It changed `pub struct Nested<'a>(syn::punctuated::Iter<'a, syn::NestedMeta, Token![,]>);` to `pub struct Nested<'a>(syn::punctuated::Iter<'a, syn::NestedMeta, Token![,]>>);` (note the extra `>` at the end.

To reproduce:

- Clone Diesel at commit https://github.com/diesel-rs/diesel/commit/a806d26
- `(cd diesel && cargo build)`
- See that it builds successfully
- `cargo fmt --all`
- `(cd diesel && cargo build)`
- See that it fails to build

**Comment by topecongiro** [comment]
This could not be reproduced with rustfmt-0.3.6. Would you please try with it?

**Comment by sgrif** [comment]
The issue no longer occurs with 0.3.6
