### ISSUE TITLE
#[cfg(debug_assertions)] is duplicated on use

### ISSUE THREAD

**Issue by nihiluis** [rust-lang-nursery/rustfmt#2394]
im using nightly from this week

```
impl SomeTrait for SomeStruct {
   fn dahaha(&mut self) {
        #[cfg(debug_assertions)]
        debug = true;
}
```
if I use rustfmt on a file like this the #[cfg(debug_assertions)] is duplicated double. like if I use rustfmt once `#[cfg(debug_assertions)]` is shown twice. if i use it again `#[cfg(debug_assertions)]` is shown four times and so on.

**Comment by topecongiro** [comment]
I could not reproduce this with rustfmt `0.3.6-nightly (e0e3e22 2018-01-18)`. Would you please try with it?

**Comment by nihiluis** [comment]
this is my nightly: rustc 1.25.0-nightly (4e3901d35 2018-01-23)

$ rustfmt -V
0.9.0-nightly ( )

how do I install 0.3.6-nightly?

**Comment by nrc** [comment]
you should use Cargo to remove rustfmt, then install rustfmt-preview using rustup (preferred) or rustup-nightly using Cargo.
