### ISSUE TITLE
Incorrectly reorders #[macro_use] imports -> compile error

### ISSUE THREAD

**Issue by FauxFaux** [rust-lang-nursery/rustfmt#2399]
`rustfmt` 0.3.6-nightly breaks the following code, during formatting:

```rust
#[macro_use]
extern crate nom;
extern crate regex;
#[macro_use]
extern crate log;

fn main() {
    error!("Hello, world!");
}
```

It is not aware that `error!` is defined in both [`nom`](https://docs.rs/nom/1.2.4/nom/macro.error!.html) and [`log`](https://docs.rs/log/0.4.1/log/macro.error.html), but the version from `log` is active, as it is imported second. (I'm not aware of any documentation about this being the case, but it's what's observed here.)

`rustfmt` reorders the imports alphabetically, into:

```rust
#[macro_use]
extern crate log;
#[macro_use]
extern crate nom;
extern crate regex;
```

...causing the wrong macro to be called, and a super confusing error:

```
   Compiling foo v0.1.0 (file:///var/tmp/faux180128.doable/foo)
error: unexpected end of macro invocation
 --> src/main.rs:8:12
  |
8 |     error!("Hello, world!");
  |            ^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Either rustfmt needs to be aware of which macros are imported, or perhaps it should not reorder `#[macro_use] extern crate`s?

---

I am using these versions of these crates:
```toml
[dependencies]
nom = "1.2"
log = "0.3"
regex = "0.1"
```

It doesn't appear to happen if you remove the `regex` line. I do not know what that is about. Found in the wild formatting https://github.com/joelself/tomllib.

**Comment by topecongiro** [comment]
cc https://github.com/rust-lang/rust/issues/32911.
