### ISSUE TITLE
Remove unnecessary parenthesis?

### ISSUE THREAD

**Issue by PSeitz** [rust-lang-nursery/rustfmt#2408]
```rust
if (chunk_size == 2) {
                        
}
```
should probably be converted to

```rust
if chunk_size == 2 {
                        
}
```
I couldn't find an option for this.

**Comment by nrc** [comment]
We could do this, but I think it would be better for the compiler to offer this as a suggestion which an IDE or Rustfix could then apply as a 'quick fix' (the compiler already warns about this, and the rewrite would be easy).

**Comment by brotzeit** [comment]
Unnecessary curly braces in imports already get removed. Where is the difference ? Would the compiler not warn about this ?

**Comment by PSeitz** [comment]
So we don't format anything that's a compiler warning and leave this to IDE's?

**Comment by nrc** [comment]
I think that makes sense, yeah, although I am somewhat making this up as I go along...

**Comment by PSeitz** [comment]
Although this would lead to problems if the compiler emits new errors.

Imho a formatter should just format everything, especially clear cases like this.
