### ISSUE TITLE
"Compressed" density for function calls

### ISSUE THREAD

**Issue by smarter** [rust-lang-nursery/rustfmt#2418]
The [`fn_args_density`](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#fn_args_density) has a `"Compressed"` value. This helps not waste too many lines on function declarations with many arguments, but there is no comparable setting for function calls, e.g.:
```rust
    foo(aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa);
```
gets reformatted to:
```rust
    foo(
        aaaaa,
        aaaaa,
        aaaaa,
        aaaaa,
        aaaaa,
        aaaaa,
        aaaaa,
        aaaaa,
        aaaaa,
        aaaaa,
        aaaaa,
    );
```

when I would much rather have:
```rust
    foo(
        aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa,
        aaaaa
    );
```
or even better:
```rust
    foo(aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa, aaaaa,
        aaaaa);
```

**Comment by smarter** [comment]
It seems that [`use_small_heuristics`](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#use_small_heuristics) already does that when things are 'small'. Would it be possible to have something like this on at all time and not just for small expressions?

**Comment by topecongiro** [comment]
cc #2196.

**Comment by topecongiro** [comment]
This is now fixed by default, closing.
