### ISSUE TITLE
Add a mode to leave lines unchanged when they are under max_width

### ISSUE THREAD

**Issue by smarter** [rust-lang-nursery/rustfmt#2420]
An auto-formatter such as rustfmt is really useful to enforce some level of consistency in a project. But it can also become a burden when the formatter has very specific ideas about how to format some things. It would be useful to have a mode that simply does not reformat lines that are short enough. The end result would probably be less consistent than the default mode of rustfmt but it would be better than just not using rustfmt at all. Is such a thing possible?

**Comment by nrc** [comment]
This is pretty difficult to do in Rustfmt because for any skipped text we'd need to know which AST nodes are included/partially included. For specific things you don't want formatted (e.g., matrix-like arrays), you can use a skip attribute.
