### ISSUE TITLE
Allow a wildcard *.rs that can be used to format all .rs file in that directory and it's subdirectories

### ISSUE THREAD

**Issue by ishanjain28** [rust-lang-nursery/rustfmt#2426]
Sometimes, I want to run rustfmt on all source files in a directory. There is a `*` wildcard that can be used but it also tries to format `toml` and any other files in the directory. 

I think, There should be a `*.rs` wildcard that formats all Rust source files in the specified directory and also any rust files in the subdirectories of specified directory.

**Comment by ishanjain28** [comment]
On a second thought, Formatting all `.rs` files in a directory and it's subdirectories might cause performance issues and there might be someone who doesn't wants to format all the source files in subdirectories. 

So, A `-r --recursive` flag is probably a good idea.

**Comment by ishanjain28** [comment]
Oh, Just found out about the `--skip-children` option. It automatically formats all imported modules in the file. My issue is now resolved but `-r --recursive` and `*.rs` wildcard might be useful for someone who has different/unrelated .rs files in a directory.

**Comment by nrc** [comment]
Rustfmt formats programs rather than files. If you format lib.rs/main.rs, it will format all files in the library/application.

**Comment by AlexAegis** [comment]
And how about workspaces?
