### ISSUE TITLE
`indent_style` for control working incorrectly

### ISSUE THREAD

**Issue by davidalber** [rust-lang-nursery/rustfmt#2427]
# Summary
The `indent_style` configuration option does not behave correctly for control flow.

# Reproduction
1. Create a file (let's call it "c.rs" for the rest of the issue) containing the following content, which is based on the [example in Configurations.md](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#control-flow).
```rust
fn main() {
    if lorem_ipsum && dolor_sit && amet_consectetur && lorem_sit && dolor_consectetur && amet_ipsum && lorem_consectetur
    {
        // ...
    }
}
```

## `"Block"` Variant
1. Create a rustfmt.toml file containing `indent_style = "Block"`.
1. Do `cargo run --bin rustfmt -- c.rs --write-mode=diff`.

Result:
```diff
 fn main() {⏎
-    if lorem_ipsum && dolor_sit && amet_consectetur && lorem_sit && dolor_consectetur && amet_ipsum && lorem_consectetur⏎
+    if lorem_ipsum && dolor_sit && amet_consectetur && lorem_sit && dolor_consectetur && amet_ipsum⏎
+        && lorem_consectetur⏎
     {⏎
         // ...⏎
     }⏎
```

## `"Visual"` Variant
1. Create a rustfmt.toml file containing `indent_style = "Visual"`.
1. Do `cargo run --bin rustfmt -- c.rs --write-mode=diff`.

Result:
```diff
 fn main() {⏎
-    if lorem_ipsum && dolor_sit && amet_consectetur && lorem_sit && dolor_consectetur && amet_ipsum && lorem_consectetur⏎
+    if lorem_ipsum && dolor_sit && amet_consectetur && lorem_sit && dolor_consectetur && amet_ipsum⏎
+       && lorem_consectetur⏎
     {⏎
         // ...⏎
     }⏎
```

# Expected
The two variations were similar, but not identical. They differ by one space.

I'm not sure what is expected. I'm guessing that the `"Visual"` variant should have produced something like:
```diff
 fn main() {⏎
-    if lorem_ipsum && dolor_sit && amet_consectetur && lorem_sit && dolor_consectetur && amet_ipsum && lorem_consectetur⏎
+    if lorem_ipsum && dolor_sit && amet_consectetur && lorem_sit && dolor_consectetur && amet_ipsum⏎
+        && lorem_consectetur {⏎
         // ...⏎
     }⏎
```

However, there's been some consolidation of configuration options that resulted in all of these things being covered by `indent_style`, so it's possible that this is not to be part of `indent_style`.

**Comment by nrc** [comment]
I think this is mostly as expected. Visual vs block indent is about how many spaces we indent by. Block indent should always be 4 spaces, visual indent aligns with the previous line (in this case, 3 spaces because the `&&` gets aligned with `lorem_...`.

We probably could leave the opening brace on the same line in visual indent mode because there is one space difference between the condition indent and the body indent, but actually a newline before the brace probably makes things clearer.

**Comment by davidalber** [comment]
You said it's "mostly as expected", and the only open question is what to do with the brace. You think it's more clear to have it on a new line (like it is now), and I'm not strongly in favor of it being on the same line for `"Visual"`. I placed it on the same line because that more closely matches the other examples of formatting for `"Visual"`.

Unless someone is strongly in favor of having the brace on the same line it seems like this should be closed as by design.
