### ISSUE TITLE
Preserve trailing whitespace in doc comments

### ISSUE THREAD

**Issue by LEXUGE** [rust-lang-nursery/rustfmt#2434]
# Situation:
I found that rustfmt do format the documentation comments in doctumentations.
# For example:
Some space which are required by Markdown to wrap will be deleted.
Original text:
```rust
/// This is content which contains to space in the end!  
```
rustfmt will delete these two spaces and documentations' format will be **terrible.**

**Comment by nrc** [comment]
We basically don't format comments, but I guess we do trim whitespace, which we shouldn't.
