### ISSUE TITLE
Workspace project layout is incompatible with Rust repo

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#2442]
Cargo does not permit nested workspaces and Rust is a workspace project, so that means we can't pull Rustfmt into Rust at the moment (my bad, I've had this problem before and completely forgot when reviewing the PR).

There are two solutions I can see (hopefully there are more):

* revert the workspaces layout and go back to a single crate (not great)
* create some kind of shim repo which has the rustfmt crates as dependencies and just exposes the binaries, then pull that repo into Rust, rather than the Rustfmt repo (also not great because of the complexity, but better than going back to the non-workspaces layout, I think).

**Comment by topecongiro** [comment]
> Cargo does not permit nested workspaces and Rust is a workspace project

Ouch, I was not aware of this limitation.

Another possible solution I can think of is to put binaries in a different repository and pull that to Rust.

**Comment by nrc** [comment]
> Another possible solution I can think of is to put binaries in a different repository and pull that to Rust.

This is what I meant with my second suggestion, sorry, I could have worded that better.

**Comment by topecongiro** [comment]
A minor downside of the second approach is that running `cargo build` in rustfmt repo will not produce binaries anymore, so testing rustfmt when fixing formatting issues will become a bit tedious.

**Comment by topecongiro** [comment]
Another possible approach is to mimic the layout of clippy repo, which uses multiple crates without workspace. Something like the following:

```
.
├── rustfmt_core
├── rustfmt_config
├── src
│   ├── rustfmt.rs
│   └── cargo_fmt.rs
└── tests
```

**Comment by nrc** [comment]
I created the https://github.com/rust-lang-nursery/rustfmt-bin repo and moved the binaries there. I haven't actually updated the Rust repo with them yet, but I think this should fix the issue...

**Comment by nrc** [comment]
But the remaining problem is how to run the tests since they are in the main repo not the rustftm-bin repo

**Comment by nrc** [comment]
I've reverted the workspaces stuff for now, but kept the new general structure. I would like to go back to a workspace in the long-run, but we'll need to sort the Rust repo stuff first.
