### ISSUE TITLE
rustfmt --version is confusing on stable release

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#2451]
:raised_hands: rustfmt is now available on stable release :raised_hands: 

Today its verstion has a `-nightly` suffix (`0.3.4-nightly (6714a44 2017-12-23)`).
We should be able to change the suffix based on whether its on stable or nightly like rls does.

```
rls-preview 0.124.0-stable (299a6a9 2017-12-25)
rls-preview 0.125.0-nightly (dee42bd 2018-02-04)
```

**Comment by csmoe** [comment]
I'll take this.
