### ISSUE TITLE
cargo fmt formats all crates in a workspace by default

### ISSUE THREAD

**Issue by rtsuk** [rust-lang-nursery/rustfmt#2488]
I would much prefer it behave like cargo build, where it only operates on the crate in the current directory unless told otherwise.

**Comment by rtsuk** [comment]
I'd be happy to try to fix this one if folks agree with my preference.

**Comment by nrc** [comment]
Yeah, following `cargo build` seems like the correct behaviour here (though of course running in the root of the workspace should still format the whole workspace, just like `cargo build` does).

> I'd be happy to try to fix this one if folks agree with my preference.

That would be awesome, thank you!

**Comment by matklad** [comment]
>just like `cargo build` does

Note that `cargo build` behavior is actually pretty nuanced these days. The flags which affect which crates are built are `--package` , `--all` and `--exclude`. Additionally, `default_members` attribute of a *virtual* root Cargo.toml manifests affects behavior in the root of the workspace. And, if the root of the workspace is **not** virtual, than only the root is built, and not the whole workspace. 

So, yeah, basically most custom subcommands should accept `--all`, `--exclude` and `--package` flags, and behave like build-in commands, but there's no easy way to achieve that behavior in custom sub commands, except by replicating parts of Cargo behavior :-(

**Comment by rtsuk** [comment]
Should I move this issue over to rustfmt-bin?

**Comment by nrc** [comment]
> Should I move this issue over to rustfmt-bin?

No, I'm not sure what the future will be like for rustfmt-bin, so we'll continue tracking issues here for a while.

**Comment by cramertj** [comment]
This issue was fixed by https://github.com/rust-lang-nursery/rustfmt/pull/2513

**Comment by topecongiro** [comment]
Closed via #2513.

**Comment by eoger** [comment]
This was re-reverted later by https://github.com/rust-lang/rustfmt/pull/3652, can be re-open this?

**Comment by calebcartwright** [comment]
@eoger would you open a new issue with your corresponding rustfmt version and other relevant details? At least with rustfmt 1.4.13 `cargo fmt` is operating as described/requested in this issue.
