### ISSUE TITLE
Weird indentation in cfg_if! blocks

### ISSUE THREAD

**Issue by glandium** [rust-lang-nursery/rustfmt#2500]
I thought rustfmt ignored macro blocks, but it looks like it does. This is what I got as output from rustfmt from the obviously properly indented version:

```rust
cfg_if! {
    if #[cfg(windows)] {
        extern crate winapi;

    fn getpid() -> usize {
        winapi::um::processthreadsapi::GetCurrentProcessId() as usize
    }

    fn gettid() -> usize {
        winapi::um::processthreadsapi::GetCurrentThreadId() as usize
    }
    } else {
        extern crate libc;

        fn getpid() -> usize {
            unsafe { libc::getpid() as usize }
        }

        fn gettid() -> usize {
            unsafe { libc::pthread_self() as usize }
        }

    }
}
```

**Comment by topecongiro** [comment]
I could not reproduce this with `0.3.8-nightly (346238f 2018-02-04)`. Would you tell us which version you used?

> I thought rustfmt ignored macro blocks, but it looks like it does.
This is true, except that rustfmt only tries to fix indentation.

**Comment by glandium** [comment]
`0.3.4-nightly (6714a44 2017-12-23)`, apparently.

**Comment by glandium** [comment]
(AFAICT that's the version on the stable channel for `rustfmt-preview`)

**Comment by glandium** [comment]
> This is true, except that rustfmt only tries to fix indentation.

I've almost never seen it touch indentation in macro blocks, except in this instance.

**Comment by topecongiro** [comment]
> 0.3.4-nightly (6714a44 2017-12-23), apparently.
> (AFAICT that's the version on the stable channel for rustfmt-preview)

Thanks!

So looks like this is already fixed, but the stable version does not include it. I am sorry for the inconvinience. If you are willing to use the nightly version, you can install and use it via the following command, even when the default channel is stable:

```shell
rustup install nightly
rustup component add --toolchain nightly rustfmt-preview
cargo +nightly fmt
```
