### ISSUE TITLE
`cargo fmt` panics when run on `diesel`

### ISSUE THREAD

**Issue by Diggsey** [rust-lang-nursery/rustfmt#2505]
Steps to reproduce:
- Checkout diesel
- Run `cargo fmt` in root of checkout

Output:
```
thread 'main' panicked at 'failed to emit error: operation not supported by the terminal', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-ap-rustc_errors-29.0.0\emitter.rs:1300:23
```

Stack trace is not useful due to no symbols being present.

OS: Windows 10

**Comment by topecongiro** [comment]
I think this is a Windows-specific issue. Could not reproduce this in Linux.

**Comment by topecongiro** [comment]
I think we can close this now that we have updated `term` to 0.5.

@Diggsey Please reopen this if the issue still persists.
