### ISSUE TITLE
rustfmt removes 'dyn'

### ISSUE THREAD

**Issue by kngwyu** [rust-lang-nursery/rustfmt#2506]
Before
```rust
#![feature(dyn_trait)]
fn main() {
    trait MyTrait {
        fn method(&self) -> u64;
    }
    fn f(a: Box<dyn MyTrait>) {}
}
```

After
```rust
#![feature(dyn_trait)]
fn main() {
    trait MyTrait {
        fn method(&self) -> u64;
    }
    fn f(a: Box<MyTrait>) {}
}
```
(rustfmt 0.4.0)

**Comment by nrc** [comment]
I'm happy to mentor this issue. If you want to explore, look at [types.rs](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/types.rs) and the Rust AST for types. We might need to update our `rustc-ap-syntax` dependency.

**Comment by ThatOtherPerson** [comment]
I'd be interested in working on this!

**Comment by kngwyu** [comment]
@nrc 
`ast::TyKind::TraitObject` has 
```rust
pub enum TraitObjectSyntax {
    Dyn,
    None,
}
```
so I think it's not hard to modify.
I'm working on PR.

**Comment by nrc** [comment]
Thanks @kngwyu !

@ThatOtherPerson https://github.com/rust-lang-nursery/rustfmt/issues/2445 might be another good issue to get your teeth into. There are some instructions in the issue, feel free to ask questions there too!
