### ISSUE TITLE
`reorder_modules` destroys inline modules 

### ISSUE THREAD

**Issue by nhynes** [rust-lang-nursery/rustfmt#2514]
Using `rustfmt 0.4.0`, when `reorder_modules = true`

```rust
mod module {
    use other_module::things;
}
```
is "fixed" to become
```rust
mod module;
```

Setting `reorder_modules = false` stops this behavior.

**Comment by sinkuu** [comment]
This may have been fixed on master. #2502

**Comment by nhynes** [comment]
Thanks!
