### ISSUE TITLE
Add option to format control flow vertically

### ISSUE THREAD

**Issue by l0b0** [rust-lang-nursery/rustfmt#2530]
It would be good to be able to format long control flow statements like this:

```
fn main() {
    if true
        && true
        && true
        && true
        && true
        && true
        && true
        && true
        && true
        && true
        && true
        && true
        && true
        && true
        && true
    {
        // ...
    }
}
```

Maybe `indent_style = "Vertical"`?

The above is the simplest example I could think of, but in complex code it should be clearer why mixing horizontal and vertical layout makes the code harder to comprehend. For example, rustfmt 0.4.0 formats like this:

```
fn main() {
    my_very_long_method_name(my_even_longer_variable_name && foo()) && short()
        && another_long_method_name(yet_another_long_variable_name)
}
```

Proposed formatting:

```
fn main() {
    my_very_long_method_name(my_even_longer_variable_name && foo())
        && short()
        && another_long_method_name(yet_another_long_variable_name)
}
```

The three top level sub-expressions are now clearly aligned. It's trivial to see that `foo()` is not a top level expression, and it's equally trivial to see that `short()` is one, and not (part of) a parameter for `my_very_long_method_name`.

**Comment by nrc** [comment]
`Block` indent doesn't mean we format like a block, it means that we format by using a single 'tab' rather than by aligning code on the new line (e.g., if we use `while let` rather than `if`, the visual indent would be 10 and the block indent would still be 4).

I'm not exactly sure where the terminology came from, I think one of the other formatters, but it is certainly a term of art from before rustfmt came around.

**Comment by l0b0** [comment]
I've updated it to a feature request; please reopen.

**Comment by topecongiro** [comment]
I think we should do this by default, but only when each expression is not simple. An example from rustfmt source code:


#### What we currently do

```rust
            if tactic == DefinitiveListTactic::Vertical && !has_long_item
                && is_every_expr_simple(exprs)
```

#### What we should do

```rust
            if tactic == DefinitiveListTactic::Vertical
                && !has_long_item
                && is_every_expr_simple(exprs)
```

**Comment by l0b0** [comment]
@topecongiro How do you define whether an expression is simple?
