### ISSUE TITLE
Support for use_nested_groups Feature

### ISSUE THREAD

**Issue by cramertj** [rust-lang-nursery/rustfmt#2544]
Now that https://github.com/rust-lang/rust/issues/44494 has been stabilized, it would be nice to have a rustfmt option to reformat all imports into the `use_nested_groups` format.

**Comment by topecongiro** [comment]
cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/24.

**Comment by nrc** [comment]
@cramertj we should discuss on rust-lang-nursery/fmt-rfcs#24
