### ISSUE TITLE
`brace_style` exclusively for function definitions

### ISSUE THREAD

**Issue by nickdonnelly** [rust-lang-nursery/rustfmt#2545]
It would be nice if we could have `brace_style=AlwaysNextLine` for function definitions. In other words, format that looks like:

```rust
fn function<T>(arg1: T)
{ // Brace on new line
    // Body
}
```

With structs/enums/etc. still looking like
```rust
enum ABC { // Brace on same line
    A,
    B,
    C
}
```

If this is already an option I've been unable to find it.

**Comment by nrc** [comment]
We've been trying to avoid very specific options like this - each new option adds code complexity, testing complexity, and opportunities for edge case bugs where options interact. Given the overall emphasis on consistency in the formatting rules I don't think an option like this would be popular enough to pull its weight, sorry.

**Comment by nickdonnelly** [comment]
@nrc  I think it would be more popular than you suspect. It's an extremely common convention used by lots of C developers. In fact, the [Linux kernel itself uses it](https://www.kernel.org/doc/html/v4.10/process/coding-style.html#placing-braces-and-spaces). I understand if you don't want to add it, but I don't buy the popularity argument.
