### ISSUE TITLE
Remove unreachable! from macros.rs

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#2558]
Currently rustfmt reaches `unreaclable!` when run against invalid macro defs:

```rust
macro_rules! foo {
    ($x:) => (),
}
```
```
thread 'main' panicked at 'internal error: entered unreachable code', src/macros.rs:690:18
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

There are 2 `unreachable!()` in macros.rs:

https://github.com/rust-lang-nursery/rustfmt/blob/2fbdedbf2fbf89bb00743e85c3b19cb765d6c1ad/src/macros.rs#L690

https://github.com/rust-lang-nursery/rustfmt/blob/2fbdedbf2fbf89bb00743e85c3b19cb765d6c1ad/src/macros.rs#L732

We need to remove them and handle errors properly.

**Comment by codeworm96** [comment]
I am interested in working on this issue. But I am not sure what is the precise meaning of "handle errors properly". When encountered the invalid cases, should rustfmt abort and print the error message or just leave the invalid part unchanged?

**Comment by topecongiro** [comment]
@codeworm96 Great, thank you!

> When encountered the invalid cases, should rustfmt abort and print the error message or just leave the invalid part unchanged?

We want to leave the invalid part unchanged rather than aborting, and we need not print any error messages.
One direction would be changing the return type of `MacroArgParser::parse` to `Option<Vec<ParsedMacroArg>>` and making it return `None` when there are invalid input.

**Comment by codeworm96** [comment]
@topecongiro Thanks. I will have a try.
