### ISSUE TITLE
Associated type projection Iterator<Item = X> looks wrong

### ISSUE THREAD

**Issue by bluss** [rust-lang-nursery/rustfmt#256]
I'm used to `Iterator<Item=X>` without spaces, not `Iterator<Item = X>`.

**Comment by nrc** [comment]
There's a few places where we do this - bounds is also one (e.g., `Box<Foo+Bar>` vs `Box<Foo + Bar>`). We should have an option for this spacing (although some of it is done by the pretty printer so we don't control it yet).

**Comment by tbu-** [comment]
I guess whatever option is introduced here should also apply to `#[attribute = foo]`.

**Comment by nrc** [comment]
I would have a different one for attributes, but yes, we should have one there too.

**Comment by marcusklaas** [comment]
Closing this in favour of https://github.com/rust-lang-nursery/rustfmt/issues/489.
