### ISSUE TITLE
Macro-expanded test code doesn't parse

### ISSUE THREAD

**Issue by willcrichton** [rust-lang-nursery/rustfmt#2564]
Steps to reproduce:

```
cargo new foobar
cd foobar
rustup override set nightly
cargo rustc -q --tests --color=always -- -Z unstable-options --pretty=expanded | rustfmt
```

Here, `cargo rustc` generates this code: https://gist.github.com/willcrichton/2599f6f19238f95904baee8b8de285fc

And it fails with this error:
```
error: expected `{`, found `self`
  --> stdin:85:70
   |
85 |                                                                      self::test::assert_test_result(::__test_reexports::tests::it_works())),}];
   |                                                                      ^^^^

error: expected one of `,`, `.`, `?`, `}`, or an operator, found `self`
  --> stdin:85:70
   |
84 |                                         self::test::StaticTestFn(|| -> _
   |                                                                         - expected one of `,`, `.`, `?`, `}`, or an operator here
85 |                                                                      self::test::assert_test_result(::__test_reexports::tests::it_works())),}];
   |                                                                      ^^^^ unexpected token
```

I'm not sure if this is a problem with `--pretty=expanded` or if it's a problem with rustfmt. But it makes me sad since I can't use [cargo-expand](https://github.com/dtolnay/cargo-expand) with rustfmt on code in tests :(

**Comment by nrc** [comment]
In general `--pretty=expanded` does not guarantee that its output will compile or if it does that it will have the same semantics as the input. It is also pretty buggy since it is old and poorly tested code.

Does the output parse if you try and compile it with rustc? I think it will not and thus this is a rustc problem (almost certainly with pretty expanded), rather than a rustfmt problem.

**Comment by willcrichton** [comment]
Yeah it appears that it's a rustc issue. Alas, my poor macros. I'll close this for now.
