### ISSUE TITLE
suggest nightly install?

### ISSUE THREAD

**Issue by rcoh** [rust-lang-nursery/rustfmt#2578]
I was confused for a while because `cargo fmt` contained problems that had been fixed in issues and released in releases. I eventually realized that it's because installing `rustfmt` via the install method suggested in the README gets you a version from December 2017.

Maybe `cargo +nightly install rustfmt-nightly` should be added as a suggested install command? I think a lot of people have a nightly toolchain installed. Since you can run rustfmt-nightly on a repository using stable, I think it would lead to a better user experience overall.

**Comment by topecongiro** [comment]
Thanks for filing an issue! Installing via `cargo` is not recomended, though, as it takes a lot of time and requires re-installing after every `rustup update`.

For users who have nightly toolchain, use stable toolchain as a default and want to use *the* latest rustfmt-nightly, `rustup component add rustfmt-preview --toolchain nightly` & `cargo +nightly fmt` will do.
