### ISSUE TITLE
trailing_comma with single entry

### ISSUE THREAD

**Issue by dbrgn** [rust-lang-nursery/rustfmt#2597]
Inside a match arm, this fix was applied by rustfmt:

```rust
                         Err(_) => Err(PushError::Other(
-                            "Unknown error (and non-UTF-8 body)".into()
+                            "Unknown error (and non-UTF-8 body)".into(),
                         )),
```

While I generally want a trailing comma for vertical function arguments, I'd make an exception for single-argument calls. (Especially since in this case it's an enum that takes a single value, not a function.)

Is that something that you'd consider supporting (something like `trailing_comma = VerticalUnlessSingle`), or is it too much of a special case?

**Comment by dbrgn** [comment]
Funnily enough, it is being done inconsistently:

```diff
+            StatusCode::Unauthorized => boxed!(future::err(PushError::ProcessingError(
+                "Unauthorized. Is the API token correct?".into()
+            ))),
+            _ => boxed!(
+                response.body().concat2().map_err(body_read_error).and_then(
+                    |chunk| match from_utf8(&*chunk) {
+                        Ok(body) => Err(PushError::Other(format!("Unknown error: {}", body))),
+                        Err(_) => Err(PushError::Other(
+                            "Unknown error (and non-UTF-8 body)".into(),
+                        )),
+                    },
                 )
+            ),
```

On line 2 there's no trailing comma, while on line 9 there is.

**Comment by nrc** [comment]
I don't think we can support this - it is too much of a niche option and consistency between things like one argument and many has been a steering principle in our formatting.
