### ISSUE TITLE
Sort the items inside proc_macro

### ISSUE THREAD

**Issue by csmoe** [rust-lang-nursery/rustfmt#2608]
Origin:
```rust
#[derive(Send, Default, Debug)]
struct Test(i32);
```
after:
```rust
#[derive(Debug, Default, Send)] // sort the items
struct Test(i32);
```
`rustfmt` currently sorts the items like 
```rust
pub mod B;             pub mod A;
               => 
pub mod A;             pub mod B;
```
Can `rustfmt` apply this kind of sorting to items inside `proc_macro`?

**Comment by nrc** [comment]
We can't do this because the order can be significant - the before and after in your example might expand to different code because custom derives are expanded in order
