### ISSUE TITLE
Support whole functions on one line

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#262]
Some people like to fit a whole function (decl and body) on one line. They are wrong, but we should support it as an option.

e.g., 

```
pub fn default_options() -> Vec<RenderOption> { vec![] }
```

**Comment by retep998** [comment]
Yes please.

**Comment by nrc** [comment]
After a small survey of the compiler and libs teams, the default should be that we only put functions on one line if the body is empty. We should also support an option of one-lining options if we fit inside the max width and there is only one expression/statement.
