### ISSUE TITLE
use Failure

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#2638]
rather than `std::Error`

**Comment by mrecachinas** [comment]
I'd love to take this. Is the general idea to simply replace `std::error` with `failure::Error` (from https://github.com/rust-lang-nursery/failure)?

**Comment by nrc** [comment]
> I'd love to take this. Is the general idea to simply replace std::error with failure::Error

Yes, exactly. There might also be something to do at the top level where we catch errors.

> Does it also include std::io::Error and other variants?

No these are the concrete error types, only the error *trait* is replaced. At some point these concrete errors will be hidden by failure::Error, but keep them concrete as much as possible.

**Comment by thibaultdelor** [comment]
@mrecachinas Sorry I start working on it before seeing your comment, feel free to piggy back on my PR

@nrc I was wondering if my PR is what your were looking for. It uses failure only for internal error but if you want more of the failure crate that's going to have an impact on more code.

I have tried to replace `FmtResult` to be `std::result::Result<T, Box<Fail>>` but I quickly ran into implicit conversion missing. I guess that would require a much more code change. Is that what you are expecting?

**Comment by thibaultdelor** [comment]
I figured it out! 

@nrc I am happy with my PR. Feel free to review.

**Comment by mrecachinas** [comment]
No prob!

**Comment by CAD97** [comment]
Where does this stand after #2650?

**Comment by nrc** [comment]
> Where does this stand after #2650?

It can be closed
