### ISSUE TITLE
format valid macro resulting in invalid macro with native newlines

### ISSUE THREAD

**Issue by dten** [rust-lang-nursery/rustfmt#2641]
i'm using `rustfmt 0.4.2-nightly (dd807e24 2018-04-18)` and formatting this macro
```
macro_rules! try_500 {
    ($res:expr) => {{
    }};
}
```

results in 
```
macro_rules! try_500 {
    ($res:expr) => {{}
    }};
}
```

which has mismatched braces

**Comment by dten** [comment]
The version I'm using claims to be from this commit, which should have the change you linked https://github.com/rust-lang-nursery/rustfmt/commit/dd807e24656c91b4ad22d3cac146edd86315e633

**Comment by dten** [comment]
in fact formatting the exact one from your PR works fine, but this one does not

**Comment by dten** [comment]
i'm actually having trouble reproducing this now I've said that :) please hold!

**Comment by dten** [comment]
So I can do this in one project, but not the other, they're using the same install from rustup, neither has an override set. That code above in one formats badly, the code in the other formats fine. I am investigating :)

**Comment by Marwes** [comment]
Aha, that explains it! I also have that set and every time I tested to see if the example was fixed I ran rustfmt from the same repo so it would have been picking up the configuration.
