### ISSUE TITLE
Rustfmt adds tab in raw string

### ISSUE THREAD

**Issue by alanhdu** [rust-lang-nursery/rustfmt#2642]
Using the latest master (fbdd0e815c80d0c7dde62cc541e866440039bafc) and 0.4.2, rustfmt is inserting an extraneous tab into the raw string:

Running `rustfmt --check-mode=write test.rs`
```rust
macro_rules! template {
    ($name: expr) => {
format_args!(r##"
"http://example.com"

# test
"##, $name)
    }
}
```

outputs

```
Diff in /home/alan/workspace/scratch/test.rs at line 1:
 macro_rules! template {
-    ($name: expr) => {
-format_args!(r##"
+    ($name:expr) => {
+        format_args!(r##"
 "http://example.com"
-
-# test
-"##, $name)
-    }
+            
+        # test
+        "##, $name)
+    };
 }
 
internal error: left behind trailing whitespace
 --> /home/alan/workspace/scratch/test.rs:5
  |
5 |             
  | ^^^^^^^^^^^^
```

AFAICT, this is some interaction between the macro declaration and the `//` in the URL (which is presumably being interpreted as a comment).

**Comment by gnzlbg** [comment]
I can still reproduce. cc @nrc this breaks user code: it modifies the contents of a raw literal string.
