### ISSUE TITLE
Reordering of imports and modules is on by default, but config option is still unstable

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang-nursery/rustfmt#2651]
On the beta channel for the rustfmt-preview component, the following options appear to now be on by default, however the configuration option is only available on nightly:

* reorder_extern_crates_in_group (this isn't affecting my code, but I think it also changed recently; no longer on nightly)
* reorder_imports
* reorder_imports_in_group (consolidated, no longer needed on nightly)
* reorder_modules

If I set these to false in `rustfmt.toml` then on beta I see the following and get a large diff that reorders the statements:

```
$ cargo +beta fmt
Warning: can't set `reorder_imports = false`, unstable features are only available in nightly channel.
Warning: can't set `reorder_imports_in_group = false`, unstable features are only available in nightly channel.
Warning: can't set `reorder_modules = false`, unstable features are only available in nightly channel.
```

Since the default has changed I had hoped to temporarily put off this change, especially since the behavior of these options seems to have changed a bit between beta and nightly.

**Comment by nrc** [comment]
I don't really want to stabilise those options yet, so I don't see a solution on the Rustfmt side. This is fairly easy to workaround locally though - use either the stable or nightly channel while formatting (Rustup makes it very easy to switch channels).
