### ISSUE TITLE
normalize_comments is ignored inside rewrite_missing_comment

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#2655]
https://github.com/rust-lang-nursery/rustfmt/blob/d19fc450c06cd480ef2b9e1031b55ff10df080a7/src/comment.rs#L506

We should replace `false` with `context.config.normalize_comments`.

**Comment by c-edw** [comment]
Sorry to go for the low hanging fruit here! Hopefully I'll be able to contribute a little more in future.
