### ISSUE TITLE
index out of bounds: the len is 216 but the index is 216

### ISSUE THREAD

**Issue by Deedasmi** [rust-lang-nursery/rustfmt#2664]
Rust version: 
rustc 1.27.0-nightly (79252ff4e 2018-04-29)
nightly-x86_64-pc-windows-msvc (default)

Rustfmt version:
rustfmt 0.6.0-nightly (ac8ae006 2018-04-25)

Platform:
Windows 10

Project:
The current master of https://github.com/Deedasmi/Inquisitor. Clone and hit it with `cargo fmt --all`. 

Specifically, all packages work except `cargo fmt --package agent_plugins` (https://github.com/Deedasmi/Inquisitor/tree/master/agent/plugins). This package should be nearly identical to the receptor plugins folder as well, but that one rustfmt is fine with.

Apologies, I am not sure how to better troubleshoot rustfmt issues.

**Comment by nrc** [comment]
Thanks for filing an issue! Do you have a backtrace?

**Comment by Deedasmi** [comment]
It's not very useful. 

> 52: BaseThreadInitThunk
> 53: RtlUserThreadStart

The rest just shows `<unknown>`. This is apparently a Windows only issue though. My Arch laptop doesn't throw any errors,

**Comment by Pazzaz** [comment]
Here is a more minimal example:
````rust
fn main() {
    let a = "extern crate inquisitor_lib;
            use inquisitor_lib::AgentPlugin;

            #[macro_use]
            extern \
            crat
            #[macro_use]
            mod plugin_initialization
            plugins!({});
            \
             ";
}
`````
The error only happens if the file uses CRLF line endings, not when using LF.

**Comment by SingingTree** [comment]
Wasn't able to repro just now when attempting with the original case or the minimal example. Possibly fixed?

**Comment by nrc** [comment]
Hopefully
