### ISSUE TITLE
rustfmt skips rustfmt.toml if using stdin

### ISSUE THREAD

**Issue by ralphtheninja** [rust-lang-nursery/rustfmt#2668]
I'm using `rustfmt` in emacs and I've noticed that it doesn't care about my local `rustfmt.toml`. I _think_ this used to work before and might be a regression, or I'm doing something wrong.

`src/main.rs`:

```rust
fn main() {
println!("Hello, world!");
}
```

`rustfmt.toml`:

```toml
max_width = 80 
tab_spaces = 2 
```

If I do `rustfmt src/main.rs` it will indent `println!` two spaces (like expected).

If I do `cat src/main.rs | rustfmt` the output is indented with four spaces (standard formatting):

```cli
$ cat src/main.rs | rustfmt
fn main() {                   
    println!("Hello, world!");
}                             
```

**Comment by nrc** [comment]
This was fixed by https://github.com/rust-lang-nursery/rustfmt/pull/2663 I'l make a release with it in soon.

**Comment by ralphtheninja** [comment]
How do I get the `0.6.1` update in the nightly toolchain? `rustup update` gives me 0.6.0.

**Comment by nrc** [comment]
There will be an update soon - it is a somewhat manual process unfortunately

**Comment by ralphtheninja** [comment]
> There will be an update soon - it is a somewhat manual process unfortunately

I did a `cargo install --path .` in the repository meanwhile.
