### ISSUE TITLE
rustfmt output wrong path on windows

### ISSUE THREAD

**Issue by Xudong-Huang** [rust-lang-nursery/rustfmt#2674]
run `rustfmt --write-mode=diff` on windows
the correct output should be `Diff in \D:\project\rust\test\src\network.rs at line 102:`

but I got the following
```
rustfmt --write-mode=diff src\network.rs
Diff in \\?\D:\project\rust\test\src\network.rs at line 102:

     pub fn recv_message(&mut self) -> Result<String> {
         let msg = self.client.read_message()?;
-        match msg {
-        }
+        match msg {}
     }

     pub fn close(mut self) -> Result<()> {
Diff in \\?\D:\project\rust\test\src\network.rs at line 109:
         self.client.close(None)?;
-         Ok(())
+        Ok(())
     }
 }
```

why `\\?` is prefixed? `\\?\D:\` is not a valid path

**Comment by codeworm96** [comment]
According to https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath, a `\\?` prefix is valid.

> To specify an extended-length path, use the "\\\\?\" prefix. For example, "\\\\?\D:\very long path".

It is strange to me, too. But it is valid...

**Comment by nrc** [comment]
In any case, we are just using `Path::display()`, so if this is a bug it is with std.

**Comment by Xudong-Huang** [comment]
Sure, I didn't know that \\? is a valid windows path. This should be not a issue. Thanks!
