### ISSUE TITLE
Example Travis config in README does not work

### ISSUE THREAD

**Issue by davidalber** [rust-lang-nursery/rustfmt#2688]
#2683 changed the README Travis config example to use `--write-mode=check` instead of `--write-mode=diff`. That's not currently working in Travis. See [this build](https://travis-ci.org/davidalber/rustfmt-travis/builds/376278625), for example.

```
$ cargo fmt --all -- --write-mode=check
Invalid write-mode: check

The command "cargo fmt --all -- --write-mode=check" exited with 1.
```

Is this a matter of waiting for a new version to be stamped or is there something more fundamental wrong?

**Comment by nrc** [comment]
I think it might just need a more up to date rustfmt in the Rust repo, which should happen with today's nightly.

**Comment by volzkzg** [comment]
I use a nightly version rustfmt, but it says
`root@d115673865b5:~/cita# cargo fmt -- --write-mode=check
Unrecognized option: 'write-mode'`

**Comment by davidalber** [comment]
The Travis config snippet in the README still fails. I added a line (in a different repository) to print version information. Here's the relevant output for the current snippet:
```
$ rustup component add rustfmt-preview
$ cargo fmt -- --version
rustfmt 0.4.1-stable (7a80726 2018-04-20)

The command "cargo fmt -- --version" exited with 0.
$ cargo fmt --all -- --check
Unrecognized option: 'check'

The command "cargo fmt --all -- --check" exited with 1.
```

Thus, the change that added `--check` is not yet available in stable.

It works in nightly, though:
```
$ rustup component add rustfmt-preview
$ cargo fmt -- --version
rustfmt 0.7.0-nightly (db8cb0b 2018-05-16)

The command "cargo fmt -- --version" exited with 0.
$ cargo fmt --all -- --check

The command "cargo fmt --all -- --check" exited with 0.
```

When will the stable version change? Should we switch the config snippet to use nightly?

**Comment by nrc** [comment]
Yeah, we should use nightly. Stable should switch at the next release, i.e., 5-ish weeks time
