### ISSUE TITLE
Reflowing doc comments containing examples breaks stdsimd

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2691]
This doc comment

```rust
/// Foo
///
/// # Example
/// ```
/// # #![cfg_attr(not(dox), feature(cfg_target_feature, target_feature, stdsimd))]
/// # #![cfg_attr(not(dox), no_std)]
/// ```
fn foo() {}
```

is formattted to:

```rust
/// Foo
///
/// # Example
/// ```
/// # #![cfg_attr(not(dox), feature(cfg_target_feature, target_feature,
/// stdsimd))] # #![cfg_attr(not(dox), no_std)]
/// ```
fn foo() {}
```

which fails to compile (with max_width = 79).

---

@nrc would it be possible to add `stdsimd` as a test to rustfmt's ci ? 

That is, a test that checks out stdsimd master, builds everything (including tests and doc tests), then formats it with rustfmt, and then re-builds ?

**Comment by nrc** [comment]
I think we should not be reformatting examples in rustdoc without an opt-in.

> @nrc would it be possible to add stdsimd as a test to rustfmt's ci ?

That sounds like a good idea for a smoke test!

**Comment by gnzlbg** [comment]
> I think we should not be reformatting examples in rustdoc without an opt-in.

I think it is ok to disable this for now, but ideally rustfmt would detect examples into doc comments, and would format them as normal rust code but handling rustdoc idiosyncrasies appropriately (like lines that start with `#`).
