### ISSUE TITLE
Add corpus of crates to rustfmt's CI

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2692]
rustfmt upgrades break `stdsimd` too often. Skimming through this repo I cannot find integration tests in which rustfmt reformats already existing crates and check that they still compile and pass tests afterwards. 

I think rustfmt should at least do this for some of the nursery crates:

* [x] `rustfmt` itself: this seems obvious, but if after reformatting itself `rustfmt` fails to compile then it should definitely not be shipped to users
* [ ] `stdsimd`
* [ ] `futures-rs`
* [ ] `rand`
* [ ] `chalk`
* [ ] `failure`
* [ ] `crater`
* [ ] `glob`
* [ ] `cargo`
* [ ] `clippy`
* [ ] `error-chain`
* [ ] `mdbooks`
* [ ] `tempdir`
* [ ] `bitflags`
* [ ] `rust-semverver`
* [ ] `log`

That should provide a large enough corpus to check that rustfmt does indeed work properly.

**Comment by nrc** [comment]
We already do Rustfmt - in fact we have the stronger constraint that it must be char-for-char the same before and after formatting. Doing some of the other crates is definitely a good idea.

**Comment by nrc** [comment]
This would be a pretty big first issue, but it doesn't require knowledge of Rustfmt's internals, so it would be a good issue to work on.
