### ISSUE TITLE
Format comments

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#27]

**Comment by nrc** [comment]
Some early notes:

comments aren't in the AST, which makes processing them difficult, but then
comments are complicated anyway. I think I am happy putting off tackling them
for now. Long term the soluton is for comments to be in the AST, but that means
only the libsyntax AST, not the rustc one, which means waiting for the ASTs
to diverge one day....

Once we do have comments, we just have to implement a simple word wrapping
algorithm to keep the width under IDEAL_WIDTH. We should also convert multiline
/* ... */ comments to // and check doc comments are in the right place and of
the right kind.

Should also make sure comments have the right indent

**Comment by nrc** [comment]
I still think having comments in the AST is the long term solution (in particular we have doc comments, so why not other kinds?). I do think we should try and tackle comments soon though, even without AST support.

**Comment by marcusklaas** [comment]
Closing this since we're pretty most comments now, just poorly. There are specific issues to improve the situation.
