### ISSUE TITLE
Unrecognized option: 'write-mode' 

### ISSUE THREAD

**Issue by volzkzg** [rust-lang-nursery/rustfmt#2714]
I was trying to use write-mode configuration in my CI server.

`cargo +nightly-2018-05-17 fmt -- --write-mode check`

It turns out to be
`Unrecognized option: 'write-mode'`

I just installed a specific nightly version 2018-05-17 and install rustfmt by
`rustup component add rustfmt-preview --toolchain nightly-2018-05-17`

**Comment by nrc** [comment]
Use `--check` rather than `--write-mode=check`

**Comment by volzkzg** [comment]
@nrc Now it turns out to be 
`cargo manifest failed.`
