### ISSUE TITLE
Shorter Formatting of Marker Traits with Bounds

### ISSUE THREAD

**Issue by cramertj** [rust-lang-nursery/rustfmt#2736]
Rustfmt changes my marker trait implementations from

```rust
unsafe impl Sync for Foo where (): Send {}
```
to
```rust
unsafe impl Sync for Foo
where
    (): Send,
{
}
```

Personally, I think the first is much more readable, and if I omit the `where` clause it stays as-is. Is this behavior intentional? I don't particularly mind moving the `where` bounds to a second line, but two extra lines for the where clause plus the two lines for braces (rather than `{}`) seems too long to me.

**Comment by topecongiro** [comment]
From https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/items.md#impls:

> If there are no items, the impl may be formatted on a single line.

So in this case I think we want to put the whole `impl` on a single line as long as it does not exceed max width.

**Comment by csmoe** [comment]
@topecongiro to be clear, should the whole `impl` on a single line when there is **ONLY** one `where` clause like this:
```rust
impl Bar For Foo where (): Send {}
```
and leave the `impl`s who have more than ONE(>=2) `where` clauses as the rustfmt does currently?

**Comment by topecongiro** [comment]
> @topecongiro to be clear, ... leave the impls who have more than ONE(>=2) where clauses as the rustfmt does currently?

Yes

> So how to manipulate the `where_clause_str` in `rewrite_impl`?

I think that we can set `WhereClauseOption.compress_where` to `true` when the impl's body is empty, though this may interact in a surprising way with other options.
