### ISSUE TITLE
Test test::verify_check_works failing on windows

### ISSUE THREAD

**Issue by thibaultdelor** [rust-lang-nursery/rustfmt#2738]
This windows bug happens no matter the git `autocrlf` configuration.
Here is the result:
```shell
---- test::verify_check_works stdout ----
thread 'test::verify_check_works' panicked at 'Assertion failed for `{XXX}\rustfmt\target\debug\rustfmt --check .\temp_check.rs`
with: Unexpected return status: failure
stdout=``````
stderr=```Unrecognized option: 'check'
```', {XXX}\.cargo\registry\src\github.com-1ecc6299db9ec823\assert_cli-0.6.1\src\assert.rs:441:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Where `{XXX}` is my home folder.

After a git bisect, the responsible commit is 5d9f5aa05a668e7dfef87b46d89dad2884df9d41

**Comment by thibaultdelor** [comment]
@nrc TLDR; `verify_check_works` depends on the output of `cargo build`, are we ok with that?
@topecongiro Since you have added the `bug` label, does that mean we should avoid doing that? I can do a PR.

**Comment by alexheretic** [comment]
I ran into this too while testing #2745, I added an assert that will fail a `cargo clean; cargo test` run with `"no rustfmt bin, try running `cargo build` before testing"` to that pr.
