### ISSUE TITLE
Frequent compile error after rustup update

### ISSUE THREAD

**Issue by topecongiro** [rust-lang-nursery/rustfmt#2752]
Recently I frequently encounter errors similar to the following:
```
   Compiling rustc-ap-rustc_data_structures v148.0.0
error[E0599]: no method named `start` found for type `R` in the current scope
   --> /home/topecongiro/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structure
    |
122 |         let start = match range.start() {
    |                                 ^^^^^
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `start`, perhaps you need to implement it:
            candidate #1: `arrayvec::range::RangeArgument`
```

This happens after I run `rustup update`, and gets fixed after updating the `rustc-ap-*` crates to the latest version.

AFAIK rustfmt is not broken in rustc repo, so that is good. But it is quite unfortunate that we need to update `rustc-ap-*` crates everyday (or at least with every PR) to make ci work.

@nrc Do you have any idea what we can do?

**Comment by nrc** [comment]
Fixed now, I think
