### ISSUE TITLE
inconsistency in custom derive fields on stable

### ISSUE THREAD

**Issue by cardoe** [rust-lang-nursery/rustfmt#2756]
Using rustfmt shipped with Rust 1.26.0 (0.4.1-stable) I formatted some code. Attempting to format it again with Rust 1.26.1 (0.4.2-stable) results in the following diff.

```diff
diff --git a/src/main.rs b/src/main.rs
index 0d2c884..f408aa0 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -54,8 +54,9 @@ struct Config {
 #[structopt()]
 struct Opt {
     /// configuration file
-    #[structopt(short = "c", long = "config", parse(from_os_str),
-                default_value = "/etc/sakcl.conf")]
+    #[structopt(
+        short = "c", long = "config", parse(from_os_str), default_value = "/etc/sakcl.conf"
+    )]
     config: PathBuf,

     /// username whose SSH public key will be fetched
```

I've even created a `rustfmt.toml` with `rustfmt --dump-default-config rustfmt.toml` using 0.4.1-stable and then used 0.4.2-stable still resulted in the diff. The code in question is at https://gitlab.com/cardoe/sakcl/tree/f68e3aedf1f6ab56af4459cacdfdb533c70540fc

**Comment by nrc** [comment]
This is intentional - we changed how we formatted long attributes.
