### ISSUE TITLE
rustfmt breaks doc api with wrap_comments=true

### ISSUE THREAD

**Issue by fafhrd91** [rust-lang-nursery/rustfmt#2759]
rust fmt replaces `#` with `\\#### #`

so it converts code like this:

```
/// #[derive(Deserialize)]
```

to a 

```
/// //#### #[derive(Deserialize)]
```

**Comment by csmoe** [comment]
Could you provide some reproducing-snippet and meta info?
`rustfmt 0.8.2-nightly (173ae0d 2018-05-28)` works fine with following code when `wrap_comments=true`:
```rust
/// #[derive(Deserialize)]
foo() {}
```

**Comment by fafhrd91** [comment]
hmm, strange. I use same version of rustfmt, but I can not reproduce it on simple code.

but I can reproduce it on my project, here is config https://github.com/actix/actix-web/blob/master/rustfmt.toml
if I uncomment `wrap_comments` and run `cargo fmt` it insert `// ####` in bunch of places

**Comment by csmoe** [comment]
I cloned your repo and `cargo fmt` locally, it's really strange, some comments are formatted as normal, but some broken.
https://github.com/rust-lang-nursery/rustfmt/blob/4e09e5479ce2aa0964b0543fccfa18b149ec142a/src/comment.rs#L393-L394
It seems that `rustfmt` fails to `trim_custom_comment_prefix` some lines.
