### ISSUE TITLE
rustfmt errors out when trying to format crate

### ISSUE THREAD

**Issue by Lapz** [rust-lang-nursery/rustfmt#2760]
If you clone [xi-editor](https://github.com/google/xi-editor) and cd to the rust/core-lib directory and run rustfmt it fails with the following error ```Error writing files: io error: Couldn't find module client```.

## rustfmt version : 
```
rustfmt 0.8.2-nightly (173ae0d7 2018-05-28)
```

## Verbose output 

```rust 
[lib] "/Users/rowlandsonpratt/Lenard/Rust/xi-editor/rust/core-lib/src/lib.rs"
[test] "/Users/rowlandsonpratt/Lenard/Rust/xi-editor/rust/core-lib/tests/rpc.rs"
rustfmt /Users/rowlandsonpratt/Lenard/Rust/xi-editor/rust/core-lib/src/lib.rs /Users/rowlandsonpratt/Lenard/Rust/xi-editor/rust/core-lib/tests/rpc.rs
Error writing files: io error: Couldn't find module client
```

**Comment by nrc** [comment]
Could you try and create a minimal test case please? I assume that Xi has some odd module structure which is causing Rustfmt to choke

**Comment by Lapz** [comment]
I've gone ahead and created a [minimal test](https://github.com/Lapz/rfmt_case) case.
