### ISSUE TITLE
Weird indentation in or_else/and_then chain

### ISSUE THREAD

**Issue by edmccard** [rust-lang-nursery/rustfmt#2773]
Using rustfmt 0.4.2-stable, on rust 1.26.1, I type this:

```
fn foo() {
    let bar = Some(0);
    bar.or_else(|| {
        // do stuff
        None
    }).or_else(|| {
        // do other stuff
        None
    }).and_then(|val| {
        // do this stuff
        None
    });
}
```

and rustfmt turns it into this:

```
fn foo() {
    let bar = Some(0);
    bar.or_else(|| {
        // do stuff
        None
    }).or_else(|| {
            // do other stuff
            None
        })
        .and_then(|val| {
            // do this stuff
            None
        });
}
```

**Comment by nrc** [comment]
I was wondering if we should apply the same combining behaviour to the `}).and_then` and/or that the second `or_else` block should be single indented like the first `or_else` block.

**Comment by edmccard** [comment]
Having the second `or_else` block single-indented so it looked like this:

```
}).or_else(|| {
    // do other stuff
    None
})
    .and_then(|| {
        // do this stuff
        None
    )};
```

would be...less ugly, maybe? I think it would look better if all the calls in the chain were at the same indentation; I wonder if a case could be made for prioritizing the "Multi-line elements" guideline:

> If any element in a chain is formatted across multiple lines, then that element and any later elements must be on their own line. 

over the one that prevents "floating":

>If the length of the last line of the first element plus it's indentation is less than or equal to the indentation of the second line (and there is space), then combine the first and second lines

so that you'd end up with

```
fn foo() {
    let bar = Some(0);
    bar
        .or_else(|| {
            // do stuff
            None
        }).or_else(|| {
            // do other stuff
            None
        }).and_then(|val| {
            // do this stuff
            None
        });
}
```
