### ISSUE TITLE
[chalk] #[cfg(not(rustfmt))] does not skip modules

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2789]
rust-lang-nursery/chalk/chalk-parse/lib.rs 

contains a 

```rust
mod parser;
```

module that is generated with a `build.rs` script and when checking the project out does not exist. When running rustfmt on the project, it rightfully errors with

```shell
 --> /chalk/chalk-parse/src/lib.rs:15:5
   |
15 | mod parser;
   |     ^^^^^^
   |
   = help: name the file either parser.rs or parser/mod.rs inside the directory "/chalk/chalk-parse/src"
```

However, when I hide the module for `rustfmt` runs, rustfmt does still produce the same error: 

```rust
#[cfg(not(rustfmt))]
mod parser;
```

**Comment by gnzlbg** [comment]
cc @nrc

**Comment by gnzlbg** [comment]
@topecongiro any idea on how to pursue this?

**Comment by nrc** [comment]
could you use `#[rustfmt::skip]`?

**Comment by gnzlbg** [comment]
I'll give that a try. `chalk_parse` requires nightly already so that might work.

**Comment by gnzlbg** [comment]
So that did work, I've sent a PR to chalk upstream to "fix" this: https://github.com/rust-lang-nursery/chalk/pull/159

But I'd rather keep this issue open, since there should be a way to do this in stable Rust.

**Comment by nrc** [comment]
rustfmt::skip will be stabilised soon (it's just finished FCP). It should be stable in Rust 1.30 so closing this.

**Comment by gnzlbg** [comment]
@nrc could you ping me when `rustfm::skip` is stabilized on nightly? I'll send a PR to remove the `tool_attributes` feature from chalk upstream.

**Comment by nrc** [comment]
@gnzlbg this is very late, but tool attributes are stable now.
