### ISSUE TITLE
When there are multiple extraneous semicolons, only one is deleted at a time

### ISSUE THREAD

**Issue by ExpHP** [rust-lang-nursery/rustfmt#2791]
This is an example of non-idempotent formatting:
```rust
fn main() {
    let x = 2;;;;
}
```
is formatted to
```rust
fn main() {
    let x = 2;;;
}
```
which is formatted to
```rust
fn main() {
    let x = 2;;
}
```
etc.

**Comment by topecongiro** [comment]
Ugh, it's me...https://github.com/rust-lang/rust/pull/45060.

**Comment by topecongiro** [comment]
Ah, or maybe not. cc https://github.com/rust-lang/rust/pull/51629.
