### ISSUE TITLE
`imports_layout = "Vertical"` not always obeyed

### ISSUE THREAD

**Issue by jechase** [rust-lang-nursery/rustfmt#2794]
As of maybe a week ago, my `cargo +nightly fmt -- --check` jobs have been failing because they want to reformat my vertical, block-style imports to place some items on the same line.

[Here's an example project illustrating the issue.](https://github.com/jechase/rustfmt_example/tree/7c95dc85dca06c17f7f8967928f50a8428e8626e) Reproducing/version information is included in its `README.md`. I'll see if I can get a test case put together as well.

Interestingly, rls seems to apply the `Vertical` option correctly. 

Edit: Walking the commit history backwards led me to find [this PR](https://github.com/rust-lang-nursery/rustfmt/pull/2769) as the culprit.

**Comment by topecongiro** [comment]
Closed via #2795.
