### ISSUE TITLE
Ordering feature, derive, and cfg

### ISSUE THREAD

**Issue by joshleeb** [rust-lang-nursery/rustfmt#2798]
I really liked the change to rustfmt a little while ago that made ordering imports, with `use` statement, the default behaviour. 

Are there any thoughts or objections around implementing this same alphabetic ordering for `feature`, `derive`, and maybe `cfg` as well. 

For example:

```rust
#![feature(nll, thread_local)]

use std::ops::{Mul, Add};

#[derive(Debug, Clone)]
struct A {
    x: i32,
}
```

to be formatted as

```rust
#![feature(thread_local, nll)]

use std::ops::{Add, Mul};

#[derive(Clone, Debug)]
struct A {
    x: i32,
}
```

Instead of just changing the order of `use std::ops::{Add, Mul};` which is what rustfmt currently does.

**Comment by nrc** [comment]
For attributes (including derive) the order is semantically important (that is `derive(foo, bar)` could give a different result to `derive(bar, foo)`, so we are not able to support this in Rustfmt.
