### ISSUE TITLE
2018 edition reserved identifiers not supported

### ISSUE THREAD

**Issue by lnicola** [rust-lang-nursery/rustfmt#2801]
Clone https://github.com/lnicola/rustfmt-raw-idents and run `cargo fmt`. It will replace `r#async` with `async` and the code will stop building.

**Comment by Mark-Simulacrum** [comment]
cc @nrc @Centril  -- this seems like a rather critical bug

**Comment by topecongiro** [comment]
This is a duplicate of #2561.
