### ISSUE TITLE
Comments after function names in declarations get removed

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/rustfmt#283]
Pre:

``` rust
fn foo/*<T: Add>*/(a: T) {
}
```

Post:

``` rust
fn foo(a: T) {
}
```

**Comment by marcusklaas** [comment]
cc https://github.com/nrc/rustfmt/issues/21

**Comment by nrc** [comment]
I think this needs more span info in the AST, so it's not going to get fixed any time soon (although the HIR has landed now, so it is possible to start the libsyntax work).

**Comment by cassiersg** [comment]
I think we might detect if there is comments in some span (eg. from the beggining of the fn decl and the beginning of the first arg) and in that case give up.

**Comment by nrc** [comment]
dup of #458
