### ISSUE TITLE
rustfmt-nightly v0.8.2 rebuild failed with rustc 1.29.0-nightly (e06c87544 2018-07-06)

### ISSUE THREAD

**Issue by huoyuanliao** [rust-lang-nursery/rustfmt#2831]
software version:   
rustc 1.29.0-nightly (e06c87544 2018-07-06)
cargo 1.29.0-nightly (af9e40c26 2018-07-05)
rustup 1.11.0 (e751ff9f8 2018-02-13)

when running: cargo install rustfmt-nightly --force
cargo prepare to reinstall rustfmt-nightly v0.8.2 , and then Error with:
error[E0658]: use of unstable library feature 'raw_vec_internals': implemention detailderive, rustc-ap-arena                                                                         
  --> /Users/liaozy/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/rustc-ap-arena-147.0.0/lib.rs:46:5
use alloc::raw_vec::RawVec;

**Comment by topecongiro** [comment]
This is fixed with `rustc 1.29.0-nightly (9fd3d7899 2018-07-07)`.

**Comment by tafia** [comment]
I have the same issue with rustc 1.30.0-nightly (73c78734b 2018-08-05), when trying to build directly from source.
