### ISSUE TITLE
formatting strings appears to be sub-optimal w.r.t. line length limits

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/rustfmt#2833]
Versions:

```
$ rustc --version
rustc 1.29.0-nightly (9fd3d7899 2018-07-07)
$ cargo --version
cargo 1.29.0-nightly (af9e40c26 2018-07-05)
$ rustfmt --version
rustfmt 0.8.2-nightly (5e59925 2018-07-02)
```

Input source code:

```rust
fn test() {
    let expected = "\
but Doctor Watson has to have it taken out for him and dusted,
";
}
```

Config:

```toml
format_strings = true
max_width = 80
```

Result of applying `rustfmt`:

```rust
fn test() {
    let expected = "\
but Doctor Watson has to have it taken out for him and \
                    dusted,
";
}
```

Since the input code was with the maximum line length limits, I would have expected `rustfmt` to not do anything here. If I remove the `max_width` setting (allowing the default of `100` to apply), then `rustfmt` leaves the above code untouched. However, modifying the string slightly causes the wrapping to fail even when `max_width` is allowed to be its default value. e.g., this code

```rust
fn test() {
    let expected = "\
[Omitted long matching line]
but Doctor Watson has to have it taken out for him and dusted,
";
}
```

gets formatted to

```rust
fn test() {
    let expected = "\
[Omitted long matching line]
but Doctor Watson has to have it taken out for \
                    him and dusted,
";
}
```

where `rustfmt.toml` just contains `format_strings = true`.

**Comment by nrc** [comment]
Yeah, since we moved formatting string literals to be an option, the formatting hasn't seen much love and is a bit rusty. Hopefully one day we'll find a way to make it awesome.
