### ISSUE TITLE
Newline separator between structs

### ISSUE THREAD

**Issue by theduke** [rust-lang-nursery/rustfmt#2843]
Currently, if a file contains multiple structs without newline separators, no empty separator line is added.
They are preserved though if already present.

eg:
```rust
struct A {
    a: bool,
}
struct B {
  b: bool,
}
```

IMO, a newline should be added between A and B.

**Comment by nrc** [comment]
This was discussed in https://github.com/rust-lang-nursery/fmt-rfcs/issues/57
