### ISSUE TITLE
Windows line endings

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#2846]
After recently changing windows default line endings from `Unix` to `Native`, it turns out that this is in fact somewhat controversial. The argument for unix is that it supports Rust's cross-platform mission and makes it easy to collaborate across platforms. The argument for native is that it is what Git does by default (I don't exactly understand what happens, but I guess you get windows line endings when editing, and then Git converts them all to unix when you commit?). An alternative is to try and detect the line endings and use that, but I'd rather avoid doing that.

cc #2626 
cc #2823 

Twitter discussion: https://twitter.com/nick_r_cameron/status/1019019484865093634

**Comment by nrc** [comment]
> An alternative is to try and detect the line endings and use that, but I'd rather avoid doing that.

I'm thinking this is perhaps a viable approach after all - mainly because it does not need to be perfect, we can capture the two main use cases (Git handling line endings or preferring `\n`) by just looking at the first line in the crate. 

The reasons I would avoid this are the risk of non-idempotence, but I believe the 'first line' check is idempotent; and implementation complexity but the 'first line' check should be pretty simple.

**Comment by nrc** [comment]
The approach I'd like to try is to add an `Auto` variant to `NewlineStyle` and to make it the default. This variant would inspect the first line of the crate and use that line ending everywhere. We'd add that to the first half of `replace_with_system_newlines` in lib.rs. We will probably want to find the first newline in `format_ast` and pass that in, or perhaps pass in the `SnippetProvider` if that has an easy API to find the first newline.

cc @fwalch are you keen to give this a go? If so is there enough info here for you to get started?

**Comment by fwalch** [comment]
@nrc I won't have time to work on this for the next week or so, but if this is still around afterwards, I might give it a shot.

**Comment by nrc** [comment]
> but if this is still around afterwards, I might give it a shot.

It should be, unless it's the only thing blocking the release candidate, in which case I'll probably fix it.

**Comment by nrc** [comment]
This addressed in https://github.com/rust-lang-nursery/rustfmt/pull/2873
