### ISSUE TITLE
Changing vec!(...) to vec![...] breaks convert_args! macro

### ISSUE THREAD

**Issue by tecywiz121** [rust-lang-nursery/rustfmt#2857]
I originally filled a bug with the developer of the maplit crate: bluss/maplit#21 .

My issue is that rustfmt seems to change `convert_args!(vec!(1, 2, 3))` to `convert_args!(vec![1, 2, 3])` which doesn't compile.

The maplit developer replied with:

> Combining macros like this was deemed idiomatic (see nom, it prefers ()'s), so it seems like an issue with rustfmt.

**Comment by nrc** [comment]
hmm, I guess we should have an option for this kind of changes? Probably the best thing to do for now is to use `#[rustfmt::skip]`.

In general, using square brackets for `vec!` is idiomatic, but when compiling macros, I guess using parens makes it easier or something? I don't think we can detect nesting of macros though.

**Comment by topecongiro** [comment]
Detecting nesting of macros should be possible via #2834. I think that I can work on it this week.

**Comment by bluss** [comment]
Inside a macro's brackets it is hard for rustfmt to tell which transformations it can do and still have the code compile. In this case the example is that brackets don't matter for the outer invocation, but the inner invocation is actually taken apart by pattern matching (nom does there combinators like this too), so `convert_args!` has to be specific about `(` vs `{`.

The careful standpoint should be that we can't reformat code inside macros IMO.

If you want format the arguments to macros, potentially use a whitelist, or even look at the macro matchers? For example, we know that in `vec![a, b, c]`, it is ok to reformat a, b, c to any other valid expressions, and we can see from the macro definition that it expects expressions.
