### ISSUE TITLE
Publishing 0.9 to crates.io

### ISSUE THREAD

**Issue by Lytigas** [rust-lang-nursery/rustfmt#2875]
I don't know what the publishing policy is, but it would be nice to have the fixes for the latest nightly compiler (#2865) because the generic `rustup run nightly cargo install -f rustfmt-nightly` is broken right now.

Also, would it make sense to add regular (nightly?) publishes with CI?

**Comment by nrc** [comment]
Rustup installation should be fixed with today's nightly (using `rustup component add rustfmt-preview`, `rustup update --force`).

I'm planning to release to Cargo (and a new version to Rustup) later this week.
