### ISSUE TITLE
Replacement for --write-mode=plain

### ISSUE THREAD

**Issue by vitalyd** [rust-lang-nursery/rustfmt#2885]
After upgrading to rust 1.28, I noticed that the `--write-mode` CLI arg is gone.  I have some code that was using `--write-mode=plain` to format some generated code and send it to stdout.  The difference between `plain` and `display` options in the previous versions is that `plain` did not include the file name in the output, whereas `display` would.

I tried `--emit stdout` but this appears to behave like `--write-mode=display`.  Is there a way to get the old behavior?

**Comment by nrc** [comment]
You need `--emit stdout` and `--quiet` (or `-q`)

**Comment by vitalyd** [comment]
Thanks @nrc - I’ll give that a try.
