### ISSUE TITLE
outdated README

### ISSUE THREAD

**Issue by isonmad** [rust-lang-nursery/rustfmt#2893]
Since the version numbering reset in 5f1bab26c4bb95e91a90a9fb581e246a08df3d85 and since rustfmt hit version 0.9 for the second time, the readme is confusing(especially since there's no rustfmt-nightly 0.8.6) and makes this sound like a recent/ongoing change:
> We are changing the default style used by rustfmt. There is an ongoing RFC process. The last version using the old style was 0.8.6. From 0.9 onwards, the RFC style is the default. If you want the old style back, you can use legacy-rustfmt.toml as your rustfmt.toml.

And `--config-help` has been gone since 798bffb8b1e24b05a93745db14ce287d5ecddef6 but it's still mentioned, instead of `--help=config`:
> See rustfmt --config-help for the options which are available, or if you prefer to see visual style previews, Configurations.md.

**Comment by isonmad** [comment]
#2902 tried to fix this but cb10e06559ce583760f964385ca38d9aa59067a9 got the command backwards.

**Comment by scampi** [comment]
@nrc this seems to be fixed.
