### ISSUE TITLE
Space struct initialisation like array initialisation: no spaces around braces

### ISSUE THREAD

**Issue by vincentdephily** [rust-lang-nursery/rustfmt#2904]
# Expected
```rust
let s1 = MyStruct{foo: 42};
let a1 = vec![42];
let f1 = MyStruct::new(42);

let s2 = YourStruct{a: 1,
                    b: 2,
                    c: 3,
                    d: 4,
                    e: 5};
let a2 = vec![1,
              2,
              3,
              4,
              5];
let f2 = YourStruct::new(1,
                         2,
                         3,
                         4,
                         5);
```

# Observed
```rust
let s1 = MyStruct { foo: 42 };
let a1 = vec![42];
let f1 = MyStruct::new(42);

let s2 = YourStruct { a: 1,
                      b: 2,
                      c: 3,
                      d: 4,
                      e: 5, };
let a2 = vec![1,
              2,
              3,
              4,
              5];
let f2 = YourStruct::new(1,
                         2,
                         3,
                         4,
                         5);
```

# Rationale
Struct initialisation is arguably much like array initialisation or function call and should be formatted similarly, instead of being formatted like control flow just because it uses braces. 

I've used `indent_style = "Visual"` in these examples to make the inconsistency more obvious, but the argument stands for the default `indent_style`, especially when code fits on a single line.

Of course that's subjective and would be a significant change, so this might need to be controlled by an option. I have no set opinion on what that option should be (name, values, default...).

**Comment by nrc** [comment]
This was discussed in the fmt RFC process and we thought it better to be consistent around braces, and that nearly all existing code does this.

**Comment by vincentdephily** [comment]
So lexical consistency was chosen over semantic consistency ? I appreciate the fact that this decision was the result of a discussion, but I can't help but feel that the other POV has a compelling argument: the meaning/function of a token is more important than its look/glyph.

Would a PR introducing some kind of `struct_brace_spacing` option be worth a shot, or is the topic definitively closed ? Are there guidelines regarding when the maintenance burden of an extra option is worth it in rustfmt ?
