### ISSUE TITLE
Poor formatting of slice_patterns

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rustfmt#2909]
```rust
#![feature(slice_patterns)]

fn main() {
    match b"123" {
        [0, ..] => {}
        _ => {}
    }
}
```

As of rustfmt 0.99.1-nightly (da17b68 2018-08-04), formatting produces the following diff which I believe is less readable than the original:

```diff
-         [0, ..] => {}
+         [0, _..] => {}
```

**Comment by faern** [comment]
Why is `_..` even accepted syntax? It is not allowed in normal pattern matching:
```rust
let (a, _..) = (1, 2 ,3);
```
does not even compile.
