### ISSUE TITLE
Deprecation error goes to stdout instead of stderr

### ISSUE THREAD

**Issue by lassik** [rust-lang-nursery/rustfmt#2913]
When I run `rustfmt` (apparently with any set of options or with no options at all), I get the message:

```
This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.

usage: rustfmt [options] <file>...

Options:
...
```

The message is printed to stdout instead of stderr, which is problematic in the case where a script runs it to format code from stdin to stdout. Because rustfmt correctly exits with a non-zero exit code, the script throws away the contents of stdout and shows the contents of stderr to the user as the error message. Since nothing is currently written to stderr in this case, the user will not see any error message.

If this behavior still persists in the current version of, I suggest fixing it so that the deprecation message is written to stderr instead of stdout. According to `rustfmt --force --version` I have version `0.10.0`.

**Comment by nrc** [comment]
You should remove your version of rustfmt, it is very old. You should install Rustfmt using Rustup if you can (`rustup component add rustfmt-preview`) or cargo (`cargo install rustfmt-nightly`). Note that the rustfmt crate is just a tombstone.
