### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by PSeitz** [rust-lang-nursery/rustfmt#2914]
The report_todo setting in my rustfmt.toml seems to produce an ``` internal error: entered unreachable code``` (project: https://github.com/PSeitz/native_search).
I am using the latest nightly version.

    report_todo = "Always"
    report_fixme = "Always"

Setting this to ```Never``` removes the issue, but the todo list is missing then.

```
➜  native_search RUST_BACKTRACE=1 cargo fmt
warning: found TODO
   --> /Users/d056831/Development/native_search/tests/tests.rs:928
thread 'main' panicked at 'internal error: entered unreachable code', tools/rustfmt/src/formatting.rs:282:18
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: rustfmt_nightly::formatting::FormattingError::format_len
   7: rustfmt_nightly::FormatReport::fancy_print
   8: rustfmt::format_and_emit_report
   9: <rustfmt_nightly::Session<'b, T>>::override_config
  10: rustfmt::execute
  11: rustfmt::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
```

**Comment by PSeitz** [comment]
It seems in this pattern match is ```ErrorKind::BadIssue(Issue)``` missing
https://github.com/rust-lang-nursery/rustfmt/blob/7c1ad96e9fca2186e691f64be55e96fec6a204be/src/formatting.rs#L265-L283

**Comment by DevOrc** [comment]
I'd like to attack this one.

**Comment by DevOrc** [comment]
After some investigating I have found that this only happens if the line is over 100 characters long

**Comment by PSeitz** [comment]
My understanding of rustfmt is, that all comments are left unchanged. TODO and FIXME may be special cases because they are traced to the console.

**Comment by nrc** [comment]
> I'd like to attack this one.

Great, thank you!

It looks like we're getting a kind of error we weren't expecting here. It sounds like you have a test case already. Next step is to figure out what should happen here in the `BadIssue` case.

**Comment by DevOrc** [comment]
I am correct in thinking that nothing should happen here unless wrap_comments is on?

**Comment by nrc** [comment]
> I am correct in thinking that nothing should happen here unless wrap_comments is on?

Sort of. If wrap_comments is not on, we might still move a comment and thus make it exceed max_width. Also the bad issue 'lint' will trigger independently of wrap_comments.

**Comment by DevOrc** [comment]
Hey, Sorry I haven't responded sooner but I am ready to get back into this!

> Next step is to figure out what should happen here in the BadIssue case
> 

In this case should the line be shortened to max width?

**Comment by nrc** [comment]
> In this case should the line be shortened to max width?

I don't think so. I think this is just about error handling and we have to be able to handle the `BadIssue` case when it occurs.

**Comment by PSeitz** [comment]
I created a pull request for this, the behavior is now the same as in the other cases, which adds snippets for TODO and FIXME. IIRC there were previously only line numbers. I think it's better with snippets.
