### ISSUE TITLE
cargo fmt --all succeeds but --check fails

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#2917]
In these two files: https://gist.github.com/gnzlbg/fda65f2f8bd7b8517be4b8db1fbc7d73

`cargo fmt --all` succeeds, but `cargo fmt --all -- --check` fails. 

cc @nrc @topecongiro

**Comment by gnzlbg** [comment]
This is currently triggered in packed_simd master, e.g., in this commit: https://github.com/rust-lang-nursery/packed_simd/commit/d8b14721f79ae696b177d443365f80269d9a92e9

It also feels like rustfmt fails to properly align the comment, e.g., it aligns the `//` comment differently than the `/* */` one.

**Comment by topecongiro** [comment]
A minimal example:

```rust
macro_rules! foo {
    () => {
        // comment
        /*

        */
    };
}
```

Diff:

```diff
 macro_rules! foo {
     () => {
         // comment
-        /*
+                /*
 
-        */
+                */
     };
 }
```

**Comment by scampi** [comment]
I will try to check this one
