### ISSUE TITLE
Inappropriate handling of environment variable LD_LIBRARY_PATH in README.

### ISSUE THREAD

**Issue by taro-yamada** [rust-lang-nursery/rustfmt#2923]
I'm sorry, this is a very trivial thing.

README.md said
> If you get an error like error while loading shared libraries while starting up rustfmt you should try the following:
> On Linux:
> `export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH`

In this case, if LD_LIBRARY_PATH is empty, the current directory will be included in LD_LIBRARY_PATH and causes potential security problems.

I think that it is good to do as following.
`export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}`

**Comment by topecongiro** [comment]
Thanks! I think we can totally remove this part from README as now rustfmt does not depend on `libsyntax` directly anymore.

**Comment by topecongiro** [comment]
Closed via #2974.
