### ISSUE TITLE
Leading :: removed but necessary for disambiguation in 2018 edition

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang-nursery/rustfmt#2927]
Heya, I think I ran into a a bug with the `uniform_paths` feature. I've included the expected output, and error case below. Run on `rustfmt 0.99.2-nightly (2018-08-07)`. I hope this comes in useful. Thanks! :sparkles:

## Expected
This is the code I'm trying to write. We need the `::log` prefix because the compiler is unsure which instace of `log` we're trying to refer to.
```rust
#![feature(rust_2018_preview, uniform_paths)]

use futures::prelude::*;
use http_03::cli::Cli;
use hyper::{service::service_fn_ok, Body, Response, Server};
use ::log::{error, info, log};
use structopt::StructOpt;
```

## Current
`rustfmt` changes `::log` to `log` which prevents the code from compiling (error included below).
```rust
#![feature(rust_2018_preview, uniform_paths)]

use futures::prelude::*;
use http_03::cli::Cli;
use hyper::{service::service_fn_ok, Body, Response, Server};
use log::{error, info, log};   // The `::` prefix is removed here
use structopt::StructOpt;
```

### Error Message
![2018-08-17-133200_1920x1080](https://user-images.githubusercontent.com/2467194/44264180-e4bcd080-a221-11e8-96dd-5394dee8656a.png)

**Comment by orium** [comment]
It doesn't need to be macro imports.  In this code:

```rust
#![feature(rust_2018_preview, uniform_paths)]
extern crate criterion;
use ::criterion::Criterion;
```

`rustfmt` will also rewrite `use ::criterion::Criterion;` to `use criterion::Criterion;`

**Comment by scampi** [comment]
@nrc Should this issue be closed, given the PR got merged ?

**Comment by orium** [comment]
@nrc what is that option?

**Comment by crw5996** [comment]
@orium you can add `edition = "Edition2018"` to rustfmt.toml to fix the problem

**Comment by orium** [comment]
That lead me to discover #2989 :)

**Comment by orium** [comment]
This bug is still present even if you set the edition to 2018:

```text
orium@laptop-orion tmp % cat .rustfmt.toml
edition = "Edition2018"
orium@laptop-orion tmp % cargo +nightly fmt -- --check
Diff in /tmp/orium/tmp/src/lib.rs at line 1:
 #![feature(rust_2018_preview, uniform_paths)]
 extern crate criterion;
-use ::criterion::Criterion;
+use criterion::Criterion;
```

**Comment by jonhoo** [comment]
The title of this issue should probably be updated. I filed #3026 before finding this by digging through the commit logs :p

**Comment by yoshuawuyts** [comment]
@jonhoo you're right -- changed it to use the title of the issue you opened, because that seems like a better description of what's going on.

**Comment by nrc** [comment]
Yeah, this is fixed on master. I'll update nightly rustfmt later in the week.

**Comment by orium** [comment]
@nrc Will this be released as part of the next beta?  I'm mentioning this because it would the current beta is the 2018 edition RC.

**Comment by nrc** [comment]
Probably. I am planning a beta uplift, not sure exactly when it'll happen.
