### ISSUE TITLE
Issue with comment in use statement

### ISSUE THREAD

**Issue by philipper905** [rust-lang-nursery/rustfmt#2934]
When I have this
```
use std::{
    // cell::RefCell,
    ops::{Index, IndexMut},
    rc::Rc,
};
```
Rustfmt will convert the file to this:
```
use std::{
    // cell::RefCell, ops::{Index, IndexMut},
    rc::Rc,
};
```
Which means that second line is also commented out.
This isn't really much of a problem in practice but just wanted to alert in case it was a unknown issue.

**Comment by crw5996** [comment]
I was unable to reproduce this error with the information given. I cloned and built rustfmt used the following program...  
```
use std::{
    // cell::RefCell,
    ops::{Index, IndexMut},
    rc::Rc,
};

fn main() {
    println!("HELLO WORLD!");
}
```
and the resulting file was exactly the same after running rustfmt on the file. I'm curious if I am missing something?

**Comment by nrc** [comment]
This might be fixed on master, but not on nightly?

**Comment by philipper905** [comment]
yeah, it works correctly on master.
