### ISSUE TITLE
comma inserted after elipses in enum match

### ISSUE THREAD

**Issue by bholley** [rust-lang-nursery/rustfmt#2936]
STR:

`cargo +nightly fmt --version` # rustfmt 0.99.2-nightly (5c9a2b6c 2018-08-07)

git clone https://github.com/mozilla/gecko-dev.git mc
pushd mc
git reset --hard 3e61ab4489121084369c2be0ef6ea9f935b6aa7b
pushd servo/ports/geckolib
cargo +nightly fmt

Console Output: https://gist.github.com/bholley/8f4b5c90f94d16d833ad5e0777d16c5d
Formatted code: https://gist.github.com/bholley/49e91bdce580394c1ab6c61088f4d4a4

**Comment by topecongiro** [comment]
Closed via #2942.
