### ISSUE TITLE
Option unstable-features is not recognised

### ISSUE THREAD

**Issue by scampi** [rust-lang-nursery/rustfmt#2958]
Seen on 10512a59d00cd5b1f134d78a7ff4e2ce5abb9b12

```sh
$ ./target/debug/rustfmt --unstable-features file.rs
Unrecognized option: 'unstable-features'
```

However, it is mentioned https://github.com/rust-lang-nursery/rustfmt/blob/e7932fa9c2591c45a37a24305de90cb63128afcf/Configurations.md#configuring-rustfmt

**Comment by nrc** [comment]
If you're building Rustfmt yourself, you need to set `CFG_RELEASE_CHANNEL` to `nightly` or `dev` to use unstable features.

**Comment by scampi** [comment]
Thanks @nrc
