### ISSUE TITLE
extern "Rust" dropped from function pointer argument

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/rustfmt#2960]
Formatting `fn foo(constructor: extern "Rust" fn(Fragment))` yields `fn foo(constructor: fn(Fragment))`. I honestly don't know if it's equivalent or not, but it's really unsettling.

**Comment by nrc** [comment]
> I honestly don't know if it's equivalent or not, but it's really unsettling.

They are equivalent. As far as I know, the Rust AST doesn't distinguish between no abi and `extern(Rust)`, so I don't think we can do anything about this.
