### ISSUE TITLE
Weird indentation for method call

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/rustfmt#2961]
The following:
```
           new_style = context.stylist.style_for_anonymous::<E>(
                &context.guards,
                pseudo,
                &new_style,
            );
```
gets formatted as:
```
           new_style =
                context
                    .stylist
                    .style_for_anonymous::<E>(&context.guards, pseudo, &new_style);
```
which turns out to be longer horizontally than the original.

**Comment by nrc** [comment]
On master, I get

```
    new_style = context
        .stylist
        .style_for_anonymous::<E>(&context.guards, pseudo, &new_style);
```

We don't try and give the shortest (in any dimension) formatting, rustfmt just sticks to rules which are defined to give a clear, fairly succinct formatting. In this case we prefer keeping the short function call on one line rather than the chain, which reflects precedence.
