### ISSUE TITLE
Possibly some good ideas for refactoring

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#297]
http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/

Seems pretty sophisticated, we can probably learn things

**Comment by nrc** [comment]
It seems mostly at odds with rustfmt's heuristic approach though

**Comment by zBaitu** [comment]
It's an interesting implementation, but I agreed some points that this guy said: http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/#comment-2251750238

@nrc 
I wrote another Rust source code formatter: rfmt, https://github.com/zBaitu/rfmt. It is just a personal toy that I use it for writing Rust code. I expect if it can suits one's taste.
