### ISSUE TITLE
Unstable formatting

### ISSUE THREAD

**Issue by casey** [rust-lang-nursery/rustfmt#2973]
I'm trying to start using rustfmt in a project, but the formatting doesn't appear to be stable. 

This pull request shows the issue: https://github.com/casey/just/pull/346

The first commit just removes some trailing whitespace that rustfmt was having problems with: https://github.com/casey/just/pull/346/commits/b1aab6147d5a85381365d30402892239160114d4

The second is post-`cargo fmt`: https://github.com/casey/just/pull/346/commits/58fbd7a3e7326d311e38ad6cece254fa438efaf9

And the third shows that running `cargo fmt` again still produced a diff: https://github.com/casey/just/pull/346/commits/5fda35323684ff1288e7c0c9a53a23ac86613ff8

If I keep running `cargo fmt`, the affected lines continue drifting to the right. I think it's an issue with my weird unit-test generating macros 😝

**Comment by nrc** [comment]
Seems to be an issue with indentation inside macros.
