### ISSUE TITLE
To specify an edition in `.rustfmt.toml` you have to set `edition = "Edition2018"`, instead of "2018"

### ISSUE THREAD

**Issue by orium** [rust-lang-nursery/rustfmt#2989]
This looks like automatic deserialization problem.  Currently it only accepts

```
edition = "Edition2018"
```

instead of 

```
edition = "2018"
```

**Comment by mehcode** [comment]
This just got fixed with https://github.com/rust-lang-nursery/rustfmt/pull/2984
