### ISSUE TITLE
Strange function call line-breaks with short variable names

### ISSUE THREAD

**Issue by daniel-ferguson** [rust-lang-nursery/rustfmt#2994]
Rustfmt version: `rustfmt 0.99.2-nightly (5c9a2b6 2018-08-07)`

I've extracted a minimal test case mimicking https://github.com/pikkr/pikkr/blob/master/src/avx.rs#L5-L38

Running `rustfmt` on the following code (default rustfmt config)...

```
fn foo(
    _: u8, _: u8, _: u8, _: u8, _: u8, _: u8, _: u8, _: u8,
    _: u8, _: u8, _: u8, _: u8, _: u8, _: u8, _: u8, _: u8,
    _: u8, _: u8, _: u8, _: u8, _: u8, _: u8, _: u8, _: u8,
    _: u8, _: u8, _: u8, _: u8, _: u8, _: u8, _: u8, _: u8,
) {
    unimplemented!()
}

fn bar(i: u8) {
    foo(
        i, i, i, i, i, i, i, i,
        i, i, i, i, i, i, i, i,
        i, i, i, i, i, i, i, i,
        i, i, i, i, i, i, i, i,
    )
}
```

Results in this:

```
fn foo(
    _: u8,
    ...
    _: u8,
) {
    unimplemented!()
}

fn bar(i: u8) {
    foo(
        i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i,
        i, i,
    )
}
```

The arguments in the call to `foo` are split pretty strangely, I'd expect them to be formatted with one arg on each line:

```
fn bar(i: u8) {
    foo(
        i,
        ...
        i,
    )
}
```

Replacing the variable name `i` with something longer results in the formatting matching my expectations.

---

Is this formatting behaviour intentional? I'm struggling to think of a case where I'd want a function's arguments split unevenly across multiple lines.

**Comment by topecongiro** [comment]
I think that this is intentional, the previous issue was #2196.

**Comment by nrc** [comment]
Hmm, I wonder if we want to only go to mixed formatting for arrays, not function calls? This is kinda sucky because I don't think there is a good formatting for this kind of edge case (at least with the currently available options) so it will probably need to be skipped in any case, but doing something different for fn decls and fn calls does seem a bit weird (c.f., arrays where there is no equivalent to the decl).

**Comment by nrc** [comment]
Well, formatting one per line looks awful, and I think usually the user will want to skip this, so lets close.
