### ISSUE TITLE
Formatting of match arms with long guards is a bit awkward. 

### ISSUE THREAD

**Issue by emilio** [rust-lang-nursery/rustfmt#3005]
```diff
             match *token {
                 Token::Dimension {
                     value, ref unit, ..
-                } if num_context.is_ok(context.parsing_mode, value) =>
+                }
+                    if num_context.is_ok(context.parsing_mode, value) =>
                 {
                     return NoCalcLength::parse_dimension(context, value, unit)
                         .map(LengthOrPercentage::Length)
                         .map_err(|()| location.new_unexpected_token_error(token.clone()))
                 },
```

Not sure it's expected, feel free to close if so, but I have never seen a human use that formatting :)

**Comment by scampi** [comment]
@emilio This indentation is expected I think as per the [style guide](https://github.com/rust-lang-nursery/fmt-rfcs/blob/070ed1396d2ad4eda919bf08a797446b957d3ca1/guide/expressions.md#line-breaking). @nrc should the guide be revised or close the issue as a wont fix ?

**Comment by nrc** [comment]
I think we didn't consider the case where there is a `}` on it's own line in the pattern of the match arm. In that case, I think we should apply the 'combining' rules. This could be clarified in the style guide.

**Comment by crumblingstatue** [comment]
I believe I'm experiencing the same issue with [rust-sfml](https://github.com/jeremyletang/rust-sfml).
Diff from old to new rustfmt behavior:
```Diff
diff --git a/examples/pong.rs b/examples/pong.rs
index 4bfa5ed..cf3928c 100644
--- a/examples/pong.rs
+++ b/examples/pong.rs
@@ -101,7 +103,8 @@ fn main() {
                 } => return,
                 Event::KeyPressed {
                     code: Key::Space, ..
-                } if !is_playing =>
+                }
+                    if !is_playing =>
                 {
                     // (re)start the game
                     is_playing = true;

```
