### ISSUE TITLE
Generics in associated types

### ISSUE THREAD

**Issue by msiglreith** [rust-lang-nursery/rustfmt#3006]
Generics of associated types are removed by rustfmt.
The future is not stable but I think the syntax is already (?).

Before:
```Rust
trait Foo<'a> {
    type Bar<'a>;
}
```
After:
```Rust
trait Foo<'a> {
    type Bar;
}
```

https://play.rust-lang.org/?gist=e0614ea726bfdc99ea733ab96e724e0a&version=nightly&mode=debug&edition=2015

**Comment by topecongiro** [comment]
This seems to be a bug in rustc, the ast node does not contain the lifetime bounds.
