### ISSUE TITLE
fails to format  commented code: ```{…}```

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rustfmt#3018]
````rust
/// ```
///  { … }
/// ```
fn main() {
  }
````
rustfmt silently bails out on this code which can be found in the clippy_lints package.

This silent bailout caused my to find #3008 and prevents all further formatting by `cargo fmt` on the clippy_lints crate.

**Comment by otavio** [comment]
This has been fixed by #3058. I think this could be closed.
