### ISSUE TITLE
Odd choice for match inside of enum constructor

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/rustfmt#3029]
Before:
```rust
            EvaluateJSReply::NumberValue(
                match FromJSValConvertible::from_jsval(cx, rval.handle(), ()) {
                    Ok(ConversionResult::Success(v)) => v,
                    _ => unreachable!(),
                })
```
After:
```rust
            EvaluateJSReply::NumberValue(match FromJSValConvertible::from_jsval(
                cx,
                rval.handle(),
                (),
            ) {
                Ok(ConversionResult::Success(v)) => v,
                _ => unreachable!(),
            })
```

This appears to be specific to `match` expressions, since a couple lines down this line is unmodified:
```rust
EvaluateJSReply::StringValue(String::from(jsstring_to_str(cx, rval.to_string())))
```

I find the formatted code difficult to read because I have trouble remembering the context in which those vertically-spaced expressions are being evaluated.

**Comment by jdm** [comment]
Also the fact that the closing `)` for `FromJSValConvertible::from_jsval` is indented at the level of `NumberValue`'s closing `)` is also visually confusing for me.

**Comment by topecongiro** [comment]
I think we should combine `match` (and `if` as well) only when its condition expression fits in a single line.
