### ISSUE TITLE
Trait implementation and trait declaration with no body and many bounds have inconsistent bracing style

### ISSUE THREAD

**Issue by daboross** [rust-lang-nursery/rustfmt#3046]
For example, see this trait and implementation

```rust
pub trait SpawnPrioritization:
    Ord + Copy + Clone + 'static + Serialize + Deserialize<'static> + TransferOwnership
{
}

impl<T> SpawnPrioritization for T where
    T: Ord + Copy + Clone + 'static + Serialize + Deserialize<'static> + TransferOwnership
{}
```

The main annoyance here is that one has a newline before `}` and the other doesn't, where they are otherwise formatted the same.

This doesn't occur for all traits, only when the `{}` has to be on a new line. See, for example, this trait:

```rust
pub trait CreepBody: Clone + 'static + Into<Cow<'static, [Part]>> + TransferOwnership {}

impl<T> CreepBody for T where T: Clone + 'static + Into<Cow<'static, [Part]>> + TransferOwnership {}
```

----

From what I can tell, there is no `fmt-rfcs` decision on this. It's such a minor thing that I don't think it matters besides being consistent. Someone could correct me on this, though.

If I were making the decision, I would prefer the version with line breaks. My ideal formatting would be:

```rust
pub trait SpawnPrioritization:
    Ord + Copy + Clone + 'static + Serialize + Deserialize<'static> + TransferOwnership
{
}

impl<T> SpawnPrioritization for T where
    T: Ord + Copy + Clone + 'static + Serialize + Deserialize<'static> + TransferOwnership
{
}
```

(ideal besides https://github.com/rust-lang-nursery/rustfmt/issues/3047, at least)

Using `rustfmt 0.99.4-nightly (1c40881 2018-08-27)`.

**Comment by nrc** [comment]
I think the trait is right and the impl is wrong - we only allow `{}` bodies where the whole signature fits on one line. If we put a newline before `{` then we should put on before `}` too.

**Comment by scampi** [comment]
I would like to have a look at this issue if no one started yet

**Comment by daboross** [comment]
:+1: thanks!
