### ISSUE TITLE
reformatting comments is inconsistent

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#305]
Sometimes we do it, sometimes we don't. Would be good to be consistent here.

**Comment by marcusklaas** [comment]
What would be a decent heuristic for comments in missed spans? I was thinking about the following rule for a start:

If the first non-whitespace character (regular space or `\t`) preceding the *first* comment is `\n` or `{`: format comment with block indentation up to ideal_width with `//` style.

Example:

```rust
loop { /* test */
    println!("Hello, world!");
}
```
->
```rust
loop {
    // test
    println!("Hello, world!");
}
```

but leave

```rust
fn main() {
     let foo = bar();  // some comment
                       // comment continuation

    let baz = quux();
}
```
unchanged for now.

**Comment by nrc** [comment]
I guess the trouble with the second example is that if we reformat `let foo = bar();`, then we lose the alignment of the comments. I guess we could try to detect when comments are aligned, but I'm not sure how well that will work.

Your heuristic seems good at first blush, we'd have to try it out over a bunch of code to see how it works in practice.

**Comment by marcusklaas** [comment]
We format most comments now, and we have more specific issues for cases where mess up (quite a few!). Closing this in favour of more specific issues.
