### ISSUE TITLE
Poor formatting: Newtype-like expression

### ISSUE THREAD

**Issue by kestred** [rust-lang-nursery/rustfmt#3064]
### Original
(Less than 100 characters)
```rust
        Err(Error::custom("data did not match any variant of enum PaymentSourceParams"))
```

### After rustfmt
```rust
        Err(Error::custom(
            "data did not match any variant of enum PaymentSourceParams",
        ))
```

**Comment by topecongiro** [comment]
This is an expected behavior: function and macro calls are split into multiple lines when the arguments have more characters than the threshold. `Err` and `Error::custom` are combined to avoid a weird-looking indentation.
