### ISSUE TITLE
Can't use rustfmt with edition 2018 on beta

### ISSUE THREAD

**Issue by Riateche** [rust-lang-nursery/rustfmt#3081]
When using `beta-2018-10-05-i686-unknown-linux-gnu` toolchain with `rustfmt-preview` component, `cargo fmt` refuses to understand 2018 edition:

> Warning: can't set `edition = Edition2018`, unstable features are only available in nightly channel.

```
rustfmt 0.99.4-beta (1c40881 2018-08-27)
```

**Comment by topecongiro** [comment]
The configuration value changed to `edition = "2018"`, please try with it.

**Comment by Riateche** [comment]
This doesn't work either:
```
Error: Decoding config file failed:
unknown variant `2018`, expected `Edition2015` or `Edition2018` for key `edition`
Please check your config file.
```
