### ISSUE TITLE
"Dangling" method call on multi-line function invocation

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#3110]
rustfmt used to format like this:
```Rust
fn new() -> Self {
    let shader = Shader::from_file(
        Some("resources/storm.vert"),
        None,
        Some("resources/blink.frag"),
    ).unwrap();
    Self { points, shader }
}

```

The new behavior is:
```Rust
fn new() -> Self {
    let shader = Shader::from_file(
        Some("resources/storm.vert"),
        None,
        Some("resources/blink.frag"),
    )
    .unwrap();
    Self { points, shader }
}

```

The `.unwrap()` looks weird alone on its own line, as if it was its own statement instead of being part of the let statement.

If this is part of the new formatting guidelines (couldn't find anything that clearly references this scenario), perhaps there could be an exception for simple cases like a single `.unwrap()` call? It's definitely more readable when it's attached to the function call.

**Comment by topecongiro** [comment]
This was discussed in https://github.com/rust-lang-nursery/rustfmt/issues/2932. In general rustfmt tries to have consistent formatting without confusing corner cases, though I agree that the current formatting is suboptimal.

The balance between consistent formatting v.s. optimal formatting is hard to get right. IMHO in this case we benefit more to handle a single-element chain.

**Comment by nrc** [comment]
Closing as won't fix. This is a bit sub-optimal, but I don't think we can improve on this without making other formatting worse. I think there is also some benefit to not 'hiding' function calls off on the right.
