### ISSUE TITLE
crate::, self::, and super:: shouldn't be alphabetically sorted

### ISSUE THREAD

**Issue by cramertj** [rust-lang-nursery/rustfmt#3118]
In imports, `crate::`, `self::`, and `super::` imports shouldn't be reshuffled to appear in alphabetical order, since they're logically distinct from other imports (of external crates). For example, I write

```rust
use {
    crate::foo::bar,
    bytes::{Buf, BufMut},
    std::io,
};

mod foo {
    pub mod bar {}
}

fn main() {}
```

which rustfmt reorganizes to

```rust
use {
    bytes::{Buf, BufMut},
    crate::foo::bar,
    std::io,
};

mod foo {
    pub mod bar {}
}

fn main() {}
```

**Comment by nrc** [comment]
`self` and `super` are already treated non-alphabetically, we should do the same with `crate`.
