### ISSUE TITLE
Strange line width boundary on #![feature] gates

### ISSUE THREAD

**Issue by cramertj** [rust-lang-nursery/rustfmt#3119]
`#![feature(async_await, await_macro, futures_api, pin, arbitrary_self_ty)]` (74 characters wide) gets wrapped to
```rust
#![feature(
    async_await,
    await_macro,
    futures_api,
    pin,
    arbitrary_self_ty
)]
```
but `#![feature(async_await, await_macro, futures_api, pin, arbitrary_self_t)]` (73 characters) doesn't. Is there a reason for this specific width? Is it configurable somewhere?

**Comment by nrc** [comment]
It is `attr_fn_like_width`, part of the width heuristics. Which means you cannot change it without changing the other width heuristics, unless you're using Rustfmt as a library. Somehow, we'll make the width heuristics more configurable in the long term.

**Comment by cramertj** [comment]
Similarly to #3120, can this also be added to the [Configuration Options page](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md)?

**Comment by cramertj** [comment]
Also, were these width heuristics specified in an RFC somewhere that I could refer to?
