### ISSUE TITLE
Strange line width boundary on struct syntax

### ISSUE THREAD

**Issue by cramertj** [rust-lang-nursery/rustfmt#3120]
rustfmt:
```rust
fn foo(a: usize, b: usize, c: usize) -> Foo {
    Foo { aaaaaaaaa: a, b, c }
}
```

rustfmt w/ one more `a`:
```rust
fn foo(a: usize, b: usize, c: usize) -> Foo {
    Foo {
        aaaaaaaaaa: a,
        b,
        c,
    }
}
```
Related to https://github.com/rust-lang-nursery/rustfmt/issues/3119. I'm not sure where this boundary is coming from, but it isn't the line width and I don't see an option for configuring it. Would it be possible to only wrap struct syntax if it actually breaks the line length limit?

**Comment by nrc** [comment]
Another width heuristic - `struct_lit_width`. You can try setting the width heuristics to `Off` or `Max`.

**Comment by cramertj** [comment]
@nrc In that case, can this be added to the [Configuration Options page](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md)?

**Comment by nrc** [comment]
`width_heuristics` is here: https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#width_heuristics

I had to change the name just now, it was using an older name for that option.

The idea of having a heuristic for 'small' is discussed in the style guide RFC, how that is implemented and configured is left up to the implementation.

**Comment by cramertj** [comment]
Is there any room for arguing that these heuristics should be at a different arbitrary value, or was the current value carefully chosen based on... something? ;)

**Comment by nrc** [comment]
> Is there any room for arguing that these heuristics should be at a different arbitrary value

At this stage, no - I want to get 1.0 out by the end of the week. It is certainly an area I'd like to improve for 2.0 though - the style team discussed some alternatives for heuristics not based on line length but on simplicity, which might give a better look.

**Comment by cramertj** [comment]
@nrc 
> It is certainly an area I'd like to improve for 2.0 though - the style team discussed some alternatives for heuristics not based on line length but on simplicity, which might give a better look.

Sounds great! I'll look forward to that.

**Comment by cramertj** [comment]
ccing some other code that gets pretty ugly as a result of this so that it isn't forgotten about: https://fuchsia-review.googlesource.com/c/garnet/+/231798/3/bin/vsock_service/src/service.rs#275
