### ISSUE TITLE
Code is moved into line comment

### ISSUE THREAD

**Issue by orlp** [rust-lang-nursery/rustfmt#3123]
With the latest nightly rustfmt (`0.99.5-nightly (90692a5 2018-09-26)`) the following code is not properly formatted by rustfmt, causing invalid code to be generated:

```rust
pub fn fail() {
    // Some comment.
    /**///
}
```

The closing bracket is moved into the comment:

```rust
pub fn fail() {
    // Some comment.
    /**///}
```

**Comment by topecongiro** [comment]
Closing in favor of #3124.

**Comment by orlp** [comment]
@topecongiro Sorry for the double-post, I thought my issue didn't post because Github was lagging out at the time.
