### ISSUE TITLE
Unnecessary split of struct enum variant in match

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#3125]
input:
```Rust
fn main() {
    match event {
        Event::KeyPressed { code: Key::Space, .. } => {
            println!("Space pressed");
        }
    }
}

```

output:

```Rust
fn main() {
    match event {
        Event::KeyPressed {
            code: Key::Space, ..
        } => {
            println!("Space pressed");
        }
    }
}

```

If you replace `Key::Space` with `Key::Spa` to reduce the width from 55 columns to 53, rustfmt leaves it alone.

Is 54 columns the arbitrary width limit at which we must split? Shouldn't it be closer to the actual width limit, which is 100 by default?

**Comment by topecongiro** [comment]
The actual heuristics value involved here is `struct_lit_width`, which is set to `18` by default.

```rust
fn main() {
    match event {
        Event::KeyPressed {
            code: Key::Space, ..
        //  ^^^^^^^^^^^^^^^^^^^^ 20 characters
        } => (),
        Event::KeyPressed { code: Key::Spa, .. } => (),
                         // ^^^^^^^^^^^^^^^^^^ 18 characters
    }
}

**Comment by crumblingstatue** [comment]
> The actual heuristics value involved here is `struct_lit_width`, which is set to `18` by default.

Well, if the consensus is that struct literals over 18 columns are unreadable, then I won't argue against it, but I would personally like to increase this limit in my project.

Is this configurable in `rustfmt.toml`? Rustfmt can't recognize `struct_lit_width`.

**Comment by sinkuu** [comment]
It's automatically set to about 18% of `max_width`. Configurability was removed for simplicity (https://github.com/rust-lang-nursery/rustfmt/commit/dd1fbca99a9518c6a0dfedd77300d0856c9d4a21).
https://github.com/rust-lang-nursery/rustfmt/blob/8b709c0019244d8554c0799084815146a5ce800a/src/config/options.rs#L377

**Comment by nrc** [comment]
You can try setting `width_heuristics` to `Off` or `Max` and see if that gives the look you want.

Closing since other than stabilising how `width_heuristics` is specified, there is no actionable change.

**Comment by crumblingstatue** [comment]
@nrc Is it possible to set it in `rustfmt.toml`? `width_heuristics = "Max"` gives 
```
Error: Decoding config file failed:
invalid type: string "Max", expected struct WidthHeuristics for key `width_heuristics`
Please check your config file.
```

**Comment by nrc** [comment]
sorry, you should set `use_small_heuristics` not `width_heuristics`

**Comment by crumblingstatue** [comment]
> you should set `use_small_heuristics`

Thanks, that works!
