### ISSUE TITLE
"async move" not parsed in all circumstances

### ISSUE THREAD

**Issue by tcr** [rust-lang-nursery/rustfmt#3149]
I think rustfmt has partial support for async move tokens, but I received these errors when running `cargo fmt` in this crate in my project: https://github.com/tcr/edit-text/tree/286a13aa09f8725882ba8885c57abe3ca1983a30/build-tools

Error contents:

```
$ cargo fmt
error: expected one of `!`, `)`, `,`, `.`, `::`, `?`, `{`, or an operator, found `move`
   --> /.../edit-text/build-tools/tests/common/mod.rs:140:36
    |
140 |             tokio::run_async(async move {
    |                                    ^^^^ expected one of 8 possible tokens here

error: expected one of `)`, `.`, `;`, `?`, `||`, `}`, or an operator, found `{`
   --> /.../edit-text/build-tools/tests/common/mod.rs:140:41
    |
140 |             tokio::run_async(async move {
    |                                         ^ expected one of 7 possible tokens here

error: expected one of `!`, `)`, `,`, `.`, `::`, `?`, `{`, or an operator, found `move`
  --> /.../edit-text/build-tools/tests/integration.rs:19:30
   |
19 |     concurrent_editing(async move |mut debug, test_id, _checkpoint| {
   |                              ^^^^ expected one of 8 possible tokens here

Error writing files: parse error
$
```

At the top of the root of the tests/ crate: `// rustfmt-edition: 2018`

`rustc -V` output:

```
$ rustc -V
rustc 1.31.0-nightly (78ff609d7 2018-10-19)
$ cat ../rust-toolchain
nightly-2018-10-20
```

Solution: I can strip out all the "async move" tokens and then re-add them in afterward.

**Comment by topecongiro** [comment]
Putting `// rustfmt-edition: 2018` does not work outside of rustfmt's test code. For now please add `edition = "2018"` to `rustfmt.toml`. In the next release, `cargo fmt` will just parse `Cargo.toml` and use the appropriate edition.
