### ISSUE TITLE
Add option to warn when max_width is exceeded

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustfmt#3163]
I'd like for `cargo fmt -- --check` to be able to produce a warning if the max_width is exceeded (e.g. in code inside macros that is not formatted). This option should be opt-in. 

This would be useful in `rust-lang/rust`, since the tidy script currently detect this everywhere, but `rustfmt` does not.

**Comment by gnzlbg** [comment]
cc @nrc @topecongiro

**Comment by gnzlbg** [comment]
@scampi is that a CLI option?

I've tried `cargo fmt --all -- --unstable-features --error-on-unformatted --check` but it does not seem to error on exceeded `max_width` inside macros.

**Comment by gnzlbg** [comment]
Ah, it is a parameter that can be added to the `rustfmt.toml`. Thanks, that fixes it :)

**Comment by scampi** [comment]
@gnzlbg no pb, however, it's strange that you didn't get an error on the invalid command line option. Maybe worth opening a separate issue for that ?
