### ISSUE TITLE
trailing commas play badly with clap builder patterns 

### ISSUE THREAD

**Issue by sourcefrog** [rust-lang-nursery/rustfmt#3166]
In this code <https://github.com/sourcefrog/conserve/blob/d20687ab5f0e9cd607185e889857e8cd124d106a/src/bin/conserve.rs#L143> for example

```rust
                .subcommand(
                    SubCommand::with_name("block")
                        .about("Debug blockdir")
                        .subcommand(
                            SubCommand::with_name("list")
                                .about("List hashes of all blocks in the blockdir")
                                .arg(Arg::with_name("archive").required(true)),
                        )
                        .subcommand(
                            SubCommand::with_name("referenced")
                                .about("List hashes of all blocks referenced by an index")
                                .arg(Arg::with_name("archive").required(true)),
                        ),
```

There's an outer call to `.subcommand()` which takes a single parameter made from the `SubCommand` builder pattern. `rustfmt` always wants to add a trailing comma, I guess on the principle that I might add another parameter to `subcommand()` later (which isn't actually possible.)

I guess ideally it would know this is a chain of builder-style function calls, not a list...

**Comment by nrc** [comment]
This is correct behaviour - we always use trailing commas when arguments cover multiple lines.
