### ISSUE TITLE
Create rustfmt.toml 

### ISSUE THREAD

**Issue by alobb** [rust-lang-nursery/rustfmt#317]
Would it be a useful feature to have a command-line option that creates a rustfmt.toml file from the default configuration and then exits?  @nrc @marcusklaas does this seem like a good thing to have?

**Comment by nrc** [comment]
This would be a great thing to have! Good idea!

I wonder if it should be a separate tool though which just does this? It would be good to keep rustfmt itself as simple as possible (Unix philosophy and so forth...).

**Comment by alobb** [comment]
Do you mean as in completely separate command, or subcommand or similar? It seems like it would be easy to add to rustfmt calling `Default::Default()`, and writing to toml format, though I understand wanting to break up separate functions.

**Comment by nrc** [comment]
I mean having another binary which uses the rustfmt library (`rfmttoml`, or something).

I imagine in the future we might want to extend it to do stuff like generate toml files for common combinations of options, etc.

**Comment by alobb** [comment]
I see; will creating another file with `fn main()` in the `src/bin` folder work then?

**Comment by nrc** [comment]
not sure, to be honest, you might have to ask in #cargo

**Comment by alobb** [comment]
Yup, all I had to do is create another file in `src/bin`.  Do you want the executable to be called `rfmttoml`?

**Comment by alobb** [comment]
Also, doing it this way means that `cargo run` no longer works, because cargo doesn't know which binary to run.  The command would now be `cargo run --bin rustfmt` or `cargo run --bin rfmttoml`.  Is that still fine, or do you want to do it a different way?

**Comment by nrc** [comment]
I'm easy with the name, if you can think of a better one that would be great.

Is there any way to provide a default to `cargo run`? If not, then I guess it is fine, as long as you update the readme too.

**Comment by cassiersg** [comment]
My 2 cents: `rfmtconfig` for the name ?

**Comment by steveklabnik** [comment]
`src/bin/*` is the standard for "secondary executables," so it'd be the right place to put this, yeah.

**Comment by mjkillough** [comment]
#1558 added a new `--dump-default-config FILE` flag to `rustfmt` which saves the default config to the `FILE` specified.

**Comment by nrc** [comment]
I think this just needs documenting (in this context) at this point

**Comment by ssilva** [comment]
> I think this just needs documenting (in this context) at this point

What would this entail? Would it be just about mentioning it in README.md (under "Tips" perhaps)?

**Comment by nrc** [comment]
> What would this entail? Would it be just about mentioning it in README.md (under "Tips" perhaps)?

That sounds like a good way to address this! Thanks!
