### ISSUE TITLE
Splitting lines on field access

### ISSUE THREAD

**Issue by whatisaphone** [rust-lang-nursery/rustfmt#3199]
Hopefully you guys don't mind these sorts of bikesheddy issues :)

I have a lot of code that ends up looking like this:

```rust
    let start_index = scenario
        .unwrap()
        .data
        .timestamps
        .iter()
        .position(|&t| t >= start)
        .unwrap_or(scenario.unwrap().end_time());
```

This seems like a lot of wasted vertical space to me. rustfmt is splitting the expression on the dots because it's too long for one line. I would propose that if possible, it should try to keep all fields and zero-argument method calls on the first line, and only begin splitting on the first method call which has at least one argument.

```rust
    let start_index = scenario.unwrap().data.timestamps.iter()
        .position(|&t| t >= start)
        .unwrap_or(scenario.unwrap().end_time());
```

This looks a lot clearer to me. It also logically makes more sense to read, since generally the first line in such a chain is "get me a thing", and the remaining lines will be "process the thing in some way".

**Comment by nrc** [comment]
We discussed this extensively in the formatting RFC process and have a style guide RFC that describes this. A very brief summary is that one item per line is easier to read and scan for fields/methods and that this outweighs vertical space usage.

**Comment by whatisaphone** [comment]
Whoops, I wasn't aware of that very through RFC, sorry! I'll review it before filing any more issues.
