### ISSUE TITLE
adds spaces to empty newlines in comments

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rustfmt#3204]
`rustfmt 0.99.6-nightly (750b252 2018-10-18)`

I have code like this
````rust
fn main() {
    /*

    */
}
````
but rustfmt decided to add empty trailing spaces to line 3 so that if there was some text it would allign with the `/*` `*/` however the line is empty and nothing needs to be aligned there:

````rust
fn main() {
    /*
    
    */
}
````

````diff
diff --git a/src/main.rs b/src/main.rs
index a3c3244..03a1f8d 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -1,5 +1,5 @@
 fn main() {
     /*
-
+
     */
 }
````

I believe this did not happen a week or two ago.

**Comment by matthiaskrgr** [comment]
This happens with the default rustfmt options (no extra settings/tweaks required)

**Comment by nrc** [comment]
I can't reproduce this with current master.

**Comment by matthiaskrgr** [comment]
Ah, indeed, looks like the the rustfmt version shipped with rust nightly is almost a month old :confused: .
