### ISSUE TITLE
Keep member chain on line up to the first method call

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang-nursery/rustfmt#3210]
I would very much prefer this formatting for a method call on a struct data member:

```rust
self.encoder.encode(
    &mut state.pending_str,
    &mut state.encoded_buf,
)?;
```

Currently, rustfmt with `max_width = 80` splits the chain like this:

```rust
self.encoder
    .encode(&mut state.pending_str, &mut state.encoded_buf)?;
```

Another example involves iterator method chains:

```rust
let n = self.chunks.iter()
    .zip(dst.iter_mut())
    .map(|(chunk, iovec)| {
        // ...
    }).count();
```

Rustfmt breaks every member in the chain into its own line:

```rust
let n = self
    .chunks
    .iter()
    .zip(dst.iter_mut())
    .map(|(chunk, iovec)| {
        // ...
    }).count();
```

I'd prefer that the line breaking heuristic makes an exception for the leading part of the chain up to the first method call, and not break before that first call if it's small enough to fit on the same line, or is the last one in the chain. Would it be possible to add an option for that?

**Comment by nrc** [comment]
This was discussed extensively in the formatting RFC process, see the fmt-rfcs repo for details.
