### ISSUE TITLE
Dynamic line splitting

### ISSUE THREAD

**Issue by Kha** [rust-lang-nursery/rustfmt#337]
As far as I can tell, rustfmt is currently based on a static line splitting model that wraps nodes at the deepest possible level in the AST, which is often the opposite of the expected behavior, e.g.

``` (rust)
        loooooooooooooooooooooooooooooooooooooooooooooooooooonnnnnnnnnnnnnnnnnnnnnnnnnnng =>
            f(aaaa + bbbb, cccc, dddd),
        caaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaat => f(aaaa +
                                                                                         bbbb,
                                                                                         cccc,
                                                                                         dddd),
    }
```

Are there plans to adopt a more dynamic cost-based model such as described in [this article](http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/) about dartfmt?

I understand the scope of this issue (the article isn't called 'The Hardest Program I've Ever Written' for nothing), and it may even be in conflict with the ['Heuristic rather than algorithmic'](https://github.com/nrc/rustfmt/blob/master/Design.md#heuristic-rather-than-algorithmic) guideline, but I've already encountered this problem multiple times, especially with the large indent of match arms, so I do not think it falls under the "1% allowed failures" case. Also, apologies if this has previously been discussed in an issue or on some other channel.

**Comment by marcusklaas** [comment]
This is a known and difficult problem. We've been thinking about ways to deal with this efficiently. This was one idea, but it had some important drawbacks: https://github.com/nrc/rustfmt/issues/169. It may be interesting to read the discussion there to get an idea of what we've considered so far.

Personally, I think walking at least parts of the solution space à la dartfmt is inevitable.

Any input would definitely be appreciated!

**Comment by Kha** [comment]
Ah, I didn't find that issue. I would welcome an easier solution, but the dartfmt way does seem to be inevitable.

I thought a bit about whether it makes sense for me to use rustfmt as an auto-formatter without this feature - I suppose it wouldn't be a problem if there was an option to not re-wrap expressions that are already sufficiently wrapped in the input. This should comply with https://github.com/nrc/rustfmt/blob/master/Design.md#first-do-no-harm, since we really can't tell right now whether re-wrapping makes the result better or worse.

**Comment by cassiersg** [comment]
I filed an issue (#346) for your suggestion, so we don't forget it and keep this issue for the hardest part: a good line-splitting algorithm.
