### ISSUE TITLE
Do better with the function multi-lining heuristic

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#371]
```
            format!("\n{}",
                    offset.block_indent(context.config).to_string(context.config))
```

Should really be on one line. I wonder if we should only apply the width heuristic if there are `> 2` args? Or maybe we can apply that rule just to macros?

**Comment by marcusklaas** [comment]
I think it's the fact that the first argument is very small that makes this look weird. Two 30 char items split over two lines would probably be better than having them on a single line.

Consider this, which already looks a lot better:
```
            macro2!(offset.block_indent(context.config).to_string(context.config),
                    "\n{}")
```
