### ISSUE TITLE
Having binary distributions? (or cargo subcommand)

### ISSUE THREAD

**Issue by KeenS** [rust-lang-nursery/rustfmt#392]
Since rustfmt requires nightly rustc, not all rust users can build rustfmt. Having binary distributions would bring rustfmt to majority of rust users.

**Comment by maximih** [comment]
I would suggest it becomes a subcommand of cargo and installed together with cargo by `rustup` script. Until then, binary distributions would be very helpful.

**Comment by killercup** [comment]
> a subcommand of cargo

This can probably already be done with minimal changes. Try this: Adjust the CLI 's [argument parsing](https://github.com/nrc/rustfmt/blob/7ea589d7b413c068443cda8ad3f24fe9a50cb07a/src/bin/rustfmt.rs#L91) to handle the `cargo` prefix, rename the binary from `rustfmt` to `cargo-fmt` (and have it in your `PATH`), then run it with `cargo fmt src/lib.rs`.

**Comment by nrc** [comment]
For `cargo fmt`, see also https://github.com/arcnmx/cargo-clippy

**Comment by marcusklaas** [comment]
Closing now rustfmt compiles on stable. I don't think there's much demand for rustfmt for those without a rust environment.

**Comment by nrc** [comment]
Reopening because I'm still keen to have `cargo fmt` - I think it would be a big usability win. I intend to get this done this week (I don't think there is much to do).
