### ISSUE TITLE
format more expressions

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#4]
basically all of them at this stage

**Comment by nrc** [comment]
Boolean expressions would be nice to tackle - we often split these across lines in if statements and so forth (and are often badly formatted).

Assignment would be interesting and useful too - we get the interesting factor of balancing the left and right hand sides, e.g.,

```
(a, b, c, d, e) = foo(w, x, y, z);
// Assuming there is not enough width we could do any of:
(a, b, c, d, e) =
    foo(w, x, y, z);
(a,
 b,
 c,
 d,
 e) = foo(w, x, y, z);
(a, b, c, d, e) = foo(w,
                               x,
                               y,
                               z);
// Or any combination thereof.
```

We should definitely use the user input as a hint in such a case.

**Comment by marcusklaas** [comment]
With very few exceptions, all expressions are rewritten at this point.
