### ISSUE TITLE
Make child module formatting optional

### ISSUE THREAD

**Issue by aarzee** [rust-lang-nursery/rustfmt#400]
Some projects (such as [uutils/coreutils](https://github.com/uutils/coreutils)) have a non-traditional building scheme where some common files are used by multiple crates. In this case, it is a waste of effort to format child modules (and can lead to confusion, see #399). It would be useful to have a `rustfmt.toml` option to disable this functionality, while keeping the default behavior.

**Comment by nrc** [comment]
Sounds like a nice option to have. Not as easy as you might expect (or the label might lead you to expect).

**Comment by marcusklaas** [comment]
How would one do this? Is there a way to prevent the parser from walking the modules?

**Comment by nrc** [comment]
You can't stop parsing, but you can stop reformatting by simply not continuing to walk in the Visitor implementation.
