### ISSUE TITLE
Comments on attributes are removed

### ISSUE THREAD

**Issue by skade** [rust-lang-nursery/rustfmt#410]
```
#[allow(missing_docs)]
 pub struct Writebatch<K: Key> {
-    #[allow(dead_code)] //only used for holding the internal pointer
+    #[allow(dead_code)]
     writebatch: RawWritebatch,
-    marker: PhantomData<K>
+    marker: PhantomData<K>,
 }
```

The comment is important, to indicate why I switched off a lint. It should not be touched.

Might be the same as #406

**Comment by sanmai-NL** [comment]
The bug reported here is no longer present. Not in `rustfmt -V`: `0.8.4 ()`.
https://is.gd/fhf4L7. @nrc: Close?

**Comment by nrc** [comment]
yeah, I think so, thanks for checking it

**Comment by conradkdotcom** [comment]
@nrc @sanmai-NL This bug is actually still present. @sanmai-NL try testing with the comment next to an attribute **within a struct**. The bug seems to occur only within a struct.
