### ISSUE TITLE
Consider putting struct enum variants on one line

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#418]
```
-    Switch { adt_def: AdtDef<'tcx> },
+    Switch {
+        adt_def: AdtDef<'tcx>,
+    },
 
     // test for equality
-    Eq { value: Literal<'tcx>, ty: Ty<'tcx> },
+    Eq {
+        value: Literal<'tcx>,
+        ty: Ty<'tcx>,
+    },
 
     // test whether the value falls within an inclusive range
-    Range { lo: Literal<'tcx>, hi: Literal<'tcx>, ty: Ty<'tcx> },
+    Range {
+        lo: Literal<'tcx>,
+        hi: Literal<'tcx>,
+        ty: Ty<'tcx>,
+    },
```

I'm not sure if the original is better or not, tbh, We should have an option for this at the least.

**Comment by cassiersg** [comment]
Should be quite easy when #407 is merged.

**Comment by rkruppe** [comment]
Is this issue specifically about struct *variants*, or does it also cover non-enum structs? Since the two are semantically close, and use the same syntax for literals, I would guess the policy should be the same.

**Comment by nrc** [comment]
Specifically variants. Although the two are the same in some sense, variants tend to have fewer fields with shorter names, so it's often nice to format them more tightly than struct items.
