### ISSUE TITLE
rustfmt should avoid rightwards drifting big blocks of code

### ISSUE THREAD

**Issue by nagisa** [rust-lang-nursery/rustfmt#439]
Currently rustfmt formats from

```rust
            let mut arms = variants.iter().enumerate().map(|(i, &(ident, v_span, ref summary))| {
                let i_expr = cx.expr_usize(v_span, i);
                let pat = cx.pat_lit(v_span, i_expr);

                let path = cx.path(v_span, vec![substr.type_ident, ident]);
                let thing = rand_thing(cx, v_span, path, summary, |cx, sp| rand_call(cx, sp));
                cx.arm(v_span, vec!( pat ), thing)
            }).collect::<Vec<ast::Arm> >();
```

to 

```rust
            let mut arms = variants.iter()
                                   .enumerate()
                                   .map(|(i, &(ident, v_span, ref summary))| {
                                       let i_expr = cx.expr_usize(v_span, i);
                                       let pat = cx.pat_lit(v_span, i_expr);

                                       let path = cx.path(v_span, vec![substr.type_ident, ident]);
                                       let thing = rand_thing(cx,
                                                              v_span,
                                                              path,
                                                              summary,
                                                              |cx, sp| rand_call(cx, sp));
                                       cx.arm(v_span, vec!(pat), thing)
                                   })
                                   .collect::<Vec<ast::Arm>>();
```

which is much worse than the original.

**Comment by nrc** [comment]
I kind of like the new version - it still fits and I find aligning the methods in the chain more readable. 

However, there should be an option for block indenting of methods of a chain (rather than visual indenting) which should avoid the huge chunk of whitespace. I also thought we could format like the first example because there is enough space and the argument to map is a closure - that is new work that just landed. @marcusklaas - do you know what is going on?

**Comment by marcusklaas** [comment]
I think rustfmt would pick the former strategy if it wasn't for the collect call.

**Comment by nrc** [comment]
Ah, that's interesting. I wonder if we could we fix that (as an option, as I said I quite like the new version).

**Comment by nagisa** [comment]
Note that the issue title mentions “big” blocks. I find current style better when the block of code is 1-to-3ish lines of code too, but it gets exponentially worse as the LOC of the block increases.

**Comment by nrc** [comment]
Hmm, good point. @arichto has also pointed out some formatting choices which make sense for small blocks but not large ones. I guess we're going to have to build in this concept some how, although the idea gives me the fear.

**Comment by nrc** [comment]
I guess it is just a cut-off at n lines, but it still seems scary some how.

**Comment by oli-obk** [comment]
how about moving to 

```rust
            let mut arms = variants
                .iter()
                .enumerate()
                .map(|(i, &(ident, v_span, ref summary))| {
                    let i_expr = cx.expr_usize(v_span, i);
                    let pat = cx.pat_lit(v_span, i_expr);

                    let path = cx.path(v_span, vec![substr.type_ident, ident]);
                    let thing = rand_thing(cx,
                                           v_span,
                                           path,
                                           summary,
                                           |cx, sp| rand_call(cx, sp));
                    cx.arm(v_span, vec!(pat), thing)
                })
                .collect::<Vec<ast::Arm>>();
```

for large blocks?

**Comment by tsion** [comment]
In the second code block in the original post, there is indentation (the closure body) past an alignment (the `.` for the method calls). If the method call `.` isn't on a multiple-of-4 column, then hitting TAB in vim (and I think other editors) will insert less than 4 space to reach the next multiple-of-4 column.

For example, in that code sample, hitting tab on the line after `let pat = cx.pat_lit(v_span, i_expr);` inserts just 1 space. This can make editing in these blocks frustrating.

Plus, the alignment forced `rand_thing(cx, v_span, path, summary, |cx, sp| rand_call(cx, sp));` far enough to the right that it had to go vertical. It seems like it's easier for an automated tool to keep from doing anything drastic like that if it sticks to a style more like @nagisa's original. Maybe that should be the default, and the rightwards alignment style should be an optional flag.

**Comment by alexcrichton** [comment]
I've run across this many many times when working with rustfmt, and I agree with @nagisa's original post that the first block of code is *much* more readable. We've often had a problem with rightward-drift of code in Rust in the past and we have tried to tailor idioms (like RAII) around preventing that. I personally prefer to have style wherever possible that avoids rightward drift as much as possible.

**Comment by killercup** [comment]
This came up recently when I ran rustfmt on Miri: https://github.com/tsion/miri/pull/6#issuecomment-211007449

**Comment by regexident** [comment]
This right-drift behaviour has been a major annoyance of mine, when working with rustfmt.

I've found passing an in-place created PDS to functions to be a nice pattern for keeping function signatures clean and extensible and even allow for some kind of faux default arguments. It however clashes with rustfmt on every single use.

This one is fine and remains as it is when fed through rustfmt:

```rust
let input = Input {
    foo: 42,
    bar: 1234,
};
some_fn_with_struct_and_closure(input, |foo, bar| {
    println!("foo: {:?}", foo);
    println!("bar: {:?}", bar);
});
```

while this one (which I'd prefer to remain untouched):

```rust
some_fn_with_struct_and_closure(Input {
    foo: 42,
    bar: 1234,
}, |foo, bar| {
    println!("foo: {:?}", foo);
    println!("bar: {:?}", bar);
});
```
gets turned into this:

```rust
some_fn_with_struct_and_closure(Input {
                                        foo: 42,
                                        bar: 1234,
                                    },
                                    |foo, bar| {
                                        println!("foo: {:?}", foo);
                                        println!("bar: {:?}", bar);
                                    });
```

😢

**Comment by nrc** [comment]
I've been experimenting with this. It is relatively easy to get a naive fix:

```

    let mut arms = variants.iter()
                           .enumerate()
                           .map(|(i, &(ident, v_span, ref summary))| {
        let i_expr = cx.expr_usize(v_span, i);
        let pat = cx.pat_lit(v_span, i_expr);

        let path = cx.path(v_span, vec![substr.type_ident, ident]);
        let thing = rand_thing(cx, v_span, path, summary, |cx, sp| rand_call(cx, sp));
        cx.arm(v_span, vec![pat], thing)
    })
                           .collect::<Vec<ast::Arm>>();
```

The obvious problem here is the orphan method call (cc #566 and probably some other issues too). Not sure what a good solution to that is. One idea (that would fix #566 too) if to always block indent method/fields on new lines. I don't think this looks as good (I've learned to really like the aligned `.`s) but it does solve the floater problem.

```
    let mut arms = variants.iter()
        .enumerate()
        .map(|(i, &(ident, v_span, ref summary))| {
            let i_expr = cx.expr_usize(v_span, i);
            let pat = cx.pat_lit(v_span, i_expr);

            let path = cx.path(v_span, vec![substr.type_ident, ident]);
            let thing = rand_thing(cx, v_span, path, summary, |cx, sp| rand_call(cx, sp));
            cx.arm(v_span, vec![pat], thing)
        })
        .collect::<Vec<ast::Arm>>();
```

Anyone got any better ideas?

**Comment by tsion** [comment]
@nrc I think block indent (your second example) looks better, but more importantly, it also seems to cause fewer problems for rustfmt, fairly consistently. On top of that, it's an easier rule for a text editor to implement.

Aligned method calls should be an optional feature for those who are willing to risk more problematic formatting. I know this is against your personal preferences, but the *defaults* should be designed so rustfmt's results are acceptable in the highest number of cases

**Comment by retep998** [comment]
I'm strongly in favor of using block indenting by default. In my experience alignment indenting has always simply caused problems for very little gain. Block indenting already serves the purpose of making it easy to see where things continue onto the next line, while alignment indenting just makes editing more difficult, causes noisy diffs, and causes horrible rightward drift that can induce even more newlines needed leading to pathological situations.

**Comment by killercup** [comment]
In some cases, I really like the look of the aligned indenting… but in most cases it just feels wrong (too far right, creating empty space on the left over several lines, etc).

Thus, I too favor block indenting. @nrc's second code block looks pretty much like [my preferred style](https://github.com/tsion/miri/pull/6#issuecomment-211007449) (though I did move the `variants.iter()` into the block and combined some lines).

**Comment by regexident** [comment]
> … but in most cases it just feels wrong (too far right, creating empty space on the left over several lines, etc)

The main issue I have with dot-aligned indenting (in addition to wasted space) is that it forces my line of sight to wander in curvy lined instead of just an almost straight line parallel to the left window edge.  
The second version (@nrc's last comment) makes scanning a code file so much quicker.

**Comment by ubsan** [comment]
Block indent is just less complicated, and less likely to go wrong. Therefore, I think we should be using block formatting.

**Comment by ubsan** [comment]
One thing I do do, which is very different from the vast majority of rust code, is to use 2-space indents; it fights against the rightward drift of rust quite well.

**Comment by oli-obk** [comment]
> is to use 2-space indents; it fights against the rightward drift of rust quite well.

rightwards drift is not in the number of spaces, but in the number of indentations.

**Comment by regexident** [comment]
> […] use 2-space indents; it fights against the rightward drift of rust quite well.

Use the shortest possible identifiers; it fights against the rightward drift of rust quite well. 😈 😇

**Comment by tsion** [comment]
2-space indent *does* reduce rightwards drift and doesn't obfuscate the code like shortening identifiers, but I can imagine it being unpopular in the Rust community. (It's arguable that 2-space is narrow enough to make it harder to scan.)

**Comment by retep998** [comment]
>Use ultra-short identifiers; it fights against the rightward drift of rust quite well. :smiling_imp: :innocent:

Not really an option when I'm working with Windows API identifiers that take up an entire line on their own :stuck_out_tongue:

**Comment by ubsan** [comment]
@tsion I thought it would be harder to scan, but it turns out it's actually not. *shrug*

@oli-obk it does fight rightward drift, with multiple matches. I keep myself to 80 columns, as well, so it's nice.

**Comment by oli-obk** [comment]
What I meant is that readability goes down with every extra indentation. If you just want to reduce horizontal space, you can reduce the font size. What we actually want is to reduce the size of jumps from one level to another, so we have a "feeling" for where we are in the code wrt nesting.

**Comment by ubsan** [comment]
@oli-obk Kinda, but smaller indentation does allow for longer lines of real code.
