### ISSUE TITLE
Multiline trailing enum comments indented poorly

### ISSUE THREAD

**Issue by marcusklaas** [rust-lang-nursery/rustfmt#446]
Example output:

``` rust
                match x {
                    Some(function_type) => some_val,
                    None => unreachable!(), // A function with unknown type is called.
                    // If this happened the compiler would have aborted the
                    // compilation long ago.
                };
```

Should be a relatively easy fix. Willing to mentor anyone wanting to dive into the guts of rustfmt.

**Comment by kingscott** [comment]
Hey! I've been learning my way around Rust since it's inception. Any chance I could get in on this issue? Just not 100% sure where to start.

**Comment by nrc** [comment]
Hi @kingscott, yes! That would be awesome!

I would start by reading `visit_enum` and `format_variant_list` and trying to work out how they work: https://github.com/rust-lang-nursery/rustfmt/blob/master/src/items.rs#L628

If you have questions, ping me on irc - I'm nrc there too.

iiuc, this call to `itemize_list` is reponsible for finding and formatting comments:https://github.com/rust-lang-nursery/rustfmt/blob/master/src/items.rs#L679 But you will need to have an explore and experiment to work out exactly what is going on.

I'm not totally clear on the best way to fix this tbh, @marcusklaas did you have a specific plan in mind?

**Comment by kingscott** [comment]
Hello @nrc! I will try and wrap my head around those. What are some options for going about the experimentation?

**Comment by kingscott** [comment]
Hey gents! Sorry about the huge delay on this, exams are coming and a school project is consuming most of my time. I'm still 100% interested in working on some rustfmt stuff. I'll be on break in a couple weeks and I'll dive right in...is this still doable?

**Comment by marcusklaas** [comment]
No worries! This is still open. Take your time and let us know if you need any guidance :-)

**Comment by kingscott** [comment]
Thanks! @marcusklaas

**Comment by Zarokka** [comment]
I'm not sure how this should be formatted. 

Consider:
```
    match x {
        Some(function_type) => some_val,
        None => unreachable!(), // A function with unknown type is called.
        // What if this comment belongs to the next arm?
        What => some_other_val,
    };
```

in this case the formatting could be correct (all tough it is probably poor coding style), according to this rule in the source code:
```
// inter-match-arm-comment-rules:
//  - all comments following a match arm before the start of the next arm
//    are about the second arm
fn rewrite_match_arm_comment( ...
```

**Comment by nrc** [comment]
@Zarokka we can never be perfect here, in the match example we might put a newline before the first comment, or assume that comments on the same line should stay there, but following comments should not.
