### ISSUE TITLE
Add 'mixed' formatting of arguments in fn calls

### ISSUE THREAD

**Issue by Manishearth** [rust-lang-nursery/rustfmt#448]
Currently, rustfmt aggressively splits argument lists in both function declarations and function calls across lines:

```
fn foo(x: u8,
          y: u8,
          ...
          ) -> ...

// or

foo(x,
      y,
      z,
      ...);
```

It's a very common style to split only as much as necessary to satisfy the horizontal limit. There's currently a config option to make function declaration splitting less aggressive, but there's nothing for function calls.

Could this be added?

**Comment by nrc** [comment]
There already is, or rather, this is what we do by default. However, we go into vertical mode more eagerly than at the line limit - there is an option `fn_call_width` which is the max width inside the `()`. You can turn this off by setting it to the max width value.

There is currently no option to format function calls using the MIXED style of formatting, e.g.,

```
foo(aaaa, bb, cccccc, dddd, eeeeee,
    f, gggggggggg, hh);
```

(which we do support for function decls. I think this style is really bad for readability, but if it's really desired we could implement it. There is the question of what to do if one of the args spills to multiple lines, I guess fallback to vertical?
```

**Comment by Manishearth** [comment]
Yeah, I was talking about the mixed style. That's the style Servo uses, and most other projects I'm involved in. Rustc itself, as usual, uses a mix of styles.

Fallback to vertical sounds great.
