### ISSUE TITLE
Don't use the function call width heuristic for tuples

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#450]
It's kinda silly:

```
-            (buf.offset(tydesc_start as isize), buf.offset(start as isize))
+            (buf.offset(tydesc_start as isize),
+             buf.offset(start as isize))
```

**Comment by marcusklaas** [comment]
Should we not? I think an argument can be made in favour of the heuristic for tuples. They are pretty much function calls without a path any way..

**Comment by nrc** [comment]
I guess I just prefer the one line version in the example above - multi-line tuples look a bit weird to me. Not sure I can explain it logically. It does seem to be borne out empirically in the reformatting we do though.
