### ISSUE TITLE
Should extern "C" include "C"

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#451]
I.e., should we format `extern "C" fn` as that or `extern fn`?

We should have an option for both versions, but I'm not sure which should be the default.

**Comment by barosl** [comment]
Personally I prefer `extern fn`, because I consider the C ABI as a lingua franca of the FFI world and this doesn't seem to change in the near future.

**Comment by retep998** [comment]
On 32-bit Windows both cdecl and stdcall are really popular. cdecl is the same as "C", and what most libraries use by default, while stdcall is the same as "system" and is used for almost the entirety of Windows API and also some libraries. As such I feel that it is always a good idea to specify the ABI and I'd prefer to have it explicit as the default.

**Comment by marcusklaas** [comment]
I think we drop the annotation by default for extern blocks. I have preference, but we should be consistent at least.

**Comment by nrc** [comment]
Reopening because we need to decide on a default value before 1.0.

**Comment by marcusklaas** [comment]
No strong opinion here. Leaning towards explicit default.

**Comment by nrc** [comment]
Closing in favour of https://github.com/rust-lang-nursery/fmt-rfcs/issues/52
