### ISSUE TITLE
spacing around ranges

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#456]
`a..b+1` is a bit odd in that it's precedence is `a..(b+1)` but we format as `a..b + 1` (I think). I wonder if we should use the tighter spacing here? (Although that dents uniformity). Or we could insert parens maybe?

**Comment by marcusklaas** [comment]
Hah, I've thought about this as well! I think adding parens for binary/ unary operations on either side of a range is a good solution.

**Comment by marcusklaas** [comment]
Closing this in favour of https://github.com/rust-lang-nursery/rustfmt/issues/625.
