### ISSUE TITLE
handle comments at the end of structs

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#457]
e.g.,

```
struct Foo {
    f: T,
    f: T,

    // comment  
}
```

Should keep the comment at the end rather than the current output:

```
struct Foo {
    f: T,
    f: T, // comment  
}
```

**Comment by LukasKalbertodt** [comment]
Yes please!

**Comment by sleepymurph** [comment]
Howdy! I was using comments like this for TODOs, and I hit an edge case where the reformatting actually lead to a syntax error.

If you have an enum with one field, it gets reformatted onto one line. And if you have a trailing comment, the closing brace ends up at the end of the comment. So you lose your closing brace.

This:

```rust
enum Foo {
    Two {
        size: usize,
        x: u64,
        // TODO: additional fields
    },
    One {
        size: usize,
        // TODO: additional fields
    }
}
```

Becomes this, which no longer compiles:

```rust
enum Foo {
    Two {
        size: usize,
        x: u64, // TODO: additional fields
    },
    One { size: usize, // TODO: additional fields },
}
```

It's easy enough to just avoid writing comments like this for now. But if someone is looking into this issue, it's an edge case they might want to keep in mind.

PS. Let me add that Rust is the first language I've used with an official reformatter, and I love it. No arguments about or even thinking about code style. It's wonderful. rustfmt rules! Thank you!

**Comment by sinkuu** [comment]
Latest rustfmt fails to format the code (see #1352)

```
> rustfmt --write-mode diff test.rs
Diff in test.rs at line 1:
 struct Foo {⏎
     f: T,⏎
-    f: T,⏎
+    f: T, ⏎
 ⏎
     // comment⏎
 }⏎
Diff in test.rs at line 7:
-⏎
Rustfmt failed at test.rs:3: left behind trailing whitespace (sorry)
```
