### ISSUE TITLE
Single line trait with empty method

### ISSUE THREAD

**Issue by goyox86** [rust-lang-nursery/rustfmt#460]
This:

```rust
trait AllTypes { fn dummy(&self) { } }
```
is getting formatted to:

```rust
trait AllTypes {    fn dummy(&self) {
    } }
```
which is wrong.

**Comment by marcusklaas** [comment]
This is https://github.com/nrc/rustfmt/issues/78.

**Comment by nrc** [comment]
I also feel like the function should stay on one line because the body is just whitespace (I'm sure I implemented that, maybe I was just dreaming?).

**Comment by marcusklaas** [comment]
Your method only retains two-character blocks, but does not transform other empty blocks into `{}`. I think there is an abstraction to do that, though.

**Comment by nrc** [comment]
fixed
