### ISSUE TITLE
Option for tighter formatting of punctuation in types

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#489]
I.e., no spaces around `+` and `=`, e.g., `M: Mirror<'tcx, Output=Expr<'tcx>+`static>`

**Comment by ConnorGBrewster** [comment]
I added an option in the config for the tighter formatting, I am not sure if the enum variants are names properly or if the description of the config value is ok, but the rest should be good. If someone could take a look before I submit a PR, that would be great.
