### ISSUE TITLE
Alternate way of specifying rustfmt_skip

### ISSUE THREAD

**Issue by rhoot** [rust-lang-nursery/rustfmt#498]
Currently `#[rustfmt_skip]` is documented as the proper way of skipping formatting on a specific piece of code. For this to work however, you must have `#![feature(custom_attribute)]` specified in the crate root. The problem with this is that `#[feature]` is not allowed on the stable rust channel, which means `#[rustfmt_skip]` also cannot be used in the stable channel.

It would be great if there was an alternative method of opting out of formatting on a specific thing that also works in the stable channel.

**Comment by nrc** [comment]
Having some kind of special comment is probably the way forward here. Using a Doc comment would be nice because these are associated with AST nodes, we could perhaps use some funky markdown so it does not actually show up in the rendered docs, e.g., `/// [](rustfmt_skip)` or something...

**Comment by matklad** [comment]
Hm there is also `#[cfg_attr(rustfmt, rustfmt_skip)]` which works on stable Rust an is mentioned in README. Should this be closed then?

**Comment by nrc** [comment]
Yeah, probably unnecessary
