### ISSUE TITLE
bad comment line break in librustc_trans/trans/consts.rs

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rustfmt#503]
I found this snippet in https://github.com/rust-lang/rust/blob/master/src/librustc_trans/trans/consts.rs#L122-L123

``` rust
fn addr_of_mut(ccx: &CrateContext, cv: ValueRef, align: machine::llalign, kind: &str) -> ValueRef {
    unsafe {
        // FIXME: this totally needs a better name generation scheme, perhaps a simple global
        // counter? Also most other uses of gensym in trans.
    }
}
```

It gets reformatted to

``` rust
fn addr_of_mut(ccx: &CrateContext, cv: ValueRef, align: machine::llalign, kind: &str) -> ValueRef {
    unsafe {
        // FIXME: this totally needs a better name generation scheme, perhaps a simple
        // global
        // counter? Also most other uses of gensym in trans.
    }
}
```

which is totally wrong. Either it needs to work with the comment in the next line, or, what I would have expected, leave it be, since it hasn't hit the 100 char line length limit.

**Comment by marcusklaas** [comment]
That's not very good.. I'm afraid some choices will have to be made when it comes to comment formatting. A bit more here: https://github.com/nrc/rustfmt/pull/505#issuecomment-149651970.

**Comment by marcusklaas** [comment]
Oh and we broke the line because we try to keep comments within 80 characters per line, excluding indentation.

**Comment by nrc** [comment]
Perhaps we should only use the shorter width when there is no indentation? The intention is that large blocks of text comments don't end up too wide, but short inline comments like this could be extended to 100.

I think that if we are breaking comments, we should aim to do proper word-wrapping. That is harder than it sounds, but not impossible.

**Comment by nrc** [comment]
More: https://github.com/rust-lang/rust/commit/2bcf540df085c67df4433de215c3283c813372a5

I think we should turn off line breaking until we have a proper word-wrap algorithm implemented, it looks pretty bad.

**Comment by topecongiro** [comment]
Triage: this is fixed, closing.
