### ISSUE TITLE
Symbol not found in OS X

### ISSUE THREAD

**Issue by zonyitoo** [rust-lang-nursery/rustfmt#52]
```
running 1 test
dyld: lazy symbol binding failed: Symbol not found: __ZN12run_compiler20hc88ddcd6c053f075F4bE
  Referenced from: /Users/zonyitoo/Projects/rustfmt/target/debug/rustfmt-4f9b0c3263d54116
  Expected in: /usr/local/lib/librustc_driver-4e7c5e5c.dylib

dyld: Symbol not found: __ZN12run_compiler20hc88ddcd6c053f075F4bE
  Referenced from: /Users/zonyitoo/Projects/rustfmt/target/debug/rustfmt-4f9b0c3263d54116
  Expected in: /usr/local/lib/librustc_driver-4e7c5e5c.dylib
```

Rustc version is
```
rustc 1.1.0-nightly (90cc83015 2015-04-22) (built 2015-04-22)
```

**Comment by killercup** [comment]
I had this problem as well and solved it by setting `DYLD_LIBRARY_PATH` to the correct path, which was `$HOME/.multirust/toolchains/nightly/lib/` in my case (found this in brson/multirust#43).

**Comment by nrc** [comment]
I wonder if we can do anything to fix this? Perhaps just pointing it out in the README?

**Comment by killercup** [comment]
In fact my problem was `dyld: Library not loaded`, not @zonyitoo's `Symbol not found`. I'd guess the latter could to indicate a mismatch of library/Rust versions.

I added a comment to brson/multirust/43 that might interest you, @nrc.

**Comment by zonyitoo** [comment]
@killercup I only have one Rust (nightly) on my computer, and all the other Rust programs/libraries work fine except this.

**Comment by marcusklaas** [comment]
Is still an issue?

**Comment by zonyitoo** [comment]
nope. I should close this now.
