### ISSUE TITLE
Can't 'cargo install'

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/rustfmt#526]
```
$ multirust run nightly cargo install rustfmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rustfmt v0.0.1
specified package has no binaries
```

I wonder if this is because it's `src/bin/rustfmt.rs` rather than `src/main.rs`.

/cc @alexcrichton

**Comment by alexcrichton** [comment]
This is because the 0.0.1 of rustfmt had no binaries in the published version.

**Comment by steveklabnik** [comment]
ah, this makes sense.

**Comment by killercup** [comment]
I'd :heart: to `cargo install rustfmt` as well! Are there any plans for releasing versions, @nrc? (`0.0.x` where `x` increase every two weeks or so would suffice.)

**Comment by nrc** [comment]
I don't have a concrete plan, but it is high on my list of priorities! I'm away this week, but once I get back I'd like to figure out what to do and do it!

**Comment by alkis** [comment]
It would be great to get a versioned release so that a homebrew formula can be written.

**Comment by marcusklaas** [comment]
Any update on this, @nrc? I think an update of the crates.io version should do the trick.

**Comment by marcusklaas** [comment]
This works now :dancers:
