### ISSUE TITLE
Tabs not expanded in macros

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustfmt#545]
Given this source:

``` rust
foo! {
    test
}
```

```
$ xxd foo.rs        
0000000: 666f 6f21 207b 0a09 7465 7374 0a7d 0a    foo! {..test.}.
$ rustfmt --write-mode overwrite foo.rs

$ xxd foo.rs
0000000: 666f 6f21 207b 0a09 7465 7374 0a7d 0a    foo! {..test.}.
```

Similar to https://github.com/nrc/rustfmt/issues/544, the tab inside the macro, "09", remained before and after the format.

**Comment by nrc** [comment]
Closing because covered by #8

**Comment by RReverser** [comment]
Are these strictly relevant? I'd expect indentation to be handled anywhere as it doesn't need to parse the contents of the macro (or any code).
