### ISSUE TITLE
Buggy alignment of method chain around array literal 

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#547]
```
         let source_rows = source.pixels[x_start + y_start * src_pitch..]
-                                .chunks(src_pitch)
-                                .take(copy_height)
-                                .map(|row| &row[..copy_width]);
-        let dest_rows = self.pixels[(x_start as isize + offset[0]) as usize
-                                    + (y_start as isize + offset[1]) as usize * dest_pitch..]
+                              .chunks(src_pitch)
```

I expect chunks to be aligned with .pixels.

**Comment by marcusklaas** [comment]
Heh, this is tricky. This isn't a chain as currently defined for rustfmt (a sequence of method calls, struct accesses or tuple accesses). Maybe we could generalize this to allow for interspersed indexation. It certainly makes sense in the presented example. I wonder what we should do when the index spans multiple lines..
