### ISSUE TITLE
special case format!-like macros

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#549]
I think we can put all args on a second line if they fit, rather than using vertical layout. This has been bugging me too recently

**Comment by addityasingh** [comment]
@nrc Or even split them to maintain the character count on single line (say 80 or 100). E.g. I used rust fmt on below code and it formatted it to a huge line:
```rust

pub fn search_case_insensitive<'a>(
    contents: &'a str, 
    query: &'a str) -> Vec<String> {
```

to 

```rust
pub fn search_case_insensitive<'a>(contents: &'a str, query: &'a str) -> Vec<String> {
```

The formatted one seems to be less readable. So maybe as part of this issue, we can fix both of these scenarios. Also, with some help I would want to work on this one
@nrc Thoughts?

**Comment by nrc** [comment]
This is discussed a bit in https://github.com/rust-lang-nursery/fmt-rfcs/issues/86

**Comment by nrc** [comment]
@addityasingh the examples you give are functions, not macros. We already split functions before they hit the max line length based on `fn_call_width`. This issue is for something like:

```
println!(
    "a {} format {} string",
    foo, bar,
);
```
