### ISSUE TITLE
Complex match arms aren't line broken

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/rustfmt#557]
Rustfmt is unable to wrap these two lines: https://github.com/sfackler/rust-phf/blob/58e222380b7fc9609a055cb5a6110ba04e47d677/phf_macros/src/lib.rs#L264-L265

```
Rustfmt failed at ../rust-phf/phf_macros/src/lib.rs:264: line exceeded maximum length (sorry)
Rustfmt failed at ../rust-phf/phf_macros/src/lib.rs:265: line exceeded maximum length (sorry)
```

**Comment by marcusklaas** [comment]
Struct patterns aren't handled yet.

**Comment by nrc** [comment]
This should be fixed now. Please re-open if not.
