### ISSUE TITLE
Perhaps don't change the indentation of raw strings?

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#559]
Seems to be some kind of style to leave them 0-indented. Not sure if indenting them actually changes the semantics (in which case this would be a bug), but I think not. Not sure if we are making the formatting better or worse here.

```
         assert_eq!(result.unwrap(),
-r#"digraph single_edge {
+                   r#"digraph single_edge {
     N0[label="N0"];
```

**Comment by Manishearth** [comment]
Indenting them does change the semantics iirc. We should only reindent the first line if it is already indented.

**Comment by nrc** [comment]
Even the first line? (Indenting subsequent lines does).

Only indenting if already indented is a good heuristic here.

**Comment by Manishearth** [comment]
First line is fine.

**Comment by topecongiro** [comment]
Closing since on the current master rustfmt changes the indent of the first line of raw string.
