### ISSUE TITLE
Add flag for not changing overall indentation

### ISSUE THREAD

**Issue by Manishearth** [rust-lang-nursery/rustfmt#561]
It would be nice to have a flag for rustfmt which doesn't change the base indentation (but still keeps in mind the X char limit).

This would be useful for doing things like formatting a single fn or impl from vim. It's easy to pipe a selection through rustfmt in vim (Visual mode, type `:!rustfmt`, which becomes `:'<,'>!rustfmt`), but rustfmt will treat the input as a module and remove the extra indentation.

**Comment by nrc** [comment]
Keeping the same indentation would be tricky, but we could certainly set the 'base' indentation to the indentation found on the first line, which should have the right effect in most cases.

**Comment by johannhof** [comment]
I think base indentation would do the job here, we could pass `indent(linenumber) / &shiftwidth` if Vim is in visual mode.

**Comment by johannhof** [comment]
Although I doubt we can make syntex_syntax parse arbitrary code that is not wrapped in `fn` right now, so e.g. visual selection would have to span the whole function and would fail otherwise.

**Comment by nrc** [comment]
I don't think we are going to do anything here. Editors should be able to pass the indent to rustfmt.
