### ISSUE TITLE
Unneeded line break in long, reformatted strings

### ISSUE THREAD

**Issue by dotdash** [rust-lang-nursery/rustfmt#564]
I have a docopt usage string like this:

``` rust
const USAGE: &'static str = "
Usage: codegen project <name> <digits> <len> <codes> <prizes> <step> <shift>
       codegen regenerate <name>
       codegen verify <name> <code>
";
```

which gets reformatted as:

``` rust
const USAGE: &'static str = "
Usage: codegen project <name> <digits> <len> <codes> <prizes> \
                             <step> <shift>
       codegen regenerate <name>
       codegen \
                             verify <name> <code>
";
```

Notice how the last line got unnecessarily split into two although it is pretty short. In fact, due to the pretty large indentation, the wrapped part now goes further to the right than the original line did.

**Comment by crumblingstatue** [comment]
I've also hit this in [cargo-fmt](https://github.com/pwoolcoc/cargo-fmt).

Original:
```
const USAGE: &'static str = "
Format all Rust source files in the project with rustfmt

Usage:
    cargo fmt [options]

Options:
    -h, --help  Print this message

The current implementation formats all .rs files in
the current directory, recursively.
";
```

Note how the line lengths are not even near the line width limit. The peak width is 57 columns.

Rustfmt output:
```
const USAGE: &'static str = "
Format all Rust source files in the project with rustfmt

Usage:
    \
                             cargo fmt [options]

Options:
    -h, --help  Print this message

\
                             The current implementation formats all .rs files in
the current \
                             directory, recursively.
";
```

Rustfmt shouldn't have touched the string at all. There isn't enough semantic information available about strings for rustfmt to know better than the author of the string. It should only touch strings if it really goes over the allowed line width limit.

**Comment by yberreby** [comment]
I think the `format_strings` option should be `false` by default, as rustfmt's poor reformatting of string literals is very annoying.

**Comment by shssoichiro** [comment]
Agreed. I've run into this as well. It makes my multiline help text completely unreadable. It's annoying having to copy my block of text, run rustfmt, then paste the block of text back every time.

**Comment by yberreby** [comment]
@shssoichiro You don't have to. You can create a `rustfmt.toml` file in your repo, containing:

```
format_strings = true
```

And *voilà*: rustfmt should stop messing with your multiline text!

**Comment by shssoichiro** [comment]
Thanks! I did figure that out from your previous comment, as well. However, is there any place that lists all of the possible rustfmt.toml options? The readme only says, "When you run rustfmt, place a file named rustfmt.toml in target file directory or its parents to override the default settings of rustfmt." It does not say what options are available.

**Comment by yberreby** [comment]
@shssoichiro 

```
$ rustfmt --config-help
```

**Comment by nrc** [comment]
Rustfmt no longer formats strings by default, so this is fixed unless you set an option.
