### ISSUE TITLE
Process a list of files instead of just one

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#580]
We currently only process a single file, it would be nice to process more. Even better would be to support globs and other wildcards.

See some discussion here https://github.com/rust-lang-nursery/rustfmt/pull/570#issuecomment-155001242 and below

**Comment by cassiersg** [comment]
Can't we rely on the shell where rustfmt is invocated to expand globs ?

**Comment by nrc** [comment]
How would that work?

**Comment by cassiersg** [comment]
You have nothing to do !
If I run the following program:
```rust
use std::env;

fn main() {
    let args: Vec<_> = env::args().skip(1).collect();
    println!("Args: {:?}", args);
}
```
I get
```sh
$ cargo run *.rs
Args: ["main.rs", "1.rs", "2.rs", "3.rs"]
```
Actually, it works on bash. I think it should work on any common shell. (The only place where I know for sure it doesn't work is Window's `cmd.exe`).

**Comment by johannhof** [comment]
I agree supporting globs might be too much right now.

This issue is still valid because even with glob expanding we would need to add support for getting more than one file from the `args`.

**Comment by JanLikar** [comment]
I could add support for more files.

**Comment by nrc** [comment]
@cassiersg wow, that is awesome, I did not know shells were that clever!

Ok, so it looks like we just need to support multiple files for input and everything will just work.

**Comment by JanLikar** [comment]
I'm working on this.
