### ISSUE TITLE
Work with Atom

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#581]
There seems to be some work here via Beautify - https://github.com/Glavin001/atom-beautify/issues/358 - I have to admit that I know nothing about Atom or Beautify, so I don't know what needs to be done to make this work. It would be great if someone could jump in and make this happen, I'm happy to work on anything in Rustfmt itself which is required.

**Comment by sidred10** [comment]
It already works. These are 2 setting that need to be configured in the atom beautifier config. 

Install rustfmt as usual by cloning the repo and using `cargo build --release`. In atom beautifier, make sure rustfmt is the formatter.

![image](https://cloud.githubusercontent.com/assets/6623285/11109392/e4bd9542-8915-11e5-805b-a02664b1f502.png)

Also set the path to your rustfmt location in atom beautifier as shown below. ( This setting is towards the bottom of the screen. Need to scroll. )
![image](https://cloud.githubusercontent.com/assets/6623285/11109320/54a0117e-8915-11e5-94be-80b5e91072eb.png)

**Comment by nrc** [comment]
Awesome! @sidred10 do you mind if I take your explanations and pop them in a markdown file?

**Comment by sidred10** [comment]
Sure go ahead !!
