### ISSUE TITLE
rustfmt diff is reversed

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang-nursery/rustfmt#606]
Normally, diff prints - lines first and then + lines, but rustfmt diff prints + lines first and then - lines.

**Comment by utkarshkukreti** [comment]
@sanxiyn this should be fixed now with diff#0.1.8. Please reinstall rustfmt (or delete Cargo.lock and recompile) and confirm whenever you have time :)

**Comment by marcusklaas** [comment]
I think we should bump the version of diff in our lock file before we close this.
