### ISSUE TITLE
if expression inside binary expressions are not indented after breaking long lines

### ISSUE THREAD

**Issue by Marwes** [rust-lang-nursery/rustfmt#608]
Ran rustfmt on the crate `base` of [embed_lang]() and got some formatting which seems a bit weird to me.

[diff](https://github.com/Marwes/embed_lang/commit/3a1e8a8691c2c0f203a2d9b9171f8d0a60e66465?diff=split#diff-dba970a7f0a105f00aa23cdac01c082cR16)

Arguably there isn't really a good way to format it in this case and I should move the if expression to a separate line but I would otherwise expect lines 17-20 to be indented to the level of the if expression's start. Might just a matter of taste though.

**Comment by nrc** [comment]
```
-    let cap = size / mem::size_of::<f64>() + (if size % mem::size_of::<f64>() != 0 { 1 } else { 0 });
+    let cap = size / mem::size_of::<f64>() +
+              (if size % mem::size_of::<f64>() != 0 {
+        1
+    } else {
+        0
+    });
```

I thought this was a known issue, but I couldn't find anything. We should be indenting the `if` bodies with the `if` itself (plus a block indent).

**Comment by Marwes** [comment]
Somewhat related so I might as well mention this.

I use `if` expressions in a few other places like this where the line is not long enough to need to be split onto separate lines but is split regardless.

```
Int(if true { 1 } else { false })
```
Is changed to something like
```
Int(if true {
    1
} else {
   false
})
```

While I think the first code before formatting is a bit clearer I don't mind the formatted version enough to think it warrants an issue.

**Comment by mbrt** [comment]
@Marwes I think that the code before formatting is better. Maybe it's worth an issue.
