### ISSUE TITLE
Rustfmt fails with 'line exceeded max length' on use of thread_local!

### ISSUE THREAD

**Issue by Marwes** [rust-lang-nursery/rustfmt#611]
Rustfmt fails with `Rustfmt failed at ./base/src\interner.rs:163: line exceeded maximum length (sorry)` when I run it against the crate base of [embed_lang](https://github.com/Marwes/embed_lang). 

[diff](https://github.com/Marwes/embed_lang/commit/3a1e8a8691c2c0f203a2d9b9171f8d0a60e66465?diff=split#diff-1474e6a5ec13e13ab36e6af981f2bcbdR163)

I would guess that this is because formatting macros are tricky or even impossible in some cases. Might need a better error message if it is not deemed possible however.

**Comment by nrc** [comment]
Yeah, likely to be because it's a macro use. We ought to be able to fix this eventually, but it is a little more challenging than other stuff. In the mean time, if you manually fix it up (to fit within the line limit), Rustfmt shouldn't break your formatting.

**Comment by radix** [comment]
perhaps certain common macros that are built-in to rust should be whitelisted as being equivalent to function calls? I ran into this with assert_eq! too

**Comment by nrc** [comment]
We actually try to format all macro calls as if they were functions, but sometimes that doesn't work and then we pretty much give up. I would have thought assert_eq would get reformatted properly though.

**Comment by radix** [comment]
hm. well, I reported (and then closed) a case of assert_eq! not being formatted properly in #1868, maybe that's worth double-checking...
