### ISSUE TITLE
Commas go missing in match

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang-nursery/rustfmt#622]
```rust
fn foo() {
    match 2 {
        1 => {},
        2 => (),
        _ => return,
    }
}
```
to
```rust
fn foo() {
    match 2 {
        1 => {}
        2 => (),
        _ => return,
    }
}
```

**Comment by nrc** [comment]
This is intentional - the style we work with is comma after every single-expression arm, no commas after block arms. There is an issue for optionally adding commas to block arms - #173.
