### ISSUE TITLE
Redundent Output

### ISSUE THREAD

**Issue by jussij** [rust-lang-nursery/rustfmt#624]
On Windows, for a simple d:\temp\test.rs Rust file:

    fn main() {
        println!("Hello World\n");
    }

Run the rustfmt command on that file and capturing the output:

    D:\Temp>rustfmt.exe --write-mode overwrite test.rs > output.txt

That command produces output:

    D:\Temp>dir output.txt
     Volume in drive D is DATA
     Volume Serial Number is 06EC-1105
    
     Directory of D:\Temp
    
    19/11/2015  12:15 AM                 1 output.txt
                   1 File(s)              1 bytes

But the output.txt contains nothing but a single line feed character:

    ==========================================================================
          xDump Version 1.05 - Hex Dump Utility
          Copyright (c) Xidicone Pty Ltd 2014  -  All rights reserved.
    ==========================================================================
    0000: 0A             

I am curious why this is so?

**Comment by marcusklaas** [comment]
This is because you're using the overwrite mode, which simply writes the output over the input file. To redirect the output to stdout, use the display mode. Please note that this will won't work well when multiple files are being reformatted!

**Comment by jussij** [comment]
My question was why does anything at all get written to stdout or stderr (which then ends up in output.txt) in this case?

I could understand this if something went wrong, but nothing went wrong and all that got captured was the \n character.

To add context, I was looking to add a macro to an editor that automatically does a reformat on the save event, hence the use of the overwrite mode.

To handle formatting errors the macro captures the stderr and stdout and if there are any they get displayed to the users.

So in this case, the user is always shown an error screen because there is always a \n character written to the output by rustfmt.

Now the macro could be changed to accommodate that, but an almost identical macro works perfectly for gofmt. 

So as I asked before, what is rustfmt trying to communicate by outputting that one character?
