### ISSUE TITLE
Poor spacing of slices

### ISSUE THREAD

**Issue by linfir** [rust-lang-nursery/rustfmt#625]
The slice `a[n-i .. i]` is reformatted to `a[n - i..n]` which is wrong because the parse is `a[(n-i) .. n]` and the spacing suggests otherwise.

**Comment by nrc** [comment]
Ah yes, this is a pain, the style to use has been discussed a bit in various places, the trouble is people want `[a..b]` and `b + 1` but not `[a...b + 1]`. Which makes things non-compositional and thus hard. We should fix this, but I'm not sure how. One suggestion was to always use parens where part of a range is a compound expression, not sure I like that idea, but maybe.

**Comment by stjepang** [comment]
Here's another example that appears in my code:
```rust
for _ in 0..1 << self.0 {
    atomic::hint_core_should_pause();
}
```

@nrc 

> One suggestion was to always use parens where part of a range is a compound expression, not sure I like that idea, but maybe.

Why not just add spaces when part of a range is a compound expression? Like this:
```
a..b
a .. b + 1
```

**Comment by nrc** [comment]
This is dicussed in https://github.com/rust-lang-nursery/fmt-rfcs/issues/60
