### ISSUE TITLE
rustfmt reformats bit manipiulations

### ISSUE THREAD

**Issue by mrmonday** [rust-lang-nursery/rustfmt#626]
Given the following code:

``` rust
fn main() {
    let (a, b, c, d) = (0, 0, 0, 0);
    let _ = u32::from_be(((a as u32) << 24) |
                         ((b as u32) << 16) |
                         ((c as u32) <<  8) |
                          (d as u32) <<  0);
}
```

Where the bit manipulation is intentionally aligned to increase readability, rustfmt produces:

``` rust
fn main() {
    let (a, b, c, d) = (0, 0, 0, 0);
    let _ = u32::from_be(((a as u32) << 24) | ((b as u32) << 16) | ((c as u32) << 8) |
                         (d as u32) << 0);
}
```

Where it is far harder to tell if the calculation is being performed correctly. Would it be possible to add an option to detect bit shifting/or-ing etc and have rustfmt skip it? Or, even better, automatically format it to be readable (no idea if that's possible).

**Comment by mrmonday** [comment]
A similar issue occurs with arrays of bytes - should I report another issue for that? Eg.

```rust
   let ref_packet = [0xde, 0xf0, 0x12, 0x34, 0x45, 0x67, /* destination */
                     0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, /* source */
                     0x86, 0xdd /* ethertype */];
```

Becomes:

```rust
   let ref_packet = [0xde, 0xf0, 0x12, 0x34, 0x45, 0x67 /* destination */, 0x12, 0x34, 0x56,
                      0x78, 0x9a, 0xbc /* source */, 0x86, 0xdd /* ethertype */];
```

**Comment by nrc** [comment]
This is somewhat of a recurring problem - users often format code with significant whitespace to make it easier to read, it's not limited to bit patterns, and of course rustfmt can't easily tell what has been deliberately aligned and what is bad formatting so it stomps all over it. The 'solution' is to use `#[rustfmt_skip]` but this is a crappy solution for a few reasons. I don't hold much hope for a good, automatic solution (maybe we can detect alignment in source code and preserve it?), but we can definitely make the skipping better (both in Rustfmt and by more flexible attributes in Rust).
