### ISSUE TITLE
Long function declarations do not get line breaks correctly

### ISSUE THREAD

**Issue by Marwes** [rust-lang-nursery/rustfmt#630]
Before:
```
pub trait Test {
    fn very_long_method_name<F>(self, f: F) -> MyVeryLongReturnType
        where F: FnMut(Self::Item) -> bool;
}
pub trait Test {
    fn very_long_method_name<F>(self, f: F) -> MyVeryLongReturnType
        where F: FnMut(Self::Item) -> bool
            , F: Fn();
}
```
After:
```
pub trait Test {
    fn very_long_method_name<F>(self, f: F) -> MyVeryLongReturnType where F: FnMut(Self::Item) -> bool;
}
pub trait Test {
    fn very_long_method_name<F>(self, f: F) -> MyVeryLongReturnType
        where F: FnMut(Self::Item) -> bool,
              F: Fn();
}
```

Might be part of #78 (?) but I think this may be a separate issue as adding an extra element to the `where` list will make it format correctly.

**Comment by nrc** [comment]
Are you using any non-default options? We do try and put the whole function on one line, but in this case we are going 3 chars over the limit, which is wrong.

(I wonder if we should exclude where clauses from the one-liner in any case, or maybe have a shorter width than the max for a one line function with where clause?)

**Comment by Marwes** [comment]
Only using the default options.

**Comment by Marwes** [comment]
Did some investigating but I am not really sure how to resolve this. As far as I can tell the function signature's indentation is not taken into account when writing the where clause and the only reason the second example succeds is because of [these lines](https://github.com/rust-lang-nursery/rustfmt/blob/b9832f2e9f703deb8f5d9b0a6c97cfc896b952c2/src/items.rs#L1314-L1322) where it checks for an already line broken where clause and only then puts it on a new line. Would like to fix this but I am not sure where the responsibility of breaking long lines should be.

**Comment by nrc** [comment]
@Marwes  I think the way to fix this is that `rewrite_where_clause` should take a width argument which is the budget for space left on the line, and in the code you highlight we should check that the where clause fits in that budget, breaking the line if it doesn't.

**Comment by nrc** [comment]
@Marwes we should use that passed-in budget, rather than the budget we compute in `rewrite_where_clause` (since that will not take into account the trailing `;`, etc.). But the key thing is to take any budget into account when we decided whether to put the where clause on a new line or not.
