### ISSUE TITLE
Matrix initialization

### ISSUE THREAD

**Issue by jhasse** [rust-lang-nursery/rustfmt#648]
When I [run rustfmt over a test project of mine](https://github.com/jhasse/rust-opengl-test/commit/685485ed6afea164bb91f132322748846288eeed), I'm not quite happy with this change:

``` diff
-        self.matrix = self.matrix * Mat4::new(1f32, 0f32, 0f32, x,
-                                              0f32, 1f32, 0f32, y,
-                                              0f32, 0f32, 1f32, 0f32,
-                                              0f32, 0f32, 0f32, 1f32);
+        self.matrix = self.matrix *
+                      Mat4::new(1f32,
+                                0f32,
+                                0f32,
+                                x,
+                                0f32,
+                                1f32,
+                                0f32,
+                                y,
+                                0f32,
+                                0f32,
+                                1f32,
+                                0f32,
+                                0f32,
+                                0f32,
+                                0f32,
+                                1f32);
```

It becomes hard to read the matrix structure if every parameter is in one line.

**Comment by nrc** [comment]
I fear that this sort of thing can't be spotted by rustfmt - you need to use a `#[rustfmt_skip]`. In general, where spacing is significant, Rustfmt will suggest worse formatting

**Comment by jhasse** [comment]
What about rustfmt allowing multiple parameters on one line if the number of them is always the same?
E. g.
```rust
foo(a, b,
    c, d);
```
would be okay, but
```rust
foo(a, b,
    c, d, e);
```
will be reformatted.

What do you think?

**Comment by nrc** [comment]
We have somewhat shied away from using layout info from the input, but that seems reasonable. I'd be interested to see how it works on a whole code base. I wonder if we should also require square-ness? I'd worry about accepting

```
foo(a, b, c,
    d, e, f);
```

**Comment by jhasse** [comment]
There are non-square matrices though.

When thinking about it: Why limit parameters to one per line at all? Shouldn't they break at the preferred line length?

**Comment by nrc** [comment]
There is an option to break at the max line length, but that also doesn't give what you want, you'd basically get:

```
foo(a, b, c, d, e,
      f);
```

The vertical style is preferred because once we hit multiple lines of arguments, it becomes easier to read if there is one argument per line. This is more important when arguments are compound expressions, rather than just variables.

**Comment by bluss** [comment]
I'd like to see this. Argument alignment is significant. Sketch example:

```rust
fn frob("x", x_scale,
        "y", y_scale);
```
