### ISSUE TITLE
Comments in functions being indented badly

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#653]
e.g.,
```
     fn test_rng_true_values() {
-        // Test vectors 1 and 2 from
-        // http://tools.ietf.org/html/draft-nir-cfrg-chacha20-poly1305-04
+    // Test vectors 1 and 2 from
+    // http://tools.ietf.org/html/draft-nir-cfrg-chacha20-poly1305-04
 ```

**Comment by nrc** [comment]
Also in impls

**Comment by marcusklaas** [comment]
I have an idea about what may have caused this.

**Comment by marcusklaas** [comment]
@nrc, I can't reproduce easily. Can you provide a more complete example?
```rust
fn main() {
    fn test() {
        // comment
    }
}
```
is unchanged by rustfmt atm..

**Comment by nrc** [comment]
I'll try and figure something out, in the mean time, the source I was reformatting is here: https://dxr.mozilla.org/rust/source/src/librand/chacha.rs#249

**Comment by marcusklaas** [comment]
This happens for skipped items. Closing in favour of https://github.com/rust-lang-nursery/rustfmt/issues/661.
