### ISSUE TITLE
[Feature request] Diff format output

### ISSUE THREAD

**Issue by saviorisdead** [rust-lang-nursery/rustfmt#656]
Hi there! 
I am working on integrating `rustfmt` to [RustyCode](https://github.com/saviorisdead/RustyCode). Right now, i am using `--write-mode=diff` to extract changes. What would really awesome if one can specify style of diff output, like `--write-mode=diff --format=json`. It will make correct integration much easier, without some magic strings manipulations.

**Comment by nrc** [comment]
This sounds like a nice feature to have. Are there well-known formats for diff as json and so forth?
