### ISSUE TITLE
Inline if statements always broken in new lines

### ISSUE THREAD

**Issue by mbrt** [rust-lang-nursery/rustfmt#665]
If statements are always broken in multiple lines, even when it's more readable to leave them in a single line. Example:
```
let r = if flag { "r" } else { "-" };
```

becomes:
```
let r = if flag {
    "r"
} else {
    "-"
};
```

Issue #608 mentioned a similar issue in [comments](https://github.com/rust-lang-nursery/rustfmt/issues/608#issuecomment-157019952). I'm reporting it as new issue, because the overall issue reported there seems different.

**Comment by marcusklaas** [comment]
There's already the `single_line_if_else` option for this. It's false by default, but should produce what you want when set to true.
