### ISSUE TITLE
Oddly formatted long line in a macro

### ISSUE THREAD

**Issue by erickt** [rust-lang-nursery/rustfmt#671]
I found this line when formatting [rust-snappy](https://github.com/veddan/rust-snappy):

``` rust
                    let (newbuf, newbuf_end) = read_new_buffer!(self,
                                                                return Err(FormatError("EOF whi\
                                                                                        le read\
                                                                                        ing tag")));
```

**Comment by marcusklaas** [comment]
This one is difficult to fix. Macro uses take arbitrary token arrays and it's hard for rustfmt to discern their meaning. When it can be interpreted as a comma separated sequence of expressions, we'll format it as a function call as above. It's probably best to `#[rustfmt_skip]` this for now.
