### ISSUE TITLE
Broken formatting for length-one tuple types in impls

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang-nursery/rustfmt#675]
``` diff
-impl JSTraceable for Box<FnBox(f64, )> {
+impl JSTraceable for Box<FnBox(f64)> {
```

**Comment by marcusklaas** [comment]
I'm not 100% sure that should be considered a tuple type. That still compiles right? Unlike basic tuples, where
```rust
let a: (i32) = (10, );
```
is a hard error.

**Comment by nrc** [comment]
Do the before and after versions have exactly the same semantics?

**Comment by Ms2ger** [comment]
I don't think so, but I haven't tried.

**Comment by topecongiro** [comment]
Is the above example really tuple type?

```rust
impl JSTraceable for Box<FnBox(f64)> {}

impl JSTraceable for Box<FnBox((f64,))> {}
```

**Comment by nrc** [comment]
> Is the above example really tuple type?

It is not
