### ISSUE TITLE
Strip trailing whitespace from attributes

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#679]
See comments on #664

**Comment by marcusklaas** [comment]
Just to be certain we're on the same page: we do this for attributes that are rewritten, just not for the ones that are skipped.

**Comment by nrc** [comment]
Ah right, I didn't understand that bit. Skipped due to `rustfmt_skip` or because we didn't handle something? If the latter, we should still fix this.

**Comment by marcusklaas** [comment]
Both cases I think.
