### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#686]
Currently blocking is that there is no way to publish deps within a crate. So, we first need to publish strings.rs and diff.rs or pull these into the rustfmt crate (or add the facility to Cargo).

I would also like to take over the cargo-fmt package on crates.io and have that within this repo.

**Comment by matklad** [comment]
> would also like to take over the cargo-fmt package on crates.io and have that within this repo.

I would want this very much. We will use `rustfmt` in IntelliJ-Rust plugin, and ability to invoke `rustmt` as `cargo fmt` together with https://github.com/rust-lang/cargo/commit/20b768e6ba214c469c9972b36de9cf122f45f28c will simplify the implementation significantly.

**Comment by marcusklaas** [comment]
Rustfmt 0.1 is on crates.io now: https://crates.io/crates/rustfmt/!
