### ISSUE TITLE
Odd reformatting of already-aligned multiline string literal

### ISSUE THREAD

**Issue by jgallagher** [rust-lang-nursery/rustfmt#687]
``` diff
 fn foo() -> &'static str {
     let sql = "ATTACH DATABASE ':memory:' AS my_attached;
                BEGIN;
+               \
                CREATE TABLE my_attached.foo(x INTEGER);
-               INSERT INTO my_attached.foo VALUES(42);
+               INSERT INTO \
+               my_attached.foo VALUES(42);
                END;";
     sql
 }
```

Easy enough to `#[rustfmt_skip]` this, but I wanted to report this because it seems like it's _almost_ doing the right thing. Not sure why it left the `CREATE` line alone but split the `INSERT` line, though.

**Comment by marcusklaas** [comment]
John! Thanks for the report. The string and comment formatting situation leaves a lot to be desired at the moment. We'll look into this.

**Comment by jgallagher** [comment]
Cool, thanks. I'm _super_ excited this tool is around now, btw. I love it!

**Comment by nrc** [comment]
Fixed without options set.
