### ISSUE TITLE
Missing comma after formatting match

### ISSUE THREAD

**Issue by m-decoster** [rust-lang-nursery/rustfmt#689]
As can be seen on this line in [a commit](https://github.com/m-decoster/Webio/commit/30115248704f564b203caabb6053af1c40a85d0c#diff-e4c21e4e005d0aa2db7c9bad0101dd55L87) I made after running rustfmt, sometimes commas are lost when reformatting a match clause:

    match x {
       Ok => {
       },
       Err(_) => {}
    }

became

    match x {
       Ok => {}
       Err(_) => {}
    }

While this is syntactically correct, this can cause issues when these braces are later removed. Should this be configurable in the `toml` file?

**Comment by nrc** [comment]
This is intended. There is a config option for this already: `match_block_trailing_comma`.

**Comment by nrc** [comment]
Feel free to re-open if that option doesn't do what you expect.
