### ISSUE TITLE
This line is broken into two lines, but shouldn’t (?)

### ISSUE THREAD

**Issue by nagisa** [rust-lang-nursery/rustfmt#692]
```
-            copysign(0.5 * P2_HI - (2.0 * s * r_ - (P2_LO - 2.0 * c) - (0.5 * P2_HI - 2.0 * f)), i)
+            copysign(0.5 * P2_HI - (2.0 * s * r_ - (P2_LO - 2.0 * c) - (0.5 * P2_HI - 2.0 * f)),
+                     i)
```

The first line is 99 characters long.

**Comment by marcusklaas** [comment]
This is part of the function call width heuristics. Multiline arguments are generally preferred over very long single line function calls. In this particular case it doesn't end up working very well, though. This can be 'fixed' by increasing the `fn_call_width` parameter.

**Comment by nagisa** [comment]
Maybe the heuristic should be changed to only break if the next argument(s) isn’t very short?

I see how this breaking could be nice if both arguments were of similar length, for example, but it will never work out if the next argument(s) are just a letter or two each.

**Comment by marcusklaas** [comment]
That sounds reasonable. Could you formulate a concrete heuristic? I could try to implement something this weekend.

**Comment by nagisa** [comment]
I’ve… no idea for a heuristic that would obviously work. I’ve tinkered with an idea of a packing algorithm that would strive to reduce area losses, but it doesn’t obviously work for different cases.

**Comment by marcusklaas** [comment]
What about keeping the current heuristic, but including an exception for when the tail arguments are no more than 10 chars each?

**Comment by marcusklaas** [comment]
cc https://github.com/rust-lang-nursery/rustfmt/issues/371.

**Comment by nrc** [comment]
@marcusklaas sounds good. To be precise, there is at least one arg > 10 chars, so 
```
f(dsfsdf....dsf,
  x,
  dsfsdfsadfdsfasdfasdf);
```
would be OK.

**Comment by marcusklaas** [comment]
Cool! I implemented this in https://github.com/rust-lang-nursery/rustfmt/pull/696.
