### ISSUE TITLE
ignore certain directories

### ISSUE THREAD

**Issue by buster** [rust-lang-nursery/rustfmt#705]
Is there a way to ignore certain directories?
Like configuration in rustfmt.tml or a commandline switch?

**Comment by nrc** [comment]
There isn't, but there should be! It would be easier, and more in the spirit of Cargo, to ignore certain crates. Ignoring modules could be done too as an alternative to `rustfmt_skip`, but that feels a bit un-Rusty.

**Comment by buster** [comment]
FYI:

My usecase is that i had a subdirectory containing another project (rust-peg) which I would like to ignore.  And also my project contains a large generated rust file which I don't want to format. 

I would have thought another option in the rustfmt.toml file would be great.. Something akin to a gitignore syntax..
