### ISSUE TITLE
Should be configurable whether we treat fails as warnings or errors

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#706]
I.e., do we return a non-zero error code

**Comment by tanadeau** [comment]
I'm interested in working on this. Should this be a config in the TOML and/or a command-line option (like -Werror in clang)?

**Comment by nrc** [comment]
@tanadeau great! I think probably a command line option (config options are generally used for how we format, and command line options for how we run). -Werror is probably a good option to use.

You could change the output to be either `warning` or `error` rather than `fail` too.
