### ISSUE TITLE
Option to have fn_args_layout="Block" not wrap if short

### ISSUE THREAD

**Issue by OneSadCookie** [rust-lang-nursery/rustfmt#708]
Most of the other block-formatting options allow things to remain on a single line if short, and only block-format if they're too long for a single line.  I'd like an option like this for function argument layout.  Currently, `fn_args_layout="Block"` _always_ wraps all arguments, which is pretty ridiculous for functions with short argument lists.

Currently, this:

```
fn f(a: isize) -> isize {
     // ...
}

fn g(areallylongargumentname: AReallyLongType, anotherreallylongargumentname: AnotherReallyLongType) -> isize {
    // ...
}
```

becomes this:

```
fn f(
    a: isize
) -> isize {
     // ...
}

fn g(
    areallylongargumentname: AReallyLongType,
    anotherreallylongargumentname: AnotherReallyLongType
) -> isize {
    // ...
}
```

I want an option whereby it can become this instead:

```
fn f(a: isize) -> isize {
     // ...
}

fn g(
    areallylongargumentname: AReallyLongType,
    anotherreallylongargumentname: AnotherReallyLongType
) -> isize {
    // ...
}
```

**Comment by topecongiro** [comment]
Closing since this is now implemented.
