### ISSUE TITLE
Whitespace isn't removed in impl headers

### ISSUE THREAD

**Issue by huonw** [rust-lang-nursery/rustfmt#709]
e.g.

```rust
impl   <   A    > Foo {     }
impl Foo < <A> :: Bar > where A   : Baz < T<u8 >> {}
```

are left as-is by the default rustfmt settings.

**Comment by nrc** [comment]
I thought we formatted impls now, so I'm surprised by this. Maybe I'm mis-remembering.

**Comment by marcusklaas** [comment]
You're not misremembering. In fact, I cannot reproduce this.

**Comment by nrc** [comment]
@huonw are you using an up to date rustfmt?

**Comment by huonw** [comment]
I thought I had an recent version (I installed it via `cargo install` a few days ago), but it seems I had previously installed it with a different multirust toolchain, and the `cargo/bin` directory of that one was earlier in my `PATH` than the one with the new `rustfmt`. Fixing that does indeed format this more nicely; sorry for the noise.
