### ISSUE TITLE
Add an option to not add a trailing comma to the last match arm

### ISSUE THREAD

**Issue by dovreshef** [rust-lang-nursery/rustfmt#712]
match_block_trailing_comma option only takes affect on block based match arms. A trailing comma is always added to the last non block based match arm.

Please add a new option to not add a trailing comma to the last match arm.

**Comment by dovreshef** [comment]
Hi

I'd like to take a stab at fixing this, but I'm not sure how.
I guess I'd need to add the [arm_comma](https://github.com/rust-lang-nursery/rustfmt/blob/65bc5c242de86f0651b34fd913ca338a880696e8/src/expr.rs#L926) function a flag that will let it know if it is in the last arm? 
Also I'm not sure how to thread such a flag through the arm.rewrite trait function...

**Comment by nrc** [comment]
That sounds like a good way to implement this. I don't think you need to thread through the flag - the comma itself is added in the match rewrite (where you know whether it's the last arm or not). In the arm rewrite, arm_comma is only used to compute the length of the line, you can therefore always assume it is not the last line to be conservative.

**Comment by dovreshef** [comment]
Thanks. I'll try to do that. 

One small question: should the new config option takes priority over match_block_trailing_comma? 
In block based match, where match_block_trailing_comma is true, and match_arm_trailing_comma is false, what should the behavior be for the last arm?

**Comment by nrc** [comment]
@dovreshef (sorry for the late reply, vacation). Your description is correct, so you can override the comma choice in rewrite_match.

> what should the behavior be for the last arm?

no comma, i.e., `match_arm_trailing_comma` takes priority (and the config option should probably have the word 'last' in there some where).

**Comment by topecongiro** [comment]
Now rustfmt does not add trailing comma to the last match arm when `trailing_comma = true`.
Do we need more fine-grained option?

**Comment by nrc** [comment]
Seems fine to me (I'm generally in favour of coarser grained options).
