### ISSUE TITLE
Considers whitespace in end of line markdown a trailing whitespace.

### ISSUE THREAD

**Issue by gamazeps** [rust-lang-nursery/rustfmt#715]
Hey,

I have a small issue with rustfmt (otherwise it's awesome :) ) which is the following: 
in markdown a line break is done by leaving a trailing whitespace at the end of the line, thus if we want to have a line break in the documentation we *must* have a trailing whitespace.

The problem is that rustfmt considers this whitespace as an error where it should not (it's part of the markdown expected behavior).

A simple hack is to put an empty line in order to have a different paragraph, which might be considered close enough to the intended markdown behavior, but that's a hack...

Thus could it be possible to *not* consider trailing whitespace in documentation an error ?

Cheers !

**Comment by nrc** [comment]
hmm, this is tricky - I sympathise with having correct markdown, but in general we do want to keep tracking whitespace errors after comments. It should be fairly easy to have an option to not track though.

Curious - would you want this for all comments or just doc comments?

**Comment by gamazeps** [comment]
Thanks for the answer :)

In my opinion it would make sense only for doc comments, as it is part of the markdown syntax used for doc comments, but would not make sense for regular comments.

**Comment by nrc** [comment]
dup of #37
