### ISSUE TITLE
Empty braces of extension trait moved to next line

### ISSUE THREAD

**Issue by colin-kiegel** [rust-lang-nursery/rustfmt#721]
```diff
-impl<T> ErrorExt for T where T: Error {}
+impl<T> ErrorExt for T where T: Error
+{}
```

In this case ErrorExt is an extension trait, where all extension methods are given in the trait definition, so the implementation is actually empty. This might be an edge case, but I think empty braces should not got to the next line in this case. It is also inconsistent with how it treets empty structs with braces.

```diff
- pub struct StringLoader
- {}
+ pub struct StringLoader {}
```

**Comment by nrc** [comment]
fixed
