### ISSUE TITLE
Mysterious comment generated for `fn bar(self: X<'a, 'b>, y: Y) {}`

### ISSUE THREAD

**Issue by colin-kiegel** [rust-lang-nursery/rustfmt#724]
I am having trouble to describe this in words - so it might be a duplicate issue I could not find.

```diff
 impl X {
     fn foo(x: X<'a, 'b>, y: Y) {}
-    fn bar(self: X<'a, 'b>, y: Y) {}
+    fn bar(self: X<'a, 'b>,
+           // 'b>,
+           y: Y) {
+    }
 }
```

Note that only methods like `bar` are affected, not static function `foo`. The issue disappears, if I omit one parameter or lifetime from `bar`.

Of course this is a reduced example which would never compile - but I experienced this in working code and tried to boil it down to the most simple form.

**Comment by colin-kiegel** [comment]
I admit that it is probably bad style to provide the self type as it is redundant with the line `impl ...`. I just removed the redundant type annotation.

Alternative behaviour for rustfmt could be to just remove this redundant type hint - but I am not sure.

**Comment by marcusklaas** [comment]
Cool! We're trying to find the start of the second argument by searching for the first comma, but that evidently does not work here. We should probably take the last comma before the second argument.
