### ISSUE TITLE
Whitespace in struct patterns is not changed

### ISSUE THREAD

**Issue by matklad** [rust-lang-nursery/rustfmt#727]
The following code is not changed by rustfmt:

```Rust
impl Error for AppError {
    fn description(&self) -> &str {
        match *self {
            AppError::InitializationError {  ref      cause} => cause.description(),
        }
    }
}
```

I would expect that `{  ref      cause}` is formatted like `{ ref cause }`

**Comment by marcusklaas** [comment]
This is a known issue: https://github.com/rust-lang-nursery/rustfmt/issues/672.

**Comment by matklad** [comment]
Ah, I missed it because I searched only for poor-formatting labeled issues =)
