### ISSUE TITLE
Braces added to just one of the match arms

### ISSUE THREAD

**Issue by ericsink** [rust-lang-nursery/rustfmt#742]
When formatting this code:

    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match *self {
            Error::Io(ref err) => write!(f, "IO error: {}", err),
            Error::Utf8(ref err) => write!(f, "Utf8 error: {}", err),
            Error::Misc(ref s) => write!(f, "Misc error: {}", s),
            Error::CorruptFile(s) => write!(f, "Corrupt file: {}", s),
            Error::Poisoned => write!(f, "Poisoned"),
            Error::CursorNotValid => write!(f, "Cursor not valid"),
            Error::InvalidPageNumber => write!(f, "Invalid page number"),
            Error::InvalidPageType(b) => write!(f, "Invalid page type: {}", b),
            Error::RootPageNotInSegmentBlockList => write!(f, "Root page not in segment block list"),
        }
    }

I'm getting braces added around the final match arm.  Seems weird.  Maybe it was triggered by line length, but if so, that condition surprises me a little.

Anyway, just letting you folks know.  Not sure if this is the behavior you want or not.

**Comment by nrc** [comment]
If this is verbatim what you are formatting, then we should not be inserting braces due to line length (you're under 100 chars here). In general it is possible we would insert braces onto just one match arm due to line length.

**Comment by ericsink** [comment]
It's not verbatim.  There is a level of indentation missing from the way I posted this above.  The actual line ends on column 101.

So if the intended behavior is that insertion of braces on a match arm can be caused by line length, then feel free to close this issue.

**Comment by marcusklaas** [comment]
Yea, it's intended behaviour in that case. Thanks for opening an issue, though.
