### ISSUE TITLE
Comments swallowed in multi-line arithmetic expression

### ISSUE THREAD

**Issue by ericsink** [rust-lang-nursery/rustfmt#743]
When formatting this code:

    fn calc_page_len(prefix_len: usize, sofar: usize) -> usize {
        2 // page type and flags
        + 1 // stored depth
        + 2 // stored count
        + varint::space_needed_for(prefix_len as u64) 
        + prefix_len 
        + sofar // sum of size of all the actual items
    }

I get:

    fn calc_page_len(prefix_len: usize, sofar: usize) -> usize {
        2 + 1 + 2 + varint::space_needed_for(prefix_len as u64) + prefix_len + sofar // sum of size of all the actual items
    }

Which means some of the comments got eaten.

I recognize that if I want a multi-line arithmetic expression like this then I'll probably need to add an attribute to prevent rustfmt from touching it, but it still seems kinda wrong to reformat it and lose comments.

**Comment by nrc** [comment]
Yeah, this is a limitation of the approach and the current Rust AST, we just don't see those comments. One day we'll fix this via a change to the Rust compiler.

**Comment by marcusklaas** [comment]
It's not actually terribly difficult to retrieve these comments. Formatting them properly, *that* is hard.

**Comment by nrc** [comment]
Fixed
