### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Fiedzia** [rust-lang-nursery/rustfmt#746]
fiedzia@Maciej-PC ~/g/coreutils> cargo install rustfmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
binary `cargo-fmt` already exists in destination as part of `rustfmt v0.2.1`

fiedzia@Maciej-PC ~/g/coreutils> cargo fmt
No such subcommand

        Did you mean `doc`?

fiedzia@Maciej-PC ~/g/coreutils> cargo -V
cargo 0.7.0 (b6cc27a 2015-11-28)

I've got cargo from ubuntu repositiories (unofficial). Is that the problem?

**Comment by killercup** [comment]
`cargo install -h` will tell you this:

> This command manages Cargo's local set of install binary crates. Only packages
> which have [[bin]] targets can be installed, and all binaries are installed into
> the installation root's `bin` folder. The installation root is determined, in
> order of precedence, by `--root`, `$CARGO_INSTALL_ROOT`, the `install.root`
> configuration key, and finally the home directory (which is either
> `$CARGO_HOME` if set or `$HOME/.cargo` by default).

My guess is that your `$PATH` is not set to contain `$HOME/.cargo`.

**Comment by Fiedzia** [comment]
That was it, thanks. Its annoying behaviour though.
