### ISSUE TITLE
Empty functions with a single line where clause should be kept on a single line

### ISSUE THREAD

**Issue by ConnorGBrewster** [rust-lang-nursery/rustfmt#760]
If the function body is empty and the where clause is a single line, the whole function should be put on a single line.
Currently rustfmt wants:
```
fn Foo<T>()
    where T: Bar
{
}
```
I am suggesting it should output:
```
fn Foo<T>() where T: Bar {}
```

**Comment by nrc** [comment]
As long as the empty fn option is set to true
