### ISSUE TITLE
Rust 1.4 build appears broken

### ISSUE THREAD

**Issue by cholcombe973** [rust-lang-nursery/rustfmt#771]
It seems that Rust 1.4 can no longer build this project. 
```
src/comment.rs:545:42: 545:71 error: use of unstable library feature 'iter_order': needs review and revision (see issue #27737)
src/comment.rs:545     let res = code_comment_content(orig).ne(code_comment_content(new));
```
I think the minimum version needs to be bumped to Rust 1.5.0

**Comment by nrc** [comment]
Where do we specify a minimum version for Rustfmt? Current stable is 1.5, so Travis should only run 1.5, 1.6, and 1.7.

**Comment by cholcombe973** [comment]
Oh it was in the readme I think. :-)

**Comment by nrc** [comment]
Oh right, found + fixed, thanks!
