### ISSUE TITLE
Pull `get_targets` logic into crate

### ISSUE THREAD

**Issue by euclio** [rust-lang-nursery/rustfmt#772]
I've noticed that this is a pattern that is duplicated by other tools inspecting Cargo.toml targets. It would be helpful to pull the lines in https://github.com/rust-lang-nursery/rustfmt/blob/master/src/bin/cargo-fmt.rs#L91-L155 into their own crate for use by other tools.

**Comment by topecongiro** [comment]
There is already [cargo_metadata](https://github.com/oli-obk/cargo_metadata) and it looks like what we need. We should probably use it in rustfmt as well?
