### ISSUE TITLE
Consider making a RFC for a style convention

### ISSUE THREAD

**Issue by Ticki** [rust-lang-nursery/rustfmt#776]
So we can discuss it!

**Comment by nrc** [comment]
I will. I expect there will be multiple RFCs. The plan has been to get rustfmt into good shape with lots of options, then use RFCs to decide on the defaults as a Rust style guide. I'm not exactly sure the RFC process is the right one to do this, but there will be somewhere public and formal-ish for making these decisions. Probably some time a bit later this year.
