### ISSUE TITLE
cargo-fmt should format tests by default

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustfmt#803]
Right now it'll only format the library and binary. You have to run `rustfmt` on the test source files directly to get tests.

**Comment by AndyBarron** [comment]
+1 to this, yes please!

**Comment by Zarokka** [comment]
I prepared a fix for this https://github.com/Zarokka/rustfmt/commit/08b17ef0976450d1f787abd5b048d65dda7d4042

but then I saw that PR #1206 seems to address this in a broader way
this is also related to #1126

**Comment by conradkdotcom** [comment]
I just tested this and it now seems to work as expected: code in `tests/*.rs` is formatted, including code from submodules in `tests/**/*.rs` that is used in `tests/*.rs`.

**Comment by nrc** [comment]
Thanks for testing it out!

**Comment by dashed** [comment]
This doesn't seem to work anymore as of `rustfmt-nightly v0.2.7`.  

My workaround is: `cargo fmt -- ./tests/**/*.rs`
