### ISSUE TITLE
rustfmt removes function call from macro arguments

### ISSUE THREAD

**Issue by jonhoo** [rust-lang-nursery/rustfmt#806]
I'm using [rust-peg](https://github.com/kevinmehall/rust-peg), and a recent update of rustfmt has started breaking my build whenever I save a file that uses the `peg_file!` macro. In particular, consider the following statement given in the [rust-peg examples](https://github.com/kevinmehall/rust-peg#as-a-syntax-extension):

```rust
peg_file! modname("mygrammarfile.rustpeg");
```

rustfmt used to leave this statement alone, but after my recent update, it now rewrites the statement into:

```rust
peg_file!("mygrammarfile.rustpeg");
```

which is clearly not correct.

**Comment by jonhoo** [comment]
@nrc: How hard to you think this will be to fix? It's preventing me from upgrading to rustfmt master, so I might look into fixing it if you think it's reasonable for someone who's new to the codebase.

**Comment by nrc** [comment]
@jonhoo I'm not sure, tbh, I've never touched the macro code. I wouldn't expect it to be too hard. Please have a go and let me know if you have any questions!

**Comment by jonhoo** [comment]
fwiw, some bisecting turned up f01ed6f507849a699c5ff3f3370264e3f234c734 as the bad commit.

**Comment by jonhoo** [comment]
From what I can tell from some preliminary debugging, [the parser](https://github.com/rust-lang-nursery/rustfmt/blob/65bc5c242de86f0651b34fd913ca338a880696e8/src/macros.rs#L74) for `mac.node.tts` doesn't [return](https://github.com/rust-lang-nursery/rustfmt/blob/65bc5c242de86f0651b34fd913ca338a880696e8/src/macros.rs#L79) the span preceding the argument list. In fact, it looks like if it did, the current code would break (because that span would become part of `expr_vec`, which is passed as the argument list to [`rewrite_call`](https://github.com/rust-lang-nursery/rustfmt/blob/65bc5c242de86f0651b34fd913ca338a880696e8/src/macros.rs#L101).

I feel like fixing this should be done with a bigger change. First, format the argument to the macro on its own (in this example, format as a function call), then format the macro, but disallow it from changing its arguments. Sounds a bit involved though. Another way to do this might be to detect this case specifically, but that seems like an ugly work-around.

**Comment by jonhoo** [comment]
Hey @kyeah, you committed f01ed6f507849a699c5ff3f3370264e3f234c734 -- any idea what it might take to fix this?

**Comment by marcusklaas** [comment]
I think that comment simply enabled the formatting of item macros. Reverting it is probably not the ideal solution.

The identifier in [`Mac_`](http://manishearth.github.io/rust-internals-docs/syntax/ast/struct.Mac_.html) is for the macro name. There doesn't seem to be an ident for the `modname` is your example. We should probably get this from the span..

**Comment by jonhoo** [comment]
@marcusklaas: no, I wasn't suggesting reverting it. Just thought it might be useful to see where the problem "started". Admittedly, as you point out, the commit probably isn't really relevant.
