### ISSUE TITLE
Don't emit the filename in diff mode

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#807]
So that the output can be piped straight into something expecting a diff. Also so that no output => no changes.

**Comment by juicejitsu** [comment]
hi @nrc - thinking about taking on this issue but have some questions.

how will users tell which diffs belong to which file with multi file changes?
how about git diff style output instead (maybe add as a config value)?
number of context lines in diff mode is hardcoded as 3 - seems like something fit for a config value?
any way to unit test output to std::out in rust?

**Comment by nrc** [comment]
> hi @nrc - thinking about taking on this issue but have some questions.

awesome!

> how will users tell which diffs belong to which file with multi file changes?
> how about git diff style output instead (maybe add as a config value)?

I would expect the diff to include the file changed, I thought that was part of the metadata emitted with the diff. (Just to be clear, the filename this issue is concerned with is the one Rustfmt emits when reading a file).

> number of context lines in diff mode is hardcoded as 3 - seems like something fit for a config value?

Seems like a good idea, but should be a separate PR please.

> any way to unit test output to std::out in rust?

I believe you can capture std::out when running a process, I'm not sure of the details though, sorry. Maybe ask on #rust.

**Comment by nrc** [comment]
This is partially addressed by #1123, so we can check for an empty diff for the case that Rustfmt makes no changes. There is still some work to do so that our output can be used by tools expecting a diff (e.g., patch).
