### ISSUE TITLE
Macro invocation made less readable by rustfmt

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#813]
Original code

``` Rust
macro_rules! tiles {
    ($($itemname:ident, $name:expr, ($x:expr, $y:expr), $solid:expr),*) => {
    }
}


tiles!(
    // id    name           x  y   solid
    F_DIRT,  "Dirt floor", (0, 0), false,
    W_STONE, "Stone Wall", (1, 0), true
);

fn main() {}
```

Formatted version:

``` Rust
macro_rules! tiles {
    ($($itemname:ident, $name:expr, ($x:expr, $y:expr), $solid:expr),*) => {
    }
}


tiles!(// id    name           x  y   solid
       F_DIRT,
       "Dirt floor",
       (0, 0),
       false,
       W_STONE,
       "Stone Wall",
       (1, 0),
       true);

fn main() {}

```

Rustfmt just indiscriminately splits it into multiple lines, even though they do not exceed the line length limit.

Also, since macros can have relatively free-form syntax, rustfmt knows very little about how the invocations can actually look good, so it should be a lot more conservative when formatting macro invocations.

**Comment by marcusklaas** [comment]
I'm not sure if there's a way to discern "function-like" macro invocations and more complex ones. I fear we'll have to use either `#[rustfmt_skip]` or curly braces for macros which shouldn't be reformatted...

**Comment by crumblingstatue** [comment]
> I'm not sure if there's a way to discern "function-like" macro invocations and more complex ones. I fear we'll have to use either #[rustfmt_skip] or curly braces for macros which shouldn't be reformatted...

Ah, so rustfmt skips curly braced macro invocations?

Actually, I think curly brace is a better match for the above code anyway.

**Comment by nrc** [comment]
> Ah, so rustfmt skips curly braced macro invocations?

Yes

**Comment by nrc** [comment]
This kind of thing just requires `#[rustfmt::skip]`
