### ISSUE TITLE
Final return statements versus implicit return

### ISSUE THREAD

**Issue by ketsuban** [rust-lang-nursery/rustfmt#814]
Exhibit A

``` rust
fn i_am_the_walrus(foo: u32) -> u64 {
    ((foo as u64) << 32) + (foo as u64)
}
```

Exhibit B

``` rust
fn i_am_the_walrus(foo: u32) -> u64 {
    return ((foo as u64) << 32) + (foo as u64);
}
```

Given that the Book refers to B as “poor style”, is it within rustfmt's bailiwick (being that it is a tool for resolving stylistic disagreements) to replace it with A?

**Comment by nrc** [comment]
Yes, this would be good to do. I wonder how general we can make the rule? I expect at some point you need more semantic info than rustfmt has access to.

**Comment by eefriedman** [comment]
See also https://github.com/rust-lang/rust/issues/31439 .

**Comment by sanxiyn** [comment]
This (the rule part, not the formatting part) is implemented as needless_return in Clippy.

**Comment by topecongiro** [comment]
Closing this as this is more of clippy-stuff.
