### ISSUE TITLE
Context-aware range formatting

### ISSUE THREAD

**Issue by syml** [rust-lang-nursery/rustfmt#817]
Does rust support context-aware range formatting? From the command-line help it seems it's not the case.
If not can we have that as a feature?

**Comment by nrc** [comment]
Could you give an example of the kind of thing you want?

**Comment by syml** [comment]
foo.rs:
struct Foo { bar: i32
}
struct Bar { baz: bool }

command:
cat foo.rs | rustfmt --lines=4-4

output:
struct Foo { bar: i32
}
struct Bar { 
    baz: bool 
}

The idea is to be able to selectively format some lines. Most formatters support that, ex: clang-format.

**Comment by kamalmarhubi** [comment]
See #434. I'm working on it at the moment.
