### ISSUE TITLE
Rustfmt on lib.rs runs against all files in src dir

### ISSUE THREAD

**Issue by matthewkmayer** [rust-lang-nursery/rustfmt#823]
Rustfmt 0.3.0:

`rustfmt src/lib.rs` doesn't format just the file as expected.  It appears to traverse files in the src dir as well, so you see errors in other files, like this output shows:

```bash
$ rustfmt src/lib.rs 
Rustfmt failed at src/xmlutil.rs:122: line exceeded maximum length (sorry)
```

Expected behavior is to format just the file specified.  Existing file can be seen here: https://github.com/rusoto/rusoto/blob/master/src/lib.rs .

**Comment by nrc** [comment]
This is a feature, not a bug. You can use the `skip_children` config option to get the behaviour you want.

**Comment by matthewkmayer** [comment]
Ah, thanks, I missed that sentence in the README.  Perhaps calling that out better can help others avoid this issue down the road.
