### ISSUE TITLE
Trailing comments in method chains are stripped

### ISSUE THREAD

**Issue by jonhoo** [rust-lang-nursery/rustfmt#825]
Consider the following file:
```rust
// x1.rs
fn main() {
    x.a(y.a() // TODO: fix something
         .b());
}
```

```diff
$ rustfmt --write-mode diff x1.rs
 fn main() {⏎
+    x.a(y.a().b());⏎
-    x.a(y.a() // TODO: fix something⏎
-         .b());⏎
 }⏎
```

This behavior is clearly wrong as it strips "vital" information. For what it's worth, if the comment is left out, rustfmt makes no modifications to the file:

```rust
// x2.rs
fn main() {
    x.a(y.a()
         .b());
}
```

```shell
$ rustfmt --write-mode diff x2.rs
Diff of x.rs:
```

**Comment by nrc** [comment]
The problem here is not that the comment is in an argument list but that it appears in the middle of a method call chain, e.g., `a.b() /* comment */ .c()`. This is a known issue, we thought people wouldn't often put comments there.

It's pretty weird that we don't reformat the version with no comment.

**Comment by nrc** [comment]
In fact, I can't repro the bug either.

**Comment by jonhoo** [comment]
Oh, that's my bad. I'm running an older version because #806 breaks my build on rustfmt master. What is the behavior on master?

**Comment by nrc** [comment]
Behaviour on master is nothing changes, i.e., we don't reformat at all, which is a worse bug. I suspect that if we fix that, then your bug will show up again.

**Comment by marcusklaas** [comment]
Was this not one a change @cassiersg made, to ensure we leave things as-is if it can be detected that a comment was stripped?

**Comment by nrc** [comment]
Ah, that sounds familiar - in which case bug is fixed! I'd like to know why we don't format the version without the comment before closing this though.
