### ISSUE TITLE
chain_ident/chain_base_indent options

### ISSUE THREAD

**Issue by jystic** [rust-lang-nursery/rustfmt#829]
I was using rustfmt while working through the Rust book exercises, and I couldn't get the following code to format like it was in the book:

```rust
    let handles: Vec<_> = philosophers.into_iter().map(|p| {
        thread::spawn(move || {
            p.eat();
        })
    }).collect();
```

or even like this would be ok:

```rust
    let handles: Vec<_> = philosophers
        .into_iter()
        .map(|p| {
            thread::spawn(move || {
                p.eat();
            })
        })
        .collect();
```

I tried different combinations of `chain_indent` and `chain_base_ident`, but the `.collect()` on the end seems to mess things up.

Is there anything silly I'm missing? or is this style not possible?

Thanks!

**Comment by nrc** [comment]
There is not currently an option to block indent closures as shown or method chains. I've thought about doing it for large closures/blocks. It might be good to do it for method chains (I think an option for that should be relatively easy).

**Comment by jystic** [comment]
Great, thanks for the quick response :+1:

**Comment by marcusklaas** [comment]
This has been implemented. The style you suggested is now the default.
