### ISSUE TITLE
Improve formatting of multi-line conditionals

### ISSUE THREAD

**Issue by jonhoo** [rust-lang-nursery/rustfmt#831]
Consider the following code to check if any of multiple iterators satisfy a particular condition:

``` rust
fn main() {
    let y = a.iter().any(|x| {
        println!("a");
    }) || b.iter().any(|x| {
        println!("b");
    }) || c.iter().any(|x| {
        println!("c");
    });
}
```

`rustfmt` currently formats it as

``` rust
fn main() {
    let y = a.iter().any(|x| {
        println!("a");
    }) ||
            b.iter().any(|x| {
        println!("b");
    }) ||
            c.iter().any(|x| {
        println!("c");
    });
}
```

This is clearly not ideal. In fact, the original formatting is probably what you would expect. If the `let y =` is removed, the resulting formatting is directly misleading:

``` rust
fn main() {
    a.iter().any(|x| {
        println!("a");
    }) ||
    b.iter().any(|x| {
        println!("b");
    }) ||
    c.iter().any(|x| {
        println!("c");
    });
}
```

**Comment by nrc** [comment]
I would expect rustfmt to change the empty multiline block to `{}`, and then do something like

```
let y = a.iter().any(|x| {}) || b.iter().any(|x| {}) ||
        c.iter().any(|x| {});
```

**Comment by nrc** [comment]
Although perhaps you are eliding code, since I don't think that would type check.

**Comment by jonhoo** [comment]
@nrc: yeah, assume each branch has some code in it. I'll update the example.
