### ISSUE TITLE
Formatting curly brace macros in impl blocks causes a compile error

### ISSUE THREAD

**Issue by burtonageo** [rust-lang-nursery/rustfmt#839]
In this [playpen link](https://play.rust-lang.org/?gist=30512539a9d0c184cf77&version=stable), a macro with curly braces is expanded to a method implementation. When formatting this example, the macro call site is changed to use square braces, which causes a compile error:

    <anon>:10:5: 10:19 error: expected one of `const`, `extern`, `fn`, `pub`, `type`, `unsafe`, or `}`, found `default_foo_fn`
    <anon>:10     default_foo_fn![]
                  ^~~~~~~~~~~~~~

**Comment by nrc** [comment]
I don't see why we'd change to square braces here

**Comment by marcusklaas** [comment]
I thought the choice of delimiters was irrelevant for empty macro invocations - it appears I was wrong. It still isn't clear to me what role they play, though...
