### ISSUE TITLE
Associated type definitions aren't formatted

### ISSUE THREAD

**Issue by cmbrandenburg** [rust-lang-nursery/rustfmt#840]
Rustfmt doesn't format the whitespace in an associated type definition. Whereas, I expect a single space following the `type` keyword, the associated type name, and the `=` token.

For example, here is what I expect:

```rust
trait Foo {
    type Bar;
}

impl Foo for i32 {
    type Bar = i32;
}
```

However, rustfmt will leave the following programs untouched:

```rust
trait Foo {
    type Bar;
}

impl Foo for i32 {
    type Bar=i32;
}
```

And:

```rust
trait Foo {
    type Bar;
}

impl Foo for i32 {
    type        Bar        =       i32;
}
```

**Comment by cmbrandenburg** [comment]
Note, I'm using rustfmt 0.3.0.

**Comment by marcusklaas** [comment]
Fixed on master.
