### ISSUE TITLE
Rustfmt breaks some closures

### ISSUE THREAD

**Issue by zrneely** [rust-lang-nursery/rustfmt#863]
See [here](http://is.gd/4MRqu3) for an example.

Running rustfmt changes the closure `closure` to match the one marked `broken_closure`, which doesn't compile and breaks builds. Possible solutions I see are not changing the original, or adding parentheses as in `fixed_broken_closure`.

**Comment by nrc** [comment]
Repeating code inline:

```
fn main() {
    
    let closure = |x| match x {
        0 => true,
        _ => false,
    } == true;
    
    // let broken_closure = |x| {
    //    match x {
    //        0 => true,
    //        _ => false,
    //    } == true
    // };
    
    let fixed_broken_closure = |x| {
        (match x {
            0 => true,
            _ => false,
        }) == true
    };
}
```

**Comment by nrc** [comment]
I'm not sure why the broken one is broken. Maybe a bug in the parser, rather than rustfmt?

**Comment by nrc** [comment]
Not a parser bug - expressions with blocks are always treated as statements when they are in possible statement position.

So changing an expression to { expression } can change whether is parses or not (changes expression context to statement context). Rustfmt needs to be aware of that.
