### ISSUE TITLE
Add a flag to emit which options are used

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#865]
Any config option which is queried should be output. This will mean refactoring the config system to some extent so a method is called rather than a bool field accessed. I don't expect this to be too difficult.

**Comment by kamalmarhubi** [comment]
:+1:

Do you mean output it every time it's queried, or just once per option?

**Comment by nrc** [comment]
once per option, otherwise the output will quickly get overwhelming

**Comment by mjkillough** [comment]
Now that #1558 has been merged, perhaps this should be closed?
