### ISSUE TITLE
Support ? mark in nightlies as alternative to try!

### ISSUE THREAD

**Issue by tupshin** [rust-lang-nursery/rustfmt#867]

**Comment by nrc** [comment]
Should be behind an option until `?` is stable.

**Comment by kamalmarhubi** [comment]
This is behind the `question_mark` lang feature.

**Comment by marcusklaas** [comment]
This makes method chain formatting a bit more complex. Looking into this.

**Comment by kamalmarhubi** [comment]
> Should be behind an option until `?` is stable.

Shouldn't we format code that uses it? Or use the `#![feature(question_mark)]` as a mark that the code is opting in.

**Comment by marcusklaas** [comment]
Yea, I don't think it needs to behind an option either.

**Comment by kamalmarhubi** [comment]
Having written that, I realize that if we are formatting individual files, we'd also have to find the crate root to see what features are in use. I kind of lean towards just accepting it unconditionally anyway.

**Comment by marcusklaas** [comment]
Me too.

**Comment by nrc** [comment]
To clarify I meant that there should be an option which changes `try!(expr)` to `expr?`. Just formatting `expr?` doesn't need to be behind an option,

**Comment by mcarton** [comment]
Pinging that issue, `rustfmt` produces weird diffs on Clippy:
```diff
@@ -57,11 +57,11 @@ impl<'a, 'tcx, 'v> Hir2Qmm<'a, 'tcx, 'v> {
         for a in a {
             if let ExprBinary(binop, ref lhs, ref rhs) = a.node {
                 if binop.node == op {
-                    v = self.extract(op, &[lhs, rhs], v)?;
+                    v = self.extract(op, &[lhs, rhs], v)?;;
                     continue;
                 }
             }
-            v.push(self.run(a)?);
+            v.push(self.run(a)?));
         }
         Ok(v)
     }
@@ -70,22 +70,22 @@ impl<'a, 'tcx, 'v> Hir2Qmm<'a, 'tcx, 'v> {
         // prevent folding of `cfg!` macros and the like
         if !in_macro(self.cx, e.span) {
             match e.node {
-                ExprUnary(UnNot, ref inner) => return Ok(Bool::Not(box self.run(inner)?)),
+                ExprUnary(UnNot, ref inner) => return Ok(Bool::Not(box self.run(inner)?))),
                 ExprBinary(binop, ref lhs, ref rhs) => {
                     match binop.node {
-                        BiOr => return Ok(Bool::Or(self.extract(BiOr, &[lhs, rhs], Vec::new())?)),
-                        BiAnd => return Ok(Bool::And(self.extract(BiAnd, &[lhs, rhs], Vec::new())?)),
-                        _ => {},
+                        BiOr => return Ok(Bool::Or(self.extract(BiOr, &[lhs, rhs], Vec::new())?))),
+                        BiAnd => return Ok(Bool::And(self.extract(BiAnd, &[lhs, rhs], Vec::new())?))),
```

**Comment by marcusklaas** [comment]
@mcarton: is that on the master branch, or using https://github.com/rust-lang-nursery/rustfmt/pull/893?

**Comment by mcarton** [comment]
@marcusklaas didn’t see that PR, just tested with it, works as expected :+1:

**Comment by marcusklaas** [comment]
Closed by https://github.com/rust-lang-nursery/rustfmt/pull/893.
