### ISSUE TITLE
User template for rustfmt.toml to set up new projects

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustfmt#872]
When a user creates a new project, it should be as easy as possible to integrate rustfmt. For users who are happy with the defaults, this works just great. For users who prefer to customize the style, we could help out by having a subcommand to install a `rustfmt.toml` file from a user template, say `~/.rustfmt.toml.template`—to be bikeshedded later.

**Comment by kamalmarhubi** [comment]
As inspiration, git provides a template facility for `git init`. Here's how it picks the template contents:

```
The template directory will be one of the following (in order):

 - the argument given with the `--template` option;

 - the contents of the `$GIT_TEMPLATE_DIR` environment variable;

 - the `init.templateDir` configuration variable; or

 - the default template directory: `/usr/share/git-core/templates`.
```
―https://www.git-scm.com/docs/git-init#_template_directory

**Comment by nrc** [comment]
See also #317

**Comment by jsejcksn** [comment]
@nrc I see you closed this as [completed](https://github.com/rust-lang/rustfmt/issues?q=is%3Aissue%20state%3Aclosed%20reason%3Acompleted) (vs. [not planned](https://github.com/rust-lang/rustfmt/issues?q=is%3Aissue%20state%3Aclosed%20reason%3Anot-planned)) — but I don't see any mention of a PR/commit or documentation — was the suggested feature implemented? If not… was it declined?
