### ISSUE TITLE
[feature request] option for spaces inside function parentheses

### ISSUE THREAD

**Issue by rdbuf** [rust-lang-nursery/rustfmt#877]
So that 

``` rust
some_function(a, b, c)
```

could become

``` rust
some_function( a, b, c )
```

and vice versa.   

(the thing that `clang-format`'s `SpacesInParentheses` option does)

Please, correct me if I'm missing something. Google haven't given anything

**Comment by topecongiro** [comment]
This feature is now configurable via `spaces_within_parens` option.
