### ISSUE TITLE
Failed to format trailing spaces

### ISSUE THREAD

**Issue by aleksander** [rust-lang-nursery/rustfmt#878]
Failed to format attached file with message:

> Rustfmt failed at tst.rs:3: left behind trailing whitespace (sorry)

[tst.rs.txt](https://github.com/rust-lang-nursery/rustfmt/files/189414/tst.rs.txt)

**Comment by nrc** [comment]
Looks like the issue is trailing whitespace inside a macro use. We should do a bunch of trims when making the macro use, I guess.

**Comment by tobarja** [comment]
Removing only the trailing comma from line 5 of the test.rs.txt file allows rustfmt to parse this with no errors. 

With the trailing comma, it appears to trigger the `or_else` on [line 164 of src/expr.rs](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/expr.rs#L164).

**Comment by duesee** [comment]
I've come across a similar bug. Error: `Rustfmt failed at main.rs:4: left behind trailing whitespace (sorry)`

File: [main.rs.txt](https://github.com/rust-lang-nursery/rustfmt/files/388337/main.rs.txt)

**Comment by SingingTree** [comment]
Looking at the initial file, it looks like what's happening is that the code getting hit is in [macro.rs](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/macros.rs#L116). The trailing comma into then the bump puts the macro formatter in the EOF case and returns none, so we don't get any formatting. I've tried messing with the behaviour and ended up breaking the trailing comma and not an expression macro tests. Will keep looking at it.

**Comment by SingingTree** [comment]
For the first file: it looks like trailing commas will prevent a macro being formatted. It does appear to be happening as I suspected above. This can be changed, but will change how [this](https://github.com/rust-lang-nursery/rustfmt/blob/master/tests/source/macros.rs#L20) test is formatted (removal of the trailing comma).

Any thoughts about this? Do we like trailing commas in macros? Would we like a separate issue for that?

Gonna check out what's going on with the second file. Doesn't look like it would be the same issue. Will dump what I find here.

**Comment by nrc** [comment]
We should not remove trailing commas - that could (theoretically) be a semantic change, since a macro could treat a comma as significant. I think it is fine (though obvs not ideal) for us not to format the macro use in this case (ideally we wouldn't go into EOF state on the comma, but I'm not sure how to fix that). But even if we don't re-format the macro, I think we should still be able to trim off the trailing whitespace.

**Comment by xftroxgpx** [comment]
the OP exsample seems to be fixed, but this one not yet:

[ma.rs.txt](https://github.com/rust-lang-nursery/rustfmt/files/966230/ma.rs.txt)

**Comment by Geobert** [comment]
same issue occurs if trailing space is in a raw string
