### ISSUE TITLE
Option to put `else` on newline

### ISSUE THREAD

**Issue by flutterhash** [rust-lang-nursery/rustfmt#884]
As of rustfmt v0.3.0 (installed via cargo install --branch master), single_line_if_else does not do anything, or does not do what I would expect it to. Regardless of whether it it set to true or false, else and else if expressions are always formatted like so:

if condition {
//statements
} else {
//more statements
}

If single_if_else is not the configuration option to control this behaviour, then there should be a flag added to control this behaviour (whether else and else if are placed on the same line as the closing brace of the previous expression in the chain). Many coding styles prefer else and else if on the next line following a closing brace.

**Comment by marcusklaas** [comment]
I'll have a look at this, but just to be clear: `single_line_if_else` will only produce single line expressions when there are no statements involved. Every branch of the if-else must be a short expression.

**Comment by flutterhash** [comment]
Thanks for the clarification!

**Comment by marcusklaas** [comment]
I'll close this for now. Feel free to reopen if there is still an issue.

**Comment by flutterhash** [comment]
Please reopen the issue. As of rustfmt v0.4.0 (installed via cargo install --branch master), there is still no option to configure placing else on a new line from the closing brace of an "if" statement. I believe that I may have muddled the issue by pointing out an unrelated flag earlier (single_line_if_else).

Current behaviour is:
if condition {
//statements
} else {
//more statements
}

Desired (optional) behaviour is:
if condition {
//statements
}
else {
//more statements
}


single_line_if_else succeeds in accomplishing the following:

if condition { //statement } else { //other statement }
