### ISSUE TITLE
Audit and rationalise config options

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#905]
There is a lot of non-orthogonality in the config options, plus some unexpected overlap, and just general confusing-ness. We should refactor the choices so that there is an elegant and orthogonal set of options.

See [this comment](https://github.com/rust-lang-nursery/rustfmt/pull/896#issuecomment-205528325) for an example of some of the confusion here.

**Comment by topecongiro** [comment]
Closing in favor of #1974.
