### ISSUE TITLE
Make sure we're using stdout and stderr correctly

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#907]
I.e., all errors go to stderr, other output to stdout.

**Comment by nrc** [comment]
Probably fixed by #103, but we should double-check for other cases.

**Comment by srinivasreddy** [comment]
I raised a PR.  https://github.com/rust-lang-nursery/rustfmt/pull/909. Could you please take a look?

**Comment by matklad** [comment]
I'd say that [this](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/lib.rs#L427-L429) should unconditionally go to stderr.

**Comment by marcusklaas** [comment]
All these issues have been fixed. I think this can be closed.
