### ISSUE TITLE
Rust crashes trying to format some macros

### ISSUE THREAD

**Issue by cjhowe** [rust-lang-nursery/rustfmt#915]
This macro from gfx:

```
gfx_pipeline!(pipe {
    vbuf: gfx::VertexBuffer<Vertex> = (),
    out: gfx::RenderTarget<ColorFormat> = "Target0",
});
```

causes rustfmt to crash with the following error:

```
~/src/game $ cargo fmt -v
[Bin] "/home/cjhowe/src/game/src/main.rs"
rustfmt /home/cjhowe/src/game/src/main.rs
thread '<main>' panicked at 'assertion failed: !fields.is_empty() || base.is_some()', /home/cjhowe/.cargo/registry/src/github.com-88ac128001ac3a9a/rustfmt-0.4.0/src/expr.rs:1393
third party subcommand `cargo-fmt` exited unsuccessfully

To learn more, run the command again with --verbose.
```

I can fix it simply by skipping formatting on that item. I still don't think rustfmt should crash if it can't format the inside of a macro, though.

**Comment by nrc** [comment]
Hmm, this is no longer crashing but it is generating incorrect output:

```
gfx_pipeline!(pipe {});
```

I guess what is happening is that we are parsing the macro argument as a struct and trying to format it. I've no idea why we would do that? I'd think we should leave the argument unformatted.

cc @marcusklaas  do you know what is happening here?

**Comment by marcusklaas** [comment]
I have some clue as to what's happening here. Our macro routine tries to parse the inner tokens as an expression. It finds something that looks like a struct expression, but actually isn't. Instead of failing, the parser just returns something weird, it looks like...

Note sure where the fault lies here, or how we could best fix it.

**Comment by marcusklaas** [comment]
`x!({ a- });` sends rustfmt into an infinite loop :-1:

**Comment by marcusklaas** [comment]
Also should be fixed once syntex is updated.
