### ISSUE TITLE
Handle empty struct defs properly

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#919]
We either don't reformat (struct structs) or lose comments (tuple structs). We should do neither.

e.g.,

```
struct Foo( /* a comment */ );
struct Foo();
struct Foo{ /* a comment */ }
struct Foo{}
```

should be idempotent

**Comment by tobarja** [comment]
Are you trying to say that those should remain untouched, but that the examples below are also idempotent, or that the code below should be reformatted to that above?

```
struct Foo ( /* a comment */ );
struct Foo ();
struct Foo { /* a comment */ }
struct Foo {}
```

**Comment by nrc** [comment]
I'm saying that the above should remain the same and the below should be changed to the above.

Although I actually made a mistake, there should be spaces before the opening braces:

```
struct Foo( /* a comment */ );
struct Foo();
struct Foo { /* a comment */ }
struct Foo {}
```
