### ISSUE TITLE
Unicode combining characters cause unnecessary warnings

### ISSUE THREAD

**Issue by euclio** [rust-lang-nursery/rustfmt#924]
On formatting the following code with `rustfmt`:

```rust
fn main() {
    println!("{}", "क्षिक्षिक्षिक्षिक्षिक्षिक्षिक्षिक्षिक्षि");
}
```

It formats it as:
```rust
fn main() {
    println!("{}",
             "क्षिक्षिक्षिक्षिक्षिक्षिक्षिक्षिक्षिक्षि");
}
```

but outputs: `src/lib.rs:3: line exceeded maximum length (sorry)`, when the line is clearly shorter than the threshold.

I think the problem lies in that `rustfmt` uses `len_utf8()` to calculate line length. It should probably use unicode grapheme clusters, but the underlying string buffer type doesn't support this.

**Comment by nrc** [comment]
Yeah, this is annoying, sorry.

Dup of #6
