### ISSUE TITLE
Rustfmt drops 'default' from 'default fn …' using specialization

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rustfmt#945]
Since specialization is only available in nightly (and maybe still changing), it's not much of a priority, though.

cf. https://github.com/tsion/miri/pull/6

**Comment by zitsen** [comment]
I'm waiting for this impl.

**Comment by julienXX** [comment]
I'd like to try to fix this one if no one is already working on it.

**Comment by regexident** [comment]
[line hint](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/items.rs#L1216) (spoiler alert! 😉 )

**Comment by lqd** [comment]
To me it looked like the syntex visitor didn't pass the defaultness ? (but I'm unfamiliar with both syntex and rustfmt so I could be very mistaken)

**Comment by regexident** [comment]
> To me it looked like the syntex visitor didn't pass the defaultness ? (but I'm unfamiliar with both syntex and rustfmt so I could be very mistaken)

That's true in fact, afaikt:

[`syntax::ast::TraitItemKind::Method(MethodSig, Option<P<Block>>)`](https://manishearth.github.io/rust-internals-docs/syntax/ast/enum.TraitItemKind.html#variant.Method)

```rust
pub struct MethodSig {
    pub unsafety: Unsafety,
    pub constness: Constness,
    pub abi: Abi,
    pub decl: P<FnDecl>,
    pub generics: Generics,
}
```

**Comment by lqd** [comment]
@julienXX salut Julien ;)

I think I'm close-ish to making a PR as I was talking about this issue with @nrc on IRC earlier today, would you mind if I took a crack at it ?

**Comment by julienXX** [comment]
@lqd no problem 👍

**Comment by nrc** [comment]
@julienXX if you want to work on a rustfmt, there are a bunch of good issues - https://github.com/rust-lang-nursery/rustfmt/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy - I'm happy to mentor any of them - either ping me on irc or comment on the bug.

**Comment by julienXX** [comment]
@nrc will do, thanks :)

**Comment by jaredmichaelsmith** [comment]
@nrc I'd love to jump on some of those. I'll find you on IRC if I have any issues.
