### ISSUE TITLE
BraceStyle for control flow blocks (if, for, match, ...)

### ISSUE THREAD

**Issue by sifton** [rust-lang-nursery/rustfmt#946]
I'll hopefully submit a PR for this in the not-too-distant future, but it'd be cool if we could add a config option enabling users to set the `BraceStyle` for `if`, `for`, `loop`, and `match` blocks (did I miss any?)

I'm not sure if it's best to break them up into individual settings or group them together. Possibilities are:

- `control_brace_style`, covering them all;
- `loop_brace_style`, covering `for` and `loop` blocks, `control_brace_style`, covering `if`, `match` blocks
- `for_brace_style`, `loop_brace_style`, `if_brace_style` and `match_brace_style`, covering each of their respective constructs separately

In any case, I'd actually enjoy working on a PR to satisfy this feature request myself, but I'd still like to solicit feedback about which of those possible config arrangements people would most like to see.

**Comment by marcusklaas** [comment]
This is indeed a gap in the configurability of rustfmt. Not 100% sure if `BraceStyle` is the perfect fit for it, though. I'd think we'd either always keep the brace on the same line or always push it to the next. `BraceStyle::SameLineWhere` does not have a clear meaning for these control structures any way.

Happy to read you're willing to work on this! I think we could probably have one option for all control structures, as I imagine most people would have all of them formatted similarly.

Let us know if you need any pointers!

**Comment by nrc** [comment]
+1 for a single option - fewer options is generally better if it is possible and I don't suppose many people will want these things formatted differently.

**Comment by flutterhash** [comment]
Ironically, I just submitted a PR for the if blocks for at least K&R, Stroustrup, and an imperfect Allman styles. I am happy to generalize that code though for other constructs.

**Comment by marcusklaas** [comment]
Closed by https://github.com/rust-lang-nursery/rustfmt/pull/948.
