### ISSUE TITLE
Unable to format question marker.

### ISSUE THREAD

**Issue by ngaut** [rust-lang-nursery/rustfmt#949]
rustfmt got panic when i am trying to format.
error message:

thread '<main>' panicked at 'Request to format inverted span: Loc { file: FileMap(./src/pd/client.rs), line: 178, col: CharPos(9) } to Loc { file: FileMap(./src/pd/client.rs), line: 178, col: CharPos(8) }'

source code: https://github.com/pingcap/tikv/blob/ngaut/untry/src/pd/client.rs#L178

Please take a look, thanks.

**Comment by marcusklaas** [comment]
There's already an issue for this: https://github.com/rust-lang-nursery/rustfmt/issues/867. The PR to implement this is blocked on serde, though :-(
