### ISSUE TITLE
Too much whitespace in struct literal

### ISSUE THREAD

**Issue by Luthaf** [rust-lang-nursery/rustfmt#952]
rustfmt add whitespaces before and after braces in struct literals, for example like this:

``` diff
 // In rustfmt.toml:
 //     struct_lit_style = "Visual"

 #[derive(Debug)]
 struct Bar {
     foo: f64,
     baz: usize,
 }

 fn main() {
-    let b = Bar{foo: 1.0, baz: 42};
+    let b = Bar { foo: 1.0,
+                  baz: 42, };
     println!("{:?}", b);
 }
```

Would it be possible to have an option preventing this behaviour? This is the main frustration that prevent me from using rustfmt :smiley:

**Comment by topecongiro** [comment]
You could set `struct_lit_width` to larger value. Also, the above example will not get reproduced on the current master.
