### ISSUE TITLE
normalise vs normalize for spelling of option names

### ISSUE THREAD

**Issue by jmesmon** [rust-lang-nursery/rustfmt#955]
Was wondering why `normalize_comments` wasn't working & noted that normalize is being spelled using the less common/UK `normalise` spelling.

Might want to do one of:

 - allow both
 - warn on one of them
 - require folks stare very hard at the help text after their comments get normalized anyhow.

Potentially relevant reference:

 - http://english.stackexchange.com/questions/107902/normalise-or-normalize-british-english

**Comment by nrc** [comment]
Yeah, I guess we should use the American spelling even though it makes me sad. It seems more common in the Rust community to use American English.

**Comment by kamalmarhubi** [comment]
Ah yeah I know that pain, @nrc! It's more common in the programming community overall, I think.

**Comment by srinivasreddy** [comment]
#992 is raised.

**Comment by gavinmcgimpsey** [comment]
#992 was merged – can this be closed?

**Comment by nrc** [comment]
yes, thanks!
