### ISSUE TITLE
option request: allow disabling insertion of `*` and reformatting of `/* */` comments

### ISSUE THREAD

**Issue by jmesmon** [rust-lang-nursery/rustfmt#956]
In some of my projects, I use larger `/* */` comments to contain formatted blocks of code. Right now rustfmt either:

 - if `normalise_comments` is enabled, changes them to `//` comments and loses all the whitespace indenting in the comment.
 - if `normalise_comments` is disabled, inserts ` *` (space followed by asterisk) on every line, and again loses all the leading white space for each line.

I suppose this could be 2 options:
 - don't strip leading white space when reformatting comments
 - don't insert ` *` on every comment line for `/* */` comments.

**Comment by nrc** [comment]
I consider this a bug with `normalise_comments` - it shouldn't be changing the `/* */` comments

**Comment by est31** [comment]
I don't know if its related, but with `normalise_comments` disabled, rustfmt will produce code that can't be compiled:
```rust
/*
TEST
// */
```

The `// */` trick is for code you maybe want to comment back in, then you only need to remove the `/*` and not edit it in two places.
