### ISSUE TITLE
option request: allow configuration of `fn_call` indent style

### ISSUE THREAD

**Issue by jmesmon** [rust-lang-nursery/rustfmt#958]
Right now it appears `rustfmt` only has `fn_call_width` to adjust how function invocations are generated.

We should really have at least an `fn_call_indent` to control the indent type (right now it appears to default to what is elsewhere called `Visual`.

Also should consider if the other `fn_args_*` options should be supported there as well.

Motivating case:

I'd like to change function calls to take a `Tabbed` form rather than a `Visual` form to prevent long function paths/names/invocations from pushing arguments too far right. Allowing multiple args per-line might also be useful (something like `fn_args_density`, but for `fn_call`, so perhaps `fn_call_density`).

As a stop gap, disabling the reformatting of function invocations would allow me to get by.

**Comment by topecongiro** [comment]
We now have `fn_call_style` to control the indent type of function call.
