### ISSUE TITLE
infinite loop, printing "error: unexpected token: `<eof>`"

### ISSUE THREAD

**Issue by jaystrictor** [rust-lang-nursery/rustfmt#964]
Running latest master branch on the following snippet produces an infinite loop where the error message

    stdin:7:1: 7:2 error: unexpected token: `<eof>`
    stdin:7 }
            ^

is printed over and over again.
Snippet:
```rust
fn s() {
    match g {
        None => {
             let i =
        }
    }
}
```

**Comment by nrc** [comment]
So, this was a problem in the Rust compiler which is now fixed. Are you using an up to date version of rustc? If you are, that is a problem for Rust which we should fix, but you can fix Rustfmt by switching to the nightly compiler.

**Comment by nrc** [comment]
Please let me know if switching compiler doesn't fix this and I'll reopen and investigate
