### ISSUE TITLE
Tweak single line if/else

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#969]
I'm not actually sure of the current behaviour, but here are some tweaks we should do if we don't already:

* only use single line for if/else in expression position, not statement position
* have a length cut-off for the whole expression as an option
* never use single line for an `if` without an `else` (I think this is covered by the first point, actually).
* do it by default with a relatively short cut-off point.

**Comment by marcusklaas** [comment]
I'd like to work on this.

**Comment by marcusklaas** [comment]
cc https://github.com/rust-lang-nursery/rustfmt/issues/417

**Comment by marcusklaas** [comment]
cc https://github.com/rust-lang-nursery/rustfmt/issues/286
