### ISSUE TITLE
Handle new visibility types

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustfmt#970]
syntex_syntax 0.31 brings a change from

```
pub enum Visibility {
    Public,
    Inherited,
}
```

to

```
pub enum Visibility {
    Public,
    Crate,
    Restricted { path: P<Path>, id: NodeId },
    Inherited,
}
```

It's unclear if the new variants need handling.

**Comment by tikue** [comment]
The following code is actually **removed** by rustfmt:

```rust
pub(super) enum WriteState<D> {
    WriteId {
        id: U64Writer,
        size: U64Writer,
        payload: Option<Writer<D>>,
    },
    WriteSize {
        size: U64Writer,
        payload: Option<Writer<D>>,
    },
    WriteData(Writer<D>),
}
```

When I pop it in tests/target/pub-restricted.rs and run `cargo test` the output is:

Mismatch at tests/target/pub-restricted.rs:1:
```rust
-pub(super) enum WriteState<D> {⏎
-    WriteId {⏎
-        id: U64Writer,⏎
-        size: U64Writer,⏎
-        payload: Option<Writer<D>>,⏎
-    },⏎
-    WriteSize {⏎
-        size: U64Writer,⏎
-        payload: Option<Writer<D>>,⏎
-    },⏎
-    WriteData(Writer<D>),⏎
-}⏎
+⏎
```

**Comment by kamalmarhubi** [comment]
This appears to be a fault of how I handled adding them, which is to say, I didn't: https://github.com/kamalmarhubi/rustfmt/commit/fd38acb86fa991f1272013d565992f2f68d76a5f#diff-3dbd16223f25e8b5e0bcf099743107e9R74

**Comment by kamalmarhubi** [comment]
@tikue I opened #1013 to support it properly. Thanks for the test!

**Comment by tikue** [comment]
Nice! Quick turnaround😉
