### ISSUE TITLE
Additional opportunities to trim whitespace

### ISSUE THREAD

**Issue by euclio** [rust-lang-nursery/rustfmt#983]
I think that rustfmt should add or remove whitespace in more cases. Two that certainly come to mind:
- Ensure that a single empty line is present between items (and methods, etc.? Not sure if that's the right terminology).
- Remove extra whitespace between block heads/tails:
  
  ```
  fn test() {
  
      // Blah blah
  
      if true {
  
          println!("hi");
  
      }
  
   }
  ```
  
   should probably be formatted like this:
  
  ```
  fn test() {
      // Blah blah
  
      if true {
          println!("hi");
      }
   }
  ```

**Comment by marcusklaas** [comment]
Yes! I think this would be a great feature. Thanks for opening an issue.

I'll have a shot at this coming weekend.
