### ISSUE TITLE
Format whitespace within attributes

### ISSUE THREAD

**Issue by euclio** [rust-lang-nursery/rustfmt#984]
I'm not sure if there's a decision on this in the wider Rust community, but I think it'd make sense to format attributes so that attributes are formatted to either

``` Rust
#[cfg(feature="nightly")]
```

or

``` Rust
#[cfg(feature = "nightly")]
```

**Comment by marcusklaas** [comment]
@nrc: do you know if there's enough info in the AST to do this?

**Comment by nrc** [comment]
I don't know, but in any case I plan to change the representation of attributes pretty soon as part of the macro reform work.

**Comment by marcusklaas** [comment]
Okay, probably shouldn't touch this yet then.

**Comment by killercup** [comment]
Just came across this, and would love to see this implemented. Especially when looking at code generated with `quote!`, attributes look weird (e.g., `# [ derive ( Clone , PartialEq , Debug , Deserialize , Serialize ) ]`).

I assume the final syntax is defined by <https://github.com/rust-lang-nursery/fmt-rfcs/issues/82>, but the only outstanding issue seems to be minor (spaces around `=`).

**Comment by nrc** [comment]
> I don't know, but in any case I plan to change the representation of attributes pretty soon as part of the macro reform work.

This is now done
