### ISSUE TITLE
meta: binaries

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/rustfmt#986]
# goals

users can:
- build rustfmt from source
- cargo install to build and install from source
- use rustup to install binaries
- download binaries from rust-lang website and install using a packaged script or manually
- use a supplied script to download and use rustfmt binaries in Travis, etc.

non-goal:
- windows installer (for the foreseeable future)

Long term, it'd be nice to have rustfmt packaged with the standard Rust repo and all this shouldn't matter, but I expect it'll take a while to get there.
## timing

For the 1.0 milestone (end of June), it would be good to have downloadable binaries, and nice to have scripts for using in Travis. Rustup support can wait.
# downloadable binaries

We'll use the exiting Travis setup to build for Linux and OS X, we'll want a new Appveyor account for Windows.

We'll create a stable branch and push releases from master to stable. The CI will build binaries on every push. Binaries from master will be available (somewhere, maybe) but not advertised. Binaries from stable will be pushed to rust-lang to be publicly available.

We'll need accounts on the rust-lang servers and upload the secrets to Travis + Appveyor. We'll presumably need to make changes to the frontend to actually have the links somewhere. And we'll have to decide on where and what they'll look like.

We'll use RustInstaller to make tarballs (I guess this happens on the CI), that should make them rustup-compatible. That will make install scripts. Not sure how much work it will be to use RustInstaller.
# rustup

Tarballs with Installer-generated install scripts are a prerequisite. We'll need to decide on whether to tie Rustfmt to a Rust channel. Disadvantage is it means users on stable Rust get a stale Rustfmt. If we make Rustfmt separate, we'll need to hack a bunch in Rustup to support multiple applications.

cc @alexcrichton @brson @edunham

**Comment by alexcrichton** [comment]
Some links:

* [`rust-installer`](https://github.com/rust-lang/rust-installer)
* [Example rust-installer usage](https://github.com/rust-lang/rust/blob/e88defe71806ad190588e168e513bc1098f7c9fb/src/bootstrap/build/dist.rs#L263-L288)
* [rustup `.travis.yml`](https://github.com/rust-lang-nursery/rustup.rs/blob/master/.travis.yml)
  * Contains config for building on a number of platforms
  * Contains config for building ultra-compatible Linux glibc binaries
  * Contains config for building compatible OSX binaries
  * Contains sample config for uploading to S3
* [rustup `appveyor.yml`](https://github.com/rust-lang-nursery/rustup.rs/blob/master/appveyor.yml)
  * Config for all 4 Windows targets
  * Config for uploading binaries to S3 and generation of these binaries
  * Note that not all of this is necessary as rustfmt probably has fewer native dependencies

Always willing to help answer questions as well :)

**Comment by nrc** [comment]
Plan is to use rustup, this issue is no longer relevant
