### ISSUE TITLE
Regression in method chain alignment?

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang-nursery/rustfmt#988]
I re-ran rustfmt on a project formatted with an older version, and I find the new method chain formatting
to be uglier.

Here are some highlights:
```diff
             let pressed_keys: HashSet<Keycode> = held_keys.difference(&old_keycodes)
-                                                          .cloned()
-                                                          .collect();
+                .cloned()
+                .collect();
```
▲ This was neatly aligned, now it's not .

```diff
 fn pressed_keycode_set(e: &sdl2::EventPump) -> HashSet<Keycode> {
     e.keyboard_state()
-     .pressed_scancodes()
-     .filter_map(Keycode::from_scancode)
-     .collect()
+        .pressed_scancodes()
+        .filter_map(Keycode::from_scancode)
+        .collect()
 }
```
▲ Ditto. Although it seems to get pushed further right instead of left?

```diff
             let surf = self.font
-                           .render("Loading maze, bro. You can quit and stuff. It's pretty cool.")
-                           .solid(Color::RGB(255, 255, 255))
-                           .unwrap();
+                .render("Loading maze, bro. You can quit and stuff. It's pretty cool.")
+                .solid(Color::RGB(255, 255, 255))
+                .unwrap();
             let tex = renderer.create_texture_from_surface(surf).unwrap();

```
▲ You can make the argument here that the new version is less rightward-drifty, but the previous version is also (although barely) sub-100 columns.

**Comment by killercup** [comment]
rustfmt seems to use block indentation (4 spaces) by default now instead of visual indentation (line up method calls). There was a lot of discussion in #439.

**Comment by crumblingstatue** [comment]
> rustfmt seems to use block indentation (4 spaces) by default now instead of visual indentation (line up method calls). There was a lot of discussion in #439.

Ah, so unconditionally block indenting everything, even if it fits nicely is intended behavior?

The second case looks especially weird to me, since it causes more rightward drift than the original.

**Comment by marcusklaas** [comment]
I, too, believe these are regressions. We recently implemented another change to combat rightward drift: breaking assignments to the next line. I'll submit a PR soon to see if this is enough to go back to visual alignment.

**Comment by killercup** [comment]
@marcusklaas, do you think it might be feasible to use a heuristic (read: trivial line length comparison) to switch between visual and block indentation?

E.g.,

```rust
    e.keyboard_state()
     .pressed_scancodes()
     .filter_map(Keycode::from_scancode)
     .collect()
```

looks nice, but

```rust
    that_event_we_caught_in_some_upper_scope.keyboard_state()
                                            .pressed_scancodes()
                                            .filter_map(Keycode::from_scancode)
                                            .collect()
```

has far too much right drift.

I would suggest reformatting the second example to this:

```rust
    that_event_we_caught_in_some_upper_scope
        .keyboard_state()
        .pressed_scancodes()
        .filter_map(Keycode::from_scancode)
        .collect()
```

---

On the other hand, I personally think having a code style that reduces diff noise is more important than having one that always looks pretty!

**Comment by marcusklaas** [comment]
Yea that could work, although I believe that right drift in itself is not a big problem, just that it causes width constraints for closures etc. There's also something to be said for consistency. It's a complex issue...

**Comment by killercup** [comment]
(Speaking of diff noise, I would love to see some analysis on this! For example, we could look at git history of some representative Rust projects, and for several rustfmt config presets run rustfmt after each new commit and compare the amount of diff lines between commits. Does that make sense? It's hard to describe nested loops in English 😄 )

**Comment by nrc** [comment]
Yeah, as others have said, the new behaviour is always to block indent, not visual indent. All else being equal I also prefer visual indentation. The motivation to change was primarily to fit in with new formatting for large closures and secondarily to avoid rightward drift. Using visual sometimes and block sometimes is an option, but I think consistency is more important (we'll get used to block indenting, but inconsistency within a file is pretty bad). Happy to experiment though.
