### ISSUE TITLE
Remove semicolon after break/continue/return by default?

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustfmt#993]
Right now it looks like rustfmt always inserts a semicolon after `break`, `return`, and `continue` expressions. Given that it is semantically invalid to include code after these expressions, why not make it _syntactically invalid_ as well? That is, the only typical need for inserting a semicolon is to change some type to `()` or to allow writing another statement, but in the case of these expressions there's no need to do either (and you save a character to boot).

Maybe this is better waiting for the RFC process, though?

**Comment by nrc** [comment]
Yeah, this should go through the RFC process. I'll leave the issue open since we should make this a config option.

I prefer semicolons after these expressions since I think it is consistent to have `return x;` and `return;` (or even `return ();`), but this is pretty subjective.
