### ISSUE TITLE
Configurable? Fn brace next line except single line definitions

### ISSUE THREAD

**Issue by jwilm** [rust-lang-nursery/rustfmt#999]
I'm trying to configure braces for `fn`s to appear on the next line _except_ when the function signature fits on a single line. Is this currently possible? Sorry if this is a duplicate; I looked around a bit and couldn't find anything.
# Examples

Single line `fn`

``` rust
/// Open brace on same line
fn thing_doer() -> Result<Thing, DoError> {
    // ...
}
```

Multi-line

``` rust
/// Open brace always comes on next line independent of return and where clause.
fn thing_doer<S>(
    a: &str,
    b: S
) -> Result<Thing, DoError>
    where S: Into<Potato>
{
    // ...
}
```

#### Edits
* Updated multi-line example formatting

**Comment by jwilm** [comment]
I should add, I've tried with AlwaysNext, but that affects the single line case. PreferSameLine and SameLineWhere don't get this right either.

**Comment by nrc** [comment]
That is not currently possible. Should be possible to add as an option though

**Comment by jwilm** [comment]
@nrc I'd be willing to do the work; could you point me in the right direction? Haven't had a chance to work with rustfmt src yet.

Thanks!

**Comment by nrc** [comment]
@jwilm great! I would start with config.rs, to see what the current options are which give you good search terms for searching the rest of the code base. You can also add your new option here which is a nice easy way to start, and you might get some helpful compiler errors when you do it.

For the actual reformatting look in items.rs, functions are quite a lot of work to format, `rewrite_fn` is the starting point and looks like it has the brace handling. `rewrite_fn_base` rewrites the signature of the function and returns some information which affects bracing.

https://github.com/rust-lang-nursery/rustfmt/blob/master/Contributing.md has information about how rustfmt works as well as building, etc.

Please ping me here or on irc with questions!

**Comment by jwilm** [comment]
Thanks for all that info! I'll probably take a whack at this over the weekend.

**Comment by dhardy** [comment]
@jwilm still working on this?

It would be nice to have this option for all related uses of braces, e.g. `if`, `while`, `for`, `match` (both opening and patterns):

```
match some_enum {
    SomeFrabricatedEnum::SomeStruct { struct_field_1,
        struct_field_2 } =>
    {
        do_something_with(struct_field_1, struct_field_2);
    }
    ...
}
```

**Comment by jwilm** [comment]
@dhardy sadly no; I sort of lost interest in this when realizing I didn't like a number of rustfmt things at the time (several months ago now).

Regarding your example, it sounds like rustfmt is moving towards favoring short lines and more vertical. In that case, this example would look like:

```rust
match some_enum {
    SomeFrabricatedEnum::SomeStruct {
        struct_field_1,
        struct_field_2
    } => {
        do_something_with(struct_field_1, struct_field_2);
    }
    // ...
}
```

Where a shorter matcher would have `} => {` on the same line. Given the extra tokens involved and different context in which this arises, I wonder if items such as `match` and `if` should have their own issues discussing brace placement.

This recommendation is based on @ubsan's [style guide](https://ubsan.github.io/style/) of which some sections have been [accepted through RFC](https://github.com/rust-lang-nursery/fmt-rfcs/pull/27). Note that her guide doesn't cover this particular matching case, but the version above is consistent with the specified long function definition syntax (see "Function Definitions" section of guide).
